### ISSUE TITLE
Session substitution between workers

### ISSUE THREAD

**Issue by crealist** [kraih/mojo#1002]
* Mojolicious version: 6.58
* Perl version: v5.20.2 built for x86_64-linux-gnu-thread-multi
* Operating system: Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09)

Sebastian, hi!
I don't know how can you reproduce it, so i'l just describe our rare, strange, but very critical trouble.
We are using sessions to authenticate users in our site. As we know, Mojo writes session code to browser cookies with encription, and rewrite it every request with the new value.
Sometimes (not often) it seems like Mojo write to cookie session code from ANOTHER user! Maybe, from another worker. One time it was a profile rewriting from user A to user B, when the both of users before this incident visited the same page... User B at this moment see on the page, that in his profile section already not his own, but user A login. After that user B has to to log out and log in again. Any time it looks good, but once profile substitution hapen again.
What a reason could in be?.. It's a real big security trouble. :(
PS: We are using Starman with 10 workers (Plack 1.0037).
Thank you! Alexey, Russia.

sub startup {
...
    $self->sessions->cookie_name('sessioncode');
    $self->sessions->default_expiration(60 * 60 * 24 * 365);
    $self->sessions->cookie_domain($self->config->{cookiedomain});

Code, where we seting up session code:
        $session = generate_session_id();
...
        $self->session(
            session => $session,
            user_id => $user_id
        );

Code, where we geting the session code:

sub setup_hooks {
    my $self = shift;

    # выполняется перед обработкой каждого запроса
    $self->app->hook(before_dispatch => sub {
        my $c = shift;
...
        my $session_code = $c->session->{session};

**Comment by kraih** [comment]
I'm afraid there is nothing we can do without a minimal example demonstrating the problem. That said, i very much doubt this could be a bug in Mojolicious. With Starman, every worker can only handle a single connection at a time, ruling out any possible data leakage between concurrently active connections. Btw. Session data is not encrypted, just cryptographically signed.

**Comment by jberger** [comment]
I don't believe that this is likely to be a Mojolicious issue. I can see two possible ways that application code or user behavior could cause something like this.

First, user behavior. Is it possible that you are testing this behavior in the same browser in separate tabs? Sometimes people are confused by the fact that cookie jars are global to the browser (or browser user session) and not the tab. I don't suspect you are doing this or you should be able to replicate regularly.

Second, application logic. If you have a global that stores the current user object and perhaps don't properly clean up after it this could certainly happen. Whether it be in a variable (package variable/closed over lexical) or even in a caching engine without proper isolation globals can cause leakage. In the case of a variable the leakage wouldn't cross workers and so would only happen occasionally when you happen to hit the same worker. An improperly isolated caching engine would cross workers and therefore I would expect (as with browser tabs) that replicating this would be easier.

I therefore suspect you are leaking user objects via a closed over lexical or package global, probably called `$current_user` or the like. If this is the case I highly recommend stuffing that information into the per-request stash on the controller object.
