### ISSUE TITLE
UA: lost callback/tx on nonblocking req with http type proxy

### ISSUE THREAD

**Issue by mche** [kraih/mojo#1003]
* Mojolicious version: Mojolicious is up to date. (7.08)
* Perl version: 5.20.3
* Operating system: GNU Linux 3.14.27

### Steps to reproduce the behavior

`curl -sL 'https://github.com/mche/mojo/raw/master/script/test-proxy.pl' | perl - http://111.222.33.4:56789`

### Expected behavior

STDOUT:
```
blocking: Proxy connection failed
nonblocking: Proxy connection failed
```

### Actual behavior

```
Use of uninitialized value $id in delete at /home/elk/perl5/lib/perl5/Mojo/UserAgent.pm line 270.
Use of uninitialized value $loop in hash element at /home/elk/perl5/lib/perl5/Mojo/UserAgent.pm line 194.
Mojo::Reactor::Poll: Timer failed: Can't call method "remove" on an undefined value at /home/elk/perl5/lib/perl5/Mojo/UserAgent.pm line 272.
blocking: Proxy connection failed
Use of uninitialized value $id in delete at /home/elk/perl5/lib/perl5/Mojo/UserAgent.pm line 270.
Use of uninitialized value $loop in hash element at /home/elk/perl5/lib/perl5/Mojo/UserAgent.pm line 194.
Mojo::Reactor::Poll: I/O watcher failed: Can't call method "remove" on an undefined value at /home/elk/perl5/lib/perl5/Mojo/UserAgent.pm line 272.
```

Socks proxy does OK:
`curl -sL 'https://github.com/mche/mojo/raw/master/script/test-proxy.pl' | perl - socks://111.222.33.4:56789`

I would obtain tx object even any proxy errors (even any errors, in general).

Regards.

**Comment by kraih** [comment]
Afraid i have to close this issue, because your example encourages everyone reading this to execute a script from an untrusted source. I don't think your intentions are malicious, but it's better to be safe than sorry.
