### ISSUE TITLE
endless loop when forward request to backend server 

### ISSUE THREAD

**Issue by sjdy521** [kraih/mojo#1008]
I 'm trying to forward request to my backend server
`client -> 127.0.0.1:80  -> 127.0.0.1:8888 `
code example:
```
use Mojolicious::Lite;
any '/*whatever'  => sub{
    my $c = shift;
    $c->render_later;
    my $tx = Mojo::Transaction::HTTP->new(req=>$c->req->clone);
    $tx->req->url->host("127.0.0.1");
    $tx->req->url->port("8888");
    $tx->req->headers->header('Host',$tx->req->url->host_port);
    return if $c->stash('mojo.finished');
    $c->ua->start($tx,sub{
        my ($ua,$tx) = @_;
        $c->tx->res($tx->res);
        $c->rendered;
    });
};
app->start;
```

when I make a request http://127.0.0.1:80/test to server ,the request isn't been forwarded to my backend http://127.0.0.1:8888/test, but still forward to its own `http://127.0.0.1:80`

thus a endless loop occurs:

```
morbo script -l http://*:80/ 
Server available at http://127.0.0.1:80/
[Thu Oct 13 17:54:39 2016] [debug] GET "/test"
[Thu Oct 13 17:54:39 2016] [debug] Routing to a callback
[Thu Oct 13 17:54:39 2016] [debug] GET "/test"
[Thu Oct 13 17:54:39 2016] [debug] Routing to a callback
[Thu Oct 13 17:54:39 2016] [debug] GET "/test"
[Thu Oct 13 17:54:39 2016] [debug] Routing to a callback
[Thu Oct 13 17:54:39 2016] [debug] GET "/test"
[Thu Oct 13 17:54:39 2016] [debug] Routing to a callback
[Thu Oct 13 17:54:39 2016] [debug] GET "/test"
[Thu Oct 13 17:54:39 2016] [debug] Routing to a callback
[Thu Oct 13 17:54:39 2016] [debug] GET "/test"
[Thu Oct 13 17:54:39 2016] [debug] Routing to a callback
[Thu Oct 13 17:54:39 2016] [debug] GET "/test"
[Thu Oct 13 17:54:39 2016] [debug] Routing to a callback
[Thu Oct 13 17:54:39 2016] [debug] GET "/test"
[Thu Oct 13 17:54:39 2016] [debug] Routing to a callback
[Thu Oct 13 17:54:39 2016] [debug] GET "/test"
[Thu Oct 13 17:54:39 2016] [debug] Routing to a callback
[Thu Oct 13 17:54:39 2016] [debug] GET "/test"
[Thu Oct 13 17:54:39 2016] [debug] Routing to a callback
[Thu Oct 13 17:54:39 2016] [debug] GET "/test"
[Thu Oct 13 17:54:39 2016] [debug] Routing to a callback
```

I do heavy reading of source code, especially these module:

Mojo::Transaction::HTTP
Mojo::UserAgent;
Mojo::URL
Mojo::UserAgent::Transactor

but I cannot find out what's wrong with my example.I think it's corrent 
So i come here and hope someone can offer some help

**Comment by brianmed** [comment]
Does the code below work?  Please note the to_abs section..

use Mojolicious::Lite;

any '/*whatever'  => sub{
    my $c = shift->render_later;

    my $tx = Mojo::Transaction::HTTP->new(req => $c->req->clone);

    $tx->req->url($tx->req->url->to_abs(Mojo::URL->new('http://127.0.0.1:8888')));
    $tx->req->headers->header('Host', $tx->req->url->host_port);

    return if $c->stash('mojo.finished');

    $c->ua->start($tx, sub{
        my ($ua, $tx) = @_;

        $c->tx->res($tx->res);
        $c->rendered;
    });
};

app->start;

**Comment by kraih** [comment]
Nothing here looks like a bug to me, please use our official support channels. http://mojolicious.org/perldoc#SUPPORT
