### ISSUE TITLE
SOCKS support is broken

### ISSUE THREAD

**Issue by kraih** [kraih/mojo#1010]
* Mojolicious version: 7.08
* Perl version: 5.24.0
* Operating system: macOS Sierra

### Steps to reproduce the behavior
Run `t/mojo/user_agent_socks.t`.

### Expected behavior
Pass.

### Actual behavior
```
t/mojo/user_agent_socks.t .. 1/? Mojo::Reactor::Poll: I/O watcher failed: Can't call method "blocking" on an undefined value at t/mojo/user_agent_socks.t line 63.

#   Failed test 'successful'
#   at t/mojo/user_agent_socks.t line 116.

#   Failed test 'right status'
#   at t/mojo/user_agent_socks.t line 119.
#          got: undef
#     expected: '200'

#   Failed test 'right content'
#   at t/mojo/user_agent_socks.t line 122.
#          got: ''
#     expected: undef
Use of uninitialized value $stream in hash element at /Users/sri/repo/mojo/lib/Mojo/IOLoop.pm line 145.
Use of uninitialized value $stream in hash element at /Users/sri/repo/mojo/lib/Mojo/IOLoop.pm line 145.
Can't call method "handle" on an undefined value at t/mojo/user_agent_socks.t line 123.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 8.
t/mojo/user_agent_socks.t .. Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 3/8 subtests 

Test Summary Report
-------------------
t/mojo/user_agent_socks.t (Wstat: 65280 Tests: 8 Failed: 3)
  Failed tests:  3, 6, 8
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=1, Tests=8,  1 wallclock secs ( 0.02 usr  0.01 sys +  0.21 cusr  0.02 csys =  0.26 CPU)
Result: FAIL
```

**Comment by kraih** [comment]
It appears a recent change in `IO::Socket::Socks` caused this. What i found when i went to investigate was very bad. It's not just a little mistake, the documentation for the `start_SOCKS` method does not at all match the reality, return values are pretty much random, making `IO::Socket::Socks` unusable in Mojolicious for the moment.

It might be worth considering the removal of SOCKS support for now, at least until the quality of `IO::Socket::Socks` improves again.

**Comment by jberger** [comment]
Is there an issue to link against from IO::Socket::Socks?

**Comment by kraih** [comment]
Looks like it has been fixed. https://rt.cpan.org/Public/Bug/Display.html?id=118471
