### ISSUE TITLE
Fixed bug where Mojolicious::Renderer would wrap text in layouts.

### ISSUE THREAD

**Issue by parserpro** [kraih/mojo#1012]
* Mojolicious version: 7.09
* Perl version: 5.20.2
* Operating system: Debian 

### Steps to reproduce the behavior
After
7.06  2016-09-17
  - Fixed bug where Mojolicious::Renderer would wrap text in layouts.
we have a big problem - our code relays on such behaviour.

### Expected behavior
We want ability to turn on previous behaviour while rendering text, may be via special key:
$c->render(old_text => $text ) or
$c->stash(force_layout => 1)

### Actual behavior
$c->render(text => $text) doesn't wrap text in layout

**Comment by kraih** [comment]
Actually, this does not need to be a new feature. You can just make your own helper.
```
$c->content(content => $text);
$c->render('layouts/whatever');
```
