### ISSUE TITLE
Mojo::Util::spurt should check syswrite's return value (number of bytes written) and croak

### ISSUE THREAD

**Issue by jkramer** [kraih/mojo#1020]
* Mojolicious version: 7.1
* Perl version: 5.18.0
* Operating system: Linux 4.8.10-1-ARCH

### Steps to reproduce the behavior
```bash
$ dd if=/dev/zero of=small-disk.img bs=1024 count=10240
$ mkfs.ext3 small-disk.img
$ mkdir mnt
$ sudo mount small-disk.img mnt
$ sudo perl -MMojo::Util -e 'my $x = "x"x(1024*10240); print length($x), "\n"; Mojo::Util::spurt($x, "mnt/test"); print "no croak\nsize: ", -s "mnt/test", "\n"'
10485760
no croak
size: 8962048
```

### Expected behavior
The result of syswrite should be compared with the size of the content and spurt should croak if they don't match.

### Actual behavior
Currently spurt only croaks if the syswrite completely fails (return value undef) and doesn't do any other checks. However I'd expect spurt to only succeed if the content was actually written - currently spurt also succeeds when only some portion of the content was written (for example when the disk is full).

**Comment by bobkare** [comment]
Possible way to test for the issue: `local *IO::Handle::syswrite = sub { $!=0; return 42 };`

Possible solution: `($file->syswrite($content)//-1) == length($content) or croak ...`
