### ISSUE TITLE
Mojo::DOM method text should work on text-nodes

### ISSUE THREAD

**Issue by wollmers** [kraih/mojo#1022]
* Mojolicious version: 7.11, Doughnut
* Perl version: v5.20.1, darwin
* Operating system: OS X El Capitan Version 10.11.6

### Steps to reproduce the behavior
```
$ perl -MMojo::DOM -E 'say q{"},Mojo::DOM->new("&amp;")->child_nodes->[0]->text,q{"};'
""
```

### Expected behavior
```
$ perl -MMojo::DOM -E 'say q{"},Mojo::DOM->new("&amp;")->child_nodes->[0]->tree->[1],q{"};'
"&"
```

Of course the work-around `->tree->[1]`can be used, but that's not an official API and can break in future.

### Actual behavior
The method `text` on nodes of type `text`, `raw`and `cdata` returns an empty string instead of the text.

The method `to_string`works but is entity-encoded and thus does not allow direct processing as plain text.

**Comment by jberger** [comment]
The underlying cause of the confusion here is that `content` is documented to work on nodes while `text` is documented to work on elements. There are several ways to proceed here:

* close, saying that the documentation already indicates this
* go slightly further and cross link the documentation for `text` to `content` since people may look in the wrong place for this ("to extract text from a node, see L</content>")
* change text to DTRT on a node element

**Comment by kraih** [comment]
If there was enough interest i guess i'd support making `->text` work on all nodes, otherwise i'd say keep everything the way it is.

**Comment by wollmers** [comment]
@jberger Thx for the work-around using `content`.

As I understand the docs, `content` is intended for extracting and setting XML/HTML fragments, as the docs state:

```
Return this node's content or replace it with HTML/XML fragment (for root and tag nodes) or raw content.
```

BTW I wouldn't expect this difference:

```
$ perl -MMojo::DOM -E 'say q{"},Mojo::DOM->new("&amp;")->child_nodes->[0]->content,q{"};'
"&"

$ perl -MMojo::DOM -E 'say q{"},Mojo::DOM->new("<a>&amp;</a>")->at("a")->content,q{"};'
"&amp;"
```

Can we agree that it would be more intuitive to use `->text` to extract text from nodes of type `text`, `cdata`and `raw`? Or should we agree to disagree?

In other parsers like XML::Twig `->text` works on all nodes as expected, i. e. returning plain Perl strings.

**Comment by wollmers** [comment]
@kraih IMHO returning an empty string is wrong in any case.

I can provide a pull request this weekend.

**Comment by wollmers** [comment]
#1024

**Comment by kraih** [comment]
It does not look like there is much interest in discussing this further.
