### ISSUE TITLE
Mojo::IOLoop::Subprocess deadlock

### ISSUE THREAD

**Issue by e477** [kraih/mojo#1026]
* Mojolicious version: 7.13
* Perl version: 5.22.2
* Operating system: Slackware Linux 14.2 64-bit

I am trying to use Mojo::IOLoop::Subprocess in a Mojolicious application to serve certain long running requests that would otherwise block the event loop. While this seems to work fine at first, concurrent requests quickly lead to stuck subprocesses and a complete lock up of the web app.

The reason for this seems to be that Mojo::IOLoop::Subprocess will run into a deadlock when two or more subprocesses are started at the same time and run for more than 15 seconds. The following example reliably reproduces the deadlock on my system, with the subprocesses being stuck in `write` and the parent process being stuck in `waitpid`:

```perl
#!/usr/bin/perl

use Mojo::Base -strict;
use Mojo::IOLoop;

# long running worker, returning 1MB data
sub worker {
    say "subprocess sleeping 20 seconds, causing a timeout";
    sleep 20;
    say "done sleeping";
    return 'M' x 1048576;
}

# start concurrent workers
Mojo::IOLoop->delay(
    sub {
    	my ($delay) = @_;
    	Mojo::IOLoop->subprocess(sub {worker;}, $delay->begin);
    	Mojo::IOLoop->subprocess(sub {worker;}, $delay->begin);
    },
    sub {
    	say "unexpectedly, this actually worked";
    }
)->wait;
```

Besides not ending up in a deadlock, it would be nice if the subprocesses had an adjustable timeout instead of the Mojo::IOLoop::Stream 15 seconds default.

**Comment by kraih** [comment]
Thank you for this excellent report, the problem should be fixed now.
