### ISSUE TITLE
Mojo::UserAgent  fail with "Mojo::IOLoop already running"

### ISSUE THREAD

**Issue by sjdy521** [kraih/mojo#1029]
When a blocking request is interrupted by a SIGINT and  try to issue a blocking request in the SIGINT handler,Mojo::UserAgent will generate a  error message:

 `Mojo::IOLoop already running at /usr/local/share/perl5/Mojo/UserAgent.pm line 60` 

run the following code and press CTRL+C immediately , You will see the error:

```
use Mojo::UserAgent;
my $ua = Mojo::UserAgent->new;
$ua->on(start=>sub{$_[0]->ioloop->stop if $_[0]->ioloop->is_running});
$SIG{INT} = sub{
    $ua->get('http://www.baidu.com')->res->body;
    exit;
};
$ua->get("http://strawberryperl.com/download/5.24.0.1/strawberry-perl-5.24.0.1-64bit.msi")->res->body;
```

It seems Mojo::UserAgent doesn't have a chance to do `$ua->ioloop->stop`  if SIGINT happends

**Comment by kraih** [comment]
Afraid this doesn't look like a bug to me. If you have an idea for what we could do better, please send a pull request.
