### ISSUE TITLE
Mojo::URL produces invalid URLs in to_string() because fragment gets decoded

### ISSUE THREAD

**Issue by dboehmer** [kraih/mojo#1033]
* Mojolicious version: 7.11
* Perl version: 5.20.2
* Operating system: Debian Linux Jessie (8)

### Steps to reproduce the behavior
    say Mojo::URL->new("/foo?bar=1%25+nacl#1%25+nacl")
    # /foo?bar=1%25+nacl#1%+nacl

### Expected behavior
    # /foo?bar=1%25+nacl#1%25+nacl
`Mojo::URL->new($str)->to_string eq $str` unless `$str` is not a valid URL because `Mojo::URL->new($str)` is a representation of the URL in `$str` and equivalence is [defined by string comparison](https://url.spec.whatwg.org/#url-equivalence).

If any de-/encoding happens I'd definitely expect all parts of the URL to be treated equally and the operation to be reversible.

However, the result of `to_string()` should be a valid URL, I think. It definitely is not in this case:

The *URL living standard* [says in section 4.1](https://url.spec.whatwg.org/#syntax-url-fragment)

> A URL-fragment string must be zero or more URL units. 

and [defines URL units](https://url.spec.whatwg.org/#url-units)

> The URL units are URL code points and percent-encoded bytes. 

A `%` is obviously not anything percent-encoded. Is it a URL code point? [The list of valid code points](https://url.spec.whatwg.org/#url-code-points) says it's not.

### Actual behavior
`new($str)` decodes `%25` in the fragment while it isn't decoded in the query.

```perl
  DB<100> x Mojo::URL->new("/foo?bar=1%25+nacl#1%25+nacl")
0  Mojo::URL=HASH(0x28a8fa0)
   'fragment' => '1%+nacl'
   'path' => Mojo::Path=HASH(0x28a2cf8)
      'path' => '/foo'
   'query' => Mojo::Parameters=HASH(0x28a2a40)
      'string' => 'bar=1%25+nacl'
```

The fragment is not encoded again in `to_string()`

### Prior history

This bug was detected in #1023.

**Comment by kraih** [comment]
I was hoping someone would also quote RFC 3986 (https://tools.ietf.org/html/rfc3986#section-3.5).
```
fragment    = *( pchar / "/" / "?" )
pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
pct-encoded   = "%" HEXDIG HEXDIG
sub-delims    = "!" / "$" / "&" / "'" / "(" / ")"
                 / "*" / "+" / "," / ";" / "="
```

**Comment by kraih** [comment]
The fragment string in question can no longer be generated. https://github.com/kraih/mojo/commit/777f24f141d2b286337e5813b1282021c5dc111a

**Comment by ilainftw** [comment]
Even more direct, from https://tools.ietf.org/html/rfc3986#section-2.4

> Because the percent ("%") character serves as the indicator for
> percent-encoded octets, it must be percent-encoded as "%25" for that
> octet to be used as data within a URI.

https://tools.ietf.org/html/rfc3986#section-3.4 and  https://tools.ietf.org/html/rfc3986#section-3.5 show the same syntax grammar applied to query part and fragment.  https://tools.ietf.org/html/rfc3987#section-2.2 shows the same treatment of percent characters in syntax grammar for IRIs. @dboehmer already referenced the living standard version of syntax grammar.

**Comment by dboehmer** [comment]
I don't know how much this is related or another issue:

```
$ perl -MMojo::URL -E 'say Mojo::URL->new("/?a=b&c=A%26B")'
/?a=b&c=A%26B
$ perl -MMojo::URL -E 'say Mojo::URL->new("/#a=b&c=A%26B")'
/#a=b&c=A&B
```

If you want another issue I can create one. Short description in case it's the same issue anyway: This behavior is wrong because the second output URL does not equal the input URL. Additionally by controlling the value of one parameter I can spoof other parameters which might have security implications. Do you need any more input regarding this?

777f24f1 makes no difference for this example.

**Comment by kraih** [comment]
@dboehmer You know what we need now. Closing this issue since unrelated issues are being brought up.

**Comment by ilainftw** [comment]
Not an unrelated issue, strictly speaking. It's a by-product of the unnecessary application of url_unescape to parsed fragment value:

https://github.com/kraih/mojo/blob/master/lib/Mojo/URL.pm#L65

My vote would have been to remove that call to url_unescape and keep Mojo::URL->to_string as it was. That would have given fragment the same treatment as query part, which is left in escaped form when set from a scalar, either through accessor or from Mojo::URL->parse, via Mojo::Parameters->parse:

https://github.com/kraih/mojo/blob/master/lib/Mojo/Parameters.pm#L116

**Comment by kraih** [comment]
@ilainftw If you really believe it's worth it, please open a new issue with a formal proposal so we can vote on it. Just make sure to explain why a breaking change in this case is reasonable (spec breaking bugs or security for example are good reasons), or present a deprecation path.

**Comment by ilainftw** [comment]
We've been patching this rather trivial thing in Mojo for a while, so we'll just keep doing so. I couldn't make a case based on spec breakage since Mojo::URL now adheres to relevant specs, and there is no requirement for Mojo::URL (or any other module) to completely round-trip the string representation of fragments. That falls into the category of "implementation detail". This really only affects testing, but it seems like a workaround would be straightforward (or just use another module). I take @dboehmer's point about parameter manipulation, but if you don't trust the URLs coming into your application, you need to check them carefully anyway.
