### ISSUE TITLE
Mojo::URL->new decodes ampersand in fragment which is not encoded in to_string

### ISSUE THREAD

**Issue by dboehmer** [kraih/mojo#1034]
* Mojolicious version: 777f24f14 (current master at time of writing)
* Perl version: 5.20.2
* Operating system: Debian Linux Jessie (8)

### Steps to reproduce the behavior
```
$ perl -MMojo::URL -E 'say Mojo::URL->new("/?a=b&c=A%26B")'
/?a=b&c=A%26B
$ perl -MMojo::URL -E 'say Mojo::URL->new("/#a=b&c=A%26B")'
/#a=b&c=A&B
```

### Expected behavior
Encoded ampersand `%26` is always preserved and URL is stringified to the original string.

### Actual behavior
For the fragment part the percent-encoding is decoded and the contained ampersand `&` is printed. This makes the resulting URL being unequal to the input URL.

**Comment by kraih** [comment]
Please quote the section of the spec requiring this behavior.

**Comment by kraih** [comment]
Closing this issue until we have more information.
