### ISSUE TITLE
text() does not allow modification of value

### ISSUE THREAD

**Issue by allenday** [kraih/mojo#1037]
* Mojolicious version: 7.19
* Perl version: 5.18.2
* Operating system: OSX 10.12.2 (16C67)

### Steps to reproduce the behavior
#!/usr/bin/perl
use strict;
use Data::Dumper qw(Dumper);
use Mojo::DOM;

my $dom = Mojo::DOM->new(qq(
<script src="mutable">mutable</script>
));

my @e;

@e = $dom->find( 'script' )->each();
foreach my $e ( @e ) {
  my $a = $e->text();
  $a =~ s#mutable#OK1#g;
  $e->text( $a );
}

@e = $dom->find( 'script' )->each();
foreach my $e ( @e ) {
  my $a = $e->attr( 'src' );
  $a =~ s#mutable#OK2#g;
  $e->attr( 'src' => $a );
}

print $dom;

### Expected behavior
should modify both instances of string "mutable"

### Actual behavior
modifies only "src" attribute, does not modify text.

**Comment by kiwiroy** [comment]
@allenday have you looked at the `content` method?

**Comment by kraih** [comment]
Basically the same discussion as https://github.com/kraih/mojo/issues/1022.

**Comment by allenday** [comment]
that works, thank you!
