### ISSUE TITLE
Smart trimming in Mojo:DOM

### ISSUE THREAD

**Issue by Eitz** [kraih/mojo#1038]
Hello,

Is there any possibility of **smart whitespace trimming in "all_text"** return to Mojo::DOM?

It's a great feature, I've used it a lot when it was available and I think it deserves its place in the lib, if not in Mojo::DOM, perhaps in Mojo::Util as a function.

This is the commit that it was removed, btw: 3e1051a7822331cf03e98db3274aa8b5e89698d0

:camel:

**Comment by kraih** [comment]
We want to bring it back. We are just waiting for someone to propose the correct behaviour for it, since the version that got removed had many problems.
