### ISSUE TITLE
Usability question: spurt(@lines)

### ISSUE THREAD

**Issue by shadowcat-mst** [kraih/mojo#1042]
It's very easy to, when e.g. copying from a filehandle into a file, to write

    path($path)->spurt(<$fh>);

which of course only writes the first line to the file.

Would adding a for loop around the syswrite seem reasonable? I can quite happily write e.g.

    path("${file}.gz")->spurt(scalar capture(gzip => -c => $file));

but it'd be nice to not need the 'scalar' there for it to DWIM.

**Comment by kraih** [comment]
Currently the scope of `Mojo::File` is limited to things we need in Mojolicious core, are there perhaps places in the code base where we could benefit from this?

**Comment by kraih** [comment]
This seems quite a bit more efficient than a loop.
```
diff --git a/lib/Mojo/File.pm b/lib/Mojo/File.pm
index 3d03a9597..e701c5383 100644
--- a/lib/Mojo/File.pm
+++ b/lib/Mojo/File.pm
@@ -90,7 +90,7 @@ sub slurp {
 }

 sub spurt {
-  my ($self, $content) = @_;
+  my ($self, $content) = (shift, join '', @_);
   open my $file, '>', $$self or croak qq{Can't open file "$$self": $!};
   ($file->syswrite($content) // -1) == length $content
     or croak qq{Can't write to file "$$self": $!};
```

**Comment by kraih** [comment]
We've talked a bit about this on IRC, and from now on we'll not artifically limit the scope of `Mojo::File`, but make new additions depend on votes. Personally, i'm indifferent on the feature, since i can't think of too many cases where it results in cleaner code.

**Comment by jhthorsen** [comment]
I'm neutral to this change as well. The only reason why I would be negative to this change is if `spurt` sometime in the future should take addition arguments.

**Comment by shadowcat-mst** [comment]
To me this isn't so much a feature as such as a "making what you'd expect to work, work" - and "making the prettier form of the code work". I read the documentation in advance and realised I needed to make my code ugly to work around the current API choice, but (a) I'm betting lots of people won't (b) Mojo APIs are normally elegant so this sticks out like a sore thumb to me.

**Comment by kraih** [comment]
Thanks everyone, this feature has been accepted. https://github.com/kraih/mojo/commit/bed400316c363c19ab030c3138c7820666427693

**Comment by shadowcat-mst** [comment]
\o/ much appreciated. Guess I'll be doing another opan release once this ships :D
