### ISSUE TITLE
MojoLite app with JSON data fails on commandline with Windows 

### ISSUE THREAD

**Issue by GwenDragon** [kraih/mojo#1043]
* Mojolicious version: 7.20
* Perl version:  Strawberry Perl 5.20.3.3 32bit
* Operating system: Windows 10 x64 1607 Build 14393.693

### Steps to reproduce the behavior
* program like example http://mojolicious.org/perldoc/Mojolicious/Guides/Tutorial#JSON does not work on Windows.
* create myapp.pl
```#!/usr/bin/env perl
use Mojolicious::Lite;

use strict;
use warnings;
use utf8;
use feature ':5.10';

get '/' => sub {
	my $c = shift;
	$c->render( template => 'index' );
};

post '/reverse' => sub {
	my $c    = shift;
	my $hash = $c->req->json;
	$hash->{test} = reverse $hash->{test};
	$c->render( json => $hash );
};

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'Welcome';
<h1>Welcome to the Mojolicious real-time web framework!</h1>
To learn more, you can browse through the documentation
<%= link_to 'here' => '/perldoc' %>.

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body><%= content %></body>
</html>
```
* call it with 
```
T:\>perl myapp.pl get -M POST -c '{"test":"12345"}' /reverse
[Mon Jan 23 09:42:53 2017] [debug] POST "/reverse"
[Mon Jan 23 09:42:53 2017] [debug] Routing to a callback
Use of uninitialized value in reverse at myapp.pl line 17.
[Mon Jan 23 09:42:53 2017] [debug] 200 OK (0.014405s, 69.420/s)
{"test":""}
```
* JSON is not read fromMojo  request
* But same code works on Linux with Perl 5.20!

### Expected behavior
The app detects sent JSON data and shows:
```
T:\>perl myapp.pl get -M POST -c '{"test":"12345"}' /reverse
[Mon Jan 23 09:42:53 2017] [debug] POST "/reverse"
[Mon Jan 23 09:42:53 2017] [debug] Routing to a callback
[Mon Jan 23 09:42:53 2017] [debug] 200 OK (0.014405s, 69.420/s)
{"test":"54321"}
```

### Actual behavior
The app does not detect sent JSON data

**Comment by kiwiroy** [comment]
Is this just the windows shell's interpretation of [single quotes](https://perlmaven.com/perl-on-the-command-line).

**Comment by GwenDragon** [comment]
My fault. Ich had to use double quotes and escape the double quotes in JSON parameter.

`perl myapp.pl get -M POST -c "{\"test\":\"12345\"}' /reverse`
works now!
