### ISSUE TITLE
default test from generate app returning 500 

### ISSUE THREAD

**Issue by senorsmile** [kraih/mojo#1047]
* Mojolicious version: 7.23
* Perl version: 5.24.0
* Operating system: Mac OS 10.12.3

### Steps to reproduce the behavior
```
# generate a new app
mojo generate app MyApp2

# first fix can't find application class "MyApp2"
vim t/basic.t
# use FindBin;
# require "$FindBin::Bin/../lib/MyApp2.pm";

#then run tests
prove t
#   Failed test '200 OK'
#   at t/basic.t line 10.
#          got: '500'
#     expected: '200'
# Looks like you failed 1 test of 3.

```

### Expected behavior
We should be seeing the test passing with a 200. 

### Actual behavior
We get a 500 response in the tests, but if I run the app with hypnotoad and curl localhost:8080, I get a 200. 

P.S.  While I feel comfortable with Perl, I know next to nothing about web programming (beyond sysadmin/http troubleshooting), so it's possible I'm just doing something wrong here.

**Comment by kraih** [comment]
Doesn't look like a bug to me i'm afraid, you're just using `prove` incorrectly.

**Comment by senorsmile** [comment]
Ah, you are right.  After rereading through initial tutorial, I see you can do one of: 

- `./myapp.pl test`
- `./myapp.pl test t/basic.t`
- `prove -l -v t/basic.t`

Indeed, even
`prove -l -v t/`
works perfectly.  

Sorry for the bad bug report.
