### ISSUE TITLE
Making the transition from Mojolicious::Lite to Mojolicious easier

### ISSUE THREAD

**Issue by kraih** [kraih/mojo#1058]
I think it would make sense to have a list of small recipes for translating `Mojolicious::Lite` idioms to `Mojolicious` in the documentation of `Mojolicious::Lite`. We use `Mojolicious::Lite` a lot in the documentation because it's so easy to demonstrate stuff, but for new users it can be quite a challenge to translate what they've just learned to full `Mojolicious` applications.
```perl
# Mojolicious::Lite
plugin 'Config';

# Mojolicious
$self->plugin('Config');
```
In the plugin docs we already have examples for both, but how much context should these recipes actually show?
```perl
=head1 NAME

Mojolicious::Lite - Micro real-time web framework

...

=head1 GROWING

A cheatsheet with hints for how to grow your L<Mojolicious::Lite>
prototype into a full L<Mojolicious> application.

=head2 Plugins

  # Mojolicious::Lite
  plugin 'Config';

  # Mojolicious
  sub startup {
    my $self = shift;
    $self->plugin('Config');
  }

=head2 Under

  # Mojolicious::Lite
  under '/foo';
  get '/bar' => sub {...};

  # Mojolicious
  sub startup {
    my $self   = shift;
    my $routes = $self->routes;
    my $under  = $routes->under('/foo');
    $under->get('/bar' => sub {...});
  }
```
What do you think? What's would be the best format for this? And what information would you include?

**Comment by s1037989** [comment]
On Thu, Feb 16, 2017 at 10:22 AM, Sebastian Riedel <notifications@github.com
> wrote:

> What do you think? What's would be the best format for this?


That sure seems reasonable to me, and it seems that it was very helpful
seeing similar formats in Plugins that I encountered.  Many would
demonstrate how to use the Plugin for both methods doing exactly what you
propose.

I reckon it's not possible to place them side by side?  I think it's
possible to do tables with Markdown, but I don't recall seeing table
support in POD?

**Comment by lindleyw** [comment]
http://www.pastebeest.com/FB   perhaps.

**Comment by ravenhall** [comment]
I think this is an excellent idea. I learned M::Lite first but found that I was often inflating them into full Mojolicious apps in the enterprise world. I spent a lot of time reading the Mojolicious code until it more or less clicked for me. So I think others would see a lot of value in this effort.

**Comment by kraih** [comment]
First step is done, now we can think about what else to add. https://github.com/kraih/mojo/commit/e0a149d1436fa15d09754045fd98c92921d28f51

**Comment by kberov** [comment]
Oh, I remember how I missed this! :+1:

**Comment by kraih** [comment]
I suppose this is done for now, we can just open new issues for more suggestions.
