### ISSUE TITLE
Example Mojo::UserAgent does not work

### ISSUE THREAD

**Issue by JJ** [kraih/mojo#1065]
* Mojolicious version: N/A
* Perl version: 5.20
* Operating system: Ubuntu server

### Steps to reproduce the behavior

Example in http://mojolicious.org/perldoc/Mojo/UserAgent

### Expected behavior

Download the page

### Actual behavior

`->get` works correctly and download, however, `result` does not seem to work. 

`Can't locate object method "result" via package "Mojo::Transaction::HTTP" at (eval 89)[/home/jmerelo/perl5/perlbrew/perls/perl-5.20.0/lib/5.20.0/perl5db.pl:732] line 2.`

I have installed the latest version of the module as far as I see it. The downloaded object contains a `res`
![screenshot from 2017-03-03 19 36 41](https://cloud.githubusercontent.com/assets/500/23563848/c3eb2de2-0048-11e7-82b0-92799b901d68.png)

The mentioned module seems to be up to date too.

**Comment by jberger** [comment]
The result method is fairly new (as of 7.13). Since you haven't included the Mojolicious version (as requested) I'm going to assume that that is your problem and close the ticket. If you do have a version greater than 7.13 please reopen the issue.

If you can't upgrade you may use the old-standard `res` method to the the response object, the major difference is handling connection errors.

**Comment by JJ** [comment]
I have included a screenshot showing that the class was up to date. Here's the same for Mojo::UserAgent (although the error does not belong to it)
![screenshot from 2017-03-03 20 21 23](https://cloud.githubusercontent.com/assets/500/23565735/18dc3638-004f-11e7-842e-07028acec6cb.png)
I'll include the 7.13 requirement in the `cpanfile` to see if I can cheat cpanm into upgrading it, but it does seem pretty convinced that the version is the last available.

**Comment by jberger** [comment]
You probably need to use a versioned module, in the Mojolicious dist that is only Mojolicious.

You can try `$ cpanm Mojolicious` or else `$ mojo version`.

**Comment by JJ** [comment]
That's exactly what I have done. 
![screenshot from 2017-03-03 20 24 12](https://cloud.githubusercontent.com/assets/500/23565838/7dc26ad6-004f-11e7-93f2-004ef298d1c7.png)
Maybe the problem is that the version available in the repos is not up to date?

**Comment by jberger** [comment]
You still are trying `Mojo::UserAgent` not `Mojolicious`

**Comment by jberger** [comment]
To clarify, the distribution is called Mojolicious and it contains Mojo::UserAgent. Installers try to be helpful and let you install a distribution by using a module name contained in the distribution and use that to install the distribution. Unfortunately this then doesn't handle versioning correctly. Please depend on Mojolicious not Mojo::UserAgent and it will work as expected.

**Comment by tyldum** [comment]
cpanm does not fetch the latest module if it already has some version installed that satisfy the requirements.
<code>cpanm --reinstall Mojolicious</code> is required.

**Comment by kraih** [comment]
This topic is most definitely out of scope for the Mojolicious documentation. Maybe try asking the `cpanm` maintainers for a tutorial, we wouldn't mind linking to that.

**Comment by TanyaSahni9** [comment]
Hi I am facing same issue although my Mojolicious is upto dated.. I am unable to use Mojo::UserAgent..

<img width="685" alt="Screenshot 2019-06-02 at 12 03 39 PM" src="https://user-images.githubusercontent.com/43196827/58756611-89e53300-852e-11e9-98a2-69b6aec69bfd.png">

**Comment by christopherraa** [comment]
@TanyaSahni9 The module `Mojo::UserAgent` is part of the `Mojolicious` distribution. You do not need to install that separately. If you have installed `Mojolicious` by running `cpanm Mojolicious` you shold be good to go. To test it you could run `perl -e 'use Mojo::UserAgent;'` in your shell. If you get no output then Mojolicious is installed.

**Comment by JJ** [comment]
@TanyaSahni9 try `cpanm --reinstall Mojolicious` as suggested by @tyldum

**Comment by TanyaSahni9** [comment]
@christopherraa I am able to run the mentioned command and there is no output so Mojo::UserAgent is working fine, although the program using ```use Mojo::UserAgent``` is still showing this error.


<img width="747" alt="Screenshot 2019-06-02 at 4 42 03 PM" src="https://user-images.githubusercontent.com/43196827/58758945-95982000-8555-11e9-9193-41591d37628b.png">



@JJ  Yes I tried that too..

**Comment by christopherraa** [comment]
@TanyaSahni9 I'm afraid it is hard to help without seeing your code or how the environment is set up. In any case; your issue is unrelated to this Github issue, so I suggest you come to IRC (https://kiwiirc.com/nextclient/#irc://irc.freenode.net/mojo) or the mailing list (http://groups.google.com/group/mojolicious). Those channels are meant for general support and have many skilled people who I am sure are willing to help.

**Comment by TanyaSahni9** [comment]
@christopherraa Only adding ```use Mojo::UserAgent```  in code gives the error.. Thanks for the links.. :)
