### ISSUE TITLE
Mojolicious Daemon server issue

### ISSUE THREAD

**Issue by choprashr** [kraih/mojo#1068]
* Mojolicious version: 7.24
* Perl version: ActivePerl 5.22
* Operating system: Windows Server 2008

### Steps to reproduce the behavior
Inconsistency: Daemon web server unexpectedly goes to sleep  (stops responding once in a day). The issue is not reproducible in a consistent manned or with a specific set of steps. It just happens sometimes.

### Expected behavior
The server once started should always remain responsive

### Actual behavior
 Daemon web server in the command window unexpectedly goes to sleep  (stops responding once in a day). It just happens sometimes and needs a key press in the command window to continue processing
I use the following command to start the server: perl.exe ez_brochure_web daemon -i 0 
I tried -m option but it has no effect, the issue still ocuurs at times.
Please help if you have seen anything similar.

**Comment by kraih** [comment]
Without steps to reproduce the problem i'm afraid there is nothing we can do. And it does not sound like a bug on our side.

**Comment by xlat** [comment]
Just a proposition to reproduce : make a mouse selection in the command window, and every STDOUT/STERR will be locked until the selection mark will be removed.
If you were on that case, it would ne be a bug, but a (windows console) feature.

Note: I have collegue of mine that reported me that 'bug' a lot of time ;-)
