### ISSUE TITLE
Pluggable backends for Morbo

### ISSUE THREAD

**Issue by kraih** [kraih/mojo#1071]
Morbo works on Windows but is not particularly pleasant to use due to slow reload times. The same is true on most other operating systems if too many files are being watched and the harddisk is slow enough. So, it would be nice if we had support for pluggable backends, like `Mojo::Server::Morbo::Backend::Inotify`, with our current implementation being the default that we ship in the Mojolicious distribution (`Mojo::Server::Morbo::Backend::Simple` perhaps). You could switch between backends with a command line flag like `morbo -b Inotify script/myapp`.

**Comment by kraih** [comment]
`Mojo::Server::Morbo::modified_files` might need to be removed, but that's ok, it was only ever meant to be for our tests anyway.

**Comment by marcusramberg** [comment]
I think that's reasonable. I've started working on a branch for this feature. How do you feel about tying the command line to a ENV variable like MOJO_MORBO_BACKEND?

**Comment by kraih** [comment]
Makes sense, like `MOJO_REACTOR=Mojo::Reactor::EV`.

**Comment by marcusramberg** [comment]
I have some work in progress on my fork, but I've hit a snag. How should we handle the watch attribute? Seems like it should be moved into the Backend abstract class, but if so, should we deprecate it from Morbo.pm, or replace it with a shortcut like shift->backend->watch ?

**Comment by kraih** [comment]
Just deprecate what you don't need from the API.

**Comment by kraih** [comment]
Did we completely misjudge the demand for this feature? It's been a week and not a single backend has reached CPAN, even though we had multiple example implementations. Guess i might end up nominating this feature for removal in 8.0.

**Comment by marcusramberg** [comment]
I'm on vacation this week in Greece, but would like to release my inotify
backend once I get back home.

ons. 12. apr. 2017 kl. 16.17 skrev Sebastian Riedel <
notifications@github.com>:

**Comment by henriiik** [comment]
Hello!

I am interested in an Inotify backend, will you release yours @marcusramberg ? :)

**Comment by kraih** [comment]
@henriiik Sadly @marcusramberg has no interest in maintaining that module on CPAN. Anyone is welcome to adopt the code and release it.

**Comment by marcusramberg** [comment]
I think @kraih must have misunderstood me, as I said previously in this thread I wanted to release this module when I got back from my vacation. I've shipped it to CPAN now, and it's also available on github here:  
https://github.com/marcusramberg/mojo-server-morbo-backend-inotify

Contributions and improvements are welcome. :heart_eyes:

**Comment by henriiik** [comment]
Awesome! :)
