### ISSUE TITLE
Changing the mode of a unix domain socket

### ISSUE THREAD

**Issue by davehayes** [kraih/mojo#1072]
* Mojolicious version: 7.29
* Perl version: 5.20
* Operating system: FreeBSD 10.3-STABLE

In using this new http+unix domain socket listening scheme, I don't see any way to change the mode (a la chmod) of the socket. Is this an oversight or deliberate?

**Comment by marcusramberg** [comment]
@davehayes is there any reason you can't just change the socket mode with chmod? A unix socket is a file.

**Comment by davehayes** [comment]
You can, but you can't do this easily in an automated fashion without having to write a Mojolicious::Command for the express purpose of doing just a chmod. The socket is created deep inside Mojo::Server::Daemon and there's no hook for changing the mode. I've had to do something like [this](http://paste.scsys.co.uk/557600). It's clearly not perfect but it works around the issue. 

The use case I have here is a separate uid for each mojo app. In this case, you want the gid of the socket to match the nginx webserver's gid. You then want the permission of the domain socket to be `rw-`.

The default (and secure) umask is 022. In my case, I did not want to change the umask such that all other files my app may decide to write will have group write permissions turned on. I suspect some others will feel the same way.

**Comment by kraih** [comment]
There should be no need to fight with the listen locations when you have access to the `Mojo::Server::Daemon` instance.
```
my $daemon = Mojo::Server::Daemon->new(listen => ['http+unix://%2Ftmp%2Fmyapp.sock']);
chmod 0644, $daemon->start->ioloop->acceptor($daemon->acceptors->[0])->handle;
...
$daemon->run;
```

**Comment by davehayes** [comment]
I had no earthly clue I could get at the handle in that way. I did not understand that "acceptor" is a listener that can `accept()` connections. So that's a much better solution than mine (which admittedly was not hard). 

I assume that if, for some odd reason, I want to listen on multiple domain sockets, I'd do something like this?

```perl
for (@{ $daemon->acceptors }) {
   chmod 0660, $daemon->ioloop->acceptor($_)->handle;
}
```

I'm closing this issue because I now see two ways to change the socket mode without asking for mojolicious to change. I will comment that it might be nice for something more convenient and less opaque than the above ideas, but that's entirely up to you guys.

**Comment by davehayes** [comment]
For those googling this, `$daemon->ioloop->acceptor($daemon->acceptors->[0])->handle` is an `IO::Socket::UNIX` glob which will not chmod. You'll need to do something like this:

```perl
chmod 0644, $daemon->ioloop->acceptor($daemon->acceptors->[0])->handle->hostpath;
```

Note that this assumes that the handle is an `IO::Socket::UNIX`.
