### ISSUE TITLE
Allow setting the configuration file directory

### ISSUE THREAD

**Issue by preaction** [kraih/mojo#1075]
I have a project with multiple different Mojolicious applications, each with their own moniker and mode-specific configuration files. To keep these configuration files separate from the root folder, I want to change the directory they are in, but I want to keep all of the other Mojolicious::Plugin::Config behavior like the `MOJO_CONFIG` override and mode-specific configuration files. I also do not want to change the home directory since that is used to resolve many other things like templates and static files (which would require me to also explicitly configure those things, some of which I might not know about).

But Mojolicious::Plugin::Config only allows me to specify the absolute path to a config file. So, in order to only change the directory searched for config files, I need to replicate all the other functionality: https://github.com/cpan-testers/cpantesters-api/blob/542b5836a354ac9fa4b7f3c29de4feb16d9823ff/bin/cpantesters-legacy-metabase#L38-L44 In addition to needing to replicate this functionality, it will need to be tested. In a Mojolicious::Lite application especially, it is difficult to test the different logic branches.

If there was a way to set the config directory, the linked code above could be simplified to:

```
app->moniker( 'metabase' );
plugin Config => (
    path => app->home->child( 'etc' ),
);
```

And the accompanying test would only need to check that the `dir` is set correctly (easy to do in Mojolicious::Lite apps).

If this change is approved, I can submit an implementation and tests for all the core configuration plugins.

**Comment by jhthorsen** [comment]
Mode still works, even you set "file":

```
$ echo "{foo=>1}" > etc/foo.conf
$ echo "{foo=>2}" > etc/foo.production.conf
$ perl -Mojo -lE'plugin config => {file => app->home->child(qw(etc/foo.conf))}; say app->config->{foo}'
1
$ MOJO_MODE=production perl -Mojo -lE'plugin config => {file => app->home->child(qw(etc/foo.conf))}; say app->config->{foo}'
2
```

And if you want MOJO_CONFIG to override this, then you could just do:

```
plugin config => {file => $ENV{MOJO_CONFIG} || app->home->child(qw(etc/foo.conf))};
```

**Comment by marcusramberg** [comment]
Closing this as @jhthorsen's suggestion seems like it solves the use case outlined.
