### ISSUE TITLE
Mojolicious 7.29 route under callback can't work

### ISSUE THREAD

**Issue by darrenli912** [kraih/mojo#1076]
* Mojolicious version: 7.29
* Perl version: 5.18
* Operating system: OSX 10.11.6

### Steps to reproduce the behavior
my code: copy from cpan example.

```
my $auth = $r->under('/' => sub {
  my $c = shift;
 
  # Authenticated
  return 1 if $c->req->headers->header('X-Bender');
 
  # Not authenticated. 
  $c->render(text => "You're not Bender.", status => 401);

  return undef;
});
$auth->get('/blackjack')->to('hideout#blackjack');
```

### Expected behavior
Render  json and text correctly under Not authenticated . 
### Actual behavior
 I tested some previous Mojolicious versions. It can't render json, for example:

```
$c->render(json => {error=>"You're not Bender."});
```

Now the latest version, both of them can't work.

[Mon Mar 27 10:52:33 2017] [debug] GET "/"
[Mon Mar 27 10:52:33 2017] [debug] Template "not_found.development.html.ep" not found
[Mon Mar 27 10:52:33 2017] [debug] Template "not_found.html.ep" not found
[Mon Mar 27 10:52:33 2017] [debug] Rendering template "mojo/debug.html.ep"
[Mon Mar 27 10:52:33 2017] [debug] Rendering template "mojo/menubar.html.ep"
[Mon Mar 27 10:52:33 2017] [debug] 404 Not Found (0.064445s, 15.517/s)

**Comment by jhthorsen** [comment]
How do you expect the under callback to be triggered, when you request `GET /`? From the example code above, you need to request `GET /blackjack`:

```
$ perl example.pl get /blackjack
[Mon Mar 27 13:01:29 2017] [debug] GET "/blackjack"
[Mon Mar 27 13:01:29 2017] [debug] Routing to a callback
[Mon Mar 27 13:01:29 2017] [debug] 401 Unauthorized (0.000568s, 1760.563/s)
You're not Bender.
```
