### ISSUE TITLE
Handling invalid Content-Length headers in UA

### ISSUE THREAD

**Issue by genio** [kraih/mojo#1077]
* Mojolicious version: 7.29
* Perl version: 5.24.1
* Operating system: MacOS Sierra

### Steps to reproduce the behavior
As was pointed out in [LWP::UserAgent Issue #86](https://github.com/libwww-perl/libwww-perl/issues/86) when a server provides a ```Content-Length``` header that is greater than the actual length of the content provided by the server, ```Mojo::UserAgent``` responds with a ```200 OK``` response.

```perl
#!/usr/bin/env perl

use strict;
use warnings;
use Data::Dumper::Concise;
use Plack::Loader;
use Test::TCP;
use v5.24;

my $server = Test::TCP->new(code => sub {
    my $port = shift;
    my $app = sub {
        my $content = "hello world\n";
        [
            200,
            ['Content-Length' => 10000], # bigger than acutual content length
            [$content],
        ];
    };
    Plack::Loader->load('Standalone', port => $port)->run($app);
});
my $url = "http://localhost:" . $server->port;

{
    use LWP::UserAgent;
    my $ua = LWP::UserAgent->new;
    my $res = $ua->get($url);
    warn "LWP::UserAgent: ", $res->status_line, "\n";
}

{
    use Mojo::UserAgent;
    my $ua = Mojo::UserAgent->new();
    my $res = $ua->get($url);
    warn "Mojo::UserAgent: ", $res->result->code, " ", $res->result->message, "\n";
}

{
    use HTTP::Tiny;
    my $ua = HTTP::Tiny->new();
    my $res = $ua->get($url);
    warn "HTTP::Tiny: ", $res->{status}, "\n";
}
```

### Expected behavior
Through reading the RFCs [HTTP/1.1 last paragraph of section 4.4](https://tools.ietf.org/html/rfc2616#section-4.4) it seems as if the```200 OK``` response is still valid, but a ```warn``` should be emitted about the content discrepancy.

Other user agents such as Curl do this. Some Perl UAs handle it slightly differently, but the RFC makes it seem like a warning should suffice.

### Actual behavior
The ```200 OK``` response is provided with no indication of the discrepancy.

**Comment by genio** [comment]
Sorry, I meant to quote the pertinent part of the RFC as well:

```
When a Content-Length is given in a message where a message-body is
allowed, its field value MUST exactly match the number of OCTETs in
the message-body. HTTP/1.1 user agents MUST notify the user when an
invalid length is received and detected.
```

**Comment by pink-mist** [comment]
Quoted from #mojo IRC:
```
10:53 <sri> genio: warnings seem kinda pointless
10:54 <sri> you don't warn about a security issue, you throw a loud exception
```

This is what I would like to see for this kind of thing.

**Comment by genio** [comment]
@kraih fiery death is perfectly ok with me.

**Comment by jhthorsen** [comment]
How about setting `$tx->res->error` ?

**Comment by marcusramberg** [comment]
I think @jhthorsen's error idea is more consistent with how the UA works in general.

**Comment by genio** [comment]
In setting ```$tx->result->error```, does that not imply that you should also set the return code? If so, are you suggesting using the ```599``` code like HTTP::Tiny?

**Comment by Grinnz** [comment]
Mojo::UserAgent has a convention where only the error message (and not code) is set for transport errors, which would IMO be appropriate for this error as well. It would also cause the new ->result method to die like transport errors do.

**Comment by genio** [comment]
Ah. Thanks for the explanation.  Sounds good to me.

**Comment by genio** [comment]
After several faltering attempts to address this (non-)issue, it seems to me that it would be more troublesome to work out a "fix" than to just continue on as is.  Every attempt made thus far just introduces more problems than it tries to solve.
