### ISSUE TITLE
Logging fails when the input String is long

### ISSUE THREAD

**Issue by gudupa** [kraih/mojo#1081]
* Mojolicious version: 5.28
* Perl version: 5.10.1
* Operating system: Linux

### Steps to reproduce the behavior
In a mojo based application, add a logging statement which logs a long string. For example
warn '*' x 1000;   ( Or a higher number)

### Expected behavior
It should be successful.

### Actual behavior
It fails with the following exception.
  '-stacktrace' => 'Can\'t write to log:  at /usr/lib/perl5/site_perl/5.10.1/Mojo/Log.pm line 34
        Mojo::Log::append(\'Mojo::Log=HASH(0xa0de7a8)\', \'[Tue Mar 28 13:03:28 2017] [debug] 200 OK (1.248654s, 0.801/s).
\') called at /usr/lib/perl5/site_perl/5.10.1/Mojo/Log.pm line 78
        Mojo::Log::_message(\'Mojo::Log=HASH(0xa0de7a8)\', \'debug\', \'200 OK (1.248654s, 0.801/s).\') called at /usr/lib/perl5/site_perl/5.10.1/Mojo/EventEmitter.pm line 15
        Mojo::EventEmitter::emit(\'Mojo::Log=HASH(0xa0de7a8)\', \'message\', \'debug\', \'200 OK (1.248654s, 0.801/s).\') called at /usr/lib/perl5/site_perl/5.10.1/Mojo/Log.pm line 54
        Mojo::Log::log(\'Mojo::Log=HASH(0xa0de7a8)\', \'debug\', \'200 OK (1.248654s, 0.801/s).\') called at /usr/lib/perl5/site_perl/5.10.1/Mojo/Log.pm line 38
        Mojo::Log::debug(\'Mojo::Log=HASH(0xa0de7a8)\', \'200 OK (1.248654s, 0.801/s).\') called at /usr/lib/perl5/site_perl/5.10.1/Mojolicious/Controller.pm line 210

**Comment by s1037989** [comment]
Perl: 5.22.1
Mojolicious: 7.29

```
get '/' => sub {
  my $c = shift;
  $c->app->log->warn('*' x 10000);
  $c->render(template => 'index');
};
```

I have *no* issues with a long logging statement.

**Comment by gudupa** [comment]
Thanks for looking into it. Do you think it is because of mojo version 5.28?

**Comment by marcusramberg** [comment]
Can't reproduce this either. Please write a failing test if you believe this to still be an issue.
