### ISSUE TITLE
Can't locate Mojo/IOLoop.pm in @INC (you may need to install the Mojo::IOLoop module)

### ISSUE THREAD

**Issue by adrianmihalko** [kraih/mojo#1091]
* Mojolicious version: latest
* Perl version: v5.18.2
* Operating system: Ubuntu 14.04

### Steps to reproduce the behavior
I am trying to use [this code,](https://www.domoticz.com/forum/viewtopic.php?t=3183) but I am getting the following error:

Can't locate Mojo/IOLoop.pm in @INC (you may need to install the Mojo::IOLoop module) (@INC contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at envisalink_domoticz.pl line 9.
BEGIN failed--compilation aborted at envisalink_domoticz.pl line 9.

On Line 9 is:

use Mojo::IOLoop;

It is possible to install Mojo::IOLoop;? I installed Mojo like this:

curl -L https://cpanmin.us | perl - -M https://cpan.metacpan.org -n Mojolicious

```
@ubuntu:~/domoticz/userscripts$ sudo curl -L https://cpanmin.us | perl - -M https://cpan.metacpan.org -n Mojolicious
[sudo] password for madrian: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  298k  100  298k    0     0   461k      0 --:--:-- --:--:-- --:--:--  645k
--> Working on Mojolicious
Fetching https://cpan.metacpan.org/authors/id/S/SR/SRI/Mojolicious-7.31.tar.gz ... OK
Configuring Mojolicious-7.31 ... OK
==> Found dependencies: IO::Socket::IP
--> Working on IO::Socket::IP
Fetching https://cpan.metacpan.org/authors/id/P/PE/PEVANS/IO-Socket-IP-0.39.tar.gz ... OK
Configuring IO-Socket-IP-0.39 ... OK
Building IO-Socket-IP-0.39 ... OK
Successfully installed IO-Socket-IP-0.39
! Installing the dependencies failed: Module 'IO::Socket::IP' is not installed
! Bailing out the installation for Mojolicious-7.31.
1 distribution installed
```

Thank you,
Adrian

**Comment by jberger** [comment]
As you can see in the output you posted, the installation failed because a prerequisite module (IO::Socket::IP) failed to install. You would have to see why that failed (running cpanm with -v helps sometimes).

Additionally, the Mojolicious project doesn't like using the github issue queue for support questions. If you need additional assistance please contact us via one of our documented support channels: http://mojolicious.org/perldoc/Mojolicious/Guides/Contributing#SUPPORT
