### ISSUE TITLE
May be bug. Can not return status 1xx.

### ISSUE THREAD

**Issue by Logioniz** [kraih/mojo#1095]
* Mojolicious version: 7.31
* Perl version: 5.22
* Operating system: Ubuntu 16.04.2

### Steps to reproduce the behavior
Run simple test
```perl
use Mojo::Base -strict;

use Test::More;
use Mojolicious::Lite;
use Test::Mojo;

get '/' => sub { shift->rendered(102) };

Test::Mojo->new->get_ok('/')->status_is(102);

done_testing;

```

### Actual behavior
Test failed

```
$ prove -v 1.pl 
1.pl .. [Wed May 17 20:34:57 2017] [debug] GET "/"
[Wed May 17 20:34:57 2017] [debug] Routing to a callback
[Wed May 17 20:34:57 2017] [debug] 102 Processing (0.000339s, 2949.853/s)
# Premature connection close

not ok 1 - GET /
not ok 2 - 102 Processing

#   Failed test 'GET /'
#   at 1.pl line 9.

#   Failed test '102 Processing'
#   at 1.pl line 9.
#          got: undef
#     expected: '102'
1..2
# Looks like you failed 2 tests of 2.
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/2 subtests 

Test Summary Report
-------------------
1.pl (Wstat: 512 Tests: 2 Failed: 2)
  Failed tests:  1-2
  Non-zero exit status: 2
Files=1, Tests=2, 15 wallclock secs ( 0.02 usr  0.00 sys +  0.22 cusr  0.02 csys =  0.26 CPU)
Result: FAIL
$
```

### Expected behavior
The test should be successful, isn't it?

### Workaround
May be anyone know workaround for mojo 7.31 which return http 102?

**Comment by marcusramberg** [comment]
I don't believe this is a bug, 1xx responses are interim responses that tell the client to expect a proper response soon, it doesn't make sense to it as a response to a request.  See for instance how 100-continue is supported in our test suite https://github.com/kraih/mojo/blob/master/t/mojo/user_agent.t#L590
