### ISSUE TITLE
Version 7.31 breaks REST::Neo4p

### ISSUE THREAD

**Issue by arobthearab** [kraih/mojo#1098]
* Mojolicious version: 7.31
* Perl version: 5.18.2 (Ubuntu) / 5.10.1 (CentOS 6)
* Operating system: Ubuntu 14.04.5 LTS (trusty) / CentOS release 6.8 (final)

### Steps to reproduce the behavior
perl -MCPAN -e"install REST::Neo4p" _without_ Mojolicious installed (pulls 7.31 as required)

### Expected behavior
REST::Neo4p should install without errors.

### Actual behavior
Reading '/u0/arobinso/.cpan/Metadata'
  Database was generated on Tue, 23 May 2017 12:41:02 GMT
Running install for module 'REST::Neo4p'
Running make for M/MA/MAJENSEN/REST-Neo4p-0.3012.tar.gz
Checksum for /u0/arobinso/.cpan/sources/authors/id/M/MA/MAJENSEN/REST-Neo4p-0.3012.tar.gz ok

  CPAN.pm: Building M/MA/MAJENSEN/REST-Neo4p-0.3012.tar.gz

Server for live tests: [http://127.0.0.1:7474 ]http://127.0.0.1:7474 
Username: [ ]Pass: [ ]Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'REST-Neo4p' version '0.3012'
Building REST-Neo4p
  MAJENSEN/REST-Neo4p-0.3012.tar.gz
  ./Build -- OK
Running Build test
t/0010_load.t ............... ok
t/0011_parse.t .............. ok
t/002_agent.t ............... 
Dubious, test returned 255 (wstat 65280, 0xff00)
All 17 subtests passed 
t/003_objs.t ................ ok
t/0041_idx_create_unique.t .. ok
t/004_idx.t ................. ok
t/0051_handle.t ............. ok
t/005_db.t .................. ok
t/006_query.t ............... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/43 subtests 
t/007_accessors.t ........... ok
t/008_batch_agent.t ......... ok
t/009_batch.t ............... ok
t/010_batch_synopsis.t ...... ok
t/011_neo4p_synopsis.t ...... ok
t/020_constraint.t .......... ok
t/021_validation.t .......... ok
t/022_constrain.t ........... ok
t/023_constrain_synopsis.t .. ok
t/030_idx_escape.t .......... ok
t/040_v2_labels.t ........... ok
t/041_v2_txns.t ............. 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 19/29 subtests 
t/050_v2_schema.t ........... ok
t/097_parse_errors.t ........ ok
t/098_pod.t ................. skipped: Test::Pod 1.00 required for testing POD
t/099_error.t ............... ok
t/agent_mod.t ............... ok
t/issue_5.t ................. ok
t/rt_80150.t ................ ok
t/rt_80196.t ................ ok
t/rt_80471.t ................ ok
t/rt_81128.t ................ ok
t/rt_90072.t ................ ok
t/rt_91640.t ................ ok
t/rt_91748.t ................ ok
t/rt_92135.t ................ ok
t/rt_96847.t ................ ok

Test Summary Report
-------------------
t/002_agent.t             (Wstat: 65280 Tests: 17 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/006_query.t             (Wstat: 65280 Tests: 43 Failed: 1)
  Failed test:  30
  Non-zero exit status: 255
t/041_v2_txns.t           (Wstat: 65280 Tests: 10 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 29 tests but ran 10.
Files=36, Tests=1868, 28 wallclock secs ( 0.27 usr  0.05 sys +  9.80 cusr  1.11 csys = 11.23 CPU)
Result: FAIL
  MAJENSEN/REST-Neo4p-0.3012.tar.gz
  ./Build test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports MAJENSEN/REST-Neo4p-0.3012.tar.gz
Running Build install
  make test had returned bad status, won't install without force
[root@vector REST-Neo4p-0.3012-D4I_ep]# 

RESOLUTION
-------------
Use cpanm to remove Mojolicious 7.31 and install version in Ubuntu repository (4.63)

**Comment by jberger** [comment]
There were some changes that CPAN modules had to make given deprecated/removed functionality around this time. Those changes were made per the Mojolicious deprecation policy. Therefore I don't think this is a bug in Mojolicious and I recommend filing a bug on the module in question.
