### ISSUE TITLE
Controller action called twice when `under`

### ISSUE THREAD

**Issue by dim0xff** [kraih/mojo#1105]
* Mojolicious version: 7.36
* Perl version: perl-5.24.1
* Operating system: Linux 4.11.9-1-ARCH

### Steps to reproduce the behavior
1. Create app `mojo generate app MyApp`
2. Add code into `MyApp.pm` to `startup` subroutine
```
  my $load = $r->under('/load/:id')->to('example#load');
  my $show = $load->under('/show');
  $show->get('/')->to('example#show');
```
3. Add code into `MyApp::Controller::Example`
```
sub load {
    my $c = shift;

    my $id = $c->stash('id');
    warn "Element '$id' loaded\n";

    1;
}

sub show {
    my $c = shift;

    $c->render( text => $c->stash('id') );
}
```
4. Get `show` endpoint
```
./script/my_app get /load/THE_ID/show
```

### Actual behavior
Action `load` is called twice here:
```
[Thu Jul 13 21:32:54 2017] [debug] GET "/load/THE_ID/show"
[Thu Jul 13 21:32:54 2017] [debug] Routing to controller "MyApp::Controller::Example" and action "load"
Element 'THE_ID' loaded
[Thu Jul 13 21:32:54 2017] [debug] Routing to controller "MyApp::Controller::Example" and action "load"
Element 'THE_ID' loaded
[Thu Jul 13 21:32:54 2017] [debug] Routing to controller "MyApp::Controller::Example" and action "show"
[Thu Jul 13 21:32:54 2017] [debug] 200 OK (0.001766s, 566.251/s)
THE_ID
```

### Expected behavior
But should be called only once.
I can't reproduce it when use `Mojolicious::Lite`
And I can disable this behavior by this code in `MyApp.pm`:
```
#  my $show = $load->under('/show');
  my $show = $load->under('/show' => sub {1} );
```

**Comment by Grinnz** [comment]
The routing is incorrect, you've told it to use the example#load action twice, each "under" call is a new subroute. It should be:

```
  my $load = $r->under('/load/:id')->to('example#load');
  my $show = $load->any('/show');
  $show->get('/')->to('example#show');
```

**Comment by dim0xff** [comment]
> The routing is incorrect, you've told it to use the example#load action twice
>
Where have I told it to use twice?

**Comment by dim0xff** [comment]
>By passing sub {1} you gave it an action for the second "under" to use instead of the example#load it was using from the parent.
>
Sure, I understand this. Just thought that without arguments it have to work like `any`

**Comment by Grinnz** [comment]
"under" and "any" are different, regardless of the arguments. "under" immediately creates an intermediate route, "any" only creates a route if no child routes are added. Whether you call ->to or not on them does not change this. If ->to is not called and a callback is not provided, the controller and action from the parent are still in the stash so they will be used.
