### ISSUE TITLE
Memory leak in Mojo::URL

### ISSUE THREAD

**Issue by degeberg** [kraih/mojo#1114]
* Mojolicious version: git 7f48299d67 (current master)
* Perl version: 5.24.2
* Operating system: Arch Linux and Ubuntu 16.04.2 LTS

### Steps to reproduce the behavior

Run the following script and watch memory usage climb:
```perl
use Mojo::URL;

my $url = Mojo::URL->new('https://www.google.com');

for my $i (0..19999999999) {
    print "$i\n";
    my $url2 = $url->clone;
    $url2->query({foo => 1});
    $url2->to_string();
}
```

### Expected behavior
No memory leaks.

### Actual behavior
Memory leaks.

**Comment by kraih** [comment]
Can't confirm this.

**Comment by degeberg** [comment]
I forgot to add that it only seems to affect perl 5.24 and not 5.26. Did you try using 5.24?

**Comment by kiwiroy** [comment]
For Mojolicious `7.37` from CPAN, I can reproduce this in `5.24.1` on `macOS 10.12.5`, but not `5.26.0`.

Adding `use Devel::LeakTrace;` to @degeberg's case, points to [Mojo::Util#319](https://github.com/kraih/mojo/blob/master/lib/Mojo/Util.pm#L319)

```
leaked AV(0x35272170) from /Users/kiwiroy/.perlbrew/libs/perl-5.24.1@random/lib/perl5/Mojo/Util.pm line 319
leaked AV(0x35272188) from /Users/kiwiroy/.perlbrew/libs/perl-5.24.1@random/lib/perl5/Mojo/Util.pm line 319
leaked SV(0x352721a0) from /Users/kiwiroy/.perlbrew/libs/perl-5.24.1@random/lib/perl5/Mojo/Util.pm line 319
...
```
**Code:**
```perl
use Devel::LeakTrace;
use Mojo::URL;

my $url = Mojo::URL->new('https://www.google.com');

for my $i (0..10) {
    print "$i\n";
    my $url2 = $url->clone;
    $url2->query({foo => 1});
    $url2->to_string();
}
```

```bash
$ perlbrew use 5.24.1@random
$ prove -l t/mem-leak.t 2>&1 | grep ^leaked | wc -l
     192
$ perlbrew use 5.26.0@random
$ prove -l t/mem-leak.t 2>&1 | grep ^leaked | wc -l
      38
## vast majority of the 38 are Encode or Encode::Alias
```

**Comment by kraih** [comment]
Should be resolved with https://github.com/kraih/mojo/commit/a7cdf6fb2c60c28ac4ab9ffad0e528bb23b0f7b8.

**Comment by degeberg** [comment]
I can confirm that it no longer leaks memory on 5.24.2.

**Comment by kraih** [comment]
Great, thanks.
