### ISSUE TITLE
Error for "no template found" in Mojolicious::Lite app misleading

### ISSUE THREAD

**Issue by pplu** [kraih/mojo#1116]
* Mojolicious version: 7.37
* Perl version: 5.22.1 (via plenv)
* Operating system: Ubuntu Linux

### Steps to reproduce the behavior
execute https://github.com/Humanstate/net-oauth2-authorizationserver/blob/master/examples/oauth2_client.pl

When the oauth server redirects to `/auth?code=XXXXX`, Mojo returns an error

### Expected behavior
Mojo to return an error saying it hasn't found a template suitable for the auth action

### Actual behavior
I got an error with:
"None of these routes could generate a response for your GET request for /auth, maybe you need to add a new one?" and a table clearly stating that I had an endpoint for `/auth`.

Finally the error got solved by putting
```
@@ auth.html.ep
% layout 'default';
You are connected
```
in the templates section, but it took some time for me to get there (trying with `any`, instead of `get`, for example), since the error message was telling me to follow another path.

**Comment by marcusramberg** [comment]
When I try your example, I get redirected to /oauth/authorize with a message about that endpoint not matching any routes, which is correct according to the routing table below. Not sure how adding an auth template would fix this. Typically if you have an endpoint that doesn't render anything, you will get no response, with this debug message in the log:

```
[Thu Sep  7 08:28:52 2017] [debug] Nothing has been rendered, expecting delayed response
```
Going to close this as it seems to be an user error.

**Comment by pplu** [comment]
Thanks for taking the time to reproduce. Now I know that it's probably an error on my side. I'll try to report back what it was if I find out (although this was just part of an experiment, so I don't have real need to get it working).
