### ISSUE TITLE
IOLoop timer not work with IPC::Run3 on Windows

### ISSUE THREAD

**Issue by tadegenban** [kraih/mojo#1123]
* Mojolicious version: 7.34
* Perl version: 5.20
* Operating system: Win7, Active Perl

### Steps to reproduce the behavior
use strict; use warnings; use 5.012;
use Mojo::IOLoop::ForkCall;
use IPC::Run3;
use POSIX;

Mojo::IOLoop->singleton->timer(1, sub { say '1s' });
my $pid = fork;
if ( ! $pid ) {
    run3('perl -e "sleep 10"', undef, \ my $stdout, \ my $stderr);
    #system('perl -e "sleep 10"');
    exit;
}
Mojo::IOLoop->singleton->recurring(1, sub { waitpid $pid, WNOHANG and Mojo::IOLoop->singleton->stop });

Mojo::IOLoop->singleton->start;

### Expected behavior
print following to screen:
1s

### Actual behavior
timer no work, NOTHING got on screen
If replace run3 with system, it will be OK.

**Comment by jberger** [comment]
This example is very confusing. You import Mojo::IOLoop::ForkCall though you don't use it. You fork manually but don't do important parts of ForkCall (or Mojo::IOLoop::Subprocess that make it DWYM) and windows is always a problem for forking since windows "fork" is emulated by threads. I highly recommend you just use Mojo::IOLoop::Subprocess to do this work since it really isn't trivial.

**Comment by jberger** [comment]
Subprocess and ForkCall use almost the same mechanism though perhaps you are right, the communication method for Subprocess I guess does exclude (native) Windows (though you can use WSL and Subprocess). The important parts include things like checking for process completion (without blocking) resetting the ioloop in the child, ignoring spurious handle closes etc etc. If you choose to do it on your own, please read the code of Subprocess and ForkCall carefully. Anyway, why not use ForkCall? Anyway Mojolicious really cannot support forking on (native) Windows.

**Comment by tadegenban** [comment]
@jberger, That's fine, I finally use system(1, @cmd) to do non-blocking sub-process in (native) windows, and wait the pid with WNOHANG in a ioloop timer, get the result through file, no fork and no pipe, which seems worked  well for me. On linux, i still use ForkCall. Thank you .
