### ISSUE TITLE
Need update documentation with Systemd and Hypnotoad 

### ISSUE THREAD

**Issue by dshadow** [kraih/mojo#1124]
* Mojolicious version: ANY
* Perl version: ANY
* Operating system: ANY with Systemd

I think it is worse way to run hypnotoad under root user. Could you please update documentation with User and Group options like in example below?

[Unit]
Description=My Perl service
Requires=network.target
After=network.target

[Service]
**User=testuser1
Group=testuser1**
Type=simple
Restart=always
SyslogIdentifier=testperlservice
PIDFile=/home/testuser1/tmp/testperlservice.pid
ExecStart=/usr/local/bin/hypnotoad /home/testuser1/script/test -f
ExecStop=/usr/local/bin/hypnotoad -s /home/testuser1/script/test
ExecReload=/usr/local/bin/hypnotoad /home/testuser1/script/test

**Comment by kraih** [comment]
Your example changes more than just user/group and you don't elaborate on why that's significant or mention the problem of binding to privileged ports. Don't like this at all.

**Comment by dshadow** [comment]
I talk about User and Group in [Service] section... You don't need to use all other lines from it...

**Comment by kraih** [comment]
Well, i'll leave this open for discussion, maybe someone else has a more complete proposal.

**Comment by jhthorsen** [comment]
I would like to have `User`and `Group` in the documentation. I always include that in my systemd files.

**Comment by Grinnz** [comment]
It is good practice, but you cannot do it if you want to bind to a privileged port, as mentioned. You must drop privileges after binding such as with https://metacpan.org/pod/Mojolicious::Plugin::SetUserGroup.

**Comment by dshadow** [comment]
I think both solutions must be included in documentation... Many people use apache/nginx behind hypnotoad without privileged port...

**Comment by jberger** [comment]
The question of course is how far to take the documentation of systemd in the mojo docs. Clearly we cannot document every systemd parameter in our documentation, that said, since we do encourage reverse proxy deployment perhaps some discussion of how systemd is best configured to do so is worth a thought.

**Comment by kraih** [comment]
While i agree that we could mention more deployment scenarios in the cookbook, it does not look like this issue is moving in a particularly constructive direction. Therefore i'm closing it now. All of you are of course welcome to open a new issue with a more complete proposal.
