### ISSUE TITLE
hypnotoad reload needs to wait synchronously in order to work properly with systemd

### ISSUE THREAD

**Issue by rglaue** [kraih/mojo#1130]
* Mojolicious version: perl-Mojolicious-6.31-2.el7
* Perl version: perl-5.16.3-286.el7
* Operating system: CentOS 7.2

### Steps to reproduce the behavior
See full explanation here: https://stackoverflow.com/questions/11141068/how-to-reload-the-mojolicious-built-in-webserver-daemon/46080842#46080842

Follow the cookbook docs to manage hypnotoad with systemd, http://mojolicious.org/perldoc/Mojolicious/Guides/Cookbook#Hypnotoad

Execute the following:
root$ systemctl start hypnotoad-app
root$ systemctl reload hypnotoad-app

### Expected behavior
systemd `ExecReload=hypnotoad myapp.pl` should wait synchronously before returning. We don't want to loose the asynchronous reload functionality, so we probably want to add a flag to hypnotoad that is usable for systemd, like the following `ExecReload=hypnotoad --reload-wait myapp.pl`
Expected behavior, `hypnotoad myapp.pl` (reload) does not return to systemd until the new PID is in the PIDFile that systemd monitors for the process.

The stackoverflow answer in the above link provides a bash script wrapper to produce a synchronous reload for systemd.

### Actual behavior
systemd expects `ExecReload=hypnotoad myapp.pl` to be synchronous - that is to not return until the process has completely reloaded and changed PID.

The systemctl call to the ExecReload= command to reload hypnotoad-app returns immediately, and systemd monitors the PIDFile= thinking the reload is finished completely.
But because either the PID in PIDFile= changes, or because PIDFile is deleted and recreated, systemd thinks that hypnotoad server stopped, and the result is that systemd schedules a restart to hypnotoad-app. The hypnotoad-app ends up getting reloaded by hypnotoad, and then hypnotoad gets restarted by systemd.

The logs show this activity (systemd unit has configured `RestartSec=5`):
systemd: hypnotoad-app: Starting hot deployment for Hypnotoad server 29344.
systemd: Reloaded hypnotoad-app.
hypnotoad: Starting zero downtime software upgrade
hypnotoad: Listening at "http://127.0.0.1:4321"
hypnotoad: Manager 30065 started
systemd: hypnotoad-app: Server available at http://127.0.0.1:4321
hypnotoad: Upgrade successful, stopping 29344
systemd: hypnotoad-app: Hypnotoad server not running.
hypnotoad: Creating process id file "/var/run/hypnotoad-app.pid"
systemd: hypnotoad-app.service holdoff time over, scheduling restart.
systemd: Started hypnotoad-app.
systemd: Starting hypnotoad-app...
hypnotoad: Listening at "http://127.0.0.1:4321"
hypnotoad: Manager 30134 started
systemd: hypnotoad-app: Server available at http://127.0.0.1:4321
hypnotoad: Creating process id file "/var/run/hypnotoad-app.pid"

**Comment by Grinnz** [comment]
This has already been fixed in 7.01. (https://github.com/kraih/mojo/commit/25471294ef714e2116dd2bbe98de4893285c1121)

**Comment by marcusramberg** [comment]
Closing this as it's obsolete.
