### ISSUE TITLE
Mojolicious::Plugin::Config don't work if you are in a directory with special characters

### ISSUE THREAD

**Issue by ldidry** [kraih/mojo#1131]
* Mojolicious version: 7.45
* Perl version: 5.26
* Operating system: Debian Sid, but also on Debian Stretch (9, stable)

### Steps to reproduce the behavior
Create an app:
```
mojo generate app Test
```

Change app's directory name with a name containing special characters, like accents:
```
mv test tëst
```

Go to the directory and launch morbo or hypnotoad
```
cd tëst
morbo script/test
```

It fails:
```
Can't load application from file "/home/luc/tmp/tëst/script/test": Configuration file "/home/luc/tmp/tëst/script/../test.conf" missing, maybe you need to create it?
Compilation failed in require at (eval 93) line 1.
```

### Expected behavior
The application should not fail and should work normally.

### Actual behavior
The application crashes instantly.

**Comment by Grinnz** [comment]
This is a very peculiar issue that I can't explain yet:

    > script/test eval 'say 1'
    Configuration file "/home/grinnz/projects/tëst/script/../test.conf" missing, maybe you need to create it?
    > env MOJO_CONFIG=test.conf script/test eval 'say 1'
    1

**Comment by kraih** [comment]
Very annoying problem, not sure the fix is entirely correct, but at least this case now works.

**Comment by ldidry** [comment]
Thx! 👍

**Comment by Grinnz** [comment]
For reference, this is due to Perl's broken unicode filename handling:

https://rt.perl.org/Public/Bug/Display.html?id=130831

https://rt.perl.org/Public/Bug/Display.html?id=132224

**Comment by kraih** [comment]
I've reverted the change again. https://github.com/kraih/mojo/commit/402e35b0e8c47bc58d863a3799e60bd58d26eb06
