### ISSUE TITLE
Warnings when encoding to MIME-Header

### ISSUE THREAD

**Issue by Tekki** [kraih/mojo#1134]
* Mojolicious version: 7.46
* Perl version: 5.26.0 (Perlbrew)
* Operating system: Debian Jessie

### Steps to reproduce the behavior

Encode a name to MIME-Header:
```
use strict;
use warnings;
use utf8;
use feature 'say';

use Mojo::Util 'encode';

my $name = 'Rolf Stöckli';
say encode 'MIME-Header', $name;
```

### Expected behavior

Should print

`=?UTF-8?B?Um9sZiBTdMO2Y2tsaQ==?=`

### Actual behavior

Prints a lot of warnings
```
Use of uninitialized value in subroutine entry at /home/tekki/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.0/x86_64-linux/Encode/MIME/Header.pm line 243.
...
Use of uninitialized value in subroutine entry at /home/tekki/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.0/x86_64-linux/Encode/MIME/Header.pm line 243.
=?UTF-8?B?Um9sZiBTdMO2Y2tsaQ==?=
```

**Comment by Grinnz** [comment]
Mojo::Util::encode is just a wrapper for Encode. The following script has the same behavior.

```
use strict;
use warnings;
use utf8;
use feature 'say';

use Encode 'find_encoding';

my $name = 'Rolf Stöckli';
say find_encoding('MIME-Header')->encode($name);
```

**Comment by dotandimet** [comment]
Yep, looks like Perl 5.26 is the source of the warnings.

**Comment by Tekki** [comment]
If you `use Encode 'encode';` there are no warnings.
I'm not sure why, maybe because of `$check ||= 0;` at https://github.com/dankogai/p5-encode/blob/master/Encode.pm#L177.

**Comment by Tekki** [comment]
@Grinnz The following script gives no warnings on 5.26, and works fine on 5.14 and 5.20:
```
use strict;
use warnings;
use utf8;
use feature 'say';

use Encode 'find_encoding';

my $name = 'Rolf Stöckli';
say find_encoding('MIME-Header')->encode($name, 0);
```
Why not call it this way?

**Comment by kraih** [comment]
I guess we might just as well pass along the default if some encoding modules require it. https://github.com/kraih/mojo/commit/29f56b09a1eb5735ecb99a3aa5f7b2854cfa3e86
