### ISSUE TITLE
Mojo::UserAgent with Basic Authentication

### ISSUE THREAD

**Issue by thechane** [kraih/mojo#1137]
* Mojolicious version: 7.46
* Perl version: 5.16.3
* Operating system: Redhat 6 - 2.6.32-642.15.1.el6.x86_64

### Steps to reproduce the behavior
http basic auth works with Perl 5.10 and Mojo 4.88, but when trying the same thing with Mojo 7.46 and Perl 5.16 I get a different result. When I export the ENV var MOJO_USERAGENT_DEBUG=1 I can see that it is not pass inside the URL in 7.46 as it is in 4.8.8

```
use strict;
use warnings;
use Data::Dumper;
use Mojo::UserAgent;
use Mojo::URL;
use Mojolicious;

my $ua = Mojo::UserAgent->new();
print "Version : $Mojolicious::VERSION\n";
my $URL = Mojo::URL->new("http://127.0.0.1/hello:4567")->userinfo("username:pass#ord");
print $URL->userinfo . "\n";
$URL->port(4567);
print Dumper $ua->post( $URL => json => {} => { 'Accept' => "application/json" } )->res->json;
```
### Expected behavior
$ ./testMojo.pl              
Version : 4.88
username:pass#ord
-- Blocking request (http://username:pass%23ord@127.0.0.1:4567/hello:4567)
-- Connect (http:127.0.0.1:4567)

### Actual behavior
$ ./testMojo.pl              
Version : 7.46
username:pass#ord
-- Blocking request (http://127.0.0.1:4567/hello:4567)
-- Connect ee2484db5a598c04a9e52c8ce8076a12 (http://127.0.0.1:4567)

**Comment by Grinnz** [comment]
Mojo::URL no longer outputs the userinfo when stringified, this is a security feature. Is the behavior actually different otherwise? It should still be using the userinfo in the user agent request.

**Comment by thechane** [comment]
Thanks for responding, yes it is also failing to pass authentication checks on the server. I just created some more test scripts, looks like the # character in the password is causing it to fail. Will do some more tests a little later. Need to sleep now...

**Comment by thechane** [comment]
tired coding eyes were to blame. Went from:

```
my $URL = Mojo::URL->new("http://127.0.0.1/hello:4567")->userinfo("username:pass#ord");
#(stuff)
$ua->post( $URL . "/some/path" => json => {} => { 'Accept' => "application/json" } )->res->json
```
... to 

```
my $URL = Mojo::URL->new("http://127.0.0.1/hello:4567")->userinfo("username:pass#ord");
#(stuff)
my $tmpURL = $URL->clone;
$tmpURL->path("/some/path");
$ua->post( $URL => json => {} => { 'Accept' => "application/json" } )->res->json
```


... and now all is well.
