### ISSUE TITLE
Is installation on Windows possible?

### ISSUE THREAD

**Issue by millerbryan** [kraih/mojo#1138]
I would like to install the latest Mojo on Windows but want to be sure it is even possible before investing more time on it.  I have cygwin installed with gcc, make, and perl.  I would prefer to install under Strawberry Perl on native Windows but happy to install in the Cygwin context if that is the only path forward.

Thanks!

**Comment by Grinnz** [comment]
https://metacpan.org/pod/Mojolicious::Guides::FAQ#How-well-is-Windows-supported-by-Mojolicious?

For future reference, support questions are better directed at the support channels like the mailing list or IRC.

**Comment by millerbryan** [comment]
Thank you for the redirect?  I thought I had done my due diligence on the Mojo site.

**Comment by millerbryan** [comment]
That is not a helpful FAQ entry.  I have tried for a full day to install Mojolicious on Windows with no success.  And I am not a rank newbie either.

**Comment by jberger** [comment]
I'm sorry to hear you are having troubles installing on windows. We support windows with some minor exceptions. As Grinnz mentions, bug reports aren't how we prefer to handle support. If you are having a specific problem that appears to be a bug please post details so we can debug it as bug report. Otherwise please contact us via IRC or mailing list for support requests.

**Comment by millerbryan** [comment]
@jberger  Joel, if I get this figured out and documented is it worth adding to the FAQ?  I usually use Mojo::DOM on Linux with no issues so this is an interesting adventure...

**Comment by jberger** [comment]
I have no idea, I don't know what your problem is (still). We have many users on windows and have had no major issues reported. Since we've asked several times, I'm going to lock this issue. If it turns out that there is a bug, please report it as a new issue.

**Comment by jberger** [comment]
FYI, here are our preferred support channels: http://mojolicious.org/perldoc#SUPPORT
