### ISSUE TITLE
Routing guide does not explain how to use parameters

### ISSUE THREAD

**Issue by Altreus** [kraih/mojo#1140]
* Mojolicious version: 7.48
* Perl version: All
* Operating system: All

### Steps to reproduce the behavior
Read the guide on routing https://metacpan.org/pod/distribution/Mojolicious/lib/Mojolicious/Guides/Routing.pod

### Expected behavior
Routing guide explains how to define route variables and then how to access them in code

### Actual behavior
Routing guide explains how to define route variables and makes almost no mention of them for the rest of the document. It would be useful and take up little space to mention that

* Route variables can be accessed from `$c->param`
* And go in the stash

When I asked about this in IRC I was told that "this is the way the docs are designed" and "I should read them in order" but honestly that seems preposterous, so I'm going to assume that's not the actual recommended thing do to.

**Comment by kraih** [comment]
The stash even has its own section in the routing guide. http://mojolicious.org/perldoc/Mojolicious/Guides/Routing#Stash

**Comment by kraih** [comment]
I'm not sure what you think is missing, maybe you can elaborate further? Perhaps with a doc patch?

**Comment by kraih** [comment]
And this section in the tutorial appears to match your problem description exactly. http://mojolicious.org/perldoc/Mojolicious/Guides/Tutorial#Placeholders

**Comment by Altreus** [comment]
It's more an issue of the direction I came into the documentation. I already knew I could use the `:name` parameter style, so I assumed that looking in that section it would tell me how to use it.

I therefore had no impetus to look under "Stash", or in the tutorial, for more information on placeholders - I didn't know they went into the stash, and I'm beyond the tutorial.

I think the section on placeholders should at least link to information about how they are accessed.

**Comment by Grinnz** [comment]
https://metacpan.org/pod/distribution/Mojolicious/lib/Mojolicious/Guides/Routing.pod#Routes does say this:

```
A fundamental concept of the Mojolicious router is that extracted placeholder values are turned into a hash.
This hash is basically the center of every Mojolicious application, you will learn more about this later on.
```
which is elaborated on in the Stash section, but maybe it should use the term 'stash' there.

**Comment by jberger** [comment]
I agree that that would be a good place to mention (and probably link to) the stash. That said I want to push back against 

> and I'm beyond the tutorial

We state quite clearly [at the top of the documentation](http://mojolicious.org/perldoc#TUTORIAL) that the tutorial is "considered a prerequisite".

**Comment by kraih** [comment]
Looks like this discussion went stale and no consensus could be reached on where the documentation needs to be improved.
