### ISSUE TITLE
Getting undef when creating a instance of Mojo::DOM

### ISSUE THREAD

**Issue by vsephirothv** [kraih/mojo#1144]
* Mojolicious version: 7.48
* Perl version: 5.26.1
* Operating system: Win10 x64

### Steps to reproduce the behavior
Tried to parse the page: http://tcdecks.net/format.php?format=Pauper

### Expected behavior
The proper DOM instance, for me to get values out of it

### Actual behavior
Returned a undef value

Sample code
use strict;
use LWP::UserAgent;
use Mojo::DOM;

my $url = 'http://tcdecks.net/format.php?format=Pauper';

my $ua = LWP::UserAgent->new();
my $response = $ua->get( $url );
if ( $response->is_success ) {
   $response = $response->decoded_content;
   my $dom = Mojo::DOM->new( $response );
   # $dom is undef at this point
}

**Comment by kraih** [comment]
Works fine for me, i get the correct DOM structure.

**Comment by vsephirothv** [comment]
Hey, wait a minute, just because it Works for you, is auto-close in here? What kind of help is this?
IF it really worked, please send me a print using any code, $dom->at( '.span5' ) for exaqmple.

It gives no erros, just can't use any method because it is actually undef

**Comment by kraih** [comment]
We don't use GitHub for support requests, too few eyeballs. For help that's not bug related please go [here](http://mojolicious.org/perldoc#SUPPORT).
