### ISSUE TITLE
Section on how to read the docs

### ISSUE THREAD

**Issue by kraih** [kraih/mojo#1145]
This keeps coming up every now and then on IRC. I think we need a few sentences in `Mojolicious::Guides` that explain how to read the docs and that they are structured into a tutorial, multiple guides, and class references.

**Comment by kraih** [comment]
Perhaps the relation between `Mojolicious::Lite` and `Mojolicious` should be mentioned too. So readers know that they are not wasting their time with the tutorial.

**Comment by yusrideb** [comment]
Maybe mojolicious should have a good tutorial on Wikibooks. 
I have created a page on wikibooks for mojolicious, this can be developed together.

English : https://en.wikibooks.org/wiki/Mojolicious
Indonesian : https://id.wikibooks.org/wiki/Mojolicious

**Comment by jberger** [comment]
@yusrideb while I appreciate the enthusiasm, I worry that an empty book looks worse than no book at all. I also think that this is the wrong place to discuss that proposal, perhaps it could be taken to the mailing list?

**Comment by yusrideb** [comment]
If taken to mailing list, I agree. I only hope many more official tutorial or book about Mojolicious.

**Comment by kraih** [comment]
I have to agree with @jberger, people have a tendency to find that stuff via Google, and then it doesn't look good. For that reason i'm also removing the links from your comment.
