### ISSUE TITLE
Question regarding Mojo::UserAgent non-blocking example in cookbook

### ISSUE THREAD

**Issue by ronstudio** [kraih/mojo#1147]
* Mojolicious version: 7.46
* Perl version: 5.24
* Operating system: Windows 7

### Steps to reproduce the behavior
Hi All,

I have recently started learning how to write non-blocking http request and Mojo::UserAgent is the best one which can help me to overcome the proxy issue within the company environment.
While learning by following the example, there is something I do not understand from the code and raised a question in perlmonks:
http://www.perlmonks.org/?node_id=1202496;showspoiler=1202547-1

However, I am still clueless regarding the behaviour, could you ask your help in explaining it further?

http://mojolicious.org/perldoc/Mojolicious/Guides/Cookbook#Non-blocking

The following is the example code:
use Mojo::UserAgent;
use Mojo::IOLoop;

my @urls = (
  'mojolicious.org/perldoc/Mojo/DOM',  'mojolicious.org/perldoc/Mojo',
  'mojolicious.org/perldoc/Mojo/File', 'mojolicious.org/perldoc/Mojo/URL'
);

# User agent with a custom name, following up to 5 redirects
my $ua = Mojo::UserAgent->new(max_redirects => 5);
$ua->transactor->name('MyParallelCrawler 1.0');

# Use a delay to keep the event loop running until we are done
my $delay = Mojo::IOLoop->delay;
my $fetch;
$fetch = sub {

  # Stop if there are no more URLs
  return unless my $url = shift @urls;

  # Fetch the next title
  my $end = $delay->begin;
  $ua->get($url => sub {
    my ($ua, $tx) = @_;
    say "$url: ", $tx->result->dom->at('title')->text;
    $end->();

    # Next request
    $fetch->();
  });
};

# Process two requests at a time
$fetch->() for 1 .. 2;
$delay->wait;

At the end of the code, it has "$fetch->() for 1 .. 2;".
From the above code, I suppose the subroutine $fetch is an example of recursion.
Suppose if I remove the sequence / for-loop, should the code process 1 request a time until all the @urls have been processed?

However, from my testing, if the for-loop has been removed, the code will always process the first url only. This is the part that I don't understand. kcott from PerlMonks helped me to do some further testing and found that if the following 2 lines are commented out:
# my $end = $delay->begin;
..
  # $send->();
  
a single $fetch->() would process all URLs.

Could I ask your help in understanding this IOLoop behaviour?

Thanks,
Ronald

**Comment by ronstudio** [comment]
I am sorry for the formatting in above post. (I'm using an outdated Chrome in office environment)

**Comment by s1037989** [comment]
Github issues are not the place for asking for help.  Can you redirect this question to the mailing list?

[Mojolicious SUPPORT](http://mojolicious.org/perldoc#SUPPORT)

**Comment by ronstudio** [comment]
Thanks, I'll raise it in the mailing list then.
