### ISSUE TITLE
Mojo::IOLoop->recurring start several job at the same time

### ISSUE THREAD

**Issue by nancyyaweili** [kraih/mojo#1158]
* Mojolicious version: 7.39
* Perl version: v5.24.9
* Operating system: Linux AND 2.6.32-504.23.4.el6.x86_64

### Steps to reproduce the behavior
I'm using Mojo::IOLoop->recurring to schedule a HTTP get request every 10s. However, from the log file, it seems the IOLoop is starting more than 1 job at the same time. Sometimes, there are 2 or 3 or 4 jobs running at the same time. 

Code: 
```  
Mojo::IOLoop->recurring(
        10 => sub {
            my $task    = 'pull_reservation';
            my $backend = $self->minion->backend;

            my $inactive_batch
                = $backend->list_jobs( 0, -1, { state => 'inactive', task => $task, queue => 'default' } );
            my $active_batch = $backend->list_jobs( 0, -1, { state => 'active', task => $task, queue => 'default' } );

            if ( ( !@$inactive_batch ) && ( !@$active_batch ) ) {
                $self->minion->enqueue( $task => [], { priority => 1 } );
            }

        }
    );
```

### Expected behavior
IOLoop should only be starting one job at the time. 

### Actual behavior
IOLoop somestimes start more than 1 job. From the log file, it is starting 2 -4 jobs. 

###Content from log file: 
```
[Wed Nov 22 11:02:35 2017] [info]  job completed with 0 reservations with job_id 244828 .
[Wed Nov 22 11:02:35 2017] [info]  job completed with 0 reservations with job_id 244827 .
[Wed Nov 22 11:02:35 2017] [info]  job completed with 0 reservations with job_id 244829 .
[Wed Nov 22 11:02:42 2017] [info]  job completed with 0 reservations with job_id 244833 .
[Wed Nov 22 11:02:42 2017] [info]  job completed with 0 reservations with job_id 244832 .
[Wed Nov 22 11:02:42 2017] [info]  job completed with 0 reservations with job_id 244831 .
[Wed Nov 22 11:02:42 2017] [info]  job completed with 0 reservations with job_id 244830 .
[Wed Nov 22 11:02:54 2017] [info]  job completed with 0 reservations with job_id 244836 .
[Wed Nov 22 11:02:54 2017] [info]  job completed with 0 reservations with job_id 244834 .
```

**Comment by Grinnz** [comment]
My guesses would be that either the jobs are bunching up before several get completed, or you accidentally added multiple recurring timers without removing old ones. Regardless this isn't really the best forum for debugging complex problems, maybe try the IRC or mailing list support options.

**Comment by nancyyaweili** [comment]
I've also checked the minion job details. For the log which shows the same time, their create time are exactly the same too.

**Comment by nancyyaweili** [comment]
Thank you for your reply. I've posted the question to the mailing list. Originally, i thought this is a bug and this is why I posted here.  
Thanks again.

**Comment by nancyyaweili** [comment]
I'm closing this issue because i found that this is probably a design issue. The problem is caused by hypnotoad in production which might be starting 4 separate processes.
