### ISSUE TITLE
Explain app->home

### ISSUE THREAD

**Issue by kraih** [kraih/mojo#1162]
We need to find a place to explain [app->home](http://mojolicious.org/perldoc/Mojo#home) somewhere in the documentation. How it is most commonly used, how `Mojo::Home` relates to `Mojo::File` and so on. Perhaps even add it as a new section to the [tutorial](http://mojolicious.org/perldoc/Mojolicious/Guides/Tutorial).

**Comment by kberov** [comment]
Yesterday I searched exactly for this. I would love to see it in the tutorial. It is so to say the root of your app (usually). All the directory structure is relative to it, isn't it?
