### ISSUE TITLE
url_escape dies if pattern includes escaped slash

### ISSUE THREAD

**Issue by evoyy** [kraih/mojo#1169]
* Mojolicious version: 7.59
* Perl version: v5.26.1
* Operating system: Ubuntu 14.04

### Steps to reproduce the behavior

````perl
use Mojo::Util qw(url_escape);

url_escape('foo;bar', '^A-Za-z0-9\-._~');      # default pattern: OK
url_escape('foo;bar', '^A-Za-z0-9\-._~\/');    # dies
````

### Expected behavior

Should not die.

### Actual behavior

Dies with:

````Unmatched [ in regex; marked by <-- HERE in m/([ <-- HERE ^A-Za-z0-9\-._~\\/ at (eval 10) line 1.````

This bug was introduced in commit a7cdf6fb2c60c28ac4ab9ffad0e528bb23b0f7b8

**Comment by kraih** [comment]
I'm open to improving `url_escape`, but that function is very performance sensitive. So i'd rather have it fail in unexpected ways than to be slow.

**Comment by evoyy** [comment]
Ok, feel free to close. It's not important to me, I just wanted to let you know about an edge case.
