### ISSUE TITLE
Clean up restrictive placeholders

### ISSUE THREAD

**Issue by kraih** [kraih/mojo#1175]
Right now you have to declare [restrictive placeholders](http://mojolicious.org/perldoc/Mojolicious/Guides/Tutorial#Restrictive-placeholders) with every route that uses them.
```perl
my $r = $app->routes;
$r->get('/users/:id' => [id => qr/[0-9]+/])->to('Users#show');
$r->get('/groups/:id' => [id => qr/[0-9]+/])->to('Groups#show');
$r->get('/rooms/:name' => [name => ['red', 'blue']])->to('Rooms#show');
...
```
This can be quite tedious, and doesn't look all that nice. What we could do instead is to allow for reusable named restrictions (needs a better name...) to be declared once on the router. And then use them with a new placeholder notation.
```perl
my $r = $app->routes;
$r->add_restriction(int => qr/[0-9]+/);
$r->add_restriction(room_name => ['red', 'blue']);

$r->get('/users/(id:int)')->to('Users#show');
$r->get('/groups/(id:int)')->to('Groups#show');
$r->get('/rooms/(name:room_name)')->to('Rooms#show');
...
```
Some restrictions like `int` could be built-in. The old way of declaring restrictive placeholders could be preserved or deprecated, i'm not sure which is better. Thoughts?

**Comment by diegok** [comment]
I love this idea!. I would call it `placeholder types` or `placeholder definition` instead of `placeholder restriction`. On the other hand, I would vote to keep the old way as I think it still fits better for small/lite apps.

**Comment by mohawk2** [comment]
I like the new syntax. I am neutral about what happens to the old syntax.

**Comment by mohawk2** [comment]
@jhthorsen What you think about incorporating this into the OpenAPI plugin? And/or being able to use this to generate an OpenAPI spec from existing route-specs?

**Comment by jhthorsen** [comment]
@mohawk2: I can't use it in m::p::openapi and keep the existing functionality: I want to return 400 and not 404 when a placeholder gets "invalid" data.

**Comment by kraih** [comment]
I've made a branch with an implementation of the feature. https://github.com/kraih/mojo/compare/placeholder_types

**Comment by scottw** [comment]
This makes some aspects of routing much more clear, and it makes perfect sense to 404 unmatched routes. On the other hand, like @jhthorsen's comment above, most of my applications use liberal route placeholders and then post-routing type validation in the controller to return a 400, rather than a 404. I think I would use this feature, but not as often as I would if it were a post-routing type check.

**Comment by kraih** [comment]
It appears we have a strong argument against this feature. Which is the lack of type validation error handling, and inability to respond with a 400 response instead of the usual 404. I guess that could be a blocker.

**Comment by kraih** [comment]
So, i think this feature is blocked until we find a solution for handling validation errors for normal restrictive placeholders, or decide that we never want to do that. Otherwise we risk making routing internals too complicated for proper validation error handling.

**Comment by lammel** [comment]
Shouldn't a route with a non-matching placeholder just be ignored and not trigger the route at all (like with the current implementation with regex matching)?
That way by adding another route with an unrestricted type you could still allow to handle the "bad input" case like in the example below.

```perl
my $r = $app->routes;
$r->add_restriction(int => qr/[0-9]+/, catch => 0);
$r->get('/users/(id:int)')->to('Users#show'); # Should match /users/646
$r->get('/users/:id')->to('Users#handlebad); # Should match all other users /users/frosty and invalid chars
```

To avoid having to define the route twice for the fallback, I tried to come up with a syntax to integrate the check into the placeholder type, but only came up with a syntax that I'm not happy with:

```perl
my $r = $app->routes;
# Route to controller Generic#badinput in case placeholder is found but invalid
$r->add_placeholder_type(int => qr/[0-9]+/, route_invalid => 'Generic#badinput');
# No invalid route defined, just skip the route if "int" is not matched
$r->add_placeholder_type(int => qr/[0-9]+/); # same as below
$r->add_placeholder_type(int => qr/[0-9]+/, route_invalid => undef); 
```

This will always trigger the same controller on invalid input, which reduces the reusability of the placeholder again. Not sure if that is what I want.

**Comment by jhthorsen** [comment]
How can you tell which route failed inside `route_invalid`? I was thinking about something similar:

```
$app->hook(after_partial_route_match => sub { my ($c) = @_ ... });
```

But it also suffers from knowing what didn't match. I mean, it can be a list of routes:

```
$r->get('/users/(id:int)')->to('user#get_by_id');
$r->get('/users/(id:str)')->to('user#get_by_username');
```

**Comment by lammel** [comment]
You cannot really tell them apart unless you check the request path again of course, but that is not a very modular approach. That is exactly why I am not really happy with that approach.

So the only way would be to add additional information to the route itself (e.g. overriding the proposed route_invalid):

```perl
$r->get('/users/(id:int)' => route_invalid => 'user#failed')->to('user#get_by_id'); #or
$r->get('/users/(id:int)')->to('user#get_by_id')->invalid_to('user#badid'); #or
```

Again here, if no route_invalid is specified the route would be silently ignored.
I kind of like the second syntax, it seems quite natural to Mojo.

Without the invalid_to handling it would be more verbose:
```perl
$r->get('/users/(id:int)')->to('user#get_by_id');
$r->get('/users/:id')->to('user#badid');
```

**Comment by kraih** [comment]
So far this seems like the only sensible solution to me.
```perl
$r->get('/users/(id:int)')->to('user#get_by_id');
$r->get('/users/:id')->to('user#badid');
```
How do you propose we differentiate between a request not matching on the `/users` part from a route not matching on the `/(id:int)` part? Wouldn't that require a total rewrite of the router? Is that even possible without breaking lots of other things?

**Comment by lammel** [comment]
The intention would be to match only on the placeholder parts, but as soon as multiple placeholders are used you would again need to map them.

```perl
$r->get('/users/(id:int)/link/(friendid:int')->to('user#get_by_id')->invalid_to(id => 'user#badid', friendid => 'user#badfriendid');
```

This would then reroute for a bad friendid to user#badfriendid and on a bad id to user#badid. Otherwise it would just skip the route. But I'm not convinced yet either.

**Comment by kraih** [comment]
I think this proposal has failed. There seems to be a lot of interest in differentiating between a route not matching at all and a placeholder type not matching. With the current router that seems almost impossible to implement.

**Comment by kraih** [comment]
Reopening this issue since no alternative proposals have surfaced and i want placeholder types.

**Comment by kraih** [comment]
So, unless there's a good reason against it, i will merge [the branch](https://github.com/kraih/mojo/compare/placeholder_types) soon.

**Comment by kraih** [comment]
Patch has been merged. https://github.com/kraih/mojo/commit/c90f3587dd2a8632e1b02b5b038358aa3db00dc0
