### ISSUE TITLE
Mojolicious::Sessions needs a ->param() method

### ISSUE THREAD

**Issue by hesco** [kraih/mojo#1178]
I am refactoring 12 year old CGI / DBI procedural scripts written without benefit of an MVC.  

They rely on CGI::Session for managing session data, and it uses a ->param() method to set/get data.  If this project supported such a method, it would serve as a drop in replacement in this refactoring effort.  And save me building scaffolding using ->isa() tests in conditionals to handle all the cases in the midst of this rewrite.  

-- Hugh 

* Mojolicious version: VERSION HERE
* Perl version: VERSION HERE
* Operating system: NAME AND VERSION HERE

### Steps to reproduce the behavior
EXPLAIN WHAT HAPPENED HERE, PREFERABLY WITH CODE EXAMPLES

### Expected behavior
EXPLAIN WHAT SHOULD HAPPEN HERE

### Actual behavior
EXPLAIN WHAT HAPPENED INSTEAD HERE

**Comment by Grinnz** [comment]
This is not really a compelling argument for why it *needs* a param method; also, the Mojolicious::Sessions object would not be the appropriate place to put such a method, as the individual session is managed by calling ->session on the controller object. I suggest writing an object class that wraps the interface you need as I have done for similar refactoring.

**Comment by kraih** [comment]
I agree with @Grinnz.
