### ISSUE TITLE
generate lite_app treats absolute paths as relative

### ISSUE THREAD

**Issue by hoelzro** [kraih/mojo#1180]
* Mojolicious version:7.60
* Perl version: 5.22
* Operating system: Arch Linux (no version because rolling)

### Steps to reproduce the behavior

```
[11:07:32] rob@pyxis ~ $ mojo generate lite_app /tmp/fake_notifier.pl
  [exist] /home/rob/tmp                                             
  [write] /home/rob/tmp/fake_notifier.pl
  [chmod] /home/rob/tmp/fake_notifier.pl 744
[11:08:00] rob@pyxis ~ $ mojo generate lite_app ~/fake_notifier.pl   
  [mkdir] /home/rob/home/rob                                     
  [write] /home/rob/home/rob/fake_notifier.pl
  [chmod] /home/rob/home/rob/fake_notifier.pl 744

```

### Expected behavior

`mojo generate lite_app` should have generated a lite app under `/tmp/fake_notifier.pl` and `/home/rob/fake_notifier.pl`, respectively.

### Actual behavior

`mojo generate lite_app` generated `/home/rob/tmp/fake_notifier.pl` and `/home/rob/home/rob/fake_notifier.pl` instead.

This might be a weird edge case that isn't worth fixing, but it surprised me when I tried it, so I thought I would at least bring it to the attention of the Mojolicious team.

**Comment by jhthorsen** [comment]
The code calls `render_to_rel_file()`, so it's by design.

I would suggest improving the documentation, but I'm not sure how, since I always understood it as it _only_ took a "simple" filename, and not a path.

**Comment by jberger** [comment]
I really never use the generate commands, I'm too used to just whipping up the code myself. That said, I have always had the impression that @jhthorsen had that it was for producing files in the local directory. Certainly this must true for the full app generation as you only specify the app name. The fact that the lite app name is also a filename seems to obscure this point.

To that end I don't know that I'd consider this a bug, but one could possibly consider a PR to provide such behavior.

**Comment by hoelzro** [comment]
Thanks for the replies @jhthorsen and @jberger! I see the reasoning behind this not being considered a bug - what about updating the generator to warn (or even fail outright) if a path separator is in the app name?

**Comment by jberger** [comment]
As no proposal has been arrived at and the issue seems to have gone stale, I'm going to close this for now. It can still be referenced if a proposal is made or reopened if warranted.
