### ISSUE TITLE
ojo should take imports which would be role names to apply

### ISSUE THREAD

**Issue by mohawk2** [kraih/mojo#1181]
This is a feature request so I have deleted the bug-report template.

My suggestion is that `ojo`'s `import`, which currently ignores its args, would take each one as a role prefixed with `ojo::Role::`, and `with` it.

This, with the obvious `ojo::Role::YAML`, would enable this:

```shell
perl -Mojo=YAML -e 'print y j f(shift)->slurp' $FILENAME
```

which currently needs to be done like this:

```shell
perl -Mojo -MYAML::XS -e '$YAML::XS::Boolean = "JSON::PP"; print Dump j f(shift)->slurp' $FILENAME
```

This would also allow `ojoBox` to be turned into `ojo::Role::Box`.

**Comment by jberger** [comment]
As the author of ojoBox, which could benefit from this interface, I'm generally inclined to 👍 . That said, I wonder if the role syntax should be consistent with others?

    perl -Mojo=+Box,+YAML -E ...

**Comment by jberger** [comment]
Also, thinking about this more, `ojo` isn't a class, it loads Mojolicious::Lite and imports a bunch of functions. You could still think of Role of behaviors but it isn't really a Role as such since there is no class that consumes it. Does this matter?

**Comment by jhthorsen** [comment]
I think it's a bit awkward for ojo.pm to take roles. I would say it's a hack to accomplish the functionality above.

Could we accomplish the same extension, without the use of roles? Or maybe it doesn't matter?

**Comment by mohawk2** [comment]
> Does this matter?

I see the heart of the functionality as introducing the use of `Role::Tiny->apply_roles_to_package($caller, @role_packages)`. I cannot see anything in `Role::Tiny` that requires the target package to be a "class", nor that the functions being introduced be methods. So strictly, as far as I can tell, it doesn't matter.

While I am naturally not asking for pre-approval before I've written code, at this point I'm not really prepared to write any code unless I see some degree of buy-in :-)

**Comment by kraih** [comment]
I don't think this proposal has succeeded. To me the idea seems strange, considering that `ojo` is not even a real class, bit a DSL exporter.

**Comment by mohawk2** [comment]
What I'm after is a way to add something "plugin"-like. I see roles as an easy way to achieve that. Is the DSL not supposed to be extensible?

**Comment by Grinnz** [comment]
I don't think it was written to be extensible. Making it extensible would be neat I think, but should be approached with care.

**Comment by kraih** [comment]
@mohawk2 No, it was definitely never intended to be extensible.

**Comment by kraih** [comment]
I'm not opposed to making `ojo` extensible, if there are good use cases that are not easily solved with a `perl -Mojo -Msome::other::dsl::exporter -E '...'`. The implementation proposed here (using roles) also does not seem feasible, considering that `ojo` is not a real class.
