### ISSUE TITLE
Mojo::Promise->all should resolve instantly when called without arguments.

### ISSUE THREAD

**Issue by jkramer** [kraih/mojo#1193]
When called without arguments, `Mojo::Promise->all` currently never finishes (neither resolves nor rejects) as it's basically waiting for its non-existent sub-promises to resolve/reject, so it's a dead end and followup `then` or `catch` code is never executed. Instead it should resolve instantly.

Reasoning:
* Not doing anything/hanging forever might be a pitfall for users
* `.all` of the JavaScript Promise API also resolves when called with an empty iterable of promises:
 "If an empty iterable is passed, then this method returns (synchronously) an already resolved promise."
* Workarounds for use-cases like `Mojo::Promise->all(map { $ua->get_p($_) } @some_or_0_urls)->then(...)` are cumbersome.
* `<@sri> jkramer: for bonus points, i think it can be implemented without adding new lines "return @promises ? $all : $all->resolve([]);"`

**Comment by kraih** [comment]
Calling for a vote on this: @jberger, @jhthorsen, @marcusramberg.

**Comment by kraih** [comment]
The use case is weak but seems reasonable, and the implementation cost is mininal. So i'll give this a weak 👍.

**Comment by jberger** [comment]
Knowing very little about promises architecture, it does seem like calling it with no arguments shouldn't deadlock. I can easily imagine situations where I'd be call a bunch of "maybe_return_promise" functions and call ->all on them. From a purely conceptual standpoint and not seeing any code, I'd be 👍  on it

**Comment by kraih** [comment]
@jberger The really strange thing is that `Mojo::Promise->race()` still deadlocks, and it's the same for the JavaScript API (`.race()`).

**Comment by kraih** [comment]
Thanks, the proposal has passed the vote.

**Comment by marcusramberg** [comment]
Nice
