### ISSUE TITLE
Use of uninitialized value in gmtime

### ISSUE THREAD

**Issue by lucas1** [kraih/mojo#1194]
* Mojolicious version: 7.59
* Perl version: 5.26.1
* Operating system: Ubuntu 16.04

### Steps to reproduce the behavior
EXPLAIN WHAT HAPPENED HERE, PREFERABLY WITH CODE EXAMPLES
code:

    # Load language
    $self->hook(before_render => sub {
        my $c = shift;
        
        # set languages
        if($c->param('lang')){
            $c->cookie(lang => $c->param('lang'), {expires => time + (86400 * 365)});
        }
    });

log:
[Wed Feb 14 00:03:29 2018] [info] Listening at "http://*:3000"
Server available at http://127.0.0.1:3000
[Wed Feb 14 00:03:31 2018] [debug] GET "/admin/users"
[Wed Feb 14 00:03:31 2018] [debug] Routing to controller "StalDenDoorn::Controller::Admin::Users" and action "index"
Use of uninitialized value in gmtime at /home/lucas/perl5/perlbrew/perls/perl-5.26.1/lib/site_perl/5.26.1/Mojo/Date.pm line 66.
[Wed Feb 14 00:03:32 2018] [debug] Rendering template "admin/users/index.html.ep"
[Wed Feb 14 00:03:32 2018] [debug] Rendering template "layouts/admin.html.ep"
[Wed Feb 14 00:03:32 2018] [debug] 200 OK (0.0576s, 17.361/s)

explain:
when get attribute 'epoch' return empty

I opened file Mojo::Date and tested code, I think the cause of log is code:
use overload bool => sub {1}, '""' => sub { shift->to_string }, fallback => 1;

when I removed code '""' => sub { shift->to_string }, attribute 'epoch' return time

Thanks.

**Comment by jhthorsen** [comment]
Not sure if this is the best test, but I cannot reproduce the warning above.

```
use Mojo::Base -strict;
use Test::More;
use Test::Mojo;

use Mojolicious::Lite;
hook before_render => sub {
  my $c = shift;
  my $x = undef . "cause warning";
  $c->cookie(lang => $c->param('lang'), {expires => time + (86400 * 365)}) if $c->param('lang');
};

get '/' => {text => "index\n"};

my $t = Test::Mojo->new;
my @warnings;
$SIG{__WARN__} = sub { push @warnings, $_[0] };
$t->get_ok('/')->status_is(200);
is int(@warnings), 1, "Only got (@warnings)";
done_testing;
```

Output:

```
ok 1 - GET /
ok 2 - 200 OK
ok 3 - Only got (Use of uninitialized value in concatenation (.) or string at foo.pl line 9.
```

**Comment by lucas1** [comment]
I trying again, but I cannot reproduce too. 
Next error, I will restart operational system first.

Thanks.

**Comment by lucas1** [comment]
Hi guys.

I found the error:
$self->cookie(foo => 'baz', {expires => -1});

-1

**Comment by aferreira** [comment]
Mojo::Date does not support negative epoch values (equivalent to dates before Jan 1, 1970).

You may do this instead, treating `0` as the "way beyond into the past":

```
$self->cookie(foo => 'baz', {expires => 0});
```

**Comment by lucas1** [comment]
Yes, but -1 is a value valid, I think need solve this.

I find in google 'delete cookie mojolicious', see a answer:
https://groups.google.com/forum/#!topic/mojolicious/bvQvwje-9vY

I had difficulties to find the problem.

Simple solve this, change code:
$date = 0 if $date =~ /^-\d+\.?\d*$/;
or 
add in warnings that does not accept number negative

**Comment by lucas1** [comment]
I don't know, but is there anywhere in the documentation that suggests -1 is invalid to pass?. 
Warning "Use of uninitialized value in gmtime" is defined per regex "/^\d+$|^\d+.\d+$/".
Better is wait "epoch" warnings about this.

**Comment by s1037989** [comment]
On Wed, Apr 4, 2018 at 4:25 PM, lucas1 <notifications@github.com> wrote:

> but is there anywhere in the documentation that suggests -1 is invalid to
> pass?
>
One excellent tip I've received from this community is that documentation
states what is possible / valid / supported, not what is not possible /
valid / supported.
