### ISSUE TITLE
Strange behavior of UTF-8 paths in Mojo::File

### ISSUE THREAD

**Issue by Tekki** [kraih/mojo#1202]
* Mojolicious version: 7.71
* Perl version: 5.26.1 (Perlbrew)
* Operating system: Debian Jessie 8.10

### Steps to reproduce the behavior
1) In console: `mkdir /tmp/Müller; touch /tmp/Müller/Müller.txt`

2) Run the following script:
```
use Mojo::Base -strict, -signatures;
use Mojo::File 'path';

path('/tmp/Müller')->list->each(sub ($file, $) {
  say $file->to_string;
});
```

### Expected behavior
Should print `/tmp/Müller/Müller.txt`.

### Actual behavior
Prints `/tmp/M�ller/Müller.txt`.

**Comment by lindleyw** [comment]
Adding `binmode(STDOUT, ":utf8");` results in the output:

`/tmp/Müller/MÃ¼ller.txt`

Curiouser and curiouser.

**Comment by kraih** [comment]
`Mojo::File` deals with binary data, not Perl characters. Nothing here looks like a bug to me i'm afraid.

**Comment by Grinnz** [comment]
Note that it's impossible to correctly handle filenames as characters due to bugs in Perl, like with https://github.com/kraih/mojo/issues/1131

**Comment by Grinnz** [comment]
Specifically, you are getting back a filepath with a decoded character in the directory name (since that's what you passed to Mojo::File, but due to the Perl bugs it used the encoded form the find the directory so it "works") but encoded bytes in the filename (since that's what it got from the filesystem). When you print without encoding to UTF-8 the bytes in the filename are already encoded so they look like they work, but in fact you need to encode the directory you initially passed to UTF-8 before passing it to Mojo::File.

**Comment by Tekki** [comment]
Thanks @Grinnz for the hint. It's really strange. In my application I'm reading data from spreadsheets.
- I can access a file with a UTF-8 name (= name contains UTF-8) in an ASCII path. 
- I can access a file with ASCII name in a UTF-8 path.
- I can't access a file with UTF-8 name in a UTF-8 path.

**Comment by Grinnz** [comment]
It's unfortunate but most of the things that seem to "work" are accidents of the bugs in Perl. If you only use encoded bytes as file paths then most things should really work.

**Comment by Tekki** [comment]
The solution suggested by @Grinnz is:
```
use Mojo::Base -strict, -signatures;

use Mojo::File 'path';
use Mojo::Util 'encode';

path(encode 'UTF-8', '/tmp/Müller')->list->each(sub ($file, $) {
  say $file->to_string;
});
```
Output: `/tmp/Müller/Müller.txt` :beers:

**Comment by Grinnz** [comment]
Just remember to decode the file paths from UTF-8 again when you want to display them on something that expects perl characters, like JSON output or a Mojo response. (or printing with `binmode(STDOUT, ':encoding(UTF-8)')`)
