### ISSUE TITLE
Request IDs for log messages

### ISSUE THREAD

**Issue by kraih** [kraih/mojo#1210]
Currently it is very easy to lose track of where the log messages for one request end and those for another start.
```
[Fri Apr 13 20:16:21 2018] [debug] GET "/"
[Fri Apr 13 20:16:21 2018] [debug] Routing to a callback
[Fri Apr 13 20:16:21 2018] [debug] Rendering cached template "index.html.ep" from DATA section
[Fri Apr 13 20:16:21 2018] [debug] Rendering cached template "layouts/default.html.ep" from DATA section
[Fri Apr 13 20:16:21 2018] [debug] 200 OK (0.001084s, 922.509/s)
[Fri Apr 13 20:16:24 2018] [debug] GET "/"
[Fri Apr 13 20:16:24 2018] [debug] Routing to a callback
[Fri Apr 13 20:16:24 2018] [debug] Rendering cached template "index.html.ep" from DATA section
[Fri Apr 13 20:16:24 2018] [debug] Rendering cached template "layouts/default.html.ep" from DATA section
[Fri Apr 13 20:16:24 2018] [debug] 200 OK (0.001129s, 885.740/s)
```
It would be great if we could find a solution to add unique IDs for every request.
```
[Fri Apr 13 20:16:21 2018] [debug] [457823493] GET "/"
[Fri Apr 13 20:16:21 2018] [debug] [457823493] Routing to a callback
[Fri Apr 13 20:16:21 2018] [debug] [457823493] Rendering cached template "index.html.ep" from DATA section
[Fri Apr 13 20:16:21 2018] [debug] [457823493] Rendering cached template "layouts/default.html.ep" from DATA section
[Fri Apr 13 20:16:21 2018] [debug] [457823493] 200 OK (0.001084s, 922.509/s)
[Fri Apr 13 20:16:24 2018] [debug] [785260225] GET "/"
[Fri Apr 13 20:16:24 2018] [debug] [785260225] Routing to a callback
[Fri Apr 13 20:16:24 2018] [debug] [785260225] Rendering cached template "index.html.ep" from DATA section
[Fri Apr 13 20:16:24 2018] [debug] [785260225] Rendering cached template "layouts/default.html.ep" from DATA section
[Fri Apr 13 20:16:24 2018] [debug] [785260225] 200 OK (0.001129s, 885.740/s)
```
Especially when multiple concurrent requests are being performed at the same time, this would be a very valuable debug tool.

**Comment by kraih** [comment]
We need to be able to handle log messages outside the request/response cycle (without unique ID), and log messages with unique IDs generated for HTTP requests, concurrent HTTP requests, and persistent WebSocket connections.

**Comment by s1037989** [comment]
One of the things I was wanting to do just recently was have a customized log format where a specific value would always be shown in the log, e.g.:

`[Fri Apr 13 20:16:21 2018] [debug] [457823493] [<username>] GET "/"`

I'm not sure if that would even be possible to do.  Surely custom helpers would be a requirement, or callbacks or something?

Anyway, having unique IDs for log entries would be _awesome_!  Much needed, IMO.

**Comment by zakame** [comment]
I recently ported [cuid](http://usecuid.org)s to [Perl](https://metacpan.org/pod/Data::Cuid), maybe the `slug()` form could be useful here? (e.g. `wqffk2lr6`, `vof5z2l07`, etc., unless you have a requirement for unique numeric IDs.)

Perhaps useful would be for the log helper have a default request ID implementation, and have some accessor to it for the user to customize with their own callback.

**Comment by elcamlost** [comment]
Nginx has built-in request_id variable and it may be useful to use it for request tracing between nginx and Mojo psgi app. So ability to customize request_id generation is a great idea.

In @kraih [current implementation](https://github.com/kraih/mojo/compare/request_id), we can set request_id in after_build_tx hook or mock request_id during application startup. Maybe this customization must be done in a more simple and elegant way.

Using cuid also looks very promising, but i'm not sure about slug. In a highloaded distributed application slug form may lead to duplicates. But it's not the problem, if Mojo provides a way to customize request_id generation process.

**Comment by zakame** [comment]
Yes, a `cuid::slug()`-alike is likely to emit more duplicates, though probably short enough and ok for identifying requests in a Mojo app while in development.  There are other ways, of course; another might be taking ideas from `Mojo::IOLoop->_id`.

Being able to customize the request ID through a generator (that can even take something external like Nginx) seems important indeed when tracing for production.

**Comment by kraih** [comment]
Mojolicious 7.81 contains a minimal implementation of request ids, i think that will be all we do for now. https://github.com/kraih/mojo/compare/v7.80...v7.81
