### ISSUE TITLE
Warnings in Mojo::Asset::Memory

### ISSUE THREAD

**Issue by pplu** [kraih/mojo#1221]
* Mojolicious version: 7.79
* Operating system: Debian Linux

### Steps to reproduce the behavior
```
#!/usr/bin/env perl

use Future::HTTP::Mojo;
my $ua = Future::HTTP::Mojo->new();

my $f = $ua->http_head(
  'http://search.cpan.org/'
)->then(sub {
  my $body = shift;
  print "Got HEAD\n";
});

$f->get;
```
### Expected behavior
No warning for uninitialized value in Mojo classes

### Actual behavior
I get
```
Use of uninitialized value $chunk in concatenation (.) or string at /home/pplu/test_mojo/local/lib/perl5/Mojo/Asset/Memory.pm line 15.
```
in the output

**Comment by Grinnz** [comment]
This seems like a bug in Future::HTTP::Mojo. Try installing Devel::Confess and running with -d:Confess to get a full stack trace of what's causing the warning.

**Comment by Grinnz** [comment]
I suspect the bug is here: https://metacpan.org/source/CORION/Future-HTTP-0.08/lib/Future/HTTP/Mojo.pm#L72-76

If you pass undef as the body to build_tx it will result in such a warning, since the body is assumed to be a string.

**Comment by kraih** [comment]
I'm sorry, but `Future::HTTP::Mojo` is not part of Mojolicious.

**Comment by pplu** [comment]
Thanks for the diagnostic. Going to report to @Corion (maintainer of Future::HTTP::Mojo).
