### ISSUE TITLE
Mojolicious does not check SSL certificates by default

### ISSUE THREAD

**Issue by jes** [kraih/mojo#1223]
* Mojolicious version: 7.79
* Perl version: 5.22.1
* Operating system: Ubuntu Xenial

### Steps to reproduce the behavior
mojofetch:

```
#!/usr/bin/perl

use strict;
use warnings;

use Mojo::UserAgent;

my $url = shift or die "usage: mojofetch URL\n";

my $ua = Mojo::UserAgent->new();

$ua->get($url, sub {
    my ($ua, $tx) = @_;
    print $tx->res->body, "\n";
    exit 0;
});

Mojo::IOLoop->start;
```

### Expected behavior

`./mojofetch https://expired.badssl.com/` should not return the content of the page and should trigger some sort of error, because the certificate is expired. Similar applies for self-signed.badssl.com, wrong.host.badssl.com etc., see the list on https://badssl.com/ for more test cases.

### Actual behavior

`./mojofetch https://expired.badssl.com/` does return the content of the page, and doesn't print any errors or warnings.

### More

I looked in `Mojo::IOLoop::TLS` and it appears as though the `_expand` function is responsible for this problem. In the event that something inside Mojolicious doesn't explicitly set `tls_*` options, `_expand` defaults them all to off and no verification. This even overrides `IO::Socket::SSL`'s defaults. Even if you set defaults using `IO::Socket::SSL->set_defaults`, they are overridden to the no-verification behaviour that Mojo defaults to.

This is really serious, but I don't know enough about Mojo to know the most effective way to fix it without breaking other features. Hopefully somebody else can do so.

**Comment by kraih** [comment]
This is something we'd consider if there was a well thought out proposal. The topic keeps coming up every now and then, but nobody ever follows up, so i wouldn't get my hopes up.

**Comment by jes** [comment]
In the absence of any actual fix, I would think a good first step would be a big scary warning in all the relevant documentation.

I for one had *no idea* that Mojolicious treats certificate verification as optional.

**Comment by jes** [comment]
I strongly urge you to reconsider.

This insecure-by-default policy is causing real people to write real software that is vulnerable to MITM attacks, while they have no idea about it because it's not documented, just to make built-in HTTPS testing easier?

I also contend that where the defaults are so obviously broken, a change in the defaults is required.

IO::Socket::SSL went through a similar change a few years ago. The default verify mode used to be SSL_VERIFY_NONE, and then for many years it would print a big scary warning (which, incidentally, Mojolicious disables by setting the verify mode *explicitly* to SSL_VERIFY_NONE), and now the default is SSL_VERIFY_PEER.

All Mojolicious needs to do to do the correct thing (on modern systems) is not disable the IO::Socket::SSL defaults.

**Comment by kraih** [comment]
Don't get me wrong, i'm just telling why it is the way it is right now. Not that i want it to be that way. If you know how to improve the situation, then please, by all means, get involved and send us pull requests!

**Comment by jberger** [comment]
Even if we wanted to flip the default to SSL_VERIFY_PEER, we'd need a way to disable it again, both for our testing and for clients who use mojo against say self-signed certs. This means that any change will need a full proposal with new pass through arguments to IO::Socket::SSL (and at several levels I suspect). There could also be knock-on breakage if cpan modules test using self-signed certs too, though I don't know how many of those there are.

N.B. "proposal" here is used as a specific term meaning a PR with tests and documentation as specified in our documentation.

**Comment by shadowcat-mst** [comment]
> I also contend that where the defaults are so obviously broken, a change in the defaults is required.

Then please make a proposal as to what to do instead - remembering that it's entirely possible that within people's infrastructure many users likely consider allowing self-signed certs to be a feature rather than a security risk.

"Obviously broken" massively depends on the point of view - "strict-by-default" would seem preferable to me, but it'd need to be a strict-by-default that allows people to ask for non-strict if they want to, in an easy way.

**Comment by shadowcat-mst** [comment]
I think everybody was more aiming for "this would be good, but somebody needs to do it, and every time previously somebody's said they were going to attempt it they've ghosted, and none of us have it at the top of our yak stack so it's either you or nobody, which kinda sucks but well, open source", but that's a lot of typing when the last twenty times you typed it the person you typed it to ghosted.

I really really hope you can find time to make enough of a start for us to discuss things (or at least, the two qualified people in this thread to discuss things with you ;)
