### ISSUE TITLE
Add SSL_check_crl and SSL_crl_file to Mojo::IOLoop::TLS (feature request)

### ISSUE THREAD

**Issue by fskale** [kraih/mojo#1230]
Hi,
my PKI generates a CRL on daily bases (revoking clients), so
it would be great to have the feature included in the next version of Mojolicious.
I think, that can be done with minimal effort by extending the _expand function to add both **IO::Socket::SSL** options if e.g. **tls_crl=/etc/crl.pem** have been supplied at the commandline.
Like:
<pre>
if ($args->{tls_crl}) {
      $tls->{SSL_crl_file} = $args->{tls_crl};
      $tls->{SSL_check_crl} = 'true';
}
</pre>
Right now i do:
<pre>
IO::Socket::SSL::set_server_defaults(
     SSL_check_crl => 'true', 
    SSL_crl_file => '/etc/crl.pem'
);
</pre>

Btw., you're doing a great job !

Best regards
Franz

**Comment by kraih** [comment]
Looks like this feature request went stale.

**Comment by shadowcat-mst** [comment]
@fskale this seems like a reasonable idea - could you try expanding it into a patch w/tests so we can discuss it in more concrete terms?

**Comment by fskale** [comment]
Hi,
will try to draft a patch with tests. Right now i'm on vacation, so i'll report back next week.

Best regards
Franz

**Comment by kraih** [comment]
Unfortunately i don't think a patch for this very specific feature has much of a chance of getting accepted, considering how little interest there is currently. Only way i could see support for this getting accepted was if someone found a nice generic way to pass along arbitrary `IO::Socket::SSL` options from `Mojo::Server::Daemon` and `Mojo::UserAgent`.

**Comment by fskale** [comment]
@kraih 
Hope, that you get my answer althought closed already.
Mojo::IOLoop::TLS already pass args directly to IO::Socket::SSL.
Mojolicious also supports both the <code> $tls->{SSL_ca_file} = $args->{tls_ca} </code>
as well as the <code>tls_verify </code> whereas the crl is a feature to it.
Anyone who uses client certificates is also aware of the ability to use a CRL.
Nothing special though.
Client Certificate authentication along with password auth are quite common in high security environments.
Anyway, i can live with my solution.

**Comment by kraih** [comment]
Yes, we do receive comments for closed issues, and regularly reopen them when there is new activity. Unfortunately you appear to be the only one who cares about this feature at the moment. So if you don't make a patch, i don't think there will be an alternative any time soon.

**Comment by jhthorsen** [comment]
I'm positive to PR for this change. I'm not actively using this feature anymore, but I know I would greatly appreciate this in my previous job, where we would revoke clients.
