### ISSUE TITLE
[Mojolicious-7.85, perl5.28.0] Manual installation, many tests fail on alpine 3.7.0

### ISSUE THREAD

**Issue by muenalan** [kraih/mojo#1232]
* Mojolicious version: Mojolicious-7.85
* Perl version: 5.28.0
* Operating system: alpine:3.7.0

### Steps to reproduce the behavior
PERL_DL_NONLAZY=1 "/opt/plenv/versions/5.28.0/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t t/*/*.t
t/mojo/asset.t ............................. 
Dubious, test returned 20 (wstat 5120, 0x1400)
Failed 20/151 subtests 
t/mojo/base.t .............................. ok
t/mojo/bytestream.t ........................ ok
t/mojo/cache.t ............................. ok
t/mojo/cgi.t ............................... ok
t/mojo/collection.t ........................ ok
t/mojo/content.t ........................... 
Dubious, test returned 7 (wstat 1792, 0x700)
Failed 7/49 subtests 
t/mojo/cookie.t ............................ ok
t/mojo/cookiejar.t ......................... 
Dubious, test returned 255 (wstat 65280, 0xff00)
All 65 subtests passed 
t/mojo/daemon.t ............................ 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/96 subtests 
t/mojo/daemon_ipv6_tls.t ................... skipped: set TEST_IPV6 to enable this test (developer only!)
t/mojo/date.t .............................. ok
t/mojo/delay.t ............................. ok
t/mojo/dom.t ............................... ok
t/mojo/eventemitter.t ...................... ok
t/mojo/exception.t ......................... ok
t/mojo/file.t .............................. ok
t/mojo/headers.t ........................... ok
t/mojo/home.t .............................. ok
t/mojo/hypnotoad.t ......................... ok
t/mojo/ioloop.t ............................ ok
t/mojo/ioloop_ipv6.t ....................... skipped: set TEST_IPV6 to enable this test (developer only!)
t/mojo/ioloop_tls.t ........................ skipped: IO::Socket::SSL 2.009+ required for this test!
t/mojo/json.t .............................. ok
t/mojo/json_pointer.t ...................... ok
t/mojo/loader.t ............................ ok
t/mojo/log.t ............................... ok
t/mojo/morbo.t ............................. ok
t/mojo/parameters.t ........................ ok
t/mojo/path.t .............................. ok
t/mojo/prefork.t ........................... ok
t/mojo/promise.t ........................... ok
t/mojo/proxy.t ............................. ok
t/mojo/psgi.t .............................. ok
t/mojo/reactor_detect.t .................... ok
t/mojo/reactor_ev.t ........................ skipped: EV 4.0+ required for this test!
t/mojo/reactor_poll.t ...................... ok
t/mojo/request.t ........................... 
Dubious, test returned 255 (wstat 65280, 0xff00)
All 353 subtests passed 
t/mojo/request_cgi.t ....................... 
Dubious, test returned 255 (wstat 65280, 0xff00)
All 186 subtests passed 
t/mojo/response.t .......................... 
Dubious, test returned 255 (wstat 65280, 0xff00)
All 267 subtests passed 
t/mojo/roles.t ............................. ok
t/mojo/signatures.t ........................ ok
t/mojo/streams.t ........................... ok
t/mojo/subprocess.t ........................ skipped: set TEST_SUBPROCESS to enable this test (developer only!)
t/mojo/template.t .......................... ok
t/mojo/tls.t ............................... skipped: IO::Socket::SSL 2.009+ required for this test!
t/mojo/transactor.t ........................ ok
t/mojo/url.t ............................... ok
t/mojo/user_agent.t ........................ ok
t/mojo/user_agent_online.t ................. skipped: set TEST_ONLINE to enable this test (developer only!)
t/mojo/user_agent_socks.t .................. skipped: set TEST_SOCKS to enable this test (developer only!)
t/mojo/user_agent_tls.t .................... skipped: IO::Socket::SSL 2.009+ required for this test!
t/mojo/user_agent_unix.t ................... skipped: set TEST_UNIX to enable this test (developer only!)
t/mojo/util.t .............................. ok
t/mojo/websocket.t ......................... ok
t/mojo/websocket_frames.t .................. ok
t/mojo/websocket_proxy.t ................... ok
t/mojo/websocket_proxy_tls.t ............... skipped: IO::Socket::SSL 2.009+ required for this test!
t/mojolicious/app.t ........................ ok
t/mojolicious/charset_lite_app.t ........... 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/44 subtests 
t/mojolicious/command.t .................... ok
t/mojolicious/commands.t ................... ok
t/mojolicious/dispatch.t ................... ok
t/mojolicious/dispatcher_lite_app.t ........ ok
t/mojolicious/embedded_app.t ............... ok
t/mojolicious/embedded_lite_app.t .......... ok
t/mojolicious/exception_lite_app.t ......... ok
t/mojolicious/external_app.t ............... ok
t/mojolicious/external_lite_app.t .......... ok
t/mojolicious/group_lite_app.t ............. ok
t/mojolicious/json_config_lite_app.t ....... ok
t/mojolicious/json_config_mode_lite_app.t .. ok
t/mojolicious/layouted_lite_app.t .......... ok
t/mojolicious/lite_app.t ................... 
Dubious, test returned 5 (wstat 1280, 0x500)
Failed 5/621 subtests 
t/mojolicious/longpolling_lite_app.t ....... ok
t/mojolicious/multipath_lite_app.t ......... ok
t/mojolicious/ojo.t ........................ ok
t/mojolicious/ojo_signatures.t ............. ok
t/mojolicious/pattern.t .................... ok
t/mojolicious/pod_renderer_lite_app.t ...... ok
t/mojolicious/production_app.t ............. ok
t/mojolicious/rebased_lite_app.t ........... ok
t/mojolicious/renderer.t ................... ok
t/mojolicious/restful_lite_app.t ........... ok
t/mojolicious/routes.t ..................... ok
t/mojolicious/signatures_lite_app.t ........ ok
t/mojolicious/static_lite_app.t ............ ok
t/mojolicious/tag_helper_lite_app.t ........ ok
t/mojolicious/testing_app.t ................ ok
t/mojolicious/tls_lite_app.t ............... skipped: IO::Socket::SSL 2.009+ required for this test!
t/mojolicious/twinkle_lite_app.t ........... ok
t/mojolicious/types.t ...................... ok
t/mojolicious/upload_lite_app.t ............ 
Dubious, test returned 11 (wstat 2816, 0xb00)
Failed 11/27 subtests 
t/mojolicious/upload_stream_lite_app.t ..... 
Dubious, test returned 10 (wstat 2560, 0xa00)
Failed 10/15 subtests 
t/mojolicious/validation_lite_app.t ........ ok
t/mojolicious/websocket_lite_app.t ......... ok
t/pod.t .................................... skipped: set TEST_POD to enable this test (developer only!)
t/pod_coverage.t ........................... skipped: set TEST_POD to enable this test (developer only!)

Test Summary Report
-------------------
t/mojo/asset.t                           (Wstat: 5120 Tests: 151 Failed: 20)
  Failed tests:  4, 12, 33-35, 38-40, 43-44, 57-58, 74-75
                77, 79-81, 85-86
  Non-zero exit status: 20
t/mojo/content.t                         (Wstat: 1792 Tests: 49 Failed: 7)
  Failed tests:  4, 6, 8, 12-13, 17, 20
  Non-zero exit status: 7
t/mojo/cookiejar.t                       (Wstat: 65280 Tests: 65 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/mojo/daemon.t                          (Wstat: 512 Tests: 96 Failed: 2)
  Failed tests:  60-61
  Non-zero exit status: 2
t/mojo/request.t                         (Wstat: 65280 Tests: 353 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/mojo/request_cgi.t                     (Wstat: 65280 Tests: 186 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/mojo/response.t                        (Wstat: 65280 Tests: 267 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/mojolicious/charset_lite_app.t         (Wstat: 512 Tests: 44 Failed: 2)
  Failed tests:  12, 20
  Non-zero exit status: 2
t/mojolicious/lite_app.t                 (Wstat: 1280 Tests: 621 Failed: 5)
  Failed tests:  136, 355, 359, 442, 444
  Non-zero exit status: 5
t/mojolicious/upload_lite_app.t          (Wstat: 2816 Tests: 27 Failed: 11)
  Failed tests:  8-9, 11-12, 14-15, 17-18, 21, 24, 27
  Non-zero exit status: 11
t/mojolicious/upload_stream_lite_app.t   (Wstat: 2560 Tests: 15 Failed: 10)
  Failed tests:  2-3, 5-6, 8-9, 11-12, 14-15
  Non-zero exit status: 10
Files=98, Tests=10396, 127 wallclock secs ( 1.13 usr  0.32 sys + 30.85 cusr 11.63 csys = 43.93 CPU)
Result: FAIL

**Comment by muenalan** [comment]
12373e236d45:/$ perl -V
Summary of my perl5 (revision 5 version 28 subversion 0) configuration:
   
  Platform:
    osname=linux
    osvers=4.9.87-linuxkit-aufs
    archname=x86_64-linux
    uname='linux 006f34f1eb51 4.9.87-linuxkit-aufs #1 smp wed mar 14 15:12:16 utc 2018 x86_64 linux '
    config_args='-Dprefix=/opt/plenv/versions/5.28.0 -de -A'eval:scriptdir=/opt/plenv/versions/5.28.0/bin''
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2'
    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong'
    ccversion=''
    gccversion='6.3.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/include/fortify /usr/lib /usr/local/lib /lib/../lib /usr/lib/../lib /lib
    libs=-lpthread -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/usr/lib/libc.a
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Locally applied patches:
    Devel::PatchPerl 1.52
  Built under linux
  Compiled at Jun 26 2018 11:03:41
  %ENV:
    PERL5LIB="/opt/plenv/mueperllib/lib"
    PERL5OPT="-MModule::Jetpack::Mue"
    PERL_CPANM_OPT="--no-wget"
  @INC:
    /opt/plenv/mueperllib/lib
    /opt/plenv/versions/5.28.0/lib/perl5/site_perl/5.28.0/x86_64-linux
    /opt/plenv/versions/5.28.0/lib/perl5/site_perl/5.28.0
    /opt/plenv/versions/5.28.0/lib/perl5/5.28.0/x86_64-linux
    /opt/plenv/versions/5.28.0/lib/perl5/5.28.0


Sidenote:
Interestingly, with the same setup under perl5.24.1, all tests pass just fine.

1759e2ba0e9d:~/.cpanm/work/1530096990.811/Mojolicious-7.85$ perl -V
Summary of my perl5 (revision 5 version 24 subversion 1) configuration:
   
  Platform:
    osname=linux, osvers=4.9.87-linuxkit-aufs, archname=x86_64-linux
    uname='linux 006f34f1eb51 4.9.87-linuxkit-aufs #1 smp wed mar 14 15:12:16 utc 2018 x86_64 linux '
    config_args='-Dprefix=/opt/plenv/versions/5.24.1 -de -A'eval:scriptdir=/opt/plenv/versions/5.24.1/bin''
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=undef, usemultiplicity=undef
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2',
    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong'
    ccversion='', gccversion='6.3.0', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678, doublekind=3
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16, longdblkind=3
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/include/fortify /usr/lib /usr/local/lib /lib/../lib /usr/lib/../lib /lib
    libs=-lpthread -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/usr/lib/libc.a, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fPIC', lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options: HAS_TIMES PERLIO_LAYERS PERL_COPY_ON_WRITE
                        PERL_DONT_CREATE_GVSV
                        PERL_HASH_FUNC_ONE_AT_A_TIME_HARD PERL_MALLOC_WRAP
                        PERL_PRESERVE_IVUV USE_64_BIT_ALL USE_64_BIT_INT
                        USE_LARGE_FILES USE_LOCALE USE_LOCALE_COLLATE
                        USE_LOCALE_CTYPE USE_LOCALE_NUMERIC USE_LOCALE_TIME
                        USE_PERLIO USE_PERL_ATOF
  Locally applied patches:
	Devel::PatchPerl 1.52
  Built under linux
  Compiled at Jun 26 2018 10:15:09
  %ENV:
    PERL_CPANM_OPT="--no-wget"
  @INC:
    /opt/plenv/versions/5.24.1/lib/perl5/site_perl/5.24.1/x86_64-linux
    /opt/plenv/versions/5.24.1/lib/perl5/site_perl/5.24.1
    /opt/plenv/versions/5.24.1/lib/perl5/5.24.1/x86_64-linux
    /opt/plenv/versions/5.24.1/lib/perl5/5.24.1
    .

**Comment by muenalan** [comment]
Interesting note, on alpine:edge same tests fail also on manual installed perl5.26.2. However, the system perl of alpine:edge (CPAN, and perl-mojolicious package (apk add perl-mojolicious)) work; the alpine:edge perl is also perl5.26.2. However, going over https://git.alpinelinux.org/cgit/aports/tree/community/perl-mojolicious/APKBUILD didn't show any special patches there.  Must be how perl is compiled, I suppose. 

Did Mojolicious require certain perl flags during compilation ?

[PERL FROM alpine:edge distribution, all tests pass]
Summary of my perl5 (revision 5 version 26 subversion 2) configuration:
   
  Platform:
    osname=linux
    osvers=4.14.39-0-vanilla
    archname=x86_64-linux-thread-multi
    uname='linux build-edge-x86_64 4.14.39-0-vanilla #1-alpine smp mon may 7 11:50:15 utc 2018 x86_64 linux '
    config_args='-des -Dcccdlflags=-fPIC -Dcccdlflags=-fPIC -Dccdlflags=-rdynamic -Dprefix=/usr -Dprivlib=/usr/share/perl5/core_perl -Darchlib=/usr/lib/perl5/core_perl -Dvendorprefix=/usr -Dvendorlib=/usr/share/perl5/vendor_perl -Dvendorarch=/usr/lib/perl5/vendor_perl -Dsiteprefix=/usr/local -Dsitelib=/usr/local/share/perl5/site_perl -Dsitearch=/usr/local/lib/perl5/site_perl -Dlocincpth=  -Doptimize=-Os -fomit-frame-pointer -Duselargefiles -Dusethreads -Duseshrplib -Dd_semctl_semun -Dman1dir=/usr/share/man/man1 -Dman3dir=/usr/share/man/man3 -Dinstallman1dir=/usr/share/man/man1 -Dinstallman3dir=/usr/share/man/man3 -Dman1ext=1 -Dman3ext=3pm -Dcf_by=Alpine -Ud_csh -Dusenm'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-Os -fomit-frame-pointer'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong'
    ccversion=''
    gccversion='6.4.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/include/fortify /usr/lib /lib/../lib /usr/lib/../lib /lib
    libs=-lpthread -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/usr/lib/libc.a
    so=so
    useshrplib=true
    libperl=libperl.so
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-rdynamic -Wl,-rpath,/usr/lib/perl5/core_perl/CORE'
    cccdlflags='-fPIC'
    lddlflags='-shared -Os -fomit-frame-pointer -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_IMPLICIT_CONTEXT
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
  Built under linux
  Compiled at Jun 13 2018 12:09:33
  %ENV:
    PERL5LIB=""
    PERL5OPT=""
    PERL_CPANM_OPT="--no-wget"
  @INC:
    /usr/local/lib/perl5/site_perl
    /usr/local/share/perl5/site_perl
    /usr/lib/perl5/vendor_perl
    /usr/share/perl5/vendor_perl
    /usr/lib/perl5/core_perl
    /usr/share/perl5/core_perl

[PERL INSTALLED FROM CPAN, fails]
b88f5e24fd31:/# perl -V
Summary of my perl5 (revision 5 version 26 subversion 2) configuration:
   
  Platform:
    osname=linux
    osvers=4.9.87-linuxkit-aufs
    archname=x86_64-linux
    uname='linux b88f5e24fd31 4.9.87-linuxkit-aufs #1 smp wed mar 14 15:12:16 utc 2018 x86_64 linux '
    config_args='-Dprefix=/opt/plenv/versions/5.26.2 -de -A'eval:scriptdir=/opt/plenv/versions/5.26.2/bin''
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2'
    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong'
    ccversion=''
    gccversion='6.4.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/include/fortify /usr/lib /usr/local/lib /lib/../lib /usr/lib/../lib /lib
    libs=-lpthread -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/usr/lib/libc.a
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Locally applied patches:
    Devel::PatchPerl 1.48
  Built under linux
  Compiled at Jun 27 2018 13:44:40
  %ENV:
    PERL5LIB=""
    PERL5OPT=""
    PERL_CPANM_OPT="--no-wget"
  @INC:
    /opt/plenv/versions/5.26.2/lib/perl5/site_perl/5.26.2/x86_64-linux
    /opt/plenv/versions/5.26.2/lib/perl5/site_perl/5.26.2
    /opt/plenv/versions/5.26.2/lib/perl5/5.26.2/x86_64-linux
    /opt/plenv/versions/5.26.2/lib/perl5/5.26.2

Test Summary Report
-------------------
t/mojo/asset.t                           (Wstat: 5120 Tests: 151 Failed: 20)
  Failed tests:  4, 12, 33-35, 38-40, 43-44, 57-58, 74-75
                77, 79-81, 85-86
  Non-zero exit status: 20
t/mojo/content.t                         (Wstat: 2048 Tests: 49 Failed: 8)
  Failed tests:  4, 6, 8, 12-13, 17-18, 20
  Non-zero exit status: 8
t/mojo/cookiejar.t                       (Wstat: 65280 Tests: 65 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/mojo/daemon.t                          (Wstat: 512 Tests: 96 Failed: 2)
  Failed tests:  60-61
  Non-zero exit status: 2
t/mojo/request.t                         (Wstat: 65280 Tests: 353 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/mojo/request_cgi.t                     (Wstat: 65280 Tests: 186 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/mojo/response.t                        (Wstat: 65280 Tests: 267 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/mojolicious/charset_lite_app.t         (Wstat: 512 Tests: 44 Failed: 2)
  Failed tests:  12, 20
  Non-zero exit status: 2
t/mojolicious/lite_app.t                 (Wstat: 1280 Tests: 621 Failed: 5)
  Failed tests:  136, 355, 359, 442, 444
  Non-zero exit status: 5
t/mojolicious/upload_lite_app.t          (Wstat: 2816 Tests: 27 Failed: 11)
  Failed tests:  8-9, 11-12, 14-15, 17-18, 21, 24, 27
  Non-zero exit status: 11
t/mojolicious/upload_stream_lite_app.t   (Wstat: 2560 Tests: 15 Failed: 10)
  Failed tests:  2-3, 5-6, 8-9, 11-12, 14-15
  Non-zero exit status: 10
Files=98, Tests=10218, 93 wallclock secs ( 1.07 usr  0.25 sys + 27.49 cusr  9.58 csys = 38.39 CPU)
Result: FAIL
Failed 11/98 test programs. 58/10218 subtests failed.
make: *** [Makefile:1047: test_dynamic] Error 255

**Comment by muenalan** [comment]
This git repo has travis setup up to perl5.26, so it seems perl5.28 is not on the radar yet.

**Comment by kraih** [comment]
Actually, i use Perl 5.28.0 daily for development on macOS and openSUSE Linux without problems.

**Comment by muenalan** [comment]
So far, it seems for me the culprit must be how perl is compiled (flags). Since t/mojo/asset.t seems pretty generic, and that fails straight away. 

I suppose I have to provide a test log, or Dockerfile to look at it ?

**Comment by fskale** [comment]
Cannot reproduce your problem on debian 8 using perlbrew and OSX 10.13.5 using brew.
Check for supported versions of perl for your distribution: (for alpine linux it's 5.26.2).
[ https://pkgs.alpinelinux.org/packages?name=perl&branch=v3.7](url)
It would urge you to try perlbrew. If the problem still exists, file a bug report to alpine linux 
using the url:
[https://bugs.alpinelinux.org/](url)

**Comment by kraih** [comment]
If it is in fact an unusual Perl built with strange flags, then it would seems rather unlikely that we'd actually want to support it.

**Comment by kraih** [comment]
Unfortunately it looks like nobody else could replicate the problem. So there is no way to investigate this problem.

**Comment by kraih** [comment]
Here's one that works perfectly fine on macOS.
```
Summary of my perl5 (revision 5 version 28 subversion 0) configuration:

  Platform:
    osname=darwin
    osvers=17.6.0
    archname=darwin-2level
    uname='darwin mac 17.6.0 darwin kernel version 17.6.0: tue may 8 15:22:16 pdt 2018; root:xnu-4570.61.1~1release_x86_64 x86_64 '
    config_args='-de -Dprefix=/Users/sri/perl5/perlbrew/perls/perl-5.28.0 -Aeval:scriptdir=/Users/sri/perl5/perlbrew/perls/perl-5.28.0/bin'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.13 -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-O3'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.13 -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=10.13 -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /Library/Developer/CommandLineTools/usr/lib/clang/9.1.0/lib /Library/Developer/CommandLineTools/usr/lib /usr/lib
    libs=-lpthread -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.13 -bundle -undefined dynamic_lookup -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Locally applied patches:
    Devel::PatchPerl 1.48
  Built under darwin
  Compiled at Jun 23 2018 17:08:37
  %ENV:
    PERLBREW_HOME="/Users/sri/.perlbrew"
    PERLBREW_MANPATH="/Users/sri/perl5/perlbrew/perls/perl-5.28.0/man"
    PERLBREW_PATH="/Users/sri/perl5/perlbrew/bin:/Users/sri/perl5/perlbrew/perls/perl-5.28.0/bin"
    PERLBREW_PERL="perl-5.28.0"
    PERLBREW_ROOT="/Users/sri/perl5/perlbrew"
    PERLBREW_SHELLRC_VERSION="0.83"
    PERLBREW_VERSION="0.83"
  @INC:
    /Users/sri/perl5/perlbrew/perls/perl-5.28.0/lib/site_perl/5.28.0/darwin-2level
    /Users/sri/perl5/perlbrew/perls/perl-5.28.0/lib/site_perl/5.28.0
    /Users/sri/perl5/perlbrew/perls/perl-5.28.0/lib/5.28.0/darwin-2level
    /Users/sri/perl5/perlbrew/perls/perl-5.28.0/lib/5.28.0
```
