### ISSUE TITLE
Mojo::File::spurt: Wide character in syswrite

### ISSUE THREAD

**Issue by dk** [kraih/mojo#1236]
* Mojolicious version: 7.87
* Perl version: v5.26.1
* Operating system: ubuntu

### Steps to reproduce the behavior
perl -MMojo::File -le 'Mojo::File->new(q(a.txt))->spurt(qq(\x{100}))'

### Expected behavior
a.txt written with 2 bytes c4 80

### Actual behavior
get error: Wide character in syswrite at /home/dk/perl5/perlbrew/perls/perl-5.26.1/lib/5.26.1/x86_64-linux/IO/Handle.pm line 483.
a.txt is zero bytes

**Comment by pink-mist** [comment]
Mojo::File::spurt is documented to take bytes, but ```qq(\x{100})``` is a character. Encode it to your favourite encoding first.

**Comment by dk** [comment]
>     Write all data at once to the file.

Doesn't seem like bytes to me

**Comment by pink-mist** [comment]
https://metacpan.org/pod/Mojo::File#spurt
```$path = $path->spurt($bytes);```

**Comment by dk** [comment]
Yes, write all bytes from the scalar.

**Comment by dk** [comment]
Wow, just "closed the issue" as a non-issue? That's mature :D

**Comment by dk** [comment]
Well it might be correct, but the documentation "Write all data at once to the file" doesn't say anything about the byte/character distinction, and $bytes can be understood as whatever bytes are there in the scalar, which I would expect. So that's at least a case to either fix the documentation or the attitude.

**Comment by kraih** [comment]
I don't see this discussion end constructively, therefore i'm locking this issue.
