### ISSUE TITLE
delay helper is DEPRECATED, but no transition options are given

### ISSUE THREAD

**Issue by muenalan** [kraih/mojo#1238]
* Mojolicious version: 7.85
* Perl version: 5.28.0
* Operating system: macos

### Steps to reproduce the behavior
Just just the delay helper. 

### Expected behavior
A deprecation warning with *explaination* what to do, alternative options. How can i replace the helper code with what ? 

### Actual behavior
Warnings that delay helper is DEPRECATED. Problem: warning without alternative options. User just panics that the code will stop to work one day.

**Comment by kraih** [comment]
Please use our official support channels. https://mojolicious.org/perldoc#SUPPORT

**Comment by muenalan** [comment]
This discussion is meant to either change/introduce documentation or code. You can mark it as a suggestion, but closing it is not very helpful. For instance, Net::OAuth2::AuthorizationServer tests upon installation produce many of these warnings, just as an example. It affects other CPAN authors along the way, and web searches should end up here, i suppose.

**Comment by kraih** [comment]
You did not propose any specific changes that could be discussed here. Until you reach that stage, please use our official support channels for discussions. https://mojolicious.org/perldoc/Mojolicious/Guides/Contributing#CONTRIBUTING-DOCUMENTATION
