### ISSUE TITLE
Rename App command

### ISSUE THREAD

**Issue by bogdan127** [kraih/mojo#1239]
* Mojolicious version: 7.85
* Perl version: 5.14
* Operating system: Ubuntu 12

Hello, is it possible to add a rename command for mojo?
For example I am generating a core app using:
mojo generate app CoreApp
In this app I add functionalities that will be common in all apps (for example register/login/logout). Then I will want to copy CoreApp to MyNewApp and rename all the files that have CoreApp to MyNewApp.
Thank you!

**Comment by kraih** [comment]
I don't see a reason for why this should be a mojo core feature. You could just release a CPAN module with this functionality.

**Comment by kraih** [comment]
There is also a cookbook recipe for how to do that btw. https://mojolicious.org/perldoc/Mojolicious/Guides/Cookbook#Adding-commands-to-Mojolicious
