### ISSUE TITLE
Mojo::DOM should provide a make_root method

### ISSUE THREAD

**Issue by alexrj** [kraih/mojo#1242]
Suppose I have a document like this:

```xml
<a:root xmlns:a="http://example.com/roots" xmlns:b="http://example.com/subs" xmlns:c="http://example.com/subsubs">
    <b:sub>
        <c:subsub>Hello World</c:subsub>
    </b:sub>
</a:root>
```

If I select the `<b:sub>` element and stringify it, I get:

```xml
<b:sub>
    <c:subsub>Hellow World<c:subsub>
</b:sub>
```

However I'd like to make it a standalone document, thus it should also carry the namespace declarations inherited from the parent elements.
For this purpose I thought about adding a `->make_root` method which would:
1. remove ancestors;
2. select all elements in the fragment having a declared namespace;
3. check whether the fragment contains declarations for those namespaces;
4. if not, find the declaration in the parent elements and add it to the new root element.

What do you think about this? Would this better suit a Mojo::DOM role? I think it would be handy in the core. I also think the current API and the current selectors don't allow to perform the second step listed above.

**Comment by alexrj** [comment]
Okay, here's a possible implementation:

```perl
$elem->descendant_nodes->grep('namespace')->map(sub { $_->tag =~ /^(.*?):/ ? $1 : undef })->compact->each(sub {
    my $ns = shift;
    say $ns;
    if (!$elem->at("xmlns:$ns")) {
        my $decl = $dom->at("[xmlns:$ns]");
        if ($decl) {
            $elem->attr("xmlns:$ns" => $decl->attr("xmlns:$ns"));
        }
    }
});
```

**Comment by kraih** [comment]
That's not a particularly generic feature many users will benefit from. Perhaps release it as a role to CPAN first.

**Comment by alexrj** [comment]
Thank you for your comment. I will consider doing that.
