### ISSUE TITLE
Mojo::Server::Daemon is brittle when Test::Mojo() doesn't have a class name argument

### ISSUE THREAD

**Issue by jamesbriggs** [kraih/mojo#1243]
* Mojolicious version: $Mojolicious::VERSION 7.88

-r--r--r-- 1 root root 12191 Jun  3 05:37 /usr/local/share/perl5/Mojo/Server/Daemon.pm

* Perl version: 5.10.1
* Operating system: CentOS 6.7

### Steps to reproduce the behavior
   # my $t = Test::Mojo->new('MyApp'); # works ok
   # my $t = Test::Mojo->new(); # has inscrutable error listed below and dies inside Mojo::Server::Daemon

### Expected behavior
Either work fine, or die with an error that is more helpful

### Actual behavior
$ prove
[ calls my $t = Test::Mojo->new(); ]

t/basic.t .. # /admin/ping
Can't call method "server" on an undefined value at
	/usr/local/share/perl5/Mojo/Server/Daemon.pm line 61 (#1)
    (F) You used the syntax of a method call, but the slot filled by the
    object reference or package name contains an undefined value.  Something
    like this will reproduce the error:
    
        $BADREF = undef;
        process $BADREF 1,2,3;
        $BADREF->process(1,2,3);
    
Uncaught exception from user code:
	Can't call method "server" on an undefined value at /usr/local/share/perl5/Mojo/Server/Daemon.pm line 61.
 at /usr/local/share/perl5/Mojo/Server/Daemon.pm line 61.
	Mojo::Server::Daemon::start(Mojo::Server::Daemon=HASH(0x47ccb80)) called at /usr/local/share/perl5/Mojo/UserAgent/Server.pm line 40
	Mojo::UserAgent::Server::_url(Mojo::UserAgent::Server=HASH(0x47ccbe0), 0) called at /usr/local/share/perl5/Mojo/UserAgent/Server.pm line 27
	Mojo::UserAgent::Server::url(Mojo::UserAgent::Server=HASH(0x47ccbe0)) called at /usr/local/share/perl5/Mojo/UserAgent.pm line 288
	Mojo::UserAgent::_start(Mojo::UserAgent=HASH(0x4637ad0), Mojo::IOLoop=HASH(0x2d41fa0), Mojo::Transaction::HTTP=HASH(0x47c8430), CODE(0x47c2d40)) called at /usr/local/share/perl5/Mojo/UserAgent.pm line 66
	Mojo::UserAgent::start(Mojo::UserAgent=HASH(0x4637ad0), Mojo::Transaction::HTTP=HASH(0x47c8430)) called at /usr/local/share/perl5/Test/Mojo.pm line 381
	Test::Mojo::_request_ok(Test::Mojo=HASH(0x47ae680), 
[...]

**Comment by kraih** [comment]
I'm afraid this issue is incomprehensible, so there is nothing we can do.
