### ISSUE TITLE
Mojolicious::Sessions should include max-age

### ISSUE THREAD

**Issue by srchulo** [kraih/mojo#1244]
Is there a reason Mojolicious::Sessions doesn't include a max-age option that defaults to 3600 like the expires time? I could help implement this if this is okay.

**Comment by kraih** [comment]
What would we gain by supporting this? And i don't mean theoretical value, but practical real world value. Which browsers would act differently in which situations?

**Comment by kraih** [comment]
The way i see it, `Expires` just works everywhere and a smaller cookie value means more space for actual session data. [RFC 6265](https://tools.ietf.org/html/rfc6265) still warns that `Max-Age` does not work everywhere.

**Comment by srchulo** [comment]
The benefit comes in when user clocks and server clocks don't match up. If you set a session for an hour and the clocks differ by an hour or more (not timezone, but just wrong), the session will be broken for users. Max-age wouldn't fix this for all users, but it could at least fix it for users using any modern browsers. All modern browsers (except for Microsoft Edge, I believe) support this:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#Browser_compatibility

So it should affect a lot of users. And if you include expires and max-age, browsers that support max-age will use that instead and browsers that don't will just ignore and use expires, so this would have no negative impact and only positive, and would only add a small amount of code.

**Comment by kraih** [comment]
I suppose my vote on this would depend on the size of the patch.

**Comment by srchulo** [comment]
Okay. I'll write something up and see if you are okay with it.

**Comment by shadowcat-mst** [comment]
IIRC if the time's off in the response, even if the cookie has no expires, firefox discards it. So honestly making sure the server time is correct is a better path anyway.

**Comment by srchulo** [comment]
I agree that making sure the server time is correct is good, except there's always the case where the user's time is incorrect and a session is invalid immediately.

**Comment by kraih** [comment]
I'll assume that this has been superseded by #1246.

**Comment by yusrideb** [comment]
if this issue stil relevant, I have updated into Mojolicious::Sessions with d8e2f21.
I guess important to adding "max-age" support
