### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by kraih** [kraih/mojo#1245]
I think it might be time for our logo to get a little refresh. Perhaps something more colorful and modern, like [this](https://dribbble.com/shots/3671457-Cloud-logo-design) for example. We currently have 5 uses where a new logo would need to work, as a favicon, as a gravatar, on t-shirts, and of course in the menu bar and at the bottom of [the site](https://mojolicious.org).

**Comment by kraih** [comment]
It might be nice to stick with Myriad Pro for the typeface. But i wouldn't really mind switching to something else like Futura if it fits.

**Comment by yusrideb** [comment]
The Logo is fresher and elegant.

**Comment by kraih** [comment]
I don't really want to limit the scope for ideas, but the logo i imagine currently would be a somewhat geometric cloud. With a color palette that's friendly but also a bit stylish and modern. Something like the [Firefox](https://blog.mozilla.org/opendesign/evolving-the-firefox-brand/) color palette.

**Comment by s1037989** [comment]
I have a few contacts and am getting some info.  Do you have any idea how many hours might be required for this?

**Comment by kraih** [comment]
@s1037989 Thank you, we already found a designer and the new logo is almost done. 😀

**Comment by kraih** [comment]
A small preview. The logo should be finalized next week.
![mojologious](https://user-images.githubusercontent.com/30094/43648946-1d56f8f8-973c-11e8-8e0c-e262c5d6be55.png)

**Comment by s1037989** [comment]
Looks great!!

**Comment by rmallah** [comment]
Hi

The Squarish logos shall be better in more situations.

The logos look great!

regds
Rajesh Kumar Mallah.

**Comment by yusrideb** [comment]
Maybe it's good if the background is dark, there are no cloud lines or thinner cloud lines.
but if the background uses bright colors, the lines of clouds with dark colors

**Comment by yusrideb** [comment]
I have a concept with a logo that doesn't matter using any color.

![mojolicious-draft-idea](https://user-images.githubusercontent.com/6322095/43657029-26b21d88-9787-11e8-81a0-27fdabb57975.png)

**Comment by yusrideb** [comment]
Can also be used as follows:
![mojolicious-draft-idea1](https://user-images.githubusercontent.com/6322095/43657536-c0104eb8-9788-11e8-944b-000eda49914f.png)

**Comment by Tekki** [comment]
Why is the cloud flat a the bottom? Everyone makes it this way, so we should not.
The colors look nice.

**Comment by kraih** [comment]
No changes, it's perfect.
