### ISSUE TITLE
Client hangs forever on error

### ISSUE THREAD

**Issue by gudupa** [kraih/mojo#1251]
Mojolicious version: 5.28
Perl version: 5.10.1
Operating system: Linux

Steps to reproduce the behavior
Simulate an error in the method _read in Stream.pm . The error will be caught in the method _listen  ( The code block $stream->on(error..., ) in Daemon.pm. The method returns by just logging the error. But it doesn't send an error code back to the HTTP response.  Due to this, the calling client will hang.

Expected behavior
It should send an HTTP error code on this error.

Actual behavior
It just prints the error and doesn't delegate error to the caller ( There is no error printed though. Just a log message with error log level with no description).

**Comment by jberger** [comment]
If you entered the mojolicious version correctly and you are actually running version 5.28, then unfortunately we will have to close this as a long obsoleted version. If you still experience this problem on the current release then you are welcome to note that and reopen.

**Comment by gudupa** [comment]
Thanks for the quick response. Appreciate.  I looked at the latest version. Here also, we dont seem to take any action on error .
https://github.com/kraih/mojo/blob/master/lib/Mojo/Server/Daemon.pm#L199
Need one help. If we were to send an error back in this block, how would it look like?.  Which is the handle name in $self for http response?.  Due to some reasons, I am unable to print this hash content.
Thanks in advance

**Comment by kraih** [comment]
There is clearly a communication problem here. Please try discussing the problem on our official support channels first, and only open an issue here once you've received confirmation that it is in fact a Mojolicious bug. https://mojolicious.org/perldoc#SUPPORT
