### ISSUE TITLE
Support setting log file location from hypnotoad

### ISSUE THREAD

**Issue by marcusramberg** [kraih/mojo#280]
My system administrators wants mojolicious to log to /var/log. Wouldn't it be useful to be able to set this from hypnotoad.conf?

**Comment by KES777** [comment]
I use hypnotoad to run my app: `$ hypnotoad myapp.pl`. Also I have log directory near my app where the 'production.log' is created. 
That seems it is not possible to point hypnotoad server save logs to different file

Also myapp.conf file is not loaded

**Comment by KES777** [comment]
I must set up MOJO_CONFIG like:
`MOJO_CONFIG=my.conf hypnotoad myapp.pl`

**Comment by jhthorsen** [comment]
@marcusramberg: https://metacpan.org/pod/distribution/Toadfarm/lib/Toadfarm/Manual/DSL.pod#logging

Just a reminder: You can use Toadfarm for just a single app as well. It will just set up the config parameters for you.
