### ISSUE TITLE
invalid pid_file not updated by hypnotoad

### ISSUE THREAD

**Issue by coffeemonster** [kraih/mojo#383]
Hi,

In Mojo::Server::Hypnotoad the _manage() loop calls _pid_file() which only checks for the existence of the pid_file - not to see if the pid contained is running.

```
sub _pid_file {
  ...
  # Check if PID file already exists
  return if -e (my $file = $self->{config}{pid_file});

  # possible replacement line
  # return if kill 0, $self->_pid;
```

I would expect at startup for this file to be initialised to a valid value otherwise you get the following situation:

```
$ echo "123" > hypnotoad.pid
$ hypnotoad myapp.pl
$ hypnotoad -s myapp.pl 
Stopping Hypnotoad server 123 gracefully.
$ ps auxf | grep myapp.pl | grep -v grep | wc -l
5
```

Not sure about the best way to resolve this - at startup is probably good enough.

```
sub run { 
  ...
+      # no existing process running with our pid file so reset it.
+      unless (kill 0, $self->_pid) {
+        if (my $file = $c->{pid_file})  { unlink $file if -w $file }
+      }

  # Mainloop
  $self->_manage while 1;
}
```

Cheers,

**Comment by port22** [comment]
If hypnotoad is run in containers and is force-stopped, it won't start the next time because it handles the pid file not very well. If there is no pid matching, it should recreate the pid-file and start the server.
