### ISSUE TITLE
Mojo::JSON evaluates dualvars in numeric context when encoding

### ISSUE THREAD

**Issue by stellatigre** [kraih/mojo#591]
The convention set by Perl itself is to render a dualvar's string data. The same goes for the encoding functions of `JSON::PP`, `JSON::XS`, and `JSON::Syck`. Can `Mojo::JSON`'s behavior be changed to follow suit?

**Comment by nichtich** [comment]
By the way YAML::XS and Data::Dumper also emit numbers for dualvars and YAML::XS reads numbers as dualvars, so there is no round-tripping with JSON::XS (but with Mojo::JSON).
