### ISSUE TITLE
Semicolon not supported as query string separator in 4.90

### ISSUE THREAD

**Issue by Gilwyad** [kraih/mojo#708]
Tested with the following simple program:

```
use Mojolicious::Lite;

# Route with placeholder
get '/foo' => sub {
        my $c   = shift;
        my $foo = $c->param('foo');
        my $bar = $c->param('bar');
        $c->render(text => "Hello from $foo.  Bar = '$bar'.\n");
    };

# Start the Mojolicious command system
app->start;
```

using 4.63 it works:

```
$ curl 'localhost:3000/foo?foo=a&bar=b'
Hello from a.  Bar = 'b'.
$ curl 'localhost:3000/foo?foo=a;bar=b'
Hello from a.  Bar = 'b'.
```

but 4.90 does not recognize the semicolon separated parameter:

```
$ curl 'localhost:3000/foo?foo=a&bar=b'
Hello from a.  Bar = 'b'.
$ curl 'localhost:3000/foo?foo=a;bar=b'
Hello from a;bar=b.  Bar = ''.
```

Is support for the semicolon dropped or is this a regression? I did not check with other versions.

**Comment by ungrim97** [comment]
https://tools.ietf.org/html/rfc3986

The full specification allows for a wide variety of separators and and web server should attempt to be as allowing as possible to prevent issue.

Also ; are often used instead of & for embedded URIs within hrefs to prevent issues with HTML entity encoding. It is even recommended in the URI docs (https://metacpan.org/pod/URI#uri-query_form-hash-delim)

**Comment by pmorch** [comment]
I understand this was done on purpose, and knowing @kraih, that is decision is probably final. For others that may have to interoperate with other systems that issue such URLs, support can be re-added with this patch:
```
diff --git a/lib/Mojo/Parameters.pm b/lib/Mojo/Parameters.pm
index c7de85c..cc6c24a 100644
--- a/lib/Mojo/Parameters.pm
+++ b/lib/Mojo/Parameters.pm
@@ -81,7 +81,7 @@ sub pairs {
     return $pairs unless length $str;
 
     my $charset = $self->charset;
-    for my $pair (split '&', $str) {
+    for my $pair (split /[&;]/, $str) {
       next unless $pair =~ /^([^=]+)(?:=(.*))?$/;
       my ($name, $value) = ($1, $2 // '');
 
```

The previous support was removed in: commit 2d1cf0eaa8abc78e44edf88dc0b4a14d4f451571
