### ISSUE TITLE
Net::DNS::Native and Mojolicious on Linux

### ISSUE THREAD

**Issue by olegwtf** [kraih/mojo#716]
As we noticed yesterday `Net::DNS::Native` with perl not linked with pthreads still may crash on Linux: https://rt.cpan.org/Public/Bug/Display.html?id=100834

Today I found a way to reproduce this problem with the following server

``` Perl
use Mojolicious::Lite;
use Mojo::IOLoop;

get '/' => sub {
        my $self = shift;

        Mojo::IOLoop->timer(rand(1) => sub {
                $self->render(json => [qw/a b c d e d/]);
        });
};

app->start;
```

and client

``` Perl
use strict;
use Mojo::UserAgent;
use Mojo::IOLoop;

my $ua = Mojo::UserAgent->new;
my @links = ("http://data-flow.ru:3000") x 5000;

while (@links) {
        Mojo::IOLoop->delay->new->steps(
                sub {
                        my @l = splice @links, 0, 50;
                        my $delay = shift;
                        $ua->get($_ => $delay->begin) for @l;
                },
                sub {
                        warn "+50";
                }
        )->wait
}
```

where you need to change data-flow.ru to your own domain (but not localhost).
This client segfaults 10 times out of 10

And the fix is as simple as

``` diff
 use strict;
+use Net::DNS::Native;
 use Mojo::UserAgent;
 use Mojo::IOLoop;
```

And all the problem caused by ... my favorite `IO::Socket::IP`. Look. Mojolicious loads `IO::Socket::IP` [here](https://metacpan.org/source/SRI/Mojolicious-5.68/lib/Mojo/IOLoop/Client.pm#L5) and `IO::Socket::IP` has [this](https://metacpan.org/source/PEVANS/IO-Socket-IP-0.34/lib/IO/Socket/IP.pm#L39) construction which executes `getprotobyname()` at compile time. Looks ok, but this loads non thread safe DNS part of libc (because our perl not linked with pthreads). And only after that Mojolicious [loads](https://metacpan.org/source/SRI/Mojolicious-5.68/lib/Mojo/IOLoop/Client.pm#L13) `Net::DNS::Native`, which can't replace non-thread safe DNS part of libc with thread safe even with [RTLD_GLOBAL](https://metacpan.org/source/OLEG/Net-DNS-Native-0.13/lib/Net/DNS/Native.pm#L23) flag.
So, you can comment mentioned line of `IO::Socket::IP` and all will work good
Or you can load `IO::Socket::IP` after `Net::DNS::Native` inside Mojolicious and all will work good
But you can't fix this inside `Net::DNS::Native`

The sad part is that if we'll fix this inside Mojolicious where is the warranty that somebody will not write smth like

``` Perl
use IO::Socket::IP
use Mojo::IOLoop::Client
```

I can disable non pthreaded perl support on Linux inside `Net::DNS::Native` again, which will fix this problem at all. But this is a big amount of users.

Btw [Tux] from #p5p promised to add "linking with pthreads by default" feature few months ago. Looks like I need to remind him about this :)

Thoughts?

**Comment by leonerd** [comment]
I wonder if at least some of this could be fixed by adjusting the code in `IO::Socket::IP` to defer that compiletime call to `getprotobyname()` somehow? Would that help?
