### ISSUE TITLE
Validate <input type="checkbox">

### ISSUE THREAD

**Issue by rshadow** [kraih/mojo#729]
The browser sends the value of the checkbox only if it is checked. So you can not write a validator that will not be considered a mistake missing value.
Please add another function (in addition to require and optional) so that you can check the value of the checkbox. For example:
```perl
sub checked{
    my ($self, $name) = @_;

    my $input = $self->input->{$name};
    $self->output->{$name} = $input;

    return $self->topic($name);
};
```
P.S.Translated by Google Translate

**Comment by jhthorsen** [comment]
@rshadow: I don't get it. Isn't that what ```optional()``` does?

**Comment by rshadow** [comment]
I want a checkbox сhecker always set to 1 for the selected and 0 for the not selected. Validator optional() set the undef if the value does not come, or come empty string. Checker does not start and I can not do anything with it.
I want to run the checker always, when I call, no matter what the value is. It is necessary only for checkboxes.

**Comment by jhthorsen** [comment]
It seems like you want to set a default value, which doesn't have anything to do with validating. You could do this on input or output. You probably want to set it on input if you want to validate the default value:

    $c->validation->input->{your_checkbox} //= 0;

i think either google translate trips me off, or this is not a bug.

**Comment by rshadow** [comment]
ok. thanks.
