### ISSUE TITLE
t/mojo/util.t requires Sub::Util v1.41

### ISSUE THREAD

**Issue by mjemmeson** [kraih/mojo#730]
Fatal test error with Sub::Util v1.40

Although t/mojo/util.t checks whether it can load Sub::Util, it doesn't check whether it loads a version with subname() and it appears that v1.40 of Sub::Util added the POD for the method but not the method itself.

So something like the following might be required?

    skip 'Sub::Util required!', 2 unless eval { require Sub::Util; return $Sub::Util::VERSION >= "1.41"  };

thanks,
Michael

**Comment by Grinnz** [comment]
Perhaps it should match the loading of Sub::Util in Mojo::Util (but check subname instead of set_subname): https://github.com/kraih/mojo/blob/master/lib/Mojo/Util.pm#L32

**Comment by mjemmeson** [comment]
Thanks, I'd tried ->can() first but didn't seem to work (must have been PEBKAC). Will submit a PR now

**Comment by kraih** [comment]
Thanks, fixed.

**Comment by kraih** [comment]
Btw. It looks like `subname` and `set_subname` do exist in `Sub::Util` 1.40, but the two checks should indeed be consistent. https://metacpan.org/source/PEVANS/Scalar-List-Utils-1.40/ListUtil.xs#L1262
