### ISSUE TITLE
The description in Rendering.pod is a little bit confusing

### ISSUE THREAD

**Issue by henryan** [kraih/mojo#732]
I find my self very confused by the description of the syntax (since line 70) in lib\Mojolicious\Guides\Rendering.pod.  I'm wondering if this could be improved. 

<% Perl code %>
<%= Perl expression, replaced with result %>
<%== Perl expression, replaced with XML escaped result %>
<%# Comment, useful for debugging %>
<%% Replaced with "<%", useful for generating templates %>
% Perl code line, treated as "<% line =%>"
%= Perl expression line, treated as "<%= line %>"
%== Perl expression line, treated as "<%== line %>"
%# Comment line, useful for debugging
%% Replaced with "%", useful for generating templates

What confused me are:
1. What's Perl code ? What's Perl expression? What's Perl code line? What are the differences between them? 
Is a variable itself considered an expression in Perl ?
It seems to me that the Perl expression here means Perl expression and Perl variable. 
It seems to me that <% Perl code %> is the start or end of the Perl code block in the template
2. What's "<% line =%>" ? It is only mentioned once in the syntax description, What does it has in difference to the "<%= line %>"  or "<% line %>" 
3. It would be more helpful if the document can provide sample and its output as well.
For example, line 132 of this pod, 
<%= All whitespace characters around this expression will be trimmed =%>
I tried several times to figure out what it really means by writing a testing script containing code snippet like the following
<%= $var1 =%>     after space

Another possible issue is in lib\Mojo\Template.pm, line 310
  % my ($num, $text) = @_;
the variable $text is never used after it is declared

**Comment by niczero** [comment]
I find myself disagreeing that these are issues, since each of the terms is using precisely its normal meaning.
'code' is any valid code;
'expression' is some code that evaluates to a value (yes it can be a variable but that is just an example),
'line' means it fits on a line, ie it contains no line endings within it.

It sounds like you are very close to understanding these terms, but they're not specific to Mojolicious, or even perl.

**Comment by niczero** [comment]
The code you mention at the bottom also caught my eye the first time I saw it.  But it's not a mistake.  It illustrates the use of multiple values passed (a typical use-case) but there would be no extra value in including $text in the remainder.  Remember that examples try to illustrate the maximum with the minimum of reading effort.

**Comment by kraih** [comment]
Yea. i've modified the example, if the variable is there we might as well use it. :smile: https://github.com/kraih/mojo/commit/f8776a388a36474e3452c686ebd971de3c0a5aa5

**Comment by kraih** [comment]
Otherwise i have to agree with @niczero, those are all very generic terms. If there are ways to make it easier to grok, i'm of course in favor of that, but i don't think that's the case here yet.

**Comment by kraih** [comment]
Closing this issue since it looks like the discussion has ended without new proposals.
