### ISSUE TITLE
Warn only once (or a few times) on deprecated functionality

### ISSUE THREAD

**Issue by eserte** [kraih/mojo#736]
This would avoid excessive logs like the one here: http://www.cpantesters.org/cpan/report/51ca89d6-a7e6-11e4-a9a5-11d7dfbfc7aa

**Comment by Grinnz** [comment]
This appears to be due to recursion in the render_not_found helper which was fixed in the latest update to Clustericious.

**Comment by kraih** [comment]
Looks like this feature request does not have much support.
