### ISSUE TITLE
Directory traversal when deployed on Windows

### ISSUE THREAD

**Issue by mmulder99** [kraih/mojo#738]
We have discovered a directory traversal issue with Mojo in a Windows environment. The following URLs allow the win.ini file to be exposed:

https://<server name>/.../.../.../.../.../.../.../.../.../windows/win.ini
https://<server name>/...\...\...\...\...\...\...\...\...\windows\win.ini

A previous fix in the dispatch subroutine of the Static.pm fixed directory traversal with '..' but there still appears to be a problem with Windows and '...'. 

Adding a check for '...' in the dispatch method in addition to the '..' appears to fix the problem. For example, the following appears to fix the problem and now the application will pass security scans on our system:

return undef if $parts[0] eq '..' || '...' || !$self->serve($c, join('/', @parts));

**Comment by kraih** [comment]
Thanks for the report, but in the future we would very much appreciate responsible disclosure. http://mojolicio.us/perldoc/Mojolicious/Guides/Contributing#Reporting-security-issues

**Comment by oliwer** [comment]
@mmulder99 can you give us more info on how to reproduce the "https:///...........................\windows\win.ini" case? None of could reproduce this bug using more than 3 dots.

**Comment by kraih** [comment]
@mmulder99 I second the request from @oliwer.

**Comment by dagolden** [comment]
Just to weigh in, it looks like File::Spec::Win32::canonpath will translate `...` to `..\..` as part of just about any File::Spec file method.  But it will not translate longer dot sequences.  But that's purely a legacy "feature" of File::Spec.  AFAICT, at least on Win7, `...` has no special handling in the OS.  I tested it myself and also found [this article](https://social.technet.microsoft.com/Forums/windowsserver/en-US/73e6ca2a-db06-4c2d-bfd0-b175aa2f325b/cd-with-three-dots-after-the-cd-would-take-you-back-two-directories-not-anymore?forum=winserver8gen).

So what I think happened is that `...` got translated to `..\..` by File::Spec, and `updir` is either buggy or is a poorly documented feature, as it only stops `.` and `..` and not longer sequences.

FWIW, in Path::Tiny terms, a robust check would be this:

```
if ( path($web_root)->realpath->subsumes( path($url_path)->realpath ) ) {
   # path is good
}
```

That ensures that `$url_path` is under the `$web_root` after resolving parent directories and symlinks.

**Comment by mmulder99** [comment]
Thanks for the fast response on this issue, and next time I'll go through the proper channels for security issues.

This problem happens on Windows 7 Enterprise (SP1). I can reproduce it in my development environment using morbo as the server and trying to access the site using a  http://localhost:3000/.../.../windows/win.ini in Chrome will cause the contents of my win.ini file to be displayed in the browser.

**Comment by dagolden** [comment]
Oh!  @mmulder99, is the "https:///...........................\windows\win.ini" example really supposed to be `https:///...\...\...\...\...\...\...\...\...\windows\win.ini`?  I.e. Github ate your backslashes?

**Comment by kraih** [comment]
@dagolden I looked into the markup of the original post, and that's exactly what happened. (`https://<server name>/...\...\...\...\...\...\...\...\...\windows\win.ini`)
