### ISSUE TITLE
Mojo::URL->path default charset when populated from external utf8 source.

### ISSUE THREAD

**Issue by coffeemonster** [kraih/mojo#740]
When providing a utf8 string from a file (eg. sitemap.xml) and using it in Mojo::URL->new($utf8_url)  the url-path gets double encoded by Mojo::Path::to_string. I came across this issue when crawling urls listed in a sitemap. I'm not sure if this a problem with Mojo::URL, Mojo::DOM or if I need to deal with the case myself.

With UTF-8 being the default everywhere (Mojo::Path, Mojo::Message) I would expect the URL that I extract from the sitemap.xml to be treated as if the "use utf8;" pragma was in use. Or be able to change the charset at a high level for Mojo::URL.

Eg.1 grab URLs from a sitemap:
    #!/usr/bin/env perl
    use strict; use warnings; use feature qw/say/; use utf8;
    use Mojo::UserAgent;
    my $ua = Mojo::UserAgent->new;
    my @urls = $ua->get("https://hootsuite.com/ja-jp/sitemap.xml")
                              ->res->dom->find('loc')->map('text')->each();
    my $url = Mojo::URL->new($urls[1]);
    say $urls[1];
    say $url; # not ok - double encoded utf8
    $url->path->charset("");
    say $url; # ok

Eg.2 expected url encoding behaviour
    perl -Mutf8 -MMojo::URL -E 'say Mojo::URL->new("https://hootsuite.com/ja-jp/リソース");'
    https://hootsuite.com/ja-jp/%E3%83%AA%E3%82%BD%E3%83%BC%E3%82%B9
    
Eg.3 without "use utf8;" that double encodes
    perl -MMojo::URL -E 'say Mojo::URL->new("https://hootsuite.com/ja-jp/リソース");'
    https://hootsuite.com/ja-jp/%C3%A3%C2%83%C2%AA%C3%A3%C2%82%C2%BD%C3%A3%C2%83%C2%BC%C3%A3%C2%82%C2%B9

(I see charset support from Mojo::DOM got removed https://github.com/kraih/mojo/commit/2dc883a6a607a965edd801305e908dffba8b982c
which is possibly where I would be looking to make this change.)

perl (v5.16.2) with Mojolicious v5.77

**Comment by kraih** [comment]
I'm afraid this is expected behavior, since `Mojo::Message::dom` does not know how to decode the message body in this case, and just passes along the raw bytes to `Mojo::DOM`.

**Comment by kraih** [comment]
This specific case might work better in the next release though. https://github.com/kraih/mojo/commit/32be807217c93e662ef443e7bdb7ecb053596481
