### ISSUE TITLE
Unescaped special characters in query parameters result in empty path used for route matching

### ISSUE THREAD

**Issue by jkramer** [kraih/mojo#751]
If query parameter in the URL contains special characters, the [START_LINE_RE regex](https://github.com/kraih/mojo/blob/master/lib/Mojo/Message/Request.pm#L13-L17) doesn't match, which results in extract_start_line returning an empty (undef) start line, discarding the entire URL and thus not matching any routes and returning a 404. This happens mostly with curl, because curl doesn't url-encode URL parameters automatically:

    curl -s 'http://localhost:3000/route/wont/match?q=straße'

Fix: Make $START_LINE_RE a little more lax. Even if a parameter does contain weird stuff, the URL should still be processed for route matching etc.

**Comment by kraih** [comment]
Could you elaborate on "a little more lax"? And what do the respective RFCs say on the topic? Are there security implications?

**Comment by kraih** [comment]
It might also be worth checking what common web servers like Apache and Nginx accept.

**Comment by Grinnz** [comment]
nginx: curl -s 'http://localhost/route/wont/match?q=straße' -> "GET
/route/wont/match?q=stra\xC3\x9Fe HTTP/1.1"
apache: curl -s 'http://localhost/route/wont/match?q=straße' -> "GET
/route/wont/match?q=stra\xc3\x9fe HTTP/1.1"

**Comment by kraih** [comment]
Thanks @Grinnz, i think we can try being a little more relaxed.

**Comment by jkramer** [comment]
I'm a little late, but I found this in RFC 3986:

> In local or regional contexts and with improving technology, users
> might benefit from being able to use a wider range of characters;
> such use is not defined by this specification.  Percent-encoded
> octets (Section 2.1) may be used within a URI to represent characters
> outside the range of the US-ASCII coded character set if this
> representation is allowed by the scheme or by the protocol element in
> which the URI is referenced.  Such a definition should specify the
> character encoding used to map those characters to octets prior to
> being percent-encoded for the URI.

I'm not sure how to interpret this. I think it either says "non-ascii characters may be used (only) WHEN they're percent-encoded" or "you may use percent-encoded octets to represent non-ascii characters (but you don't have to)".

**Comment by fheyer** [comment]
I think it's an interesting discussion. This is the relevant part of the url spec (http://www.w3.org/Addressing/URL/url-spec.html): 
> This specification makes no assumptions or requirements about the character sets, if any, referred to  the (decoded) octets a URL. Character codes other than those allowed by the syntax shall not be used unencoded in a URL.

IMHO in HTTP spec (http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.3) there is no way to specify the character set used in the url. Theres is only a header `Accept-Charset` to specify accepted character sets in the responso. Did i read that correctly?
