### ISSUE TITLE
POST parameters not available when run with CGI

### ISSUE THREAD

**Issue by abracadaniel** [kraih/mojo#752]
Hi,

I am experiencing a quite strange bug, i've made a small API and i am trying to make a POST request with some data to it, but i am not able to get the POST parameters, when i am running the API with apache, but when i am running it as a daemon it works fine. So how the POST parameters are missing in Mojolicious when running it with apache?

Here is the code:

use Mojolicious::Lite;
use CGI;
use ComparisonFeed::Item;
use functions;
use db;
use Data::Dumper;
use JSON;
 
my $q = new CGI;
my ($dbh_master, $dbh_slave) = &db::connect;
 
group {
    my $feedItem;
   
    under '/comparisonFeedItem' => sub {
        my $c = shift;
      
        $feedItem = new ComparisonFeed::Item($c->param('id'));
    };
   
    post 'save' => sub {
        my $c = shift;
        #my $data = $q->param('data');              # works when executed in apache2 using CGI
        my $data = $c->param('data');           # works when executed in daemon
        $c->render(text => $data);
    };
};

app->mode('production');
app->start;
db::disconnect();
exit 0;

**Comment by kraih** [comment]
Using Mojolicious with `CGI.pm` is unsupported i'm afraid.
