### ISSUE TITLE
Hypnotoad multi app setup

### ISSUE THREAD

**Issue by raigad** [kraih/mojo#755]
Hi, 
It seems that hypnotoad can not run several apps on different port at same time.  
For e.g, two script app1.pl and app2.pl I want to be able to run them on different port on same server. 

app1.pl
```

use Mojolicious::Lite;

app->config(hypnotoad => {listen => ['http://127.0.0.1:3001'],multi_accept=>2});

get '/' => {text => 'Hello World, APP2 port:3001'};

app->start;

```

app2.pl
```
use Mojolicious::Lite;

app->config(hypnotoad => {listen => ['http://127.0.0.1:3002'],multi_accept=>2});

get '/' => {text => 'Hello World, APP2 port:3002 '};

app->start;

```

I run following command 

``` hypnotoad app1.pl ```

and

``` hypnotoad app2.pl  ```

For second app second , I get message **Starting hot deployment for Hypnotoad server** but nothing happens. 

I might be missing something is there any other way to achive this ?

Thanks
Regards
Rohit

**Comment by kraih** [comment]
This looks more like a question for the mailing-list or IRC. http://mojolicio.us/perldoc/Mojolicious/Guides/Contributing#SUPPORT
