### ISSUE TITLE
Centos 6 EPOLL Mojo::IOLoop::Client strange behaviour

### ISSUE THREAD

**Issue by alexbyk** [kraih/mojo#759]
Rewritten to make it possible find this issue with the help of Google and save someone's time:

If you get a connection timeout error with localhost (or 127.0.0.1), stop looking for heisenbugs, check your /etc/hosts file twice.
`::1 localhost ...` - this might be an issue. See an explanation from Grinnz below

**Comment by Grinnz** [comment]
In my case I had this issue because "localhost" was allowing an IPv6
connection which seems to have issues on my Centos6 box. Using 127.0.0.1
forces it to use IPv4.

**Comment by Grinnz** [comment]
To clarify what I think is happening: In your example, localhost doesn't
work because it tries IPv6 which resolves it to ::1; this is not what you
are listening on.

**Comment by alexbyk** [comment]
@Grinnz thanks, ur right! I was sure that I disabled IPv6 and was going to answer 'no, that's smthng differend'. But I checked my /etc/hosts file and found a surprise.

I'll rewrite this issue to make it possible find your answer using google.
