### ISSUE TITLE
Test failures on Windows

### ISSUE THREAD

**Issue by nanis** [kraih/mojo#761]
With Mojolicious 6.02, I get the following test failures. It seems to me all three failures stem from the same underlying cause, but I may be wrong.

This is Perl 5.20.2 64-bit on Windows 8.1 compiled with Visual Studio 2013.

<pre>C:\...\Mojolicious-6.02> prove -b t\mojolicious\app.t     
t\mojolicious\app.t .. 241/?                                                                  
#   Failed test 'Last-Modified: Sat, 21 Feb 2015 05:08:18 GMT'                                
#   at t\mojolicious\app.t line 405.                                                          
#          got: 'Sat, 21 Feb 2015 06:08:18 GMT'                                               
#     expected: 'Sat, 21 Feb 2015 05:08:18 GMT'                                               
                                                                                              
#   Failed test '304 Not Modified'                                                            
#   at t\mojolicious\app.t line 425.                                                          
#          got: '200'                                                                         
#     expected: '304'                                                                         
                                                                                              
#   Failed test 'exact match for content'                                                     
#   at t\mojolicious\app.t line 425.                                                          
#          got: 'Hello Mojo from a development static file!                                   
# '                                                                                           
#     expected: ''                                                                            
# Looks like you failed 3 tests of 440.                                                       
t\mojolicious\app.t .. Dubious, test returned 3 (wstat 768, 0x300)                            
Failed 3/440 subtests</pre>

Sanity checking:

<pre>C:\...\Mojolicious-6.02> perl -MMojo::Date -E "say Mojo::Date->new((stat 't/mojolicious/public/hello.txt')[9])"
Sat, 21 Feb 2015 05:08:18 GMT</pre>

*Is there an extra DST adjustment happening somewhere?* (something Windows specific maybe?)

**Comment by nanis** [comment]
Well, exactly what type of information would be helpful?

<pre>C:\...\Mojolicious-6.02> dir t\mojolicious\public_dev         
...
2015-02-21  01:08 AM                43 hello.txt                                                  </pre>

<pre>C:\...\Mojolicious-6.02> perl -MTime::Local -E "say scalar gmtime(timelocal(0, 8, 1, 21, 1, 2015))"</pre>

Sat Feb 21 06:08:00 2015</pre>

**Comment by nanis** [comment]
Also:

<pre>C:\...\Mojolicious-6.02> perl -MDateTime -E "$dt = DateTime->new(year=>2015, month=>1, day=>21, hour=>1, minute=>8, second=>0, time_zone=>'America/New_York')->set_time_zone('UTC'); say $dt"
2015-01-21T06:08:00</pre>

**Comment by kraih** [comment]
We would ask if we knew what information was need. All i can say so far is that this just isn't enough to even try anything.

**Comment by kraih** [comment]
What i can say, is that it doesn't look like any of the responsible Mojolicious code has changed much in years, and so far you are the only one who has ever encountered this problem.

**Comment by nanis** [comment]
OK. So, to summarize, there is a file with local filesystem date:

2015-02-21  01:08 AM                43 hello.txt  

in the America/New_York time zone. I have checked with Time::Local and DateTime as well as an online service that this resolves to 2015-02-21T06:08:00 UTC.

The last modified header value is returned correctly, whereas the expected value obtained using `Mojo::Date->new((stat $path)[9])->to_string;` is `Sat, 21 Feb 2015 05:08:18 GMT` which is one hour earlier.

<pre>C:\...> perl -E "say +(stat 't\mojolicious\public_dev\hello.txt')[9]"
1424495298</pre>

<pre>perl -E "say scalar gmtime 1424495298"
Sat Feb 21 05:08:18 2015</pre>

**OUCH!**

So, either this is a problem specific to `stat` in the context of my build, or Windows.

Note timezone offset change that happened on March 1st in this time zone. Interesting.

You are right that this does not seem to be a Mojolicious issue.

**Comment by nanis** [comment]
It turns out, this is a known issue, and there is a CPAN module for it [Win32::UTCFileTime](https://metacpan.org/pod/Win32::UTCFileTime). To avoid spurious test failures, it may be a good idea to conditionally require and load this module.

**Comment by kraih** [comment]
That seems silly, the server uses `stat` too to set the `Last-Modified` header. https://github.com/kraih/mojo/blob/master/lib/Mojo/Asset/File.pm#L122

**Comment by kraih** [comment]
Does this make a difference? https://github.com/kraih/mojo/commit/f0f3e916170b4f278c360e9ac63140e5e181a10a

**Comment by nanis** [comment]
I know, it seems weird, but that's the only thing I can think of that would create a one hour difference. I will check if `f0f3e91` helps.

Thank you.

**Comment by nanis** [comment]
<pre>All tests successful.
Files=85, Tests=10164, 183 wallclock secs ( 1.69 usr +  0.20 sys =  1.89 CPU)
Result: PASS</pre>

Thank you.

That was a clever way to fix this particular problem, although the Windows time adjustment would affect non-Windows clients checking with a server on Windows with certain `If-Modified-Since` requests.

I am going to leave this link here in case anyone else comes across this thread.

[UTC in Windows](https://wiki.archlinux.org/index.php/Time#UTC_in_Windows)

**Comment by kraih** [comment]
So to sum it up calling `stat` on the path of a file gives different results than calling `stat` on a handle for the same file. Stay classy Windows. :hankey:

**Comment by nanis** [comment]
Well, it's bad:

<pre>C:\...\Temp> c:\opt\cygwin64\bin\touch -t 201502210108.00 test-file.txt
C:\...\Temp> dir
...
2015-02-21  02:08 AM                 0 test-file.txt</pre>

**OUCH!**

Also,

<pre>C:\...Temp> perl -E "say scalar gmtime( (stat 'test-file.txt')[9] )"
Sat Feb 21 06:08:00 2015</pre>

<pre>C:\...\Temp> perl -E "open my $fh, 'test-file.txt'; say scalar gmtime( (stat $fh)[9])"
Sat Feb 21 07:08:00 2015</pre>

Double **OUCH!**

This does not happen if the file is created with a date after the time zone offset switchover.

Thank you.
