### ISSUE TITLE
Why Mojo::IOLoop::Delay uses IOC?

### ISSUE THREAD

**Issue by alexbyk** [kraih/mojo#762]
hello. I asked in GG but got no answer, sorry for repeating myself, but i'm very-very curious.

Why Mojo::IOLoop::Delay uses  Hash::Util::FieldHash ? And how it does fulfil this: "stored outside the object to protect from circular references".

**Comment by amenonsen** [comment]
Sorry, this is not an appropriate forum for such questions.

**Comment by alexbyk** [comment]
But it looks like this is a mistake that confuses others

**Comment by alexbyk** [comment]
ok, here is an example of the leak, that shows that storing steps outside an instance with registered hash does nothing at all about circ. refs.
```perl
use Mojo::Base -strict;
use Mojo::IOLoop::Delay;

sub leak {
  my $d = Mojo::IOLoop::Delay->new;
  $d->steps(sub { say "$d" })->catch(sub { say "catched" });

  Mojo::IOLoop->reset;
  Mojo::IOLoop->one_tick;
}

leak();
```

**Comment by olegwtf** [comment]
You should get delay as callback argument to prevent leak: `$d->steps(sub { my $d = shift; say "$d" })`

**Comment by alexbyk** [comment]
@olegwtf I know that, you missed my point. I tried to explain that dancing with ioc only slows down the perf. and does nothing at all, and the explanation only confuses users: https://github.com/kraih/mojo/commit/0caa9135ae85f6a413fe0483e526e69e7e808ba3#commitcomment-10180006

**Comment by alexbyk** [comment]
so you can rewrite that 7 lines with this one:
```perl
has remaining => sub {[]};
```
It will have the same effect but it will work a little bit faster.

**Comment by jhthorsen** [comment]
@alexbyk: Please point out the leak with a unit test.

**Comment by olegwtf** [comment]
I can confirm that @alexbyk's example leaks with `for (1..1_000_000) { leak() }`. But don't know is it valid usage of delay.

**Comment by alexbyk** [comment]
Hi, @jhthorsen this is not about the leak. This is about using fieldhash a wrong way and wrong documentation.

So let's start again from the question: can someone explain why instead of ```has remaining => sub {[]};``` %FIELDHASH with autoregistry is used. If you try to answer this question, you get my point

**Comment by alexbyk** [comment]
Ok, more clearly: "I think that this part of code is wrong, and the author made a mistake". I should have said that in a first place, but I thought this would sound not so nicely and decided to point more softely: asking a question.

You can safely rewrite it with my onliner above. It has absolutely the same effect but works faster. IOC doesn't protect you from circ. refs and does nothing at all. And the tail of this mistake grows from the times when delay was used only to synchronize events.

An looks many people think that dancing with hashutils makes some magic about GC (and the author of the method's documentation too), but it doesn't

**Comment by alexbyk** [comment]
It killed Kenny!

**Comment by jhthorsen** [comment]
@alexbyk: Your example code from https://github.com/kraih/mojo/issues/762#issuecomment-78837502 is not valid usage. We can't provide you from doing anything stupid, but at least using fieldhash makes it a bit harder. The reason for using fieldhash is so you *normally* don't have to use ```Scalar::Util::weaken()``` all over the place.

```perl
package Obj;
use strict;
use Hash::Util::FieldHash 'fieldhash';

fieldhash my %REMAINING;

sub remaining {
  my $self = shift;
  return $REMAINING{$self} //= [] unless @_;
  $REMAINING{$self} = shift;
  return $self;
}

package main;
use strict;
use Devel::Cycle;

{
  my $o = bless {}, 'Obj';
  my $x = bless {}, 'Obj';
  $x->{o} = $o;
  $o->remaining([sub {$x}]);
  warn "Does it leak with fieldhash?\n";
  find_cycle($o); # output nothing
}

{
  my $o = bless {}, 'Obj';
  my $x = bless {}, 'Obj';
  $x->{o} = $o;
  $o->{remaining} = sub { $x };
  warn "Does it leak without fieldhash?\n";
  find_cycle($o); # gives you output
}
```

**Comment by alexbyk** [comment]
@jhthorsen I know exactly that my example causes a leak and isn't a valid usage, and i should use the first argument as a delay ref. I showed it for that purpose. I also know what does fieldhash (it calls `register` method with the ref of \%REMAINING and convert object to `id` while using it as a key). You still miss my point.

You don't have to store steps in the outer hash and don't need use weaken at all. You can just rewrite the module with `has remaining => sub {[]}` and it will have the same effect. My example causes a leak for both variants

**Comment by alexbyk** [comment]
And about a Devel::Cycle - you should use it to test leaks it this case. I'll write you an example how to check it

**Comment by jhthorsen** [comment]
So... You're saying:

* "sorry for repeating myself"
This is my last answer to this thread. As @amenonsen said, this is not the place

* "looks like this is a mistake"
You're not giving any suggestion on how to improve what looks like something. Also, "looks" is not exactly the work I would use when I have "hard proof".

* "example of the leak"
Sure. You can always write code that leaks. But Mojo::IOLoop::Delay makes it harder.

* "missed my point"
I have no idea what your point is. You're just saying "looks" and "thinks", without any constructive feedback on what should be changed, except.... (see next bullet point)

* "so you can rewrite that 7 lines with this one"
That is incorrect, and my example code above is proof of that.

* "fieldhash a wrong way and wrong documentation."
You fail to give any example code on what is right. See bullet point above.

* "If you try to answer this question"
I did. See https://github.com/kraih/mojo/issues/762#issuecomment-78857195

* "You don't have to store steps in the outer hash and don't need use weaken at all"
You're wrong.

**Comment by alexbyk** [comment]
@jhthorsen 
1) You should use Devel::Cycle to test your code about leaks. You can use it only to find a leak.
2) The simplest way to check leaks: try to execute my example 1000_000 times and see a res. mem.
For example in another console
`watch -n 0.1 "ps -aux | grep perl | grep -v grep"`

For testing leaks you can do smthng like that: that because perl has a simple GC

```perl
package Obj;
use strict;
use Hash::Util::FieldHash 'fieldhash';

fieldhash my %REMAINING;

sub remaining {
  my $self = shift;
  return $REMAINING{$self} //= [] unless @_;
  $REMAINING{$self} = shift;
  return $self;
}

sub DESTROY {
  print "destroying: ", shift, "\n";
}

package main;
use strict;

SCOPE: {
  my $o = bless {}, 'Obj';
  my $x = bless {}, 'Obj';
  $x->{o} = $o;
  $o->remaining([sub {$x}]);
}

print "ALL below are leaks----------\n";

```

**Comment by alexbyk** [comment]
@jhthorsen  I try to help and improve Mojo, don't take offence - i can barely explain myself i have problems with english. I'm a nice person)

**Comment by olegwtf** [comment]
Can confirm that @jhthorsen's example with fieldhash leaks.

**Comment by alexbyk** [comment]
@amenonsen wasn't friendly at all and closed this ticket without explanations)
Ok. Let's take a break.) Candies for everyone)

**Comment by jhthorsen** [comment]
@alexbyk: I don't follow. Are you saying that making a million objects is the same as leaking, because your application use more memory...?

**Comment by alexbyk** [comment]
@jhthorsen
```perl
package Obj;
use strict;
use Hash::Util::FieldHash 'fieldhash';

fieldhash my %REMAINING;

sub remaining {
  my $self = shift;
  return $REMAINING{$self} //= [] unless @_;
  $REMAINING{$self} = shift;
  return $self;
}

package main;
use strict;

do {
  my $o = bless {}, 'Obj';
  my $x = bless {}, 'Obj';
  $x->{o} = $o;
  $o->remaining([sub {$x}]);
  }
  for 1 .. 100_000_000;

```

But save all you important work before and be ready to press CTRL-C.

**Comment by olegwtf** [comment]
@jhthorsen in your example objects will be destroyed during global destruction, while should be (I believe) destroyed when will go out of the scope.

**Comment by alexbyk** [comment]
@jhthorsen if you app uses a memory while creating million of objects and destroying it one by one - this is exactlly what called leaks. I was sure that it's obvious, sorry that I didn't explaine it. And don't take offence, I'm trying to help the project

**Comment by jhthorsen** [comment]
@alexbyk: Yeah, I'm just replying to why "stored outside the object to protect from circular references" is correct.

@alexbyk: I really want my application to keep around all the objects I create... Are you looking for the line in Mojo::IOLoop::Delay that clear the %REMAINING has?

**Comment by jhthorsen** [comment]
@alexbyk: Another thing is that perl never release memory. That's why things like slurp($really_big_file) is a bad idea. So if you make a million objects and then garbage collect them, perl will still use the whatever memory it used at the "peak".

http://learn.perl.org/faq/perlfaq3.html#How-can-I-free-an-array-or-hash-so-my-program-shrinks

**Comment by alexbyk** [comment]
@jhthorsen 
This is about GC: http://perldoc.perl.org/5.8.9/perlobj.html#Two-Phased-Garbage-Collection . And Also Hash::Util::FieldHash contains detailed examples why and when use it  - It doesn't suit our case, Also it contains a detailed explanation how it works - you will find why Devel::Cycle can't detect leaks.

Object that are created and destroyed one by one doesn't use a memory, you can create a billion of object and without leaks you app will be working like expected: try to do it yourself, fix a leak and see a memory

I'm going to fry a chicken because I'm hungry. So let's take a break and I recommend to open this issue: I'm not good at debates but I'm right 100%. Maybe some of the exper.devs. will take a look at this conversation and confirm this

**Comment by olegwtf** [comment]
@jhthorsen Do you want to say that after
```
{
  my $o = bless {}, 'Obj';
  my $x = bless {}, 'Obj';
  $x->{o} = $o;
  $o->remaining([sub {$x}]);
  warn "Does it leak with fieldhash?\n";
  find_cycle($o); # output nothing
}
```
when you lost references to $o and $x you still want they will exists in the memory inside %REMAINING? This is not expected behavior for me. I want they to be garbage collected.

BTW, fieldhash should remove items from %REMAINING automatically when last reference to object  used as key will be deleted.

**Comment by alexbyk** [comment]
I also think that mojolicious maintainers should be more friendly. amenonsen, smarty pants, closed this ticket without hesitations, while I spent an hour trying to explain obvious thing.

Let's summary, the code now doesn't contains a bug, it just do thing the wrong way and looks funny at least. If it will remain as is it's not a big problem, just a mistake

**Comment by olegwtf** [comment]
@alexbyk, the only person who can make decision about this issue is @kraih and you need to wait about 6 hours when he will be online. Then you can also discuss this on irc.perl.org#mojo

**Comment by jhthorsen** [comment]
@olegwtf: It's not the fieldhash %REMAINING that keeps the objects around, it's the ioloop.

https://github.com/kraih/mojo/blob/master/lib/Mojo/IOLoop/Delay.pm#L32

```perl
use Mojo::Base -strict;
use Mojo::IOLoop::Delay;

my $i = 0;
sub foo {
  my $d = Mojo::IOLoop::Delay->new;
  $i++;
  $d->steps(sub { my $d = shift; warn "#$i\n"; $i--; });
}

foo() for 0...1000;

Mojo::IOLoop->timer(2 => sub { Mojo::IOLoop->stop; });
Mojo::IOLoop->start;
```

**Comment by olegwtf** [comment]
@jhthorsen, i wrote about your example with fieldhash. There was no Mojo::IOLoop :)

**Comment by alexbyk** [comment]
@olegwtf I hope I will be having a good time by that time, also I decided to let it go)

**Comment by jhthorsen** [comment]
@olegwtf: Are you saying the object is not automatically garbage collected by Hash::Util::FieldHash? If so, can you show me the complete code?

https://metacpan.org/pod/Hash::Util::FieldHash#How-field-hashes-work

**Comment by alexbyk** [comment]
@olegwtf for example JS collects object when no roots refers to them, perl has a simple counter and destroys object right after no other objects refer to them. FHU does nothing with objects, it can't make a magic. It destroys only keys when object are destroyed.

I made an example for you so you can step by step see what's happening. Try to play with it. This is how HUF::fieldhash works under the hood. In the second case %HASH isn't empty because object isn't destroyed, and FHU doesn't worry about that

```perl
use Mojo::Base -base;
use Hash::Util::FieldHash ':all';
use Data::Dumper;

my %HASH;
my $object = Mojo::Base->new;

# register an object with hash, when
# it will be destroyed, the value $HASH{NUM_ID} will be destroyed to
register $object, \%HASH;

# get and id
my $id = id($object);
say $id;

$HASH{$id} = "Foo";
say Dumper \%HASH;

# destroy object, the corresp key will be cleared
undef $object;
say Dumper \%HASH;

say "--- circular";

# and let's create a circular ref
$object = Mojo::Base->new;
register $object, \%HASH;
$id = id($object);
say $id;
$HASH{$id} = $object;
undef $object;

# nothing is destroyed
say Dumper \%HASH;

```

**Comment by olegwtf** [comment]
In your example %REMAINING has one more reference to $o inside $x->{o}, so after $o will go out of the scope reference count to $o will decrease to 1. But fieldhash need it to be 0, so it will be able to automatically delete it from %REMAINING. This is why your example leaks.

**Comment by jhthorsen** [comment]
@alexbyk: You're provoking a circular reference, just like in your example https://github.com/kraih/mojo/issues/762#issuecomment-78837502. I totally agree that will make a circular reference. At this point it sounds like you're arguing for the argument's sake. Sorry, but if that's not true, then I simply don't understand what your point is.

**Comment by jhthorsen** [comment]
@olegwtf, @alexbyk: At this point I need actual code that output your point. I mean, running code that print something useful to screen, that I can run on my computer.

**Comment by alexbyk** [comment]
@jhthorsen i thought we have this conversation because you don't know what exactly does FHU. I gave you a links but ur stil arguing with olegwtf instead of learning it. I decided to show you step by step but insted of spen a little time and learn something new UR trying to argue with me.

**Comment by jhthorsen** [comment]
@alexbyk: I'm having this conversation because you submitted an issue asking "Why Mojo::IOLoop::Delay uses Hash::Util::FieldHash?", not because I want to learn anything. I tried to answer that question with words, with references and actual running code.

I'm out.

**Comment by alexbyk** [comment]
@jhthorsen  I have no idea why can't you just take a little break as I suggested above, spend a little time for learning the stuff. After that you can say "sorry guys, I was wrong, take a beer".

**Comment by alexbyk** [comment]
I took my meal and I'm nice person again. I decided to clean up my posts: https://github.com/kraih/mojo/commit/b8e21f3b97e9855d84947acf22aae94a1ff0a03b#commitcomment-10182839 this link should be enough to explain this ticket . @jhthorsen sorry If I said smthng offensive - I didn't mean that. You are a good guy!

**Comment by jberger** [comment]
@alexbyk, I understand that you are saying that the fieldhash didn't prevent all leaks. True, but the leaks it was intended to prevent were when users used the same object in multiple step (or other similar code). I wrote a blog post here with an example and a means of demonstrating it via carton. You can see that here http://blogs.perl.org/users/joel_berger/2014/07/non-blocking-mojolicious-apps-are-even-easier-now.html

In practice I have found that this leak protection is incredibly effective and even if not perfect (nothing can be perfect with reference counting after all) it is useful. 

In @amenonsen's defense it is mojolicious policy to only use github issues for bug tracking and pull requests and not discussion or feature requests. http://mojolicio.us/perldoc/Mojolicious/Guides/Contributing

Since I can demonstrate that the code in question works without bug then it seems that this story is a request to remove this feature, and since feature requests are not tracked via issues he was right to close it.  You may open a pull request with your changes if you wish, but I really like this feature so I can say now that I will be :-1: on its inclusion. Sorry about that. 

This discussion is interesting, but if it continues it should be in the appropriate channels, that is the mailing list or irc.

**Comment by alexbyk** [comment]
1) The are no protection from the leaks in H::U::F, in theory, in practice - at all. So your post at blogs.perl is wrong (sorry), and missinform others

2) It make even worse, you and  jhthorsen believe to Devel::Cycle output, but look at https://github.com/kraih/mojo/issues/762#issuecomment-78857195 - both of that examples have the same leak, but D::C can't detect it in the first place so you and  jhthorsen have wrong confident about it (which is worse than knowing the true).

So here is advice - don't use D::C to test for the leaks! It gives you a fake confidence.

3) I got it. You really believe that H::U::F does something with circular refs, - it does 100% nothing.

4) https://github.com/kraih/mojo/issues/762#issuecomment-78857195 -  is a good example of wrong confident, please tell me should I proof that it contains the same leaks? Or give me a sample of code where you think H::U::F protects your somehow, I'll demonstrate that it does nothing.

5) Summary is the same: https://github.com/kraih/mojo/commit/b8e21f3b97e9855d84947acf22aae94a1ff0a03b#commitcomment-10182839

**Comment by alexbyk** [comment]
Stop. I started explanation again.

Could you just give me a code where you think H::U:::F protects you like  jhthorsen  did I'll explain you by the you own example.

**Comment by jberger** [comment]
@alexbyk what is your citation of your (2) above? In my blog post, there is code. Did you look at it before refuting it?

**Comment by alexbyk** [comment]
jberger yes I read it in 2014 and I did it now. Citation 2 -  jhthorsen thought that the first example "# output nothing " is protected from the leaks because of H::U::F, while second example has leaks. So could you please pick me to the simmilar example where you think H::U::F does something  and put it here?

**Comment by jberger** [comment]
I feel no obligation to do so. I have provided an example that does prevent leaks as presented with evidence.

**Comment by alexbyk** [comment]
You only gave me a link from 2014 where you use  old M::I::D, how I suppose to prof something with that?

Your are right, you have no obligations to waist you time with me.

But think other way. I said above that all this time you were wrong (sorry again) and had the false confident. and "In practice I have found that this leak protection is " - is wrong too. And D::C lied to you all this time

And I can proof it - just paste here a code where you think H::U::F protects you like jhthorsen did.

You can do it, or you can just ignore me and feel yourself protected by "incredibly effective and even if not perfect". If you choose not wasting you time I get it. And I even can apologize for wasting you time, and we'll never know the truth.

**Comment by alexbyk** [comment]
Guys, I have an excellent idea. Maybe someone knows the author of that module and can ask him "Does H::U::F protects me from circ. refs". "No" from him may be more trusting for you than my typing here.

**Comment by jberger** [comment]
@alexbyk the burden of proof is on you. 

I feel I must quote Woody Allen at this point:
> The fact that you tell me I have no rooks means little in actuality, as I need only glance downward at the board to see them darting about with cunning and vigor. -- Vardebedian

**Comment by alexbyk** [comment]
jberger It's impossible to proof an absence of something. So i't impossible to proof that using H::U::F has no reason. The very first comment contains a proof, but you said that there are other cases and that isn't enough for you.

Look at this line: `has remainings => {[]};` 
I can proof that this line is faster, simpler and shorter than the current implementation.

Could you proof that current implementation differs from this line?

**Comment by Grinnz** [comment]
Please join IRC or the mailing list if you wish to discuss this in an
appropriate venue. The issue was closed at the beginning for a reason.

**Comment by jberger** [comment]
I feel that I have convincingly shown this is not a bug. @alexbyk I see that you are not going to let it drop, but I will reiterate, this is the wrong place for this discussion. I rarely do this, but I feel it is time to lock the issue.

**Comment by jberger** [comment]
See also: http://rec.data-flow.ru/articles/2015/3/circular-references-memory-leaks-and-mojo.html
