### ISSUE TITLE
again Mojo::Reactor::EV

### ISSUE THREAD

**Issue by bakanov** [kraih/mojo#767]
When I try perform 'again' with Mojo::Reactor::EV backend and timer that not exist it cause server error:
[Fri Mar 20 10:35:06 2015] [error] Can't call method "again" on an undefined value at /usr/local/share/perl/5.14.2/Mojo/Reactor/EV.pm line 12.
If I do the same with Poll backend it causes only warning. 
I think usage of wrong timer value shouldn't cause server error. Or there should be method to check if timer exists

**Comment by kraih** [comment]
I think this feature request needs an actual use case, so far it sounds to me like it would only hide timing bugs.

**Comment by kraih** [comment]
Something like [this](https://gist.github.com/anonymous/9c214442dc86e3e6333f) would seem reasonable, since it could be used for testing as well, but we still need a good use case.

**Comment by kraih** [comment]
Since no use case has been presented, i've decided to go the opposite direction and make both reactors fail consistently. Hopefully this can prevent a few bugs in the future.

**Comment by bakanov** [comment]
OK, it's reasonable, thanks. 

P.S. Sorry for late answer. Actually, this issue was connected to this thread: https://groups.google.com/forum/#!topic/mojolicious/tWZmcc-mfoM
