### ISSUE TITLE
cookbook: eventsource example

### ISSUE THREAD

**Issue by powerman** [kraih/mojo#768]
Current example result in HTTP timeout on client if there will be no events sent until inactivity_timeout (or 504 Gateway Timeout when nginx is used before hypnotoad). I think, according to spec http://www.w3.org/TR/eventsource/#processing-model server should immediately return 200 OK, not with first event (which may be sent much later, if ever).

Maybe I miss something, but looks like only way to do this is to add `$c->write;` to that example, which isn't really documented - `$c->write;` is mentioned in Mojolicious::Controller doc but it's effect and use isn't described, and this way to call Mojo::Content->write isn't documented at all. (BTW, `$c->write('');` isn't documented to be handled as EOF and close connection).

1. Is there better (documented) way to output status and headers without any content and without closing connection?
2. Cookbook example should probably be updated.

**Comment by kraih** [comment]
Thanks, fixed.
