### ISSUE TITLE
typo in Changes

### ISSUE THREAD

**Issue by powerman** [kraih/mojo#769]
https://github.com/kraih/mojo/blob/master/Changes#L57 should mention Mojolicious::Routes::Pattern instead of Mojolicious::Routes::Route

**Comment by powerman** [comment]
Also https://github.com/kraih/mojo/blob/master/Changes#L62 probably should mention Mojo::DOM.

**Comment by powerman** [comment]
And looks like Mojo::DOM->match used to return dom object while Mojo::DOM->matches now return boolean.

**Comment by kraih** [comment]
Thanks, fixed.
