### ISSUE TITLE
Warnings when using Mojo::Util standalone

### ISSUE THREAD

**Issue by e477** [kraih/mojo#770]
I like using Mojo::Util as a convenient set of tools outside of Mojolicious projects, too. Since commit 413320b98d7e6c842a4c0c2fdc9656f87a535d7c released with 6.04 I get the following warnings when trying to do so:

    Useless use of a constant ("has") in void context at /usr/share/perl5/vendor_perl/Mojo/Base.pm line 39.
    Useless use of reference constructor in void context at /usr/share/perl5/vendor_perl/Mojo/Base.pm line 39.
    Useless use of private variable in void context at /usr/share/perl5/vendor_perl/Mojo/Base.pm line 65.
    Useless use of reference constructor in void context at /usr/share/perl5/vendor_perl/Mojo/Base.pm line 65.
    Useless use of private variable in void context at /usr/share/perl5/vendor_perl/Mojo/Base.pm line 73.
    Useless use of reference constructor in void context at /usr/share/perl5/vendor_perl/Mojo/Base.pm line 73.
    Useless use of private variable in void context at /usr/share/perl5/vendor_perl/Mojo/Base.pm line 77.
    Useless use of reference constructor in void context at /usr/share/perl5/vendor_perl/Mojo/Base.pm line 77.

**Comment by kraih** [comment]
Thanks, fixed. I'm not happy with the solution though, and might just revert the original optimization instead. https://github.com/kraih/mojo/commit/5adf5589710f80a4fab37926ac710f0fc6aecb84

**Comment by shadowcat-mst** [comment]
02:16 <@mst> sri: isn't that just a circular require problem?
02:16 <@mst> yep
02:16 <@sri> possibly, the warnings are very useless though
02:21 <@sri> curious how "Mojo::Util::monkey_patch $caller, 'has', sub { 
             attr($caller, @_) };" causes "Useless use of a constant ("has") in 
             void context at lib/Mojo/Base.pm line 39."
02:21 <@sri> i guess Mojo::Util::monkey_patch is not yet defined
02:21 <@sri> triggering that oddity
02:21 <@mst> and so you parse it as indirect object notation
02:21 <@mst> $caller->Mojo::Util::monkey_patch(), 'has', ...
02:21 <@sri> oh shit... of course... indirect object notation
02:22 <@sri> *facepalm*
02:22 <@mst> which is what ciruclar requires cause, which can easily break 
             things later, which is why I went "ew" at this
02:22 <@mst> Moose::Util::TypeConstraints predeclares its subs for exactly this 
             reason
02:22 <@sri> i guess i can predeclare monkey_patch
02:23 <@mst> right
02:23 <@mst> sub monkey_patch;
02:23 <@mst> sorts it out

**Comment by Tekki** [comment]
Will this solve the following problem too?

    use Mojo::Util;
    use Mojo::UserAgent;

results in "syntax error at [...]/Mojo/IOLoop/Client.pm line 30, near "has reactor".

**Comment by kraih** [comment]
@Tekki Yes.
