### ISSUE TITLE
Method and attributes renaming

### ISSUE THREAD

**Issue by parserpro** [kraih/mojo#772]
Hi!
Could it be possible to rename methods and attributes only in major release, please. 
Потомучто уже зае...

**Comment by olegwtf** [comment]
https://metacpan.org/pod/distribution/Mojolicious/lib/Mojolicious/Guides/FAQ.pod#What-about-backwards-compatibility

**Comment by parserpro** [comment]
А еще можно чесать руки об деревья.

**Comment by kraih** [comment]
The official project language is english, please respect that.
