### ISSUE TITLE
Optional modules and $SIG{__DIE__}

### ISSUE THREAD

**Issue by powerman** [kraih/mojo#774]
When user set `$SIG{__DIE__}` before loading Mojo (for ex. to send all errors to log file, including compile-time errors - this makes sense for services/daemons) then it will be called when Mojo try to load optional modules:
```
$ perl -e 'BEGIN{ $SIG{__DIE__} = sub { warn @_ } } use Mojo::IOLoop'
Can't locate Net/DNS/Native.pm in @INC …
Can't locate Net/DNS/Native.pm in @INC …
BEGIN failed--compilation aborted at (eval 12) line 1.
Can't locate IO/Socket/Socks.pm in @INC …
Can't locate IO/Socket/Socks.pm in @INC …
BEGIN failed--compilation aborted at (eval 29) line 1.
$
```
This can be fixed in this way:
```perl
# replace this:
eval 'use Net::DNS::Native 0.15 (); 1';
# with this:
eval 'local $SIG{__DIE__}; require Net::DNS::Native; Net::DNS::Native->VERSION(0.15); 1';
```
If you agree to add this fix then I can prepare pull request.

**Comment by Grinnz** [comment]
Could be helpful, but $SIG{__DIE__} handlers should always account for eval dies themselves, as described at the end of http://perldoc.perl.org/functions/die.html .

**Comment by olegwtf** [comment]
@Grinnz, don't know why but `$^S` check doesn't help in this case

**Comment by powerman** [comment]
If die happens inside eval this doesn't automatically mean this die message shouldn't be logged, so __DIE__ handler can't make this decision at all. But when your code try to load optional module - your code know error while loading isn't important and must not be shown to user, so this is the right place to quiet error message.

**Comment by Grinnz** [comment]
The code does not know that you're going to use $SIG{__DIE__} to log error messages, how can it make that decision?

**Comment by Grinnz** [comment]
@olegwtf it does not suppress the compilation errors, perhaps changing "use" to "require" alone could fix that.

**Comment by olegwtf** [comment]
@Grinnz, yes can confirm that `require` fixes this. So, I would replace `use` with `require` and suggest to @powerman to check `$^S` inside `$SIG{DIE}` handler.

**Comment by powerman** [comment]
> The code does not know that you're going to use $SIG{__DIE__} to log error messages, how can it make that decision?

It shouldn't know this. `$SIG{__DIE__}` handler may exists or not, and do any thing, but this isn't important. Important thing is what this code generate error, which is completely optional, local to this code, and not interested to end-user in any case. So, no matter what user does in handler, handler shouldn't be called in this case.

**Comment by olegwtf** [comment]
Also a way to omit warnings without any changes of Mojolicious:
`perl -e 'BEGIN{ $SIG{__DIE__} = sub { warn @_ if defined($^S) && !$^S } } use Mojo::IOLoop;'`

**Comment by powerman** [comment]
Quoting perldoc:
```
Due to an implementation glitch, the $SIG{__DIE__} hook is
called even inside an "eval()". Do not use this to rewrite a
pending exception in $@, or as a bizarre substitute for
overriding "CORE::GLOBAL::die()". This strange action at a
distance may be fixed in a future release so that $SIG{__DIE__}
is only called if your program is about to exit, as was the
original intent. Any other use is deprecated.

$^S         State
---------   -------------------------------------
undef       Parsing module, eval, or main program
true (1)    Executing an eval
false (0)   Otherwise
```
Well, I'm not trying to catch errors inside `eval{}` with `__DIE__`, this doesn't makes sense (`eval` is usually there because these errors are already handled in some way so there is no need to specially log them using global `__DIE__` handler). I'm trying to catch unhandled errors and log them before my daemon will exit.

But problem is this issue happens not just inside eval, but inside eval **while parsing**. Errors while parsing usually result in crash and thus should be logged. And `$^S` doesn't allow us to distinguish between **while parsing** and **inside eval while parsing**, so I either won't be able to log errors like "use No::Such::Module;" or I will log Mojo failed attempt to load optional modules or I'll have to add special Mojo-specific filter which will break each time Mojo will add new optional module or one of optional module became non-optional.

Also such errors can't be handled using `CORE::GLOBAL::die` or `END{}`, so only way to log them is use `$SIG{__DIE__}`.

For now only working solution which doesn't require modification in Mojo is:
```perl
$SIG{__DIE__} = sub {
    return if grep {defined && $_ eq '(eval)'} (caller 1)[3], (caller 2)[3];
    warn @_;
};
```
but I'm not sure how reliable is this logic:
- why exactly perl call it twice per each error with `(eval)` in different position in stack?
- is there any other possible case when I may get `(eval)` at these positions in stack (false positives which must be logged, not ignored)?

**Comment by kraih** [comment]
I'm afraid the proposed change did not get the required votes. :-1:
