### ISSUE TITLE
Spurious test failure in t\mojo\daemon.t

### ISSUE THREAD

**Issue by nanis** [kraih/mojo#779]
<pre>t\mojo\daemon.t ............................ 1/?
#   Failed test 'right script name'
#   at t\mojo\daemon.t line 83.
#          got: 'C:\Users\...\.cpanm\work\1428402499.3108\Mojolicious-6.06\t\mojo\lib\myapp.pl'
#     expected: 'C:/Users/.../.cpanm/work/1428402499.3108/Mojolicious-6.06/t/mojo/lib/../lib/myapp.pl'
# Looks like you failed 1 test of 81.</pre>

These paths clearly refer to the same file. But, the strings are different.

    # Script name
    my $path = "$FindBin::Bin/lib/../lib/myapp.pl";
    is(Mojo::Server::Daemon->new->load_app($path)->config('script'),
        $path, 'right script name');

In [load_app](https://github.com/kraih/mojo/blob/master/lib/Mojo/Server.pm#L42) (which, coincidentally, start on line 42), you have `local $0 = $path = rel2abs $path;` which calls `canonpath`.

The `File::Spec` docs do say "Note that [`canonpath`] does *not* collapse `x/../y` sections into `y`."

I haven't examined this, but it looks like, on Windows, it actually does collapse `lib/../lib` into `lib` seemingly based on the wrong assumption that there are no symlinks on Windows, but that does not help this issue.

In the mean time, changing the definition of `$path` to

    my $path = File::Spec->canonpath( "$FindBin::Bin/lib/../lib/myapp.pl" );

fixes the test and should not affect anything anywhere else. Ideally, all test paths would be constructed using <del>`catfile`</del> <ins>`catpath`</ins> and `canonpath`, but I understand what you have works most of the time.

**Comment by kraih** [comment]
This was the commit that broke it. https://github.com/kraih/mojo/commit/7efcb3e184973040b1acabf8d975092dd92639a2

**Comment by kraih** [comment]
I tend towards reverting the switch from `abs_path` to `rel2abs`, instead of trying more test workarounds.

**Comment by kraih** [comment]
This may fix the issue too. https://github.com/kraih/mojo/commit/8d64f62bd9721090d6335b41a48d7ed71b0dc41a

**Comment by nanis** [comment]
I am not familiar with the internals and why the change from `abs_path` to `rel2abs` was made, so I thought of applying the least intrusive fix ... Since `rel2abs` does apply `canonpath` to arguments, it seemed logically parsimonious to me that the `$path` also should have `canonpath` applied to it.

From a casual observer's point of view, reverting to `abs_path` makes sense to me. After all, these paths should and ought to resolve.

**Comment by nanis** [comment]
> This may fix the issue too. [8d64f62](https://github.com/kraih/mojo/commit/8d64f62bd9721090d6335b41a48d7ed71b0dc41a)

Yes, it should ... Safer, just in case `$FindBin::Bin` is not an absolute path.

**Comment by kraih** [comment]
We have reverted the original change. https://github.com/kraih/mojo/commit/693a3cf2ba8288cca89a45781dc9b33406251bde
