### ISSUE TITLE
Websocket close socket error

### ISSUE THREAD

**Issue by Logioniz** [kraih/mojo#780]
I have such code with websocket connect and close connection immediately after open it,
but close event triggered only after 15 sec in browser and i have such error:
```
WebSocket connection to 'ws://127.0.0.1:3000/ws' failed: Connection closed before receiving a handshake response
```
Code
```perl
#!/usr/bin/perl

use strict;
use warnings;

use v5.10;

use Mojolicious::Lite;

websocket '/ws' => sub { shift->finish } => 'ws';
get '/' => sub { shift->render } => 'index';
app->start;

__DATA__

@@ index.html.ep

<div id="msg"></div>
<script>
  ws = new WebSocket('<%= url_for('ws')->to_abs %>');
  ws.onclose = function(event) {
    document.getElementById('msg').innerHTML += 'close' + '<br>';
  };
</script>
```
If connection not establish and handshake continue when action call then may be need to add event `open` which triggered when connection establish to use it something like this:
```perl
$c->on(open => sub { shift->finish });
```
?

**Comment by kraih** [comment]
I'm afraid everything you describe here is expected behavior.

**Comment by kraih** [comment]
This issue might have been meant as a feature request, but the description was very unclear and hard to understand for me. Anyway, i posted a patch for an open event on IRC earlier, and the reactions from the community were not very encouraging. http://irclog.perlgeek.de/mojo/2015-04-08#i_10409552

**Comment by kraih** [comment]
This commit makes your original code work i believe. https://github.com/kraih/mojo/commit/04f92e74186388a66c6ba9f1b76694f30ff2934b
We have not decided yet if it stays though.

**Comment by Logioniz** [comment]
What result do you expect from this code

```perl
#!/usr/bin/perl

use strict;
use warnings;

use v5.10;

use Mojolicious::Lite;

websocket '/ws' => sub { shift->send('qwe' => sub { shift->finish }) } => 'ws';
get '/' => sub { shift->render } => 'index';

app->start;

__DATA__

@@ index.html.ep

<div id="msg"></div>
<script>
  ws = new WebSocket('<%= url_for('ws')->to_abs %>');
  ws.onmessage = function(event) {
    document.getElementById('msg').innerHTML += event.data + '<br>';
  };
  ws.onclose = function(event) {
    document.getElementById('msg').innerHTML += 'close' + '<br>';
  };
</script>
```
?
I expect that page will have two words:
```
qwe
close
```
But i have only `close` after 15 sec.

I don't understand what difference between http context and websocket context, 
but that i can't understand when websocket connection open is very terrible.

I must to write such code to understand that connection open:

```perl
#!/usr/bin/perl

use strict;
use warnings;

use v5.10;

use Mojolicious::Lite;

websocket '/ws' => sub {
  shift->on(message => sub {
    my ($c, $msg) = @_;
    if ($msg =~ m/open/) {
      $c->send('qwe' => sub { shift->finish });
    }
  });
} => 'ws';

get '/' => sub { shift->render } => 'index';

app->start;

__DATA__

@@ index.html.ep

<div id="msg"></div>
<script>
  ws = new WebSocket('<%= url_for('ws')->to_abs %>');
  ws.onmessage = function(event) {
    document.getElementById('msg').innerHTML += event.data + '<br>';
  };
  ws.onclose = function(event) {
    document.getElementById('msg').innerHTML += 'close' + '<br>';
  };
  ws.onopen = function(event) {
    ws.send('Client said that connection open');
  }
</script>

```
This is wrong solution because the client may not send on open this message.
I think that this is very awfully...
Easy things must do easy.

I hope that I have helped anything

**Comment by Logioniz** [comment]
Oh, i forgot that i have solution.
See https://groups.google.com/forum/#!topic/mojolicious/1SsRmG0SOoU on /ws3.
But i can't understand why it works).

**Comment by kraih** [comment]
You've convinced me to revert the earlier commit and add a few more examples instead. :smile: https://github.com/kraih/mojo/commit/2b6dabd6b530a2d4c65052f1a1fa018967a2f457

**Comment by kraih** [comment]
Perhaps this is a better solution. https://github.com/kraih/mojo/commit/941129830039b5989152d4ce0b99e2b29d855128

**Comment by Logioniz** [comment]
Thanks, now works good.
