### ISSUE TITLE
Template syntax issue when using "<% %>"

### ISSUE THREAD

**Issue by uynap** [kraih/mojo#782]
For the template lines below, I got syntax error at the debugging console.
<% if (1) { %>
<% } %>
<% else { %>
<% } %>
Is it supposed to be working?

Both of these blocks work:
<% if (1) { %>
<% } =%>
<% else { %>
<% } %>
or
<% if (1) { %>
<% }  else { %>
<% } %>

I went through the documents for Mojo::Template and didn't find clear explanation for "<% =%>". Can you please explain for the syntax of "<% =%>" ?

**Comment by uynap** [comment]
BTW, I'm using the latest Mojolicious version 6.08.

**Comment by kraih** [comment]
This is already explained in the documentation.

**Comment by uynap** [comment]
I can see the most related documentation is Mojo :: Template and the only related part is "whitespace trimming", which only has a few words for explanation. What I don't understand is why we need "whitespace trimming" and when we need it? Can you please explain it further?

**Comment by uynap** [comment]
i had a look at the code & understand it.
