### ISSUE TITLE
to_string() freezes the state in Mojo::Message::Response

### ISSUE THREAD

**Issue by polettix** [kraih/mojo#792]
Please consider documenting that "to_string()" freezes the object, and possibly include hints on how to get the string representation without being hit by the optimization.

This issue is a consequence of the discussion in #789.

**Comment by tempire** [comment]
This is unlikely to happen in the core.

You are, of course, welcome to create a serialization plugin that fits your needs. You could handle this in the after_render hook.

**Comment by polettix** [comment]
I'm only suggesting to document the current behavior, not to change it - this is why I closed PR #789 and opened this issue.

You can of course think that "to_string()" name and documentation are clear enough as to its semantics and effect on the object, and disregard this Issue. Just take into account that other people might to be biten in the future and you probably want to avoid bothering!

**Comment by tempire** [comment]
Ah, you're right. I missed that part.

This is reasonable, considering several people have been tripped up on this issue.

**Comment by kraih** [comment]
Closing this issue, since no actual proposals have been made yet for how this should be documented.

**Comment by polettix** [comment]
I would suggest reconsidering this decision and label is issue at least as "future". An "excellent documentation" shouldn't leave space to undocumented behaviour like this.

I can try again with a (new) PR, although this trading performance for behaviour might happen somewhere else or in a wider context than the one I tried to pinpoint. In case, it would be useful to know that as well and this probably calls for a core developer to chime in.

Before wasting anyone's time, though, it would be interesting to know if this is of any interest. If you don't bother, probably there's nothing to bother about.

**Comment by jberger** [comment]
I think that that is indeed what @kraih is asking for. Keep it brief, I
imagine it can be a sentence or less.

**Comment by kraih** [comment]
@polettix Considering that nobody else has commented in over a week (aside from a misunderstanding), it may very well be that there is no interest.

**Comment by kraih** [comment]
Perhaps i should mention that this is actually a lot more complicated than it may look, some `Mojo::Message::Request`/`Mojo::Message::Response` objects have dynamically generated content and can only be rendered once.

**Comment by polettix** [comment]
@jberger I didn't see requests by @kraih. @tempire asked for some wording, but given how this goes into the inner working of the objects my Mojolicious-fu is too weak.
@kraih some people seemed to acknowledge that docs should be fixed. It surprises me that an issue like this can be closed without any change (considering we're talking about docs), maybe I'm just easy at being surprised.

I'll try to switch to "interview mode" and then propose a PR based on the answers:
* should I target Mojo::Message, where to_string() is documented? Or is the performance enhancement peculiar to the two derived classes only, and should be placed there?
* Are there other methods that have the same behaviour that come to mind? I'd like to include them in the same sweep.
* Is there a way to copy/clone a Mojo::Message so that the freezing method can be safely called on the copy without spoiling the original object? I can try to propose a best practice to call them "multiple times".

**Comment by kraih** [comment]
@polettix Stale issues get closed, and reopened if there's new activity. I don't know how the documentation needs to be updated, otherwise i would have done so already. There is no best practice for cloning `Mojo::Message` objects, because cloning might not even be possible for very dynamic content.
