### ISSUE TITLE
ASCII art broken in pod

### ISSUE THREAD

**Issue by jberger** [kraih/mojo#795]
#781 removes leading whitespace in pod verbatim sections. This breaks the ASCII art in pages like the [Growing Guide](http://mojolicio.us/perldoc/Mojolicious/Guides/Growing#Model-View-Controller). Interestingly it doesn't seem to break all of them, like the end of this [one](http://mojolicio.us/perldoc/Mojolicious/Guides/Growing#Differences). 

Not sure if we should revert the patch or harden the ASCII art. My initial reaction is that for a general purpose pod renderer we should leave leading whitespace as-is for purposes such as these.

**Comment by jberger** [comment]
Oh I understand the difference now, the indent depth is assumed by checking the first line (see https://github.com/kraih/mojo/blob/551a6e11c60b5edaf48572b2eb2de96503f1ecd6/lib/Mojolicious/Plugin/PODRenderer.pm#L101). This is likely true for non-ascii art blocks, but as seen in Growing, clearly not always true.

**Comment by kraih** [comment]
:+1: for reverting the patch.

**Comment by kraih** [comment]
Fixed by https://github.com/kraih/mojo/commit/29ce807786c6ae16980395b29ec27f9a0762e42b.
