### ISSUE TITLE
Logging ECONNRESET

### ISSUE THREAD

**Issue by augensalat** [kraih/mojo#806]
This is a wishlist request.

A client that prematurely cuts the connection is not logged.

I found this statement
https://github.com/kraih/mojo/blob/master/lib/Mojo/IOLoop/Stream.pm#L104

I would appreciate something that makes connection resets visible, either logging or maybe an event.

**Comment by tempire** [comment]
This is reasonable. IIRC, I've run into this connection a couple of times in the past. I can't see any downside to it.

**Comment by kraih** [comment]
@tempire Why is it reasonable?

**Comment by tempire** [comment]
It sounds reasonable based on the idea that the occurrence is not logged. If that's not the case, then it doesn't matter.

**Comment by kraih** [comment]
@tempire Afraid i have to give this a :-1: then, because the explanation does not convince me that `ECONNRESET` is an error worth logging.

**Comment by kraih** [comment]
After talking about this a bit on IRC, i don't think there can actually be a vote without a use case and good technical argument. So i'm closing this issue for now.

**Comment by augensalat** [comment]
Here is my use-case:
Occasionally we get complaints about problems with large volume uploads.
Uploads are managed internally by Mojolicious until the last byte has been transmitted. If the connection is lost in this phase, there aren't any traces in our logs.
Afaict there is no easy way to debug this as long Mojo::IOLoop::Stream is discarding ECONNRESET.
Lbnl we can't do any statistics about how many upload connections may have failed.
It would be very helpful if there was at least an event for ECONNRESET.

**Comment by augensalat** [comment]
Just noticed Apache mod_log_config has %X for the connection status, which gets an "X" if connection is aborted:
https://httpd.apache.org/docs/2.2/mod/mod_log_config.html
