### ISSUE TITLE
Failure parsing a specific template with error "Global symbol ..." (temporary workaround: make morbo reload code)

### ISSUE THREAD

**Issue by flowdy** [kraih/mojo#808]
Hi,

it is quite weird: Usually, if you get an error like that, it is either simply a syntax/spelling error or it can be that Mojo could not found a key of the variable's name in the stash.

In my case, the template in question can be parsed okay as soon as morbo has got to reload the app. Prior to that, the same variable cannot be resolved.

    <dt>Server running since / recently restarted at</dt>
    <dd><%= $server_started %></dd>

(view [full file](https://github.com/flowdy/FlowgencyTM/blob/master/templates/info/basic.html.ep) on GitHub)

In my [controller code](https://github.com/flowdy/FlowgencyTM/blob/master/lib/FlowgencyTM/Server/Info.pm):

    sub basic {
        my ($self) = @_;
        $self->stash(
            version => $FlowgencyTM::VERSION,
            commit_id => qx{git rev-list -1 HEAD},
            changes => qx{git diff-index --shortstat HEAD},
            server_started => FlowgencyTM::Server::get_started_time(),
        );
    }

... and in the [app code](https://github.com/flowdy/FlowgencyTM/blob/master/lib/FlowgencyTM/Server.pm):

    my $started_time;
    BEGIN { $started_time = scalar localtime(); }
    sub get_started_time { $started_time; }

It is hardly feasible making the local repository dirty in one way or another (suffice to `touch` any file in a directory morbo watches, but unfortunately, that is already a change in git's eyes) only to have the info page rendered properly, as this is what I would have to ask from the users of the project.

Tested on versions 5.54, 5.71, and 6.11.

I'd love to pin the issue down to a tiny app if you request so. As I do not have an idea of what is potentially essential for that, this would cost time I'm sorry I cannot spend in the moment. My hope is you get a clue nevertheless.

Thank you & Tschüß
-- flowdy

**Comment by kraih** [comment]
I'm afraid this report makes no sense to me, you might want to try preparing a fully self-contained minimal test case.

**Comment by flowdy** [comment]
The fault in fact turned out at my side: In list context, the 'qx' operator used to execute a shell command and return standard output returns an empty list if there is no output, because there are no uncommitted changes. So, the Mojolicious::Controller::stash() gets `(..., changes => 'server_started', FlowgencyTM::Server::get_started_time())` as arguments. Guess perl would issue a warning like

    Odd number of elements in anonymous hash
        (W misc) You specified an odd number of elements to initialize a hash,
        which is odd, because hashes come in key/value pairs.

Oh, guess what I just found analysing the server log file? Oops, could have checked the log more more thoroughly before posting .

**Suggestion:**
So, in order to make that thread something of purpose, I'd like to suggest you let stash() throw an exception if it gets an uneven number of arguments of which it cannot make a hash. I just wonder why this is not fatal to perl.

**Comment by Grinnz** [comment]
This is just how lists and hashes work in perl. See also the issue with using methods like ->param() in hash constructors that was fixed sometime ago by not depending on context. Really you should not use anything in a hash constructor format (or methods like stash which put their args in a hash) unless you are sure they return a well formatted hash; qx in list context has no such guarantee. You can fix it in the code you posted above by prefixing the qx calls with "scalar" so they always return a string or undef.

**Comment by flowdy** [comment]
Did that already but thank you, it might be worth learning for other stumbling-upons. Nevertheless, it is always good to make error conditions clear to the user when they are disambiguous. A `croak "..." if @_ % 2` as a kind of interface contract could save hours of debugging (you could alright argue that I should have better looked in the server log). Isn't this even a best practice according to Conway(2006)?

**Comment by Grinnz** [comment]
Best practices are unique to each developer or project. Many disagree with some of Conway's practices and agree with others. I have suggested similar "developer friendly" croaks in the past but it would really need to be consistent through the whole framework, it would be a performance difference with no benefit to code that is already correct, and it only catches when methods are used incorrectly; Mojo is more focused on correct functionality when it is used correctly (as documented).
