### ISSUE TITLE
Mojo::JSON Compatibility

### ISSUE THREAD

**Issue by alnewkirk** [kraih/mojo#809]
Currently, the Mojo::JSON module supports encoding blessed objects which have a TO_JSON method, which means that module has the ability to handle encoding of data decoded using a foreign serializer (e.g. JSON, JSON::PP, etc). If the Mojo::JSON::_Bool module had a TO_JSON method defined, it would support the inverse operation, i.e. encoding a Mojo::JSON decoded JSON string which has true and/or false values.

**Comment by kraih** [comment]
I think `Mojo::JSON::MaybeXS` is good enough.
