### ISSUE TITLE
adding to renderer->classes  (_warmup should 'require' everything?)

### ISSUE THREAD

**Issue by wrog** [kraih/mojo#810]
Evidently, if one wants to have DATA templates/files in packages other than `main` to be recognized, it's not enough to edit renderer`->classes`; you also have to make sure the files are loaded, i.e., do

    push @{$app->renderer->classes}, 'My::Class';
    require My::Class;

otherwise, `Mojo::Loader::data_section`() will silently fail to produce them (followed by mysterious "template not found", etc)

Seems to me `Renderer::_warmup` ought to be doing a require on everything past `main` on the class list, i.e., it's building an index, so we have to read the files then and there anyway, and if they don't exist, that's a mistake that's worth raising an error for.

(... pod for `Renderer::classes` might also want to mention that modifying the class list after the application has started won't actually do anything...)

**Comment by kraih** [comment]
For now i've documented the current behavior, loading classes automatically is an option, but i'd rather be careful with that.
