### ISSUE TITLE
CSS selector "image" is not consistent

### ISSUE THREAD

**Issue by Logioniz** [kraih/mojo#811]
I have such code:
```perl
#!/usr/bin/perl
use Mojo::Base -strict;
use Mojo::DOM;

my $html ='<div><image src="/image"/></div>';
my $dom  =  Mojo::DOM->new($html);

say $dom->at('div image')->attr('src'); # not found
say $dom->at('div img')->attr('src');   # found
```
which, i think, work not consistent.
So, if tag "image" convert to img then need css selector convert to img too (only for html, not for xml).
What are you think?

**Comment by genio** [comment]
It seems that Mojo's behavior is the same as that of jQuery and a couple of others that I have tested.

```html
<html>
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
</head>
<body>
    <img src="foo" />
    <image src="bar" />
</body>
</html>
```

```
$('img').each(function(index){console.log(index+$(this).attr('src'));});
# 0foo
# 1bar
$('image').each(function(index){console.log(index+$(this).attr('src'));});
# []
```

Given that, I don't think this is an error.

**Comment by pink-mist** [comment]
The HTML5 spec says that when you encounter a tag with the name 'image', to simply /change/ its name to 'img'. This means the DOM never sees an 'image' tag, so you can't expect to match against it. The CSS Selector spec doesn't say anything about "translating" such things, so of course it shouldn't.

**Comment by jberger** [comment]
@pink-mist found this gem:

> **A start tag whose tag name is "image"**
> Parse error. Change the token's tag name to "img" and reprocess it. (Don't ask.)
-- http://www.w3.org/TR/html5/syntax.html

I'm inclined to agree with @genio and @pink-mist, since the HTML parse tree is explicitly instructed to never contain an image tag, I don't think that the CSS selectors should be handling them. It is strange, but we didn't write the HTML5 spec.

**Comment by Logioniz** [comment]
Ok
