### ISSUE TITLE
Validation 'required' check doesn't work for file fields using multipart/form-data

### ISSUE THREAD

**Issue by degeberg** [kraih/mojo#812]
Checking required fields using the validator does not work for file fields when enctype is multipart/form-data. The code below illustrates the problem. I would have expected the output to be "no error" if a file is uploaded, but it's always "has error" regardless of the submitted data.

```perl
use Mojolicious::Lite;

get '/' => 'index';

post '/' => sub {
  my $c = shift;

  my $validation = $c->validation;
  $validation->required('upload_file');

  my $msg = $validation->has_error ? 'has error' : 'no error';
  $c->render( text => $msg );
} => 'submit_form';

app->start;
__DATA__

@@ index.html.ep
<!DOCTYPE html>
<html>
  <head><title>Upload test</title></head>
  <body>
    <h1>Without multipart/form-data</h1>
    %= form_for 'submit_form', method => 'post' => begin
      %= file_field 'upload_file'
      %= submit_button
    % end
    <h1>With multipart/form-data</h1>
    %= form_for 'submit_form', method => 'post', enctype => 'multipart/form-data' => begin
      %= file_field 'upload_file'
      %= submit_button
    % end
  </body>
</html>
```

**Comment by kraih** [comment]
I'm afraid this is not actually a bug, just unsupported functionality. We've considered adding support a few times, but so far nobody could come up with a good proposal for how it should work exactly.

**Comment by s1037989** [comment]
has_error(): Check if validation resulted in errors, defaults to checking all fields.

What is it that causes an error 100% of the time when checking a file field when enctype is multipart/form-data?

**Comment by kraih** [comment]
@s1037989 Uploads are not GET/POST parameters, and therefore do not get merged into the validation input hash. Like i've said on IRC before, that can be changed very easily, but would cause new problems, such as none of the checks (like `size`, `like`...) actually working. This is a big design problem, not a bug.

**Comment by jhthorsen** [comment]
I don't see any benefit from having validation care about uploaded files.

**Comment by s1037989** [comment]
For me it was having a single validation system that could enforce that a file attachment was necessary.  I built a registration page it which it was a requirement that someone upload a valid copy of a license.  I was hoping to use the same validation system to kick back an error and highlight the missed attachment field when one wasn't present.

**Comment by jhthorsen** [comment]
@s1037989: does that mean that you do ```$v->required("upload")->like(qr{content fo the uploaded file});``` ?

**Comment by s1037989** [comment]
Well, I don't do anything since it isn't supported.  :)

But what I wanted to do was just this:

$v->required('upload');

That is, is there a value there?  It would be nice to be able to require a certain file type, but just validation that something was provided would be sufficient.

**Comment by kraih** [comment]
Feel free to post more complete proposals here, we can reopen the issue at any time.

**Comment by s1037989** [comment]
What about adding

$hash->{$_->name} = $_->filename for @{$req->uploads};

to Mojolicious::Controller::validation?

**Comment by kraih** [comment]
@s1037989 Please don't ignore my earlier comments.

**Comment by kraih** [comment]
A lot of this has been discussed again on IRC yesterday, and a new problem was discovered. Tag helpers would have to be updated for upload validation as well.

**Comment by kraih** [comment]
I've committed something, but the IRC discussion was inconclusive, so there's a good chance it might get removed again. https://github.com/kraih/mojo/commit/954e97c8e5314a573c73e623c052b05addecfa94

**Comment by jhthorsen** [comment]
I don't think there's much to gain from 954e97c, so I'm not actively giving the thumbs up. I just hope there won't be another case (I have no idea what that would be) which need similar special handling.

**Comment by kraih** [comment]
And it's gone again. https://github.com/kraih/mojo/commit/260db334b689d9504548085cef0778cc5a254ff5

**Comment by jberger** [comment]
I'd like us to first decide if Mojo's validation is meant to be generic or to be for query parameters. I liked the removed solution if it was the latter. I'm not sure where I stand on that question, @jhthorsen has declared for the former.
