### ISSUE TITLE
File::Copy 'move' blocks

### ISSUE THREAD

**Issue by lnussel** [kraih/mojo#813]
Mojo/Asset/File.pm uses File::Copy 'move' which may block the daemon for quite a while if MOJO_TMPDIR is not on the same file system as the target directory.

**Comment by kraih** [comment]
How else would we move files?

**Comment by jberger** [comment]
I'm not sure there is much that core mojo can do about that. If you know that you face this situation perhaps you want to look at Mojo::IOLoop::ForkCall to unblock. 

Anyway i don't believe that this can really be considered a bug, nor is it a feature that could be implemented easily. So I'm going to close this for now.

**Comment by lnussel** [comment]
well, mojo could try rename() itself and if it fails use a non-blocking copy via it's ioloop

**Comment by jberger** [comment]
is there a portable non-blocking copy?

**Comment by ravenhall** [comment]
Something like this or a File::Find example would be great for another blocking to non-blocking tutorial or cookbook recipe.

**Comment by jberger** [comment]
```perl
my $fc = Mojo::IOLoop::ForkCall->new;
$fc->run(
  sub { $asset->move_to($target) },
  sub { my ($fc, $err) = @_; ... }
);
```

**Comment by kraih** [comment]
It can be done with `IO::AIO` too, but you have to be very careful with that module.
