### ISSUE TITLE
print in recurring timer

### ISSUE THREAD

**Issue by bakanov** [kraih/mojo#814]
For some reason, when I print in recurring timer without newline ('\n') I have nothing printed. It's misleading, because I think that my timer is not working and I try to find problem in something different from this small symbol. 

I use latest version of Mojolicious:
CORE
  Perl        (v5.14.2, linux)
  Mojolicious (6.12, Clinking Beer Mugs)

OPTIONAL
  EV 4.0+                 (4.18)
  IO::Socket::Socks 0.64+ (0.66)
  IO::Socket::SSL 1.94+   (2.012)
  Net::DNS::Native 0.15+  (n/a)

1. Without newline:
#!/usr/bin/perl
use strict;
use warnings;
use Mojo::IOLoop;
my $loop = Mojo::IOLoop->new;
$loop->recurring(1 => sub { print "Hello" } );
$loop->start;
(nothing printed)
2. With newline:
#!/usr/bin/perl
use strict;
use warnings;
use Mojo::IOLoop;
my $loop = Mojo::IOLoop->new;
$loop->recurring(1 => sub { print "Hello\n" } );
$loop->start;
(printed multiple 'Hello')
3. Not recurring timer:
#!/usr/bin/perl
use strict;
use warnings;
use Mojo::IOLoop;
my $loop = Mojo::IOLoop->new;
$loop->timer(1 => sub { print "Hello" } );
$loop->start;
(printed one 'Hello')

**Comment by nnutter** [comment]
Is this just an autoflush issue?  If so, see, `perldoc perlvar`, for:

 * *HANDLE->autoflush( EXPR )*
 * *$OUTPUT_AUTOFLUSH*
 * *$| *

On Fri, Jun 26, 2015, at 05:41 AM, bakanov wrote:
> For some reason, when I print in recurring timer without newline
> ('\n') I have nothing printed. It's misleading, because I think that
> my timer is not working and I try to find problem in something
> different from this small symbol.


> I use latest version of Mojolicious:
>
CORE
>
  Perl        (v5.14.2, linux)
>
  Mojolicious (6.12, Clinking Beer Mugs)


> OPTIONAL
>
  EV 4.0+                 (4.18)
>
  IO::Socket::Socks 0.64+ (0.66)
>
  IO::Socket::SSL 1.94+   (2.012)
>
  Net::DNS::Native 0.15+  (n/a)


>  1. Without newline:
#!/usr/bin/perl
use strict; use warnings; use Mojo::IOLoop; my $loop = Mojo::IOLoop-
>new; $loop->recurring(1 => sub { print "Hello" } ); $loop->start;
>  2. With newline:
#!/usr/bin/perl
use strict; use warnings; use Mojo::IOLoop; my $loop = Mojo::IOLoop-
>new; $loop->recurring(1 => sub { print "Hello\n" } ); $loop->start;
>  3. Not recurring timer:
#!/usr/bin/perl
use strict; use warnings; use Mojo::IOLoop; my $loop = Mojo::IOLoop-
>new; $loop->timer(1 => sub { print "Hello" } ); $loop->start;
> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/kraih/mojo/issues/814

**Comment by bakanov** [comment]
It works with autoflush:
#!/usr/bin/perl
use strict;
use warnings;
$|++;
use Mojo::IOLoop;
my $loop = Mojo::IOLoop->new;
$loop->recurring(1 => sub { print "Hello" } );
$loop->start;

**Comment by kraih** [comment]
This has absolutely nothing to do with Mojolicious.
