### ISSUE TITLE
is_abs behaves wrong, if I change $url->scheme instead of $url->base->scheme

### ISSUE THREAD

**Issue by nugged** [kraih/mojo#816]
Regarding Mojo::URL in Mojolicious request cycle:

If I change `$c->req->url->scheme(...)` somewhere, things with `->url->to_abs` goes wrong, because is_abs very simple and relays only on scheme (`sub is_abs { !!shift->scheme }`)

Yes, direct example from http://mojolicio.us/perldoc/Mojolicious/Guides/Cookbook#Rewriting works,
but if I follow http://mojolicio.us/perldoc/Mojo/URL#scheme I can decide that `$url = $url->scheme('http');` have no side effects (but I got them ;-) ).

So, if I use:

    $c->req->url->base->scheme('https');
    warn $c->req->url->to_abs;

it warns with some of my devel proj url: https://run4iq.com/about/?someQuery=1
but

    $c->req->url->scheme('https');
    warn $c->req->url->to_abs;    

gives: https:/about/?someQuery=1
And even more

    $c->req->url->base->scheme('https');
    warn $c->req->url->to_abs . "\n";
    $c->req->url->scheme('https');
    warn $c->req->url->to_abs . "\n";

this 4 commands, executed in a row somewhere in Mojo code gives this warning output:

    https://run4iq.com/about/?someQuery=1
    https:/about/?someQuery=1

if this is not an issue but feature, just not so well documented, maybe to include remark in cookbook,
or this is issue?

**Comment by kraih** [comment]
Afraid i don't see the problem, everything seems to be working perfectly, and consistent with the specs.
