### ISSUE TITLE
Allow Mojolicious::Validation to validate hierarchical structure

### ISSUE THREAD

**Issue by avkhozov** [kraih/mojo#818]
Some data which needs to be validated is the json data, not only html form data. It would be nice if input and output data for validation can contain hierarchical structure (may be Mojo::JSON::Pointer). This feature may appear in Mojolicious?

**Comment by kraih** [comment]
This topic comes up a lot, and i would really like to support it, but so far there has been no proper proposal we could all agree on.

**Comment by kraih** [comment]
This also brings up the question of how generic the validation framework should be, which is still unanswered. https://github.com/kraih/mojo/issues/812#issuecomment-115714024

**Comment by jhthorsen** [comment]
I'm using https://metacpan.org/release/Swagger2 for this.

**Comment by kraih** [comment]
Looks like this issue already went stale, but at least we got the question of how generic the validation framework should be answered once and for all with a commit. https://github.com/kraih/mojo/commit/918c13f45d017305ffebe601af564936e5ce0776

**Comment by s1037989** [comment]
I'm interested in @jhthorsen's recommendation of using Swagger2 and am further encouraged by his excellent blog post this morning explaining how to do it in detail.

http://thorsen.pm/perl/programming/2015/07/05/mojolicious-swagger2.html
