### ISSUE TITLE
"remove" method called on undef in from destructor in M::UA - if Net::DNS::Native is installed

### ISSUE THREAD

**Issue by charliebrady** [kraih/mojo#819]
[root@amc2-199:]# mojo version 
CORE
  Perl        (v5.10.1, linux)
  Mojolicious (6.11, Clinking Beer Mugs)

OPTIONAL
  EV 4.0+                 (n/a)
  IO::Socket::Socks 0.64+ (n/a)
  IO::Socket::SSL 1.94+   (1.94)
  Net::DNS::Native 0.15+  (0.15)

You might want to update your Mojolicious to 6.12!
	(in cleanup) Can't call method "remove" on an undefined value at /usr/share/perl5/vendor_perl/Mojo/UserAgent.pm line 80 during global destruction.
~
[root@amc2-199:]# rpm -e perl-Net-DNS-Native
~
[root@amc2-199:]# mojo version              
CORE
  Perl        (v5.10.1, linux)
  Mojolicious (6.11, Clinking Beer Mugs)

OPTIONAL
  EV 4.0+                 (n/a)
  IO::Socket::Socks 0.64+ (n/a)
  IO::Socket::SSL 1.94+   (1.94)
  Net::DNS::Native 0.15+  (n/a)

You might want to update your Mojolicious to 6.12!
~
[root@amc2-199:]#

**Comment by kraih** [comment]
Afraid i was unable to replicate this problem.

**Comment by charliebrady** [comment]
What can I do to help you reproduce it?

This is somehow related to:

https://github.com/kraih/mojo/issues/715

**Comment by charliebrady** [comment]
powerman's proposed patch from https://github.com/kraih/mojo/issues/715 avoids the breakage, although it could be expressed more succinctly as:

--- /usr/share/perl5/vendor_perl/Mojo/UserAgent.pm.orig	2015-07-07 10:51:10.535538217 -0400
+++ /usr/share/perl5/vendor_perl/Mojo/UserAgent.pm	2015-07-07 10:52:01.773061339 -0400
@@ -76,7 +76,7 @@
   $self->_finish($_, 1) for keys %{$self->{connections} || {}};
 
   # Clean up keep-alive connections
-  my $loop = $self->_loop(0);
+  my $loop = $self->_loop(0) or return;
   $loop->remove($_->[1]) for @{delete $self->{queue} || []};
   $loop = $self->_loop(1);
   $loop->remove($_->[1]) for @{delete $self->{nb_queue} || []};

**Comment by kraih** [comment]
I need to be able to replicate it, or at least fully understand what exactly is causing the warning before a patch can be applied.

**Comment by charliebrady** [comment]
Understood, but shouldn't the issue stay Open until you do understand?

What can I do to help? Do you have access to a RHEL6/CentOS6 OS? Have you tried with perl 5.10.1? Does the Net::DNS::Native issue provide a helpful clue.

**Comment by kraih** [comment]
I just added a note about that to the docs. https://github.com/kraih/mojo/commit/fb90277e030e73b3eb0f8a4c9cf34b5ef829c393

**Comment by Grinnz** [comment]
I've reproduced it on CentOS 6:

````
$ /usr/local/bin/mojo version
CORE
  Perl        (v5.10.1, linux)
  Mojolicious (6.12, Clinking Beer Mugs)

OPTIONAL
  EV 4.0+                 (n/a)
  IO::Socket::Socks 0.64+ (n/a)
  IO::Socket::SSL 1.94+   (1.998)
  Net::DNS::Native 0.15+  (0.15)

This version is up to date, have fun!
        (in cleanup) Can't call method "remove" on an undefined value at /usr/local/share/perl5/Mojo/UserAgent.pm line 80 during global destruction.

$ sudo /usr/local/bin/cpanm --uninstall Net::DNS::Native
Net::DNS::Native contains the following files:

  /usr/local/lib64/perl5/Net/DNS/Native.pm
  /usr/local/lib64/perl5/auto/Net/DNS/Native/Native.so
  /usr/local/share/man/man3/Net::DNS::Native.3pm

Are you sure you want to uninstall Net::DNS::Native? [y] y

Unlink: /usr/local/lib64/perl5/Net/DNS/Native.pm
Unlink: /usr/local/lib64/perl5/auto/Net/DNS/Native/Native.so
Unlink: /usr/local/share/man/man3/Net::DNS::Native.3pm
Unlink: /usr/local/lib64/perl5/auto/Net/DNS/Native/.packlist

Successfully uninstalled Net::DNS::Native

$ /usr/local/bin/mojo version
CORE
  Perl        (v5.10.1, linux)
  Mojolicious (6.12, Clinking Beer Mugs)

OPTIONAL
  EV 4.0+                 (n/a)
  IO::Socket::Socks 0.64+ (n/a)
  IO::Socket::SSL 1.94+   (1.998)
  Net::DNS::Native 0.15+  (n/a)

This version is up to date, have fun!
````

I am not sure how much of a priority this will be though, on Perl 5.10.1 there are a ton of extraneous global-destruction warnings.

**Comment by kraih** [comment]
Oh, i did not realize that this might be a 5.10.1 specific problem. Then @Grinnz is absolutely correct, we have decided some time ago that we will not add workarounds for unsupported versions of Perl just to make a few warnings disappear.

**Comment by charliebrady** [comment]
But is it not a trivial fix?

**Comment by Grinnz** [comment]
As expected, on my Fedora 22 box this issue occurs with perls 5.10.1 and 5.12.5, but not 5.14.4 or above. Global-destruction warnings are generally harmless.

**Comment by charliebrady** [comment]
FWIW, this will quieten a few more warnings:

```
--- /usr/share/perl5/vendor_perl/Mojo/Server/Daemon.pm.orig     2015-07-08 19:31:34.490396726 +0000
+++ /usr/share/perl5/vendor_perl/Mojo/Server/Daemon.pm  2015-07-08 19:40:58.508284143 +0000
@@ -20,7 +20,7 @@
   return if Mojo::Util::_global_destruction();
   my $self = shift;
   $self->_remove($_) for keys %{$self->{connections} || {}};
-  my $loop = $self->ioloop;
+  my $loop = $self->ioloop or return;
   $loop->remove($_) for @{$self->acceptors};
 }

@@ -209,7 +209,7 @@

 sub _remove {
   my ($self, $id) = @_;
-  $self->ioloop->remove($id);
+  $self->ioloop->remove($id) if $self->ioloop;
   $self->_close($id);
 }
```

**Comment by kraih** [comment]
Thanks @Grinnz, that settles it.
