### ISSUE TITLE
PodRenderer requests

### ISSUE THREAD

**Issue by girlwithglasses** [kraih/mojo#821]
Two requests for the excellent PodRenderer plugin:

- remove dependency on external css so that it can be used entirely offline

- change display for `h1`/`h2`/`h3` elements from `inline-block` to `block` to prevent issues with `#` (appears when hovering over a title) running into the previous element. I added a top and bottom margin to these elements to increase legibility

**Comment by kraih** [comment]
What *external css* are you referring to?

**Comment by girlwithglasses** [comment]
run-prettify.js loads external css from its google code repo -- see screenshot for details:

![screen shot 2015-07-15 at 11 59 42](https://cloud.githubusercontent.com/assets/556057/8707224/62e14c56-2ae9-11e5-9013-ca75da439818.png)

I guess this is a prettify.js issue rather than a Mojo issue so I can raise it there (or just comment out the line `A.push("https://google-code-prettify.googlecode.com/svn/loader/prettify.css");`, which is the culprit).

Design issue - mousing over the method name:

![screen shot 2015-07-15 at 12 03 31](https://cloud.githubusercontent.com/assets/556057/8707261/994f6016-2ae9-11e5-9829-e06e37678102.png)

fix: 
`h1,h2,h3 {
        display: block;
        margin: .5em 0;
}`

![screen shot 2015-07-15 at 12 07 06](https://cloud.githubusercontent.com/assets/556057/8707365/0f8509ac-2aea-11e5-9eea-3acb284b7896.png)

**Comment by kraih** [comment]
Yes, that is indeed a prettify.js problem, and should be raised there. Do you have an example POD file demonstrating the problem?

**Comment by kraih** [comment]
Looks like it didn't actually serve a purpose anyway.

**Comment by girlwithglasses** [comment]
Thanks a lot for the speedy response!
