### ISSUE TITLE
Mojo::JSON enhance with pretty and sort_by

### ISSUE THREAD

**Issue by fayland** [kraih/mojo#822]
sort_by is https://metacpan.org/pod/JSON::PP#sort_by

if you need any patch, let me know.

Thanks

**Comment by iakuf** [comment]
This is two very good and common features. The default is to support very well.

**Comment by sjdy521** [comment]
looking forward to

**Comment by flw-cn** [comment]
Great, waiting this day for a long long time.

**Comment by jberger** [comment]
Within the Mojolicious project features are rarely added if they aren't needed to improve the behavior of the core system. The JSON format isn't needed as a human-readable output within the core so I don't think these features are likely to be added.

**Comment by jhthorsen** [comment]
Sorting (not quite the same) has been discussed before: https://github.com/kraih/mojo/pull/665.

If you need to prettify the data structure, I would suggest using ```Mojo::Util::dumper()``` on the decoded JSON structure.

Also, please provide some examples/usecases why these two features would enhance the existing API.

**Comment by fayland** [comment]
Actually sorting is for viewing. for example, I'm providing an API to customers and it contains many keys, so it would be better if output keys are in certain order (like id is always the first key) so people do not need a search to find related stuff.

I'm not talking a default sorting on keys by alpha. but a custom sub like in JSON::PP.

ty

**Comment by jhthorsen** [comment]
Viewing where..? If it's from command line, you can pipe the output into json_pp and if it's in a browser I would rather use a plugin. Google Chrome has https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc?hl=en

Doesn't matter if the sorting is by alpha. The problem is making sure you don't spend CPU cycles on server side, when you don't have to.

**Comment by kraih** [comment]
Lets just not do this. You can already use a tied hash with your own sorting algorithm, like the one i used in Mango back in the days. https://github.com/kraih/mango/blob/master/lib/Mango/BSON/Document.pm

**Comment by kraih** [comment]
Anyway, looks like this issue went stale.

**Comment by jberger** [comment]
I would contend that it actually failed a vote, but sure, stale works too.
