### ISSUE TITLE
Mojolicious templates are now supported in Camelcade plugin for IntelliJ IDEA

### ISSUE THREAD

**Issue by hurricup** [kraih/mojo#823]
Didn't know where to add this, so, sorry if doing it wrong way.

Anyway, Perl5 plugin for IntellJ IDEA I'm currently developing supports Mojolicious templates starting from today's build.

Would be nice to mention it somewhere.

Here is it: https://plugins.jetbrains.com/plugin/7796

**Comment by jberger** [comment]
While I'm happy to see this effort undertaken, I'm not sure that it would belong in the main documentation. I don't believe that we reference mojo.vim for example. 

While we wait for inspiration if you would prefer to make a wiki page, you are free to do so.

**Comment by jhthorsen** [comment]
jberger: :+1:

**Comment by hurricup** [comment]
Well, I ment IDE/Editor support of wiki. Just didn't know I could edit it myself :) Thanks!
