### ISSUE TITLE
Mojo::UserAgent sends useless "Content-Length" header for GET request

### ISSUE THREAD

**Issue by olegwtf** [kraih/mojo#828]
This is how default GET request from Mojo::UserAgent looks like:
```
GET / HTTP/1.1
Content-Length: 0
Accept-Encoding: gzip
User-Agent: Mojolicious (Perl)
Connection: keep-alive
Host: www.google.com
```

The HTTP/1.1 specification is not very clear about GET request and `Content-Lngth` header. This is what I found:
>The presence of a message-body in a request is signaled by the
>inclusion of a Content-Length or Transfer-Encoding header field in
> the request's message-headers. A message-body MUST NOT be included in
> a request if the specification of the request method (section 5.1.1)
> does not allow sending an entity-body in requests.

The logic is: GET request doesn't allow body (?), so `Content-Length` header shouldn't be specified.

Anyway, I have example of the server which sends 403 for me when `Content-Length: 0` is in the request and 200 when there is no `Content-Length` specified. This is how I found this bug (?). Furthermore I didn't see that any popular user agent sends `Content-Length` header for GET request.

**Comment by tempire** [comment]
I wouldn't consider this a bug. A server that responds with a 403 just because a GET request has content-length: 0, however, that sounds like a bug.

**Comment by sjdy521** [comment]
why should we keep a useless header? I notice this exists for a long time

**Comment by olegwtf** [comment]
I was wrong. It responses with 404.
```Perl
use Mojo::UserAgent;

my $ua = Mojo::UserAgent->new();
warn Mojo::UserAgent->new->get('http://www.raiffeisen.ru/')->res->code;
```

**Comment by sjdy521** [comment]
@olegwtf  the worse thing I cann't remove this header when I want to

    use Mojo::UserAgent;
    my $ua = Mojo::UserAgent->new();
    my $tx = $ua->build_tx(GET=>'http://www.raiffeisen.ru/');
    $tx->req->headers->remove('Content-Length');
    print $tx->req->to_string;

**Comment by marcusramberg** [comment]
I agree it seems like an useless header to send on get requests. I don't think it's a big deal, and that raiffeisen.ru server seems broken for returning a 404, but I'm still in favor of dropping the useless overhead.

**Comment by kraih** [comment]
If minimal message size is a goal, then this patch might make sense.
```
diff --git a/lib/Mojo/Message.pm b/lib/Mojo/Message.pm
index 56d5cd9..cebe161 100644
--- a/lib/Mojo/Message.pm
+++ b/lib/Mojo/Message.pm
@@ -99,8 +99,8 @@ sub fix_headers {
   my $headers = $content->headers;
   if ($content->is_multipart) { $headers->remove('Content-Length') }
   elsif ($content->is_chunked || $headers->content_length) { return $self }
-  if   ($content->is_dynamic) { $headers->connection('close') }
-  else                        { $headers->content_length($self->body_size) }
+  if ($content->is_dynamic) { $headers->connection('close') }
+  elsif (my $size = $self->body_size) { $headers->content_length($size) }
 
   return $self;
 }
diff --git a/t/mojo/request.t b/t/mojo/request.t
index fd838f2..22d0b40 100644
--- a/t/mojo/request.t
+++ b/t/mojo/request.t
@@ -1248,7 +1248,6 @@ is $req->url->to_abs, 'http://example.com/demo', 'right absolute URL';
 is $req->headers->connection, 'Upgrade',     'right "Connection" value';
 is $req->headers->upgrade,    'websocket',   'right "Upgrade" value';
 is $req->headers->host,       'example.com', 'right "Host" value';
-is $req->headers->content_length, 0, 'right "Content-Length" value';
 is $req->headers->sec_websocket_accept, 'abcdef=',
   'right "Sec-WebSocket-Key" value';
 is $req->headers->sec_websocket_protocol, 'sample',
@@ -1276,7 +1275,6 @@ is $req->url->to_abs, 'http://example.com/demo', 'right absolute URL';
 is $req->headers->connection, 'Upgrade',     'right "Connection" value';
 is $req->headers->upgrade,    'websocket',   'right "Upgrade" value';
 is $req->headers->host,       'example.com', 'right "Host" value';
-is $req->headers->content_length, 0, 'right "Content-Length" value';
 is $req->headers->sec_websocket_accept, 'abcdef=',
   'right "Sec-WebSocket-Key" value';
 is $req->headers->sec_websocket_protocol, 'sample',
@@ -1292,7 +1290,6 @@ is $clone->url->to_abs, 'http://example.com/demo', 'right absolute URL';
 is $clone->headers->connection, 'Upgrade',     'right "Connection" value';
 is $clone->headers->upgrade,    'websocket',   'right "Upgrade" value';
 is $clone->headers->host,       'example.com', 'right "Host" value';
-is $clone->headers->content_length, 0, 'right "Content-Length" value';
 is $clone->headers->sec_websocket_accept, 'abcdef=',
   'right "Sec-WebSocket-Key" value';
 is $clone->headers->sec_websocket_protocol, 'sample',
@@ -1319,7 +1316,6 @@ is $req->url->to_abs, 'http://example.com/demo', 'right absolute URL';
 is $req->headers->connection, 'Upgrade',     'right "Connection" value';
 is $req->headers->upgrade,    'websocket',   'right "Upgrade" value';
 is $req->headers->host,       'example.com', 'right "Host" value';
-is $req->headers->content_length, 0, 'right "Content-Length" value';
 is $req->headers->sec_websocket_accept, 'abcdef=',
   'right "Sec-WebSocket-Key" value';
 is $req->headers->sec_websocket_protocol, 'sample',
diff --git a/t/mojo/response.t b/t/mojo/response.t
index 7a75c2b..e8db698 100644
--- a/t/mojo/response.t
+++ b/t/mojo/response.t
@@ -671,7 +671,6 @@ is $res->code,        '404', 'right status';
 is $res->message,     'Not Found', 'right message';
 is $res->version,     '1.1', 'right version';
 is $res->headers->date, 'Sun, 17 Aug 2008 16:27:35 GMT', 'right "Date" value';
-is $res->headers->content_length, 0, 'right "Content-Length" value';
 
 # Build HTTP 1.1 response start-line with minimal headers (strange message)
 $res = Mojo::Message::Response->new;
@@ -684,7 +683,6 @@ is $res->code,        '404', 'right status';
 is $res->message,     'Looks-0k!@ ;\':" #$%^<>,.\\o/ &*()', 'right message';
 is $res->version,     '1.1', 'right version';
 is $res->headers->date, 'Sun, 17 Aug 2008 16:27:35 GMT', 'right "Date" value';
-is $res->headers->content_length, 0, 'right "Content-Length" value';
 
 # Build HTTP 1.1 response start-line and header
 $res = Mojo::Message::Response->new;
@@ -698,7 +696,6 @@ is $res->message,     'OK', 'right message';
 is $res->version,     '1.1', 'right version';
 is $res->headers->connection, 'keep-alive', 'right "Connection" value';
 is $res->headers->date, 'Sun, 17 Aug 2008 16:27:35 GMT', 'right "Date" value';
-is $res->headers->content_length, 0, 'right "Content-Length" value';
 
 # Build full HTTP 1.1 response
 $res = Mojo::Message::Response->new;
@@ -879,8 +876,7 @@ is $res->message,     'Switching Protocols', 'right message';
 is $res->version,     '1.1', 'right version';
 is $res->headers->connection, 'Upgrade', 'right "Connection" value';
 is $res->headers->date, 'Sun, 17 Aug 2008 16:27:35 GMT', 'right "Date" value';
-is $res->headers->upgrade,        'websocket', 'right "Upgrade" value';
-is $res->headers->content_length, 0,           'right "Content-Length" value';
+is $res->headers->upgrade, 'websocket', 'right "Upgrade" value';
 is $res->headers->sec_websocket_accept, 'abcdef=',
   'right "Sec-WebSocket-Accept" value';
 is $res->headers->sec_websocket_protocol, 'sample',
@@ -902,7 +898,6 @@ $res2->parse($res->to_string);
 ok $res2->is_finished, 'response is finished';
 is $res2->code,        404, 'right status';
 is $res2->version,     '1.1', 'right version';
-is $res2->headers->content_length, 0, 'right "Content-Length" value';
 ok defined $res2->cookie('foo'),   'cookie "foo" exists';
 ok defined $res2->cookie('bar'),   'cookie "bar" exists';
 ok defined $res2->cookie('baz'),   'cookie "baz" exists';
diff --git a/t/mojolicious/static_lite_app.t b/t/mojolicious/static_lite_app.t
index 5df2f01..17b962e 100644
--- a/t/mojolicious/static_lite_app.t
+++ b/t/mojolicious/static_lite_app.t
@@ -173,8 +173,7 @@ $t->get_ok('/asset' => {'Range' => 'bytes=3-5'})->status_is(206)
 
 # Empty file
 $t->get_ok('/hello4.txt')->status_is(200)
-  ->header_is(Server           => 'Mojolicious (Perl)')
-  ->header_is('Content-Length' => 0)->content_is('');
+  ->header_is(Server => 'Mojolicious (Perl)')->content_is('');
 
 # Partial empty file
 $t->get_ok('/hello4.txt' => {Range => 'bytes=0-0'})->status_is(416)
```
As far as i can see it is compliant with RFC 7230.

**Comment by kraih** [comment]
It might also make sense to omit `Connection: keep-alive` in some cases, i do not have a patch for that though.

**Comment by olegwtf** [comment]
>A user agent SHOULD send a Content-Length in a request message when
> no Transfer-Encoding is sent and the request method defines a meaning
> for an enclosed payload body.  For example, a Content-Length header
> field is normally sent in a POST request even when the value is 0
> (indicating an empty payload body).  A user agent SHOULD NOT send a
> Content-Length header field when the request message does not contain
> a payload body and the method semantics do not anticipate such a
> body.

Will it send `Content-Length: 0` for POST with empty body after this patch?

**Comment by kraih** [comment]
@olegwtf No, doing so would be very complicated, and it is just a `SHOULD`.

**Comment by shadowcat-mst** [comment]
@kraih doesn't that mean that the server can't tell there's no body unless the client closes the connection after sending, or am I missing something?

**Comment by kraih** [comment]
@shadowcat-mst Which section of the spec are you referring to? As far as i can see without a `Content-Length` header there simply can't be a message body.

**Comment by kraih** [comment]
I don't care very much about this change, both versions are spec compliant. But there is no cost and i do like the flexibility of being able to create messages without `Content-Length` header, as well as manually adding `Content-Length: 0`.

**Comment by shadowcat-mst** [comment]
19:59 <sri> for a keep-alive connection Content-Length: 0 will be implicit
20:00 <sri> but if the connection gets closed, the message will be terminated  
             by EOF
20:00 <mst> http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.4
20:01 <mst> I don't see anything about implicit CL there
20:02 <sri> i don't use the old spec anymore
20:05 <mst> 3.3.3 of 7230 says the same thing
20:06 <mst> > 7.  Otherwise, this is a response message without a declared  
             message body length, so the message body length is determined by 
             the number of octets received prior to the server closing the 
             connection.
20:08 <mst> sri: I can't see anything in section 6 of 7230 either
20:08 <mst> is there a bit of the standard I'm missing that says 'for a  
             keep-alive connection Content-Length: 0 will be implicit' ? I 
             can't find it :/
20:11 <sri> i don't remember if it was actually written down somewhere like  
             that
20:16 <mst> ok, so as far as I can see, omitting it on responses isn't valid
20:16 <mst> might work for some clients, but 3.3.3 7 indicates it's incorrect  
             unless I'm misreading it

**Comment by kraih** [comment]
I'm afraid the change caused problems with Chrome and had to be reverted. https://github.com/kraih/mojo/commit/139938c8d80b8dfc97b266dad84a3bf22a5343c6

**Comment by shadowcat-mst** [comment]
Given chrome's heavy use of persistent connections, I'm sadly unsurprised.

**Comment by forki** [comment]
Setting Content-Length 0 does not work against asp.net core - the server rejects that
/cc @dfowler
