### ISSUE TITLE
Simple set selected in select_field helper

### ISSUE THREAD

**Issue by rshadow** [kraih/mojo#829]
Please add the option for easy generation with the current value.

For example:
```
%= select_field country => [qw(de en)], 'en'
```
make
```html
<select name="country">
  <option value="de">de</option>
  <option value="en" selected="selected">en</option>
</select>
```

**Comment by jhthorsen** [comment]
@rshadow: Is this too complicated?

    % param country => 'en' unless param 'country';
    %= select_field country => [qw(de en)]

**Comment by zoffixznet** [comment]
My two cents on this:

It's definitely something that needs to be addressed. Even if you know of `param`, it's not the first thing to come to mind when you're writing a bunch of form controls, all of which offer a method to set a defaults. I myself had to ask on IRC how to set `<select>`'s default. I saw another person ask the same. And now we have @rshadow mention it too.

@jhthorsen 's method above works, but it feels like a hack and isn't the first thing that comes to mind when coding a whole bunch of form controls, all of which offer a way to specify the default.

I think this way would be easier to implement, for users to understand, and would mirror the way the defaults are set on other form controls: `%= select_field country => en => [qw(de en)]`

**Comment by kraih** [comment]
Not sure this can be discussed further without an actual patch.

**Comment by zoffixznet** [comment]
I'll make a patch for us to look at.

**Comment by kraih** [comment]
As @zoffixznet mentioned before, the `select_field` helper keeps causing problems, so i think we should also consider its removal, instead of making it even more complicated.

**Comment by zoffixznet** [comment]
As we just talked on IRC, there is already a way to set a default by passing it `selected => 'selected'` for the appropriate value. So I take it back, no 3rd way to set a default is needed.

I agree. The issues likely stem from `select_field`'s complexity rather than any missing features.

**Comment by kraih** [comment]
There's also a consistency problem, similar helpers like `check_box` do not accept the proposed argument.

**Comment by pink-mist** [comment]
Why not just add the `selected` attribute to the documentation for `select_field` like so:
https://github.com/pink-mist/mojo/commit/fc523eda03edf05d8766ab9ebbb1f90ec4eaf4fc

**Comment by kraih** [comment]
@pink-mist I believe that doesn't actually work, since it won't be able to automatically deselect when a different selection has been submitted by a user.

**Comment by pink-mist** [comment]
Alright fair enough; I'd still say this is just a documentation problem though

**Comment by kraih** [comment]
Not sure anymore if there actually is a problem, generating select/optgroup/option elements is complex by nature, i vote for keeping everything the way it is.

**Comment by pink-mist** [comment]
Perhaps this is a better suggestion for the docs?
https://github.com/kraih/mojo/compare/master...pink-mist:select_field_doc

**Comment by zoffixznet** [comment]
:+1:  on the doc change to include `param` way of setting the default
> Perhaps this is a better suggestion for the docs?
> master...pink-mist:select_field_doc

**Comment by kraih** [comment]
Perhaps some more consistency might be in order. https://github.com/kraih/mojo/commit/a244d566927850f800f17e152899011000147ebf

**Comment by kraih** [comment]
Thanks everyone, i think we can consider this issue resolved.
