### ISSUE TITLE
Can't call method "remove" on an undefined value 

### ISSUE THREAD

**Issue by johnnywang1991** [kraih/mojo#831]
I found a bug in perl 5.10 like this: 
# cat t.pl
#!/usr/bin/perl
use Mojolicious::Lite;

get '/' => {text => 'I  Mojolicious!'};

app->start;

1;

# perl t.pl get /
[Wed Aug 19 10:20:32 2015] [debug] Your secret passphrase needs to be changed
[Wed Aug 19 10:20:32 2015] [debug] GET "/"
[Wed Aug 19 10:20:32 2015] [debug] 200 OK (0.000513s, 1949.318/s)
I  Mojolicious!	(in cleanup) Can't call method "remove" on an undefined value at /usr/local/share/perl5/Mojo/Server/Daemon.pm line 24, <DATA> line 2231 during global destruction.
	(in cleanup) Can't call method "remove" on an undefined value at /usr/local/share/perl5/Mojo/UserAgent.pm line 80, <DATA> line 2231 during global destruction.

**Comment by iakuf** [comment]
I often appear error in other case.

**Comment by jberger** [comment]
@kraih can correct me if I'm wrong, but I think that global destruction errors on old perls aren't worth the effort of fixing.

**Comment by kraih** [comment]
@jberger is correct, we only keep Mojolicious installable on old versions of Perl, but do not specifically optimize for it. http://mojolicio.us/perldoc/Mojolicious/Guides/FAQ#Which-versions-of-Perl-are-supported-by-Mojolicious

**Comment by johnnywang1991** [comment]
@kraih I found that nera 20% ( [w3cook](http://www.w3cook.com/os/summary/) ) website in the world use CENTOS, and most of them use the CENTOS 6. The default version of perl at Centos 6 is 5.10.1.
For example, our website has thousands of centos 6 servers, and many application on it. we use perl and mojolicious in part of our website. If we update the version of perl, it will be an huge project, and our website might be down if there have a mistake.
And if we upgrade the OS, or change the OS, it will be a disaster.
So, you might rethink the lowest version of mojolicious supported, and the fatal bug like this should be fixed

**Comment by kraih** [comment]
@johnnywang1991 I've considered offering commercial support contracts to pay for the extra work hours required to support things like that. If you or your employer are interested in something like that, please let me know.

**Comment by uynap** [comment]
@kraih Since all our servers in my company are RHEL 6.x, I'm curious about the cost for the "commercial support". Any thought on that?

**Comment by kraih** [comment]
@uynap Not yet, just collecting contact information of companies that might be interested.

**Comment by iakuf** [comment]
@kraih  You can write a special page. To let everyone know. I believe there are a lot of people interested. 
PS: our servers in my company are all Centos 6.x .

**Comment by jberger** [comment]
> So, you might rethink the lowest version of mojolicious supported, and the fatal bug like this should be fixed

@johnnywang1991 is it really a "fatal bug" if it only occurs in global destruction (ie once the server is terminating anyway)?

**Comment by johnnywang1991** [comment]
@jberger I have an object based on [stf](https://github.com/stf-storage/stf), and I migrate part of web server to mojolicious. It become an "fatal bug" when I use in this

**Comment by sjdy521** [comment]
@kraih @jberger 
just want to emphasize the point of @johnnywang1991 
my company is maintaining about more than 30000 servers of Centos 5.8 with perl-5.8 for many years.
system upgrade is always complicated, not a easy job. I really don't think perl-5.10 should be overlooked, hope reconsidering the lowest version of mojolicious supported

**Comment by jhthorsen** [comment]
I think also plenv/perlbrew should be an alternative. I've heard many companies running centos are using custom Perl with Mojolicious (And other modules).

**Comment by nnutter** [comment]
We're using Perlbrew to run Perl 5.22 on CentOS 6.5.

**Comment by iakuf** [comment]
@kraih @jhthorsen    Now our company have more than 100 servers and running Mojolicious app. If we use Perlbrew, I will mad. this will  affect other perl apps. The last company of mine had more than 11000 servers at 2001 year. they run POE app and other perl apps(Centos 6).  if the company replace the Perlbrew, it will be a nightmare!!
![20150821101612](https://cloud.githubusercontent.com/assets/1662228/9400122/252e2a68-47f0-11e5-9430-7c14a4482919.png)

**Comment by kraih** [comment]
@iakuf Not sure what you're arguing for, maintaining support for old versions of Perl is expensive, and right now nobody wants to pay for it.

**Comment by jhthorsen** [comment]
@iakuf it's only a nightmare without automation. Use Ansible, Puppet, Chef, ... and you should be fine.

Anyhow. I'm drifting the discussion, so I will end this "sub thread" about automation now. Use google or send me an email if you want to know more.

**Comment by leonkyneur** [comment]
5.10 is old  - Red Hat themselves acknowledge that, and that's why Software Collections exist
http://developerblog.redhat.com/2013/01/28/software-collections-on-red-hat-enterprise-linux/
