### ISSUE TITLE
"Can't open file error" in Mojo::Asset::File

### ISSUE THREAD

**Issue by prg** [kraih/mojo#833]
Recently upgraded from 4.26 to 6.15 (and now 6.16), suddenly getting lots of errors from uploads:

```
[2015/08/20 13:46:38] error: Can't open file "/tmp/mojo.tmp.096a27496a2b8632cada9bd978f822f2": No such file or directory
```

Even stranger, sometimes the errors look like this:

```
[2015/08/20 13:33:57] error: Can't open file "/tmp/mojo.tmp": No such file or directory
```

Since there are 2 Instances of this application running on two servers behind a load-balancer, I figured the load-balancer directed upload chunks to different servers and thus caused the problem. So I set MOJO_TMPDIR to a path on a shared NFS volume, hoping it would solve the problem, but unfortunately it didn't.

The culprit in my upload endpoint code is probably this:

```
  my $asset;
  if ($c->req->content->is_multipart) {
      $asset = $c->param('file')->asset;
  } else {
      $asset = $c->req->content->asset;
  }

  if (open(my $fh, ">>", $part_path)) {
      print $fh $asset->slurp;
      close($fh);
  }
```

I haven't been able to reproduce this in my development environment, so I can't provide a test case. It doesn't even always happen in production, only intermittently.

But from looking at the source of Mojo::Asset::File (https://github.com/kraih/mojo/blob/v6.16/lib/Mojo/Asset/File.pm#L27), shouldn't ```md5_sum()``` be appended to ```$base``` before the ```until```-loop starts? That at least explains the different filenames I'm seeing.

Otherwise I'm at a loss here, any help would be greatly appreciated.

**Comment by jhthorsen** [comment]
Are you sure you can write to /tmp as the user that the process is running as? Are you running the server with hypnotoad? Maybe you missed out on https://github.com/kraih/mojo/blob/master/Changes#L39

The md5_sum() logic is simply to ensure a unique file, if there is already a temp file existing.

**Comment by prg** [comment]
Yes, I'm running hypnotoad and no, I didn't miss that change. The user has permissions to write to /tmp, in fact there are temporary files there:

```
-rw-r--r--  1 www www  334K Aug 20 15:13 mojo.tmp.ec248220e3554cb30c2e28f034ef63db
```

Also, since the error is "No such file" and not "Permission denied", I kinda doubt that's the problem :(

**Comment by prg** [comment]
FYI: this was previously running under ```perl-5.16.3```, I just upgraded to ```5.22.0```. Problem persists.

**Comment by kraih** [comment]
We need a test case for this, preferably in `t/mojo/asset.t`.

**Comment by kraih** [comment]
The `slurp` method got optimized a little recently, perhaps that caused it, but impossible to say until we are able to replicate the problem. https://github.com/kraih/mojo/commit/959157c767c93e777d32e1b778103adce5c8cd65#diff-4e1bdb34da448764c931ba03e53f8feeL130

**Comment by prg** [comment]
As I said, haven't been able to reproduce this on my machine. Will give it another shot tomorrow, though.

**Comment by kraih** [comment]
I'm afraid then there is not much more we can do at the moment. Closing this issue for now, and will reopen it if there is new information.

**Comment by prg** [comment]
I don't think the ```slurp``` optimizations are the cause, AFAICT we never reach that code.

**Comment by prg** [comment]
FYI: I downgraded Mojo on one of the two machines to ```4.67```, no error in the last 15 minutes.

**Comment by jhthorsen** [comment]
@prg: Try upgrading in steps. As in 4.90, 5.00, 5.xx, 6.00, ...

**Comment by prg** [comment]
Already on it, currently running ```5.00``` and waiting for errors to occur.

**Comment by prg** [comment]
So far everything ```>= 5.40``` produced errors, everything ```<= 5.30``` seemed fine (although that's harder to tell, but I waited for approx. 20 minutes every time which should be plenty).
Currently running ```5.35```, hopefully I'm closing in on this...

**Comment by prg** [comment]
I just noticed something else:
I was running ```5.31``` for about 20 minutes without problems, and just as I started ```cpanm Mojolicious@5.32``` an error occured. I'm guessing something in the build process/tests is wiping MOJO_TMPDIR?

**Comment by jberger** [comment]
Perhaps you could git bisect around that time to see if you can pin it down
to a commit?

**Comment by prg** [comment]
@jberger I'll try to make time for that.

Right now I'm back to running ```5.30```, when I downgraded once more from ```5.32``` to ```5.31``` (to verify it was OK) I got another error. Looking at the Changelog, this makes no sense to me at all.

**Comment by prg** [comment]
Been running on ```5.30``` for an hour now without any incident.

Looking at https://github.com/kraih/mojo/compare/v5.30...v5.31, there have been some changes to Mojo::Asset::File. I'm guessing they are the problem.

**Comment by jhthorsen** [comment]
"The culprit in my upload endpoint code is probably this" ... does that mean that it's not your actual code? Please paste more of your actual code.

**Comment by jhthorsen** [comment]
The change I can see is that 0.30 use the filehandle, while 0.31 use the path... Maybe the file is somehow unlinked from the filesystem, but still accessible by the direct handle? Can you try to Change back the slurp() method, but leave everything else is in 0.31?

https://github.com/kraih/mojo/compare/v5.30...v5.31#diff-4e1bdb34da448764c931ba03e53f8feeR128

Also, did you say that the temp file is stored on nfs..?

**Comment by prg** [comment]
It is my actual code, and the rest of it is probably irrelevant. Stuff like
```
  my $file_path = try { $c->_order->uploadPath($file_name) };
  ...
  my $part_path = "$file_path.part";
```
which I think doesn't help anyone in debugging this.

Initially I tried pointing ```MOJO_TMPDIR``` to a path on a NFS share, but since it was clear that this wasn't the problem I reverted that (defaulting to ```/tmp``` again).

Right now I have other issues to handle, I'll try to manually modify ```slurp()``` and/or do a git bisect when I have time.

**Comment by kraih** [comment]
That's literally the commit i pointed at earlier. https://github.com/kraih/mojo/commit/959157c767c93e777d32e1b778103adce5c8cd65#diff-4e1bdb34da448764c931ba03e53f8feeL130

**Comment by kraih** [comment]
And i assume this commit makes all problems go away. (still without tests!) https://github.com/kraih/mojo/commit/ec7920ea74e9fdb8316037316d3c08cf195a9e0b

**Comment by prg** [comment]
Well, since you said recently, I figured you meant https://github.com/kraih/mojo/commit/683f4a23db4bd48ea09189d9fb83d95f4c620ce9 and https://github.com/kraih/mojo/commit/04732845a2b30d7e6d5e7f0d9064b58205dfa678. Surely my mistake that I didn't look more closely, but to be honest: you have an interesting definition of recently, seeing as https://github.com/kraih/mojo/commit/959157c767c93e777d32e1b778103adce5c8cd65 is from almost exactly one year ago.

And since you came up with the solution, I'm confident you'll be able to write tests for this :)

**Comment by kraih** [comment]
@prg Actually, i've been unable to find a test case. So odds are someone will break it again at some point.

**Comment by jhthorsen** [comment]
@kraih how about:
```
diff --git a/t/mojo/asset.t b/t/mojo/asset.t
index 8b82fbe..b476a02 100644
--- a/t/mojo/asset.t
+++ b/t/mojo/asset.t
@@ -191,7 +191,9 @@ ok $asset->is_file, 'stored in file';
 $asset = $asset->add_chunk('lala');
 is $upgrade, 1, 'upgrade event was not emitted again';
 ok $asset->is_file, 'stored in file';
-is $asset->slurp,   'lalalalalala', 'right content';
+ok $asset->handle, 'got handle';
+unlink $asset->path;
+is $asset->slurp, 'lalalalalala', 'right even if file is removed';
 ok $asset->cleanup, 'file will be cleaned up';
 $asset = Mojo::Asset::Memory->new(max_memory_size => 5);
 $asset = $asset->add_chunk('lala');
```

**Comment by prg** [comment]
Just wanted to confirm the problem is gone in ```6.17```, been running that since this morning.

**Comment by akelwood** [comment]
Hi,
sorry i'm a newbie with Mojo, and i have a question related to this topic if you don't mind.

I see that Mojo is temporary storing the file uploaded into /tmp/mojo.tmp

What is going on if i run multiples workers with prefork and the service receive multiples upload simultaneously ? Does mojo use different tmp file names ?

Otherwise, a workaround is tu use slurp, but slurp is returning "more" than the file content posted 
ie :
------WebKitFormBoundaryZthpSWxw9tWBTrTj
Content-Disposition: form-data; name="filepdf"; filename="msg.pdf"
Content-Type: application/octet-stream
...
Finally
Is there any way to only get the file content and only the file content ?

Many thx.

**Comment by jberger** [comment]
@akelwood please don't reuse closed issued for a different (if related question). It sounds to me like you should ask the mailing list or come chat with us on #mojo on irc.perl.org. http://mojolicious.org/perldoc#SUPPORT
