### ISSUE TITLE
Incorrect sysctl settings on 2.6.x Centos

### ISSUE THREAD

**Issue by mpapec** [kraih/mojo#834]
There are no `kern.maxfiles` and `kern.maxfilesperproc`.

    #sysctl -w kern.maxfiles=40960 kern.maxfilesperproc=20480
    error: "kern.maxfiles" is an unknown key
    error: "kern.maxfilesperproc" is an unknown key

Linux rs200516 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jberger** [comment]
Is this in the main documentation? IIRC this is only on the wiki, in which case you could simply add the working settings for your platform.

**Comment by zoffixznet** [comment]
I grepped mojo's repo for `kern.maxfilesperproc` and `kern.maxfilesperproc` and did not find any matches.

**Comment by mpapec** [comment]
I guess sysctl parameters changed in the meantime. Docs are at https://github.com/kraih/mojo/wiki/Tuning-servers-for-high-concurrency-workloads

**Comment by mpapec** [comment]
@jberger I've tried these settings in belief that it would improve hypnotoad performance => http://stackoverflow.com/questions/32170038/hypnotoad-performance

**Comment by jberger** [comment]
As I have said, the wiki is not part of the core documentation and can be edited without code changes. As a result I'm going to close this issue.

That said, why are you using the OSX instructions when using centos (linux)?

**Comment by mpapec** [comment]
@jberger re:OSX; you're right; not enough coffee I guess.
