### ISSUE TITLE
Expand documentation for "?ca=/..." option 

### ISSUE THREAD

**Issue by TobyGoodwin** [kraih/mojo#840]
I spent ages trying to work out why a listen URL that included a "ca=" option was not working. The server was correctly sending the right certificate, but then aborting the connection.

As far as I can tell, "?ca=/..." actually enables client authentication (and presumably points to the trust anchor that the server will use to verify the client's certificate). A note in the documentation explaining this would have saved me a lot of trouble!

**Comment by kraih** [comment]
Afraid i don't understand what this issue is about, and the `As far as i can tell...` bit seems to suggest you're not sure either. Please open a new issue once you can describe the problem in more detail.
