### ISSUE TITLE
Basic authorization over https

### ISSUE THREAD

**Issue by grinya007** [kraih/mojo#843]
Hi!
Does Mojo::UserAgent support basic auth over https?
Cannot make it happen, while LWP::UserAgent and Chrome do the thing (
I can hardly give any debug output, setting MOJO_USERAGENT_DEBUG over
````
my $tx = Mojo::UserAgent->new()->get('https://kraih:mojo@httpbin.org/basic-auth/kraih/mojo');
````
 only gives:
````
-- Blocking request (https://kraih:mojo@httpbin.org/basic-auth/kraih/mojo)
-- Connect 626b1a75d946faeddd6bd750671a8845 (https://httpbin.org:443)
````
with no luck.
Although, it generates correct Authorization header (same as Chrome does).
And Mojo works over http ceteris paribus.

Thank you in advance!

**Comment by zoffixznet** [comment]
Do you have `IO::Socket::SSL` 1.94+  installed?

Here's what I get when I run this on a box that doesn't. Note the error message in the dump.


perl -MMojo::UserAgent -MData::Dumper -wlE 'say Dumper(Mojo::UserAgent->new()->get(q{https://kraih:mojo@httpbin.org/basic-auth/kraih/mojo})->res);'

`
$VAR1 = bless( {
                 'events' => {},
                 'content' => bless( {
                                       'headers' => bless( {
                                                             'headers' => {}
                                                           }, 'Mojo::Headers' ),
                                       'events' => {
                                                     'read' => [
                                                                 sub { "DUMMY" }
                                                               ]
                                                   },
                                       'read' => $VAR1->{'content'}{'events'}{'read'}[0]
                                     }, 'Mojo::Content::Single' ),
                 'error' => {
                              'message' => 'IO::Socket::SSL 1.94+ required for TLS support'
                            },
                 'finished' => 2,
                 'state' => 'finished'
               }, 'Mojo::Message::Response' );
`

**Comment by jzawodn** [comment]
Also, try running with the env var MOJO_USERAGENT_DEBUG=1 and see if any clues appear.

**Comment by grinya007** [comment]
Thank you guys, IO::Socket::SSL made the magic happen =)
I believe it is still a minor issue that this unmet dependency is not warned out itself.
Not a big problem while having such a quick and thoughtful support =)
Have a nice day!

**Comment by zoffixznet** [comment]
That's an optional module :smile:  And the error message informs of the module missing :smile: 

Not a problem. Feel free to visit our [mailing list](http://groups.google.com/group/mojolicious) or join our IRC channel [`#mojo` on irc.perl.org](irc://irc.perl.org/#mojo)
