### ISSUE TITLE
"perl -0" Changes -Mojo "x()" HTML-Escaping Behavior

### ISSUE THREAD

**Issue by DabeDotCom** [kraih/mojo#849]
I ran into the following:

```
echo "&amp;" | perl -Mojo -E 'print x(<>)'
&amp;       # OKAY

echo "&amp;" | perl -0777 -Mojo -E 'print x(<>)'
&amp;amp;   # ?!?
```

But it doesn't just happend when reading from STDIN:

```
perl -Mojo -E 'say x("&amp;")'
&amp;       # OKAY

perl -0 -Mojo -E 'say x("&amp;")'
&amp;amp;   # ?!?
```

And html_unescape() doesn't seem to help:

```
perl -Mojo -E 'say b(x("&amp;"))->html_unescape'
&           # OKAY

perl -0 -Mojo -E 'say b(x("&amp;"))->html_unescape'
perl -0 -Mojo -E 'say Mojo::Util::html_unescape x("&amp;")'
&amp;amp;   # ?!?!!

perl -0777 -Mojo -E 'say b(x("&amp;"))->html_unescape'
perl -0777 -Mojo -E 'say Mojo::Util::html_unescape x("&amp;")'
&amp;amp;   # ?!?!!
```

I **CAN** work around it by using "local $/" in the body of my script, but that feels clunky:

```
printf "&gt;\n\n&lt;\n" | perl -Mojo -E 'local $/; print x(<>)'
&gt;

&lt;
```

At any rate, it seems to happen even under the latest releases of Mojolicious and Perl:

```
perl -Mojo -E 'say "Perl $^V; Mojolicious $Mojolicious::VERSION"'
Perl v5.22.0; Mojolicious 6.22
```

**Comment by kraih** [comment]
Is this a bug report? Could you please elaborate on what exactly the bug is?

**Comment by kraih** [comment]
Should be addressed with https://github.com/kraih/mojo/commit/eaf239fe32c2b15627a6b4d7abd31a414b10c4f1.

**Comment by DabeDotCom** [comment]
Looks good, thanks!!

(PS — I love it when the fix takes less time than it took to actually write up the problem, hehe!)
