### ISSUE TITLE
Mojo::DOM Broken Behaviour When Selector Ends With Whitespace

### ISSUE THREAD

**Issue by zoffixznet** [kraih/mojo#855]
## Problem

When selector provided to methods like `->at` or `->find` contains whitespace at the end of it, [Mojo::DOM](https://metacpan.org/pod/Mojo::DOM) gives incorrect results.

## Steps to reproduce

Run this code:

```bash
perl -MMojo::DOM -wlE 'my $d = Mojo::DOM->new("<a class=c e=f>d</a>"); say eval{$d->at($_)->all_text} || $@ for ".c ", "[e=f] "'
```
#### Expected Results

Output is
```bash
d
d
```
#### Current Results

Output is
```bash
Can't call method "all_text" on an undefined value at -e line 1, <DATA> line 2231.

Can't call method "all_text" on an undefined value at -e line 1, <DATA> line 2231.

```

## Misc

I originally tried to fix this by sticking `(\s*$)?` at [the end of `$ATTR_RE`](https://metacpan.org/source/SRI/Mojolicious-6.24/lib/Mojo/DOM/CSS.pm#L15), but then I noticed class selectors also have this issue and I decided to leave this for better minds to fix.

Here're the currently-failing tests I was using:
```perl
$dom = Mojo::DOM->new(<<EOF);
<parent class=value1>
  parent <child attr=value2>child</child>
</parent>
EOF
is $dom->at('.value1 ')->text, 'parent', 'right text';
is $dom->at('[class=value1] ')->text, 'parent', 'right text';
is $dom->at('[class=value1] [attr=value2] ')->text, 'child', 'right text';
```

And if anyone's wondering how I found the bug... it's through line alignment OCD :smile_cat: :
```perl
    $t->get_ok('/')->status_is(200)
        ->element_exists('#upload_form                ')
        ->element_exists('#upload_form [type="file"]  ')
        ->element_exists('#upload_form [type="submit"]')
```

## Versions
```bash
zoffix@:/tmp$ perl -MMojolicious -E 'say Mojolicious->VERSION'
6.24
zoffix@:/tmp$ perl -v

This is perl 5, version 22, subversion 0 (v5.22.0) built for i686-linux
(with 1 registered patch, see perl -V for more detail)
```

**Comment by kraih** [comment]
I could swear we've talked about this before, and decided that it's too hard to fix.

**Comment by zoffixznet** [comment]
Ah, then I'll close this. I can't think of any real usecase for this; and if one shows up, the user can just `s/\s+$//` on their selectors :)

**Comment by jberger** [comment]
is it not sufficient to change [this line](https://github.com/kraih/mojo/blob/master/lib/Mojo/DOM/CSS.pm#L75) to:

`my $css = Mojo::Util::trim "$_[0]";`

**Comment by kraih** [comment]
Wasn't there problems with new CSS4 selectors last time?

**Comment by jberger** [comment]
I only remember problems with trailing strings with `begin

**Comment by kraih** [comment]
If there's no problem with the spec, i guess i'd be fine with using `trim`.

**Comment by kraih** [comment]
Trying it now. https://github.com/kraih/mojo/commit/dca86b86b68b608751a141f32f8759b183915626

**Comment by nicomen** [comment]
I had a similar request but I think it was with whitespace in front of selector: http://irclog.perlgeek.de/mojo/2015-06-07#i_10712871 - forgot about going further making speed tests
