### ISSUE TITLE
Mojo::JSON Boolean compability

### ISSUE THREAD

**Issue by cziebuhr** [kraih/mojo#857]
Mojo::JSON::_Bool has recently been replaced with JSON::PP::Boolean. I suggest to use JSON::true and JSON::false instead and check for boolean values with JSON::is_bool. It improves compability with JSON, which can have JSON::PP or JSON::XS as backend.
I'm currently struggling with encoding errors when I try to re-encode data with JSON::XS which has previously been decoded by Mojo::JSON (and vice versa).

**Comment by zoffixznet** [comment]
Would you be able to provide a testcase that demonstrates the problem?

I can't reproduce this on my box:
```bash
$ perl -MMojo::JSON=j -MJSON::XS=encode_json -wlE 'say encode_json j "[false, true]"'
[false,true]
```

**Comment by cziebuhr** [comment]
Does it work the other way around? I'm using an older version of JSON::XS, but I've just seen that in version 3.0 the class Types::Serialiser::Boolean is used which is an alias for JSON::PP::Boolean. Previously they used JSON::XS::Boolean.

**Comment by kraih** [comment]
Use of `JSON::XS` is discouraged actually, we recommend `Cpanel::JSON::XS` and `Mojo::JSON::MaybeXS`.

**Comment by kraih** [comment]
One more thing, we've specifically chosen `JSON::PP::Boolean` because it ships with core Perl, in the hopes that other serializers will standardize on it as well, since it is as close to a core boolean type as we can get with Perl.

**Comment by zoffixznet** [comment]
> Does it work the other way around? 
Yes.

> I'm using an older version of JSON::XS
Confirming the problem exists with an outdated `JSON::XS`, but that's solved by simply upgrading it to the latest version.

As stated above use of `JSON::XS` is discouraged. [Cpanel::JSON::XS](https://metacpan.org/pod/Cpanel::JSON::XS), [Mojo::JSON::MaybeXS](https://metacpan.org/pod/Mojo::JSON::MaybeXS), and [JSON::MaybeXS](https://metacpan.org/pod/JSON::MaybeXS) are all fine alternatives.

**Comment by cziebuhr** [comment]
Unfortunately some Mojo classes uses a stringify overload, which only works with Mojo::JSON. Maybe a TO_JSON method can be added in those classes to also work with Mojo::JSON::MaybeXS.

**Comment by kraih** [comment]
There is already an open issue for `Cpanel::JSON::XS`. :wink: https://github.com/rurban/Cpanel-JSON-XS/issues/37
