### ISSUE TITLE
decode_json for large integers

### ISSUE THREAD

**Issue by cziebuhr** [kraih/mojo#859]
Large integers get decoded as float instead of int.
`Mojo::JSON::decode_json('[123456789012345678]')` returns `[1.23456789012346e+17]` instead of `[123456789012345678]`.

It seems that `$1` is special when used in numeric context:
```
# Number
return 0 + $1
  if /\G([-]?(?:0|[1-9][0-9]*)(?:\.[0-9]*)?(?:[eE][+-]?[0-9]+)?)/gc;
```
It works when replacing this part with:
```
# Number
my ($i) = /\G([-]?(?:0|[1-9][0-9]*)(?:\.[0-9]*)?(?:[eE][+-]?[0-9]+)?)/gc;
return 0 + $i if defined($i);
```

**Comment by zoffixznet** [comment]
I'm confirming the issue, but your fix does not solve it.

However, doing `use bignum` in `Mojo::JSON` makes the number correctly survive the decode/encode roundtrip.

**Comment by Grinnz** [comment]
This is expected, Perl cannot natively represent very large integers. `bignum` has an unacceptable performance impact. For numbers this large they should really be represented as strings to be portable.

**Comment by zoffixznet** [comment]
To add to the discussion: most other JSON modules correctly handle this case. Only JSON::Tiny failed:
```bash
zoffix@:~$ perl -MJSON::PP -wlE 'say encode_json decode_json "[123456789012345678]"'
["123456789012345678"]
zoffix@:~$ perl -MJSON -wlE 'say encode_json decode_json "[123456789012345678]"'
["123456789012345678"]
zoffix@:~$ perl -MJSON::Parse=parse_json -MJSON::Create=create_json -wlE 'say create_json parse_json "[123456789012345678]"'
["123456789012345678"]
zoffix@:~$ perl -MJSON::Meth -wlE 'say "[123456789012345678]"->$j->$j'
["123456789012345678"]
zoffix@:~$ perl -MJSON::MaybeXS -wlE 'say encode_json decode_json "[123456789012345678]"'
["123456789012345678"]
zoffix@:~$ perl -MJSON::PP -wlE 'say encode_json decode_json "[123456789012345678]"'
["123456789012345678"]
zoffix@:~$ perl -MJSON::Parse=parse_json -MJSON::Create=create_json -wlE 'say create_json parse_json "[123456789012345678]"'
["123456789012345678"]
zoffix@:~$ perl -MJSON::Tiny=j -wlE 'say j j "[123456789012345678]"'
[1.23456789012346e+17]
zoffix@:~$ 
```

**Comment by cziebuhr** [comment]
Hmm, it fails on perl 5.14.2, but works in 5.18.2.

**Comment by zoffixznet** [comment]
I'm on Perl 5.22.0, so I'm guessing whatever made it work was removed.

**Comment by cziebuhr** [comment]
Do you have a 32 bit perl?

**Comment by zoffixznet** [comment]
> Do you have a 32 bit perl?

Um, yeah.. And I'm surprised this isn't a 64bit OS as I thought it were :cat: 

```bash
zoffix@:~$ perl -v

This is perl 5, version 22, subversion 0 (v5.22.0) built for i686-linux
(with 1 registered patch, see perl -V for more detail)
zoffix@:~$ uname -a
Linux . 3.2.0-4-686-pae #1 SMP Debian 3.2.51-1 i686 GNU/Linux
```

**Comment by cziebuhr** [comment]
Just found a perl commit which may have solved the issue:
```
commit 7dbe31506f4be3f410f64640daa16b8ad483d61f
Author: Father Chrysostomos <sprout@cpan.org>
Date:   Wed Jun 6 23:05:24 2012 -0700

    pp_negate: Support magic big ints as strings
    
    -$1 was treating $1 as a float even if the string consisted of an
    integer, due to incorrect flag checks.  It was doing the same things
    with tied variables returning str+int dualvars.
```

**Comment by Grinnz** [comment]
This is an initial attempt at solving the problem like the other JSON modules do, but I don't think it's a portable way to determine the max integer size yet.

https://github.com/kraih/mojo/compare/json_large_integer

**Comment by Grinnz** [comment]
This is how JSON::PP determines the max integer size but it looks very inefficient and fragile to me. https://metacpan.org/source/MAKAMAKA/JSON-PP-2.27300/lib/JSON/PP.pm#L582

**Comment by cziebuhr** [comment]
Imho this is even wrong, because it should be tested with '9' instead of '1', but that's not the matter here. I'm fine with having 64bit integers on a 64bit system. Getting to know the max integer size doesn't fix my issue.

**Comment by kraih** [comment]
So, is the conclusion here that there is nothing to be done?

**Comment by Grinnz** [comment]
If anyone can come up with a portable way to determine the size at which perl starts representing integers as floats, then I think it should be fixed as in that branch, to match the other JSON parsers.

**Comment by zoffixznet** [comment]
> So, is the conclusion here that there is nothing to be done?

I would recommend that. In the examples above, I was actually wrong. Even the modules that preserve the digits intact still decode the number as a string rather than the original number, so none of CPAN modules Do The Right Thing in this case anyway.

**Comment by Grinnz** [comment]
I would say that decoding the number as a string is as much "the right thing" as anything, because Perl cannot innately represent integers that large, and using BigInt/bignum is out of the question.

**Comment by zoffixznet** [comment]
I guess what I'm saying is that we may as well leave things as is, since getting an incorrect data type is as much of an error as getting the precision of a number off by 2.6 quadrillionth of a percent :smile_cat:

**Comment by cziebuhr** [comment]
There's still the perl-bug I mentioned above. This has nothing to do with the amount of digits which can be represented as integer. I would be happy if mojo could have a workaround to support older perl versions. If numbers are even larger, they should be returned as string (as done in JSON::PP). I actually had an issue with an external api, where I got a large number which I had do treat "discrete", i.e. it mustn't get converted to float.

**Comment by kraih** [comment]
@cziebuhr I'm afraid only the last two stable release series of Perl are fully supported. http://mojolicio.us/perldoc/Mojolicious/Guides/FAQ#Which-versions-of-Perl-are-supported-by-Mojolicious

**Comment by kraih** [comment]
Looks like this issue went stale, closing it for now.

**Comment by jzawodn** [comment]
Sadly, I ran into this same problem this week...

FWIW:

```
This is perl 5, version 14, subversion 2 (v5.14.2) built for x86_64-linux-nothread-multi-thread
```

Yeah, we're sorta stuck on our OS provided Perl. :-(
