### ISSUE TITLE
hypnothoad threads has no names

### ISSUE THREAD

**Issue by KES777** [kraih/mojo#861]
When I try to use `pstree | grep myapp`
I get empty output
The problem is:
```
init(1)-+-/home/kes/work/(9422)-+-/home/kes/work/(9423)
        |                       |-/home/kes/work/(9424)
        |                       |-/home/kes/work/(9425)
        |                       `-/home/kes/work/(9426)
```

But:

```
$ ps ax|grep myapp
 9422 ?        Ss     0:00 /home/kes/work/www/mojo/data/myapp.pl
 9423 ?        S      0:00 /home/kes/work/www/mojo/data/myapp.pl
 9424 ?        S      0:00 /home/kes/work/www/mojo/data/myapp.pl
 9425 ?        S      0:00 /home/kes/work/www/mojo/data/myapp.pl
 9426 ?        S      0:00 /home/kes/work/www/mojo/data/myapp.pl
```

**Comment by nicomen** [comment]
Try 

pstree -l

But this bug is not Mojo-related.

**Comment by kraih** [comment]
Thanks @nicomen.

**Comment by KES777** [comment]
```
$ pstree -p -l
init(1)─┬─/home/kes/work/(14793)─┬─/home/kes/work/(14794)
        │                        ├─/home/kes/work/(14795)
        │                        ├─/home/kes/work/(14796)
        │                        └─/home/kes/work/(14797)
```

**Comment by nicomen** [comment]
What kind of pstree is this?

Seems we might be using different versions:

```
$ pstree --version
pstree (PSmisc) 22.21
Copyright (C) 1993-2009 Werner Almesberger and Craig Small
```

**Comment by KES777** [comment]
pstree (PSmisc) 22.20

**Comment by kraih** [comment]
Either way, it doesn't look like a bug in Mojolicious, could you please move the discussion to the mailing-list or IRC?

**Comment by KES777** [comment]
Why not related? Bug in perl?

**Comment by nicomen** [comment]
IRC: irc://irc.perl.org/mojo 

Not related. Because your hypnotoad process childs are there and showing (just match the pid number against ps auxf output). The bug is about pstree truncating (cutting off) long process names, and that's not the fault of perl or mojolicious.

**Comment by KES777** [comment]
do not put absolute path to process name as other processed do
