### ISSUE TITLE
no error message about failed operation

### ISSUE THREAD

**Issue by KES777** [kraih/mojo#862]
When I start my application `MOJO_CONFIG=myapp.conf hypnotoad myapp.pl`
```
[Thu Oct 29 18:44:55 2015] [info] Manager 18916 started
[Thu Oct 29 18:44:55 2015] [info] Creating process id file "/home/kes/work/www/logs/hypnotoad.pid"
```
But there is no '/home/kes/work/www/logs/' path on file system.
```
$ cd /home/kes/work/www/logs/
bash: cd: /home/kes/work/www/logs/: No such file or directory
```

EXPECTED: warn message in log file about that the pid file is not created.

**Comment by kraih** [comment]
I think we would accept a patch for this.
