### ISSUE TITLE
Missed info about configuration

### ISSUE THREAD

**Issue by KES777** [kraih/mojo#863]
The [doc says](http://mojolicio.us/perldoc/Mojolicious/Guides/Cookbook#Hypnotoad)
```
http://mojolicio.us/perldoc/Mojolicious/Guides/Cookbook#Hypnotoad
```
**Or just add a hypnotoad section to your Mojolicious::Plugin::Config or Mojolicious::Plugin::JSONConfig configuration file.**

But anything about that the *application must load `plugin Config`*. If application does not than the hypnotoad will not be configured properly

**Comment by kraih** [comment]
This has also been discussed on IRC, and for now we consider the current wording sufficiently specific.
