### ISSUE TITLE
Mojo::Transaction refactoring

### ISSUE THREAD

**Issue by kraih** [kraih/mojo#876]
To be able to add new protocols like HTTP/2 in the future, we are going to need to refactor `Mojo::Transaction`, `Mojo::Transaction::HTTP` and `Mojo::Transaction::WebSocket` a bit. I've mentioned this before in https://github.com/kraih/mojo/issues/423#issuecomment-10928845, and now it's time to make this a priority.

Specifically, as a first step, i want to see the `client_*` and `server_*` methods from `Mojo::Transaction::HTTP` and `Mojo::Transaction::WebSocket` to be moved to `Mojo::Channel::HTTP::Client`, `Mojo::Channel::HTTP::Server`, `Mojo::Channel::WebSocket::Client` and `Mojo::Channel::WebSocket::Server`.

**Comment by kraih** [comment]
It would be nice if this refactoring task resulted in a little more encapsulation. Right now `Mojo::UserAgent` and `Mojo::Server::Daemon` are dealing directly with the transaction objects a lot.
```
Mojo::UserAgent      -> Mojo::Transaction::HTTP
                     -> Mojo::Transaction::WebSocket

Mojo::Server::Daemon -> Mojo::Transaction::HTTP
                     -> Mojo::Transaction::WebSocket
```
The new channel objects could act more like intermediaries in many cases.
```
Mojo::UserAgent      -> Mojo::Channel::HTTP::Client      -> Mojo::Transaction::HTTP
                     -> Mojo::Channel::WebSocket::Client -> Mojo::Transaction::WebSocket

Mojo::Server::Daemon -> Mojo::Channel::HTTP::Server      -> Mojo::Transaction::HTTP
                     -> Mojo::Channel::WebSocket::Server -> Mojo::Transaction::WebSocket
```
This won't always be possible, since methods like `Mojo::UserAgent::start` actually take a transaction object as argument. But if a proxy method or event emitted by the channel object can do the job too, i think it's the better choice.

**Comment by amenonsen** [comment]
I'm working on the UserAgent now. I'm keeping the interfaces unchanged for now (i.e., accepting or returning Transaction::HTTP objects directly), but operating on them through the channel. It's slow going because I can't focus fully on it for some days, but after the first tranche of changes I'll push my branch and continue to work on it.

**Comment by kraih** [comment]
@amenonsen Sounds good. I think the server will actually be easier to refactor than the user agent.

**Comment by kraih** [comment]
And backwards compatibility is not a big priority here, since the task is significant enough to warrant a major release.

**Comment by kraih** [comment]
We've talked a bit about this on IRC and came up with a very promising approach. There's a data structure (`$self->{connections}`) in `Mojo::Server::Daemon` and `Mojo::UserAgent`, that currently contains a bunch of hashes. Those hashes could be turned into channel objects, and functionality then be moved into methods in small steps.

**Comment by kraih** [comment]
This project is now being led by @jberger, since we've not heard from @amenonsen recently.

**Comment by kraih** [comment]
We've had a very productive hackathon this weekend, and the refactoring is about half-finished now. :tada: https://github.com/kraih/mojo/tree/channels/master

**Comment by jhthorsen** [comment]
sri++, jberger++ :+1:

**Comment by kraih** [comment]
We've stopped with the refactoring work for now, because the performance cost is getting too high, and it makes no sense to sacrifice performance before we actually have the resources to implement HTTP/2 support afterwards.

So, while the `Mojo::Channel` classes have not actually been added yet, all preparations are finished and it would only take a few hours to get done. `Mojo::UserAgent` is mostly HTTP/2 ready, while `Mojo::Server::Daemon` still needs some work to be able to handle concurrent HTTP/2 streams.

**Comment by kraih** [comment]
Closing this issue because we only need #423 for tracking progress from now on.
