### ISSUE TITLE
Unexpected MOJO_MODE value

### ISSUE THREAD

**Issue by prg** [kraih/mojo#878]
I think there might be a bug in the way mojo resolves the value for `mode`. At least this caught me by surprise, steps to reproduce:
```
$ mojo generate app TestApp && cd test_app

$ env | grep MOJO_MODE
MOJO_MODE=production

$ cat > init << EOF
> #!/bin/bash
> export MOJO_MODE="development"
> hypnotoad script/test_app
> EOF

$ chmod u+x init

$ ./init
```

When using `mode`, for example like this in `lib/TestApp/Example.pm`...
```
-  $self->render(msg => 'Welcome to the Mojolicious real-time web framework!');
+  #$self->render(msg => 'Welcome to the Mojolicious real-time web framework!');
+  $self->render(msg => $self->app->mode);
```
... I'd expect its value to be "development" instead of "production":

```
$ perl -Mojo -E 'say g("localhost:8080")->dom("h2")'
<h2>production</h2>
```

 In fact, when looking at the value of `mode` or `$ENV{MOJO_MODE}` during startup, it's "development" as expected:

`script/test_app`:
```
-BEGIN { unshift @INC, "$FindBin::Bin/../lib" }
+BEGIN {
+    unshift @INC, "$FindBin::Bin/../lib";
+    print "$ENV{MOJO_MODE}\n";
+}
```

`lib/TestApp.pm`:
```
   # Normal route to controller
   $r->get('/')->to('example#welcome');
+
+  say $self->mode;
 }
```

```
$ ./init
development
development
```

**Comment by niczero** [comment]
Hi prg,
It's looks like you're misunderstanding what 'export' should do.  Everything here looks correct.
The script runs in its own shell, and the export affects that shell and all child shells.
But where you run 'env', you're back in the parent shell, and so unaffected by the 'export'.
Hope that clarifies there's no bug, just mistaken expectation,
Nic

**Comment by prg** [comment]
I think you're misunderstanding. As you said, I'd expect all child processes to have the value from that script but that's not the case. Edited initial post for clarification.

**Comment by kraih** [comment]
Whatever happens here, i think we can conclude that it is not something Mojolicious does, but unexpected behaviour of the shell.

**Comment by jhthorsen** [comment]
@prg: Could it be that you try to change MOJO_MODE _after_ hypnotoad started the first time? It's not possible to "inject" environment into a running process. The way "hot reloading" works is simply by sending a USR2 signal to the running server. This means that the second call you do to hypnotoad does not start anything, and therefor unable to "send" any environment variables to the already started server.

**Comment by prg** [comment]
@jhthorsen: I don't think so. As you can see in my example above, `MOJO_MODE` is set to `production` in the shell, but changed to `development` in the shell script that starts hypnotoad. When calling that shell script repeatedly "hot reloading" kicks in, but the value is never changed in the shell script.

**Comment by prg** [comment]
@jhthorsen: you might be on the right track here:
```
$ hypnotoad -s script/test_app
Hypnotoad server not running.

$ perl -Mojo -E 'say g("localhost:8080")->dom("h2")'
<h2>production</h2>
```

Why didn't hypnotoad stop in this case?

**Comment by kraih** [comment]
Looks like this topic might belong on the mailing-list. http://mojolicio.us/perldoc#SUPPORT

**Comment by prg** [comment]
@kraih: you're right, I digress. Just in case someone stumbles over this in the future:

Everything working as expected, hypnotoad just wasn't properly stopped (which might or might not be a problem of its own):
```
$ ps ax | grep test_app
14540 pts/1    S+     0:00 grep test_app

$ env | grep MOJO_MODE
MOJO_MODE=foobar

$ ./init
development
development

$ perl -Mojo -E 'say g("localhost:8080")->dom("h2")'
<h2>development</h2>
```

**Comment by kraih** [comment]
That should result in an error message now. https://github.com/kraih/mojo/commit/350c563602c99ebe1e35c6817f4d63bf5b1fa375
