### ISSUE TITLE
it seems there is a bug when handle connect request

### ISSUE THREAD

**Issue by secyunshu** [kraih/mojo#879]
hey,

as you know,  connect method let web server to create a tcp channel to remote server. then, web server forward any next packets. 

but mojo::server::daemon think ssl handshake packets are new request, handle them using request callback, that's not the right way. I try to set a tag via remote_host and remote_port , and forward the packets with my tag. but mojo::message say it's "Bad request start-line", I can not forward the raw packets. could you help me? should i use mojo::ioloop ?

    #!/usr/bin/perl
    use strict;
    use warnings;
    use Bloom::Filter;
    use Mojo::IOLoop;
    use Mojo::UserAgent;
    use Mojo::Server::Daemon;
    use Mojo::Message::Response;
    use Data::Dumper;

    #my $bloom_filter = Bloom::Filter->new( error_rate => 0.001, capacity => 100000 );
    my $ua = Mojo::UserAgent->new;
    my $daemon = Mojo::Server::Daemon->new(	listen => ['http://*:3128'])->unsubscribe('request');
    
    my %buffer;

    $daemon->on(request => sub {
	    my ($daemon, $client_tx) = @_;

	    print $client_tx->connection,"\n";
	    print Dumper(\%buffer);

	    if( exists $buffer{$client_tx->original_remote_address.':'.$client_tx->remote_port} ){
	    	    print "got ssl data:\n";
		    print Dumper($client_tx->req);
		    Mojo::IOLoop->stream($buffer{$client_tx->connection}{connection})->write($client_tx->req->to_string);
		    return;
	    }
	
	    if( $client_tx->req->method eq 'CONNECT' ) {
		    &handle_connect( $daemon, $client_tx );
		    return;
	    }

	    $ua->start(Mojo::Transaction::HTTP->new(req => $client_tx->req) => sub {
		    print "here\n";
		    my ($ua, $proxy_tx) = @_;
		    my $response = $proxy_tx->res;

		    $client_tx->res($response)->resume;
	
		    my $url = $proxy_tx->req->url->to_string;
		    if( $url =~ /jsonp|callback/ || defined($response->headers->content_type) && $response->headers->content_type =~ /json/) {
			    my $json = $response->text;
			    #if( ! $bloom_filter->check($url.$json) ) {
			    #	$bloom_filter->add($url.$json);
				    print "$url\n$json\n\n";
			    #}
		    }
	    });
    });

    $daemon->run;

    sub handle_connect {
	    my ($daemon, $client_tx) = @_;
	    my $host = $client_tx->req->url->host;
	    my $port = $client_tx->req->url->port;

 
	    my $client_stream = Mojo::IOLoop->stream($client_tx->connection);
	    $client_stream->on(read=>sub{
		    my($stream, $chunk) = @_;

		    # we got ssl data, just forward it to the real server.
		    my $server = $buffer{$client_tx->connection}{connection};
		    if( $chunk !~ /^CONNECT/ ){
			    Mojo::IOLoop->stream($server)->write($chunk);
			    return;
		    }

		    print $chunk;
		    # we got a "connect" request, try to create a channel.
		    $buffer{$client_tx->connection}{connection} = Mojo::IOLoop->client({address=> $host, port=>$port}=>sub {
			    $buffer{$client_tx->original_remote_address.':'.$client_tx->remote_port}=1;
			    my ($loop, $err, $stream) = @_;
			    if($err) {
				    my $res = Mojo::Message::Response->new;
				    $res->code(500);
				    $client_tx->res($res)->resume;
				
				    $client_tx->server_close();
				    Mojo::IOLoop->remove($client_tx->connection);
				    return delete $buffer{$client_tx->connection};
			    }

			    my $res = Mojo::Message::Response->new;
			    $res->code(200);
			    $res->headers->connection("keep-alive");
			    $client_tx->res($res)->resume;

			    $stream->on(read=>sub{
				    my ($stream, $chunk) = @_;
				    $client_stream->write($chunk);
			    });
		    });
	    });
    }

**Comment by kraih** [comment]
I'm afraid nothing you describe here is a bug, `Mojo::Server::Daemon` is an HTTP and WebSocket server, nothing more. You might be interested in #876 though, which could allow new protocols to be added.
