### ISSUE TITLE
Mojolicious::Controller timing code affected by locale setting

### ISSUE THREAD

**Issue by mbudde** [kraih/mojo#880]
If the locale is set to a value where numbers are formatted with comma, [a comparison in Mojolicious::Controller::rendered](https://github.com/kraih/mojo/blob/v6.35/lib/Mojolicious/Controller.pm#L208) gives an "argument isn't numeric" warning.

I can reproduce with the following app (with Perl 5.16.3):

``` perl
#!/usr/bin/env perl
use Mojolicious::Lite;
use locale;
use POSIX;

setlocale(LC_ALL, 'da_DK.utf8');

get '/' => sub {
  my $c = shift;
  $c->render(text => 'Hello world');
};

app->start;
```

**Comment by zoffixznet** [comment]
How to reproduce this warning? I tried running your app with both 5.22 and 5.14 using morbo and then reloading it multiple times in the browser... I'm not seeing any warnings.

**Comment by mbudde** [comment]
I start the app with `MOJO_LOG_LEVEL=debug perl myapp.pl daemon` and the make a request. The warning should then be visible in the console output.

**Comment by zoffixznet** [comment]
Still nothing. I tried on Debian + `perl-5.14.4` + Mojolicious version 6.35,  Debian + `perl-5.22.0` + Mojolicious version 6.33, and Windows 7 + Strawberry Perl 5.20.2 + Mojolicious version 5.81.

I'm also unsure how the line you linked to could be causing the warning. `$elapsed` is created with `sprintf '%f'` on the line above. I can make `sprintf` generate a warning, but not when its result is used in comparison:
```bash
$ perl -wlE 'use locale; use POSIX; setlocale(LC_ALL, 'da_DK.utf8'); my $s = sprintf "%f", 0+"2,2"; say $s > 2,33,3,3'
Argument "2,2" isn't numeric in addition (+) at -e line 1.
3333
```

Anyone else can reproduce?
@mbudde what are your OS, perl version, Mojolicious version?

**Comment by mbudde** [comment]
This gives a warning for me:
```
$ LC_ALL=da_DK.utf8 perl -E 'use warnings; use locale; use POSIX; setlocale(LC_ALL, "da_DK.utf8"); my $v = sprintf("%f", 0.001241); if ($v == 0) { };'
Argument "0,001241" isn't numeric in numeric eq (==) at -e line 1.
```
but if I remove `LC_ALL=da_DK.utf8` the warning disappears.

**Comment by kraih** [comment]
I can't replicate the problem either.

**Comment by mbudde** [comment]
I can replicate the problem on a brand new Ubuntu 14.04 EC2 instance with Perl 5.18, but not on Ubuntu 15.10 with 5.20, so I guess it is a bug in Perl that has been fixed in newer versions.

Here's how I set up the instance:
```console
$ sudo aptitude update
$ sudo aptitude install language-pack-da build-essential liblocal-lib-perl
$ sudo cpan install Mojolicious::Lite
$ vim myapp.pl # Paste program posted in this issue
$ perl myapp.pl daemon &
[Tue Dec  8 10:38:10 2015] [info] Listening at "http://*:3000"
Server available at http://127.0.0.1:3000
$ curl localhost:3000
[Tue Dec  8 10:38:18 2015] [debug] GET "/"
[Tue Dec  8 10:38:18 2015] [debug] Routing to a callback
Argument "0,000677" isn't numeric in numeric eq (==) at /usr/local/share/perl/5.18.2/Mojolicious/Controller.pm line 208.
[Tue Dec  8 10:38:18 2015] [debug] 200 OK (0,000677s, ??/s)
Hello world

**Comment by zoffixznet** [comment]
Tried it with 5.20 on Debian Wheezy and not getting anything. My sugestion would be you use [perlbrew](http://perlbrew.pl/) to build perl instead of using system one. The bug you mention might've been introduced by the vendor (that happened twice already).

**Comment by kraih** [comment]
Also, we only fully support Perl 5.20 and 5.22. So, i'm afraid a warning on older versions wouldn't be reason enough to add a workaround. http://mojolicio.us/perldoc/Mojolicious/Guides/FAQ#Which-versions-of-Perl-are-supported-by-Mojolicious

**Comment by s1037989** [comment]
```
$ cat /tmp/myapp.pl 
#!/usr/bin/env perl
use Mojolicious::Lite;
use locale;
use POSIX;
use Linux::Distribution qw(distribution_name distribution_version);

setlocale(LC_ALL, 'da_DK.utf8');

get '/' => sub {
  my $c = shift;
  $c->render(text => 'Hello world');
};

warn sprintf "Distro: %s %s\nPerl: %s\nMojolicious: %s\n",
  distribution_name, distribution_version, $], $Mojolicious::VERSION;
app->start;
```

```
$ perl /tmp/myapp.pl get /
Distro: ubuntu 14.04
Perl: 5.020001
Mojolicious: 6.35
[Tue Dec  8 08:54:22 2015] [debug] GET "/"
[Tue Dec  8 08:54:22 2015] [debug] Routing to a callback
[Tue Dec  8 08:54:22 2015] [debug] 200 OK (0.000522s, 1915.709/s)
Hello world

$ /usr/bin/perl /tmp/myapp.pl get /
Distro: ubuntu 14.04
Perl: 5.018002
Mojolicious: 6.35
[Tue Dec  8 08:54:36 2015] [debug] GET "/"
[Tue Dec  8 08:54:36 2015] [debug] Routing to a callback
[Tue Dec  8 08:54:36 2015] [debug] 200 OK (0.000543s, 1841.621/s)
Hello world
```

**Comment by mbudde** [comment]
@s1037989, are you sure you have the `da_DK.utf8` locale installed? I suspect not, because then it should show the timing info with commas instead of full stops.

To be clear, the code I posted will only give a warning if the `da_DK.utf8` locale is available (`da_DK` can be replace with any other locale that uses comma for the decimal point).

But anyway, I don't think we need to spend more time on this bug. I will consider the case closed at least :)

**Comment by s1037989** [comment]
@mbudde Haha!  Doh!  There ya have it.

```
$ perl /tmp/myapp.pl get /
Distro: ubuntu 14.04
Perl: 5.020001
Mojolicious: 6.35
[Tue Dec  8 09:55:18 2015] [debug] GET "/"
[Tue Dec  8 09:55:18 2015] [debug] Routing to a callback
[Tue Dec  8 09:55:18 2015] [debug] 200 OK (0.000506s, 1976.285/s)
Hello world

$ /usr/bin/perl /tmp/myapp.pl get /
Distro: ubuntu 14.04
Perl: 5.018002
Mojolicious: 6.35
[Tue Dec  8 09:55:42 2015] [debug] GET "/"
[Tue Dec  8 09:55:42 2015] [debug] Routing to a callback
Argument "0,000491" isn't numeric in numeric eq (==) at /home/stefan/perl5/lib/perl5/Mojolicious/Controller.pm line 208.
[Tue Dec  8 09:55:42 2015] [debug] 200 OK (0,000491s, ??/s)
Hello world
```
