### ISSUE TITLE
Disable auto format detection, when format is already in route

### ISSUE THREAD

**Issue by kak-tus** [kraih/mojo#881]
Hello, i found inconvenient behavior in route detection, where format is already in route.

```
$r->get('/index.html')
```

routes with format autodetection to this paths

```
/index.html
/index.html.html
/index.html.txt
...
```

It can be fixed with

```
$r->get('/index.html', [ format => 0 ])
```

or

```
$r->get('/index', [ format => [qw(html)] ])
```

But it is not convenient and may be it is a good idea, to disable format auto detection, when one of the Mojolicious::Types extension is in route?

**Comment by kraih** [comment]
This topic has been discussed many many times before, i don't think it makes much sense to try again without having a very well thought out proposal first.
