### ISSUE TITLE
UNIX domain socket support

### ISSUE THREAD

**Issue by kraih** [kraih/mojo#883]
This keeps coming up every now and then, and members of the core team have voiced interest in working on this. For `Mojo::Server::Daemon` a listen location like `listen => ['unix:///foo/bar.sock']` should be relatively easy to get working, but there have been no actual proposals for a `Mojo::UserAgent` API yet.

**Comment by kraih** [comment]
This feature might depend on #876.

**Comment by acamari** [comment]
I'd like to work on this, at least the Mojo::Server::Daemon part... where do we discuss more of this?

**Comment by kraih** [comment]
@acamari Most discussions happen on IRC (#mojo on irc.perl.org), but the feature can be discussed here too.

**Comment by kraih** [comment]
Maybe support in `Mojo::UserAgent` is not necessary, but testing would get harder then. I expect portable tests to be the biggest obstacle for getting this feature ready.

**Comment by kraih** [comment]
There does not appear to be much interest in this feature anymore, maybe we should consider giving it a a :-1:.

**Comment by s1037989** [comment]
What is the value to listening on a UNIX domain socket?  Example use case?

**Comment by kraih** [comment]
Personally, i don't think there are too many good use cases, so i'll just give the feature a :-1: vote.

**Comment by jzawodn** [comment]
My understanding is that you may see a marginal performance increase. But that's about it. There's also a security feature in that you can apply filesystem permissions to the socket, which can't be done on a normal TCP socket.

But, yeah, agreed. Not really important...

**Comment by ldidry** [comment]
I'll give the feature a :+1: vote: it allows to not worry about which port is available.

**Comment by kraih** [comment]
Looks like @jhthorsen wants to take the lead on this project, so i'll change my vote to neutral for now.

**Comment by wttw** [comment]
Most of the potential use cases I can think of would only benefit marginally from using unix sockets rather than local tcp sockets, and they'd almost all require writing client code as well as server code.

So :-1: on support just in Mojo::Server::Daemon, neutral on support in both Mojo::Server::Daemon and Mojo::UserAgent.

**Comment by jhthorsen** [comment]
I can't remember why I wanted this after coming back from vacations. I don't want to implement it just for the sake of the functionality: There must be a good use case.

:-1: from me as well.

**Comment by kraih** [comment]
Allright, without @jhthorsen to implement this, i don't think it makes sense to keep this issue open.

**Comment by CodingMinds** [comment]
Based on https://github.com/jhthorsen/mojo-redis2/issues/14 I've a use case for UNIX sockets.
We have to host our Mojo application on an openVZ container which has a hard numtcpsock limit of 700. In combination with websockets, Mojo::Redis2 and some hypnotaod workers it's easy to reach those 700 open TCP sockets.
If we could use a UNIX socket to connect the Apache with our Mojo application it would be a first aid to reduce the socket count. And of course it would be better if we could also use UNIX sockets to connect to redis.

I know it's a OS / infrastructure problem and not a Mojo problem but it's a use case for UNIX sockets
