### ISSUE TITLE
WebSocket subprotocol negotiation

### ISSUE THREAD

**Issue by kraih** [kraih/mojo#886]
The `websocket` method in `Mojo::UserAgent` already supports a list of subprotocols, but we do not have an API for negotiating a subprotocol on the server-side yet. It could work something like this.
```
websocket '/whatever' => sub {
  my $c = shift;
  $c->tx->with_protocols('v1.proto', 'v2.proto');
  my $proto = $c->tx->selected_protocol;
  ...
};
```

**Comment by kraih** [comment]
I don't think we should be doing this before #876 is finished.

**Comment by kraih** [comment]
The `with_protocols` method would be consistent with the `with_compression` method for negotiating the `permessage-deflate` extension.

**Comment by jberger** [comment]
Note that I was able to hack around this using the following:

```perl
$app->hook(after_build_tx => sub {                                                         
  my ($tx, $app) = @_;                                                                     
  $tx->on(upgrade => sub { shift->res->headers->sec_websocket_protocol('binary') });       
});
```

where I'm always choosing the "binary" protocol of the novnc websocket agent.

**Comment by kraih** [comment]
And implemented. https://github.com/kraih/mojo/commit/1dfaf12f78b20b255a35b83c5bb88a78aba6af2c
