### ISSUE TITLE
ALPN

### ISSUE THREAD

**Issue by kraih** [kraih/mojo#888]
It looks like HTTP/2 will always require TLS, for backwards compatibility with web servers that can't handle `Upgrade: h2c` headers correctly, so we are going to need ALPN support in `Mojo::IOLoop::Client` and `Mojo::IOLoop::Server`. `IO::Socket::SSL` already has a pretty decent API, so it shouldn't be too hard.

**Comment by vlet** [comment]
Please review this branch https://github.com/vlet/mojo/tree/vlet/alpn2
I've moved some common code to Mojo::TLS and also add NPN fallback if ALPN is not available

**Comment by kraih** [comment]
@vlet Can't say i'm a fan of `Mojo::TLS`, but it's hard to form an opinion as long as tests and documentation are missing.

**Comment by kraih** [comment]
@vlet In fact, i think it might be better to split up the branch, and make the `Mojo::TLS` part a separate pull request.

**Comment by kraih** [comment]
Don't think we'll ever need NPN, it is already on the way out in all major browsers.

**Comment by vlet** [comment]
NPN support available in openssl 1.0.1 (since 2012), APLN support available in openssl 1.0.2 (jan 2015). There is no major stable linux distributions released with openssl 1.0.2 yet (except recent fedora). Lack of NPN support will make http2 protocol feature totally not available for current stable linux distros.

**Comment by kraih** [comment]
@vlet  HTTP/2 support is such a long term goal, i doubt it will matter by then.

**Comment by kraih** [comment]
This feature now exists in a branch and could be merged into master. https://github.com/kraih/mojo/tree/alpn

**Comment by kraih** [comment]
Closing this issue because we only need #423 for tracking progress from now on.
