### ISSUE TITLE
WebSocket multiplexing support

### ISSUE THREAD

**Issue by kraih** [kraih/mojo#891]
Imagine you have two things on your website that need to be updated in real-time over WebSockets. Like a chat window on the left, and a stock ticker on the right. You could just open two WebSocket connections, but that would be rather wasteful. Or you could design your own WebSocket subprotocol to send both types of information over the same connection, but that's not much fun at all, especially if you have to do it over and over for each new application.

Instead we could just bundle a JavaScript library with Mojolicious that deals with WebSocket messages on a higher level. Like a common pub/sub system perhaps, with named topics you can subscribe to, automatically JSON serialized payloads, heartbeats and reconnect. And i imagine on the server-side it might be fun to get the router involved, connecting topics to controllers and/or actions.

This is a bit of a research project, and there are no concrete plans right now, but maybe we can come up with something together!

**Comment by kraih** [comment]
One big problem that comes to mind, how do you integrate your actual pub/sub system into this? Depending on a specific database, like Redis or PostgreSQL, wouldn't be very Mojolicious.

**Comment by akarelas** [comment]
Let's not forget that MQs like RabbitMQ can also play the role of a pub/sub system. And an even better one, since it doesn't lose messages when the perl server gets briefly disconnected.

**Comment by kraih** [comment]
I guess this might not fit into Mojolicious core after all, since we don't want to ship any kind of database bindings.

**Comment by s1037989** [comment]
I'd love to see this get included!  I understand the fit problem and will understand if it just can't be made to work, but I'd love to see it happen!  Specifically because any extra features that make development faster, easier, and funner are ideal!

Maybe an offshoot, just as was done with Minion??

Or, would this function perfectly well as just a plain ol' M::Plugin?

**Comment by kraih** [comment]
Yes, this might be better off in a plugin, so i'm giving the feature a :-1: vote.

**Comment by s1037989** [comment]
Where would be a good place to keep track of wishlist plugins?  It might be great for the community to be able to get together on this.  It also might be great to have a kind of Mojolicious-specific CPAN-type thing where we can have a blossoming ecosystem of plugins, usage, scenarios, etc...

**Comment by jhthorsen** [comment]
Mojolicious::Plugin::Swagger2 and the new "batcode" branch in Convos ships with something that might be sort of this functionality. The links below should link to the important parts:

https://github.com/jhthorsen/swagger2/blob/master/lib/Swagger2/Guides/WebSocket.pod
https://github.com/jhthorsen/swagger2/blob/master/lib/Mojolicious/Plugin/Swagger2.pm#L124
https://github.com/Nordaaker/convos/blob/batcode/assets/js/swagger2-client.js

Please take any comments to #swagger on irc.perl.org or drop me an email if you have comments/questions specific to the implementation above.

**Comment by brianmed** [comment]
Also, I have some javascript 'n perl that might be useful:

https://github.com/brianmed/notify/blob/master/templates/index/slash.html.ep#L19-L77

https://github.com/brianmed/notify/blob/master/lib/Mojolicious/Plugin/Notify.pm

Fairly rough around the edges, a bit naive, and some naming doesn't work well; however, seems to be functional.

**Comment by kraih** [comment]
Looks like we have reached consensus that this should be implemented as a plugin on CPAN.
