### ISSUE TITLE
Config plugin's use of decamelize inconsistent with Generate::app command's use of class_to_file

### ISSUE THREAD

**Issue by dotandimet** [kraih/mojo#892]
When generating a new app with mojo generate, we require a proper CamelCase class name and use class_to_file to name the project directory.

However, the Config plugin uses decamelize on the app class name to determine the name of its config file.

This causes an inconsistency that will surprise developers who choose to use acronyms in their class names - for example XML, CI, etc.

**Comment by zoffixznet** [comment]
The trouble is it needs to be reversable back into the CamelCase. To implement what you're proposing would lose some of the information. For example, consider `CamelCaseXMLParser`. If you convert it to `camel_case_xmlparser`, there's no way to know how to capitalize the `xmlparser` portion back into camel case.

**Comment by jberger** [comment]
I tried just for fun and this line nicely does the decamelization as I would like

    join('_', map {lc} grep {length} split /([A-Z]+(?![^A-Z])|[A-Z]{1}[^A-Z]*)/

where `XMLParser` becomes `xml_parser. And yet @zoffixznet is correct, it doesn't round trip. The camelization of `xml_parser` is `XmlParser`.

**Comment by jberger** [comment]
But now reading @dotandimet 's original statement again I see what he means. The actual algorithm for going from the name of class to the name of a file is different. That said I'm not sure what to do about it. The config plugin works from the moniker which is not necessarily a class name. For a lite app its the name of the file and of course you can set a different moniker.

**Comment by jhthorsen** [comment]
I don't see how this is fixable. Do you have a suggestion @dotandimet ?

Also when I say "fixable": I don't see why it needs fixing. Just use https://metacpan.org/pod/Mojolicious::Plugin::Config#file if you want a "pretty" config file name.

**Comment by kraih** [comment]
Looks like the discussion is over.
