### ISSUE TITLE
Mojolicious 6.36 is_websocket error

### ISSUE THREAD

**Issue by teo-binary** [kraih/mojo#893]
There is a lot of such error generated when using websocket in Mojolicious 6.36

EventLoop error: I/O watcher failed: Can't call method "is_websocket" on an undefined value at /home/repo/cpan/local/lib/perl5/Mojolicious/Controller.pm line 252.

Is this a known issue?

**Comment by zoffixznet** [comment]
No. Would you, please, provide a testcase app that reproduces the issue, so we could debug?

**Comment by jberger** [comment]
This usually is indicative that you didn't keep a strong reference to the transaction while doing asynchronous programming. If the transaction goes out of scope (and doesn't have any strong references) by the time you get the callback your transaction would then be `undef`. I'm going to close this as a matter of housekeeping, if you need more assistance please try the mailing list or irc and preferably attach a minimal example. If there is a true bug, please make a test case and reopen.
