### ISSUE TITLE
Use FindBin in generators and documentation again

### ISSUE THREAD

**Issue by kraih** [kraih/mojo#896]
Back in 2014 we made a change (https://github.com/kraih/mojo/commit/2ccaefe4c0b44c4324fa322fffea454c46cd8512), since then most of the application scripts we generate and show in the documentation contain `use lib`, which causes problems for our users every now and then. While we want to keep the `#!perl` shebang, it might be nice to switch back to something `FindBin` based instead of `use lib`. The documentation has changed a bit since then, so the commit cannot simply be reverted, some sections of the documentation also need to be updated.

**Comment by jhthorsen** [comment]
Awesome! :+1:
