### ISSUE TITLE
hangs on t/mojo/daemon.t

### ISSUE THREAD

**Issue by ntchuang** [kraih/mojo#897]
I am running win10 64bit. When I try installing Mojolicious it hangs at this point.

with Strawberry Perl 5.18.4 it hangs at
t/mojo/daemon.t ............................ 1/?

with Strawberry Perl 5.22.1 it hangs at 
t/mojo/daemon.t ............................ 50/?

matrix shows it should work?

edit:
I don't know if that number at the end matters but now it seems to vary now.

edit2: Here is the [Pastebin](http://pastebin.com/dVURDHCZ)

**Comment by Tekki** [comment]
Tried on Win10 x64, Strawberry Perl 5.22.1, and it works:
Configuring Mojolicious-6.40 ... OK
Building and testing Mojolicious-6.40 ... OK
Successfully installed Mojolicious-6.40

**Comment by ntchuang** [comment]
How long should it be at that line for? I am assuming 1 hour is too long?

I checked the CPU use and it was 0% for dmake so I am assuming it hanged.

**Comment by genio** [comment]
I too have noticed the "hanging" issue in Windows (although not only with Mojolicious).  It might possibly have something to do with the differences between CMD and PowerShell.  However, during said hangs, it usually does what it's supposed to just by hitting <enter>.

Since that "work-around" seems to do the trick for me every time, I haven't put much effort into figuring out why.

**Comment by ntchuang** [comment]
what should i be hitting? space or period?

i am using CMD

**Comment by genio** [comment]
Sorry, I had an error with markdown formatting.  ```enter```

**Comment by ntchuang** [comment]
any other ideas?

**Comment by ntchuang** [comment]
so a person on another forum suggested I end process the test, and after some confusion I was able to do that and allow testing to proceed past this one hang up. It seems that was the only error for me. Here is the [pastebin](http://pastebin.com/m8U29PpY)

**Comment by kraih** [comment]
Have you tested how far back the problem goes? 6.0, 5.0, 4.0...?

**Comment by kraih** [comment]
Or have you even checked with `prove -v` to see at which test exactly it hangs?

**Comment by kraih** [comment]
CPANTesters results look pretty good at the moment. http://matrix.cpantesters.org/?dist=Mojolicious+6.40

**Comment by ntchuang** [comment]
I did not check how far back the problem goes and I did not know the `prove -v` syntax. I think if there's no major issues then having the daemon.t fail testing is fine for me.

**Comment by kraih** [comment]
Looks like this problem only affects a very small subset of Windows machines. Is there any chance one of the affected users will be able to track it down? Otherwise i don't think it makes much sense to keep this issue open.

**Comment by ntchuang** [comment]
I am not sure how to track it down, otherwise I would've. I think since it only affected me it probably should not be kept open.

**Comment by kraih** [comment]
Too bad, but yea, it's not easy even with access to an affected machine.
