### ISSUE TITLE
Deprecation warnings in Mojo::JSON

### ISSUE THREAD

**Issue by nanis** [kraih/mojo#901]
Noticed while running tests:

<pre>t\mojolicious\app.t ........................ ok
Use of strings with code points over 0xFF as arguments to bitwise and (&) operator is deprecated at C:\...\.cpanm\work\1453635541.4320\Mojolicious-6.41\blib\lib/Mojo/JSON.pm line 252, &lt;DATA> line 112.
Use of strings with code points over 0xFF as arguments to bitwise and (&) operator is deprecated at C:\...\.cpanm\work\1453635541.4320\Mojolicious-6.41\blib\lib/Mojo/JSON.pm line 252, &lt;DATA> line 112.
Use of strings with code points over 0xFF as arguments to bitwise and (&) operator is deprecated at C:\...\.cpanm\work\1453635541.4320\Mojolicious-6.41\blib\lib/Mojo/JSON.pm line 252, &lt;DATA> line 112.
Use of strings with code points over 0xFF as arguments to bitwise and (&) operator is deprecated at C:\...\.cpanm\work\1453635541.4320\Mojolicious-6.41\blib\lib/Mojo/JSON.pm line 252, &lt;DATA> line 112.
t\mojolicious\charset_lite_app.t ........... ok
</pre>

<pre>C:\> perl -v 
This is perl 5, version 23, subversion 6 (v5.23.6) built for MSWin32-x64-multi-thread</pre>

**Comment by kraih** [comment]
Thanks, fixed. https://github.com/kraih/mojo/commit/d76e408bc98bda105466b208e71224d99cb88243
