### ISSUE TITLE
Default values in validator.

### ISSUE THREAD

**Issue by rshadow** [kraih/mojo#906]
Please add ability to set default value for undef in Mojolicious::Validator.
For example:

```
$self->validation->optional('name')->size(1, 100)->default('Anonimous');
```

Defaults must apply after filters and if check fail.
Yes i can write:
```
my $name = $self->validation->param('name') // 'Anonimous';
```
but it spreads in the code.

**Comment by kostya-ten** [comment]
+1

**Comment by jhthorsen** [comment]
What will has_error() return then? Sounds very strange to default to something if the input is invalid. Can you provide a real life example where this is useful?

**Comment by kraih** [comment]
And how is this supposed to interact with tag helpers?

**Comment by kraih** [comment]
Closing this issue since the description is too vague and there are still too many unanswered questions.
