### ISSUE TITLE
Force array in validator

### ISSUE THREAD

**Issue by rshadow** [kraih/mojo#907]
Please add ability to force arrays in Mojolicious::Validator::Validation.
For example:
```
$self->validation->required('tariffs')->array;
```
or maybe filter?
```
$self->validation->required('tariffs', 'array');
```

On undef result must be empty array. On one or more values non empty array.

**Comment by kraih** [comment]
What are the use cases for this?

**Comment by rshadow** [comment]
Use case:
1. Set of checkboxes with same name:
```
%= check_box tariffs => 1
%= check_box tariffs => 2
%= check_box tariffs => 3
```
2. Database need arrayref. CREATE TABLE in Postgresql example:
```
...
"tariffs"    INTEGER NOT NULL DEFAIL ARRAY[]::INTEGER[]
...
```
3. And Model need arrayref too:
```
package MyApp::User;
use Mouse;
has tariffs => is => 'ro', isa => 'ArrayRef[Num]', default => sub {[]};
...
```

So if I get `undef` (no tariffs checked) or `scalar` (one tariffs checked) the Model drop exception. Even if I try save parameter manually (via DBI execute) then database drop exception.

**Comment by rshadow** [comment]
Now I use this code everywhere:
my $tariffs = $self->validation->required('tariffs')->int;
$tariffs = [] unless defined $tariffs;
$tariffs = [ $tariffs ] unless 'ARRAY' eq ref $tariffs;

**Comment by jhthorsen** [comment]
Not sure if I like the idea that it defaults to empty array on "unless defined". As in: It should still be undef, if it doesn't pass validation.

I'm a bit positive on adding this as a filter.

**Comment by rshadow** [comment]
Oh. We have not post processing filters. Maybe we need:
```
$self->validation->required('tariffs')->post('filter1', ...);
```

**Comment by jhthorsen** [comment]
Why does it have to be post?

**Comment by kraih** [comment]
Ok, none of those use cases can actually work (or already work with `every_param`).

**Comment by plopidou** [comment]
Hi,


Not sure if I should comment on here or open a new suggestion/issue? Please let me know :-)

I have a similar use case, where several form inputs with the same name are submitted.

    <input name="foo" id="foo1" value="111">
    <input name="foo" id="foo2" value="222">
    <input name="foo" id="foo3" value="">

Server-side:

   my $foo = $c->validation->required('foo')->check('custom_check')->every_param;

Dumping the `$c->validation` outputs the following:

    <snip>
      'input' => {
                'foo' => [
                         '111',
                         '222',
                         ''
                       ],
              },
    'error' => {
                'foo' => [
                           'required'
                         ]
              },
    'output' => {},
    <snip>

How is it possible for the validation object to contain a more detailed list of errors **_per input_**? i.e., something similar to this instead:

        'input' => {
                'foo' => [
                         '111',
                         '222',
                         ''
                       ],
              },
    'error' => {
                'foo' => [
                           undef,
                           undef,
                           'CUSTOM_CHECK_ERROR_CODE'
                         ]
              },
    'output' => {
                'foo' => [
                           '111',
                           '222',
                           undef
                         ]
               },

Thanks to which we can know which "index" of the same name is in error mode?

Many thanks!
