### ISSUE TITLE
Speed up url_for("route_name") by caching on route construction

### ISSUE THREAD

**Issue by anielsen** [kraih/mojo#914]
In our app we have many named routes and we love url_for. url_for does caching but the misses are quite expensive since they transverse the route tree.

During setup when the route tree is built the mapping from route name to Mojo::Router::Route object could be placed in the cache so misses aren't possible.

**Comment by jhthorsen** [comment]
Could you please provide a benchmark for what "expensive" means?

**Comment by kraih** [comment]
I do have a few ideas for making `url_for` faster, but it might be awhile till i get around to it.

**Comment by kraih** [comment]
Caching during route construction should not work though, since the route tree is mutable until the first request.

**Comment by anielsen** [comment]
@jhthorsen we have 9000+ routes in our app. I have created a small example app with 
$ mojo generate app
And added this to MyApp.pm
```perl
$r->get("/foo/$_")->to("example#welcome")->name("route$_") for 1..10_000;
```
To benchmark we user NYTProfiler with this script
```perl
#!/usr/bin/env perl

use utf8;
use strict;
use Devel::NYTProf;
use Test::Mojo;
use MyApp;
my $t = Test::Mojo->new('MyApp');

DB::enable_profile;
for (1..100) {
    my $r = 10_000 - $_;
    $t->app->url_for("route$r") for 1..100;
}
DB::disable_profile;
```
Here is the resulting flame graph
![](http://i.imgur.com/UjSKTbm.png)

We make 100 request for each of the 100 last routes. So we have 1% cache miss and 99% hits but the run time is dominated by Mojolicious::Routes::lookup which is used in the miss case.

**Comment by anielsen** [comment]
We are using version 6.29 btw

$ mojo version
CORE
  Perl        (v5.16.3, linux)
  Mojolicious (6.29, Clinking Beer Mugs)

OPTIONAL
  EV 4.0+                 (n/a)
  IO::Socket::Socks 0.64+ (n/a)
  IO::Socket::SSL 1.94+   (2.000)
  Net::DNS::Native 0.15+  (n/a)

**Comment by anielsen** [comment]
@kraih maybe it's possible to update the cache for all checked named routes in Mojolicious::Routes::Route->find when traversing the tree?

**Comment by kraih** [comment]
If we index all routes only once, it should be fast enough for most use cases.
```
perl -Mojo -E 'get "/test$_" for 1 .. 10000; my $c = app->build_controller; n { $c->url_for("test$_") for 1 .. 10000 }'
```
This one-liner drops from 185s down to 0.8s.

**Comment by anielsen** [comment]
@kraih @jhthorsen I just want to add that you guys rock. Thank you :+1:

**Comment by msporleder** [comment]
@anielsen can you give some (obfuscated) details about how to landed with so many routes?  I think a lot of people are curious.

**Comment by anielsen** [comment]
sure @msporleder I can understand your curiosity :-)
https://www.youtube.com/watch?v=SiMHTK15Pik

We serve 5 web sites from the same mojo app. We have created our own layer on top of mojo to handle this. All 5 web sites are job boards and they share a lot of URLs but the URLs are localized.

So for a given feature we have 5 routes - one for each sites. All routes map to the same action. Our layer wrap url_for in our_url_for. So in our template we write our_url_for("horse") and it will return a localized URL i.e. /pferd og /hest.
