### ISSUE TITLE
Mojo::Exceptions's examples need some more detail

### ISSUE THREAD

**Issue by assistcontrol** [kraih/mojo#918]
`Mojo::Exception`'s pod is a bit sparse. There aren't much in the way of tests about it in `t/`, so it's pretty hard to figure out how to use it correctly.

Take, for example, the `line` property.

```
my $line = $e->line;
$e       = $e->line([3 => 'foo']);
```

The example apparently shows how to set the `line` property manually (isn't that supposed to be set automatically by generating the exception? Why would I want to set it myself?). But it doesn't show what the contents of the `line` property are, or how to get to them.

```
use Try::Tiny;
use Data::Dumper qw(Dumper);
  try {
          die Mojo::Exception->new('oops!');
  }
  catch {
          $c->app->log->info->("Line: " . Dumper($_->line) );
  };
```

This produces:

```
[Thu Feb 25 12:19:53 2016] [info] Line: $VAR1 = [];
```

So, can Mojo::Exception please be updated with a little more info about how to actually get at the property values, or something in `t/` that shows how to use it?

**Comment by kraih** [comment]
The lack of documentation is very much intentional i'm afraid, `Mojo::Exception` is meant for internal use.

**Comment by kraih** [comment]
Or are there use cases outside the core framework i might be missing?

**Comment by assistcontrol** [comment]
It seems like a great lightweight way to handle custom exceptions in my app.

```
use Try::Catch;
get '/' => sub {
  my $c = shift;
  try {
    $foo > 1 or die Mojo::Exception->new('Foo must be greater than 1');
    $bar < 2 or die Mojo::Exception->new('Bar must be less than 2');
    complex_procedure or die Mojo::Exception->new('complex procedure failed');

    $c->render;
  } catch {
    $c->app->log->debug('Error ' . $_ . 'triggered at line ' . $_->line);
    $c->render("We did not like your answer. Here's a picture of a taco");
  }
}
```

Mojolicious is fantastic for having accessible, usable modules that prevent me from having to roll my own solutions all the time. `Mojo::Exception` seems like a perfect way to log what went wrong, where it happened, etc, while providing a custom response to the user and detailed logging for myself. Having line numbers in there is extra great.

I would absolutely suggest exposing its power outside the core framework!

**Comment by kraih** [comment]
Can't agree with that, the API of `Mojo::Exception` is rather crude and very specific to the requirements of `Mojo::Template`. How do you even begin to explain support for multiple source files?

**Comment by kraih** [comment]
So, to sum it up, you want `Mojo::Exception` to become a generic container for exceptions with context.

**Comment by kraih** [comment]
Writing documentation wouldn't be enough for that though, the API also needs to be redesigned to be more generic. And so far there have been no proposals.

**Comment by assistcontrol** [comment]
Yeah, that summary sounds about right. Just having a simple way to throw an exception, and be able to log the line it happened on, makes for a pretty useful and lightweight way to handle validation flow and to make development easier.

**Comment by kraih** [comment]
We've talked about this a bit on IRC, and it appears we have consensus on changing nothing for now. I've updated the documentation a bit, but we do not consider `Mojo::Exception` ready for use outside of Mojolicious core. If a good proposal for making it more generic pops up, we will reconsider though.

**Comment by kraih** [comment]
I've made some changes to `Mojo::Exceptions`, and it might be good enough for generic use now. :smiley: https://github.com/kraih/mojo/compare/d9600327f006744fb55d9627e698c38ddb233c29...5ae4a30bf6d26190da2321a46552f79387294464

**Comment by david-dot-krupicka** [comment]
Hello, I am very new to Mojolicious, trying f****g hard to tame it. With `Moose` and `Exception::Class::Try::Catch`.
Dumpers everywhere, I've tried a lot of different constructs, asking why oh my the conditions for my custom exceptions do not match. :-D
I had only a little time to check the documentation, I am rather gliding over it. Well, now I probably understand my approach was not good. I see there are callbacks, that's maybe, maybe why I don't have to implement the exceptions bubbling up to the controller. :-D 

So I need to change the approach. But anyway, some tutorial about this topic would be, IMHO, greatly appreciated! :-)

Best regards
David
