### ISSUE TITLE
File::Find does not return canonical paths

### ISSUE THREAD

**Issue by nanis** [kraih/mojo#919]
This leads to a test failure in `t\mojo\util.t`:

```
t\mojo\util.t .. 1/?                                            
#   Failed test 'right files'                                   
#   at t\mojo\util.t line 425.                                  
#     Structures begin differing at:                            
#          $got->[0] = 't\mojo\lib\Mojo/BaseTest/Base1.pm'      
#     $expected->[0] = 't\mojo\lib\Mojo\BaseTest\Base1.pm'      
# Looks like you failed 1 test of 200.                          
t\mojo\util.t .. Dubious, test returned 1 (wstat 256, 0x100)    
Failed 1/200 subtests 
```
This is due to [line 120 in `Mojo\Util.pm`](https://github.com/kraih/mojo/blob/master/lib/Mojo/Util.pm#L120):

```
 my $wanted = sub { -d $File::Find::name or push @files, $File::Find::name };
```
`File::Find` has never returned canonical paths on Windows. Therefore, if you want canonical paths, you must do so manually.

I may have time to put together a pull request later.

**Comment by kraih** [comment]
Thanks, already fixed. https://github.com/kraih/mojo/commit/d20f2a424d9539727107c570459c2ba22368e985

**Comment by nanis** [comment]
Apologies for the interruption. I am not sure how I missed that. Thank you for your work.
