### ISSUE TITLE
Commit eac8210 changes the precedence of multiple routes with same name

### ISSUE THREAD

**Issue by anielsen** [kraih/mojo#920]
Before eac8210 the following would return /first but the commit changed it to /last

```
perl -Mojo -E 'get "/first" => "same" ; get "/last" => "same"; my $c = app->build_controller; say $c->url_for("same")'
```
Yes, we do have multiple routes with the same name due to... Well, sloppiness :-)

Maybe it would be better to warn in this situation. However it should easy to get the old behaviour back by changing Mojolicious::Routes::Route like this

``` diff
-    if ($child->has_custom_name) { $index{$child->name} = $child }
+    if ($child->has_custom_name) { $index{$child->name} ||= $child }
```

**Comment by kraih** [comment]
This can't work, custom names need to have a higher precedence than automatically generated ones.

**Comment by anielsen** [comment]
I checked the docs and I see that you are right :-)

Thank you for fixing this.
