### ISSUE TITLE
Better support for 20+ CPU cores

### ISSUE THREAD

**Issue by kraih** [kraih/mojo#925]
So far we've focused mostly on 4 cores with profiling, but moving forward we should make sure that `Mojo::Server::Prefork` (and Hypnotoad) scale well much further. Aside from optimizations like high/low watermarks (for when to start/stop accepting connections), we could also experiment with different configurations, and perhaps adjust the defaults and/or documentation.

Since most members of the core team do not have access to such servers, we will need volunteers to help us.
```
perl examples/fast.pl prefork -w 20 -m production -l http://*:8080
```
For load testing we recommend [this](https://github.com/kraih/mojo/blob/master/examples/fast.pl) example application, and [wrk](https://github.com/wg/wrk).
```
wrk -c 100 -d 30s http://127.0.0.1:8080/
```

**Comment by kraih** [comment]
For starters we need a baseline, a series of load tests with an incrementally increasing number of workers workers (steps of 2?).

**Comment by jyrgenn** [comment]
Okay -- I have run this on the server where I use Mojolicious anyway; this is Mojolicious 6.03 (I have been admittedly lazy with updates) on a HP DL-380 Gen8 server with 64 (or 66?) GB RAM and 2 x 6 cores with hyperthreading, so I let it run with up to 24 workers in steps of 2.

If _really_ necessary, I can install and use a newer Mojolicious version, but I am afraid this means work _and_ I am a bit hesitant to fix what ain't broken (for me).

[multicore-benchmark.sh.txt](https://github.com/kraih/mojo/files/154817/multicore-benchmark.sh.txt)
[typescript.txt](https://github.com/kraih/mojo/files/154818/typescript.txt)

**Comment by jyrgenn** [comment]
Ah, and if you think my test driver script does the right thing, anyone else is of course welcome to use it, too.

**Comment by jyrgenn** [comment]
Here are two more runs that don't show that don't show that extreme outlier at 20 workers like the first one, but connection problems for 16 and 18 workers instead, and a fourth one that has no connection problems, but an outlier at 20 workers again. And at 24. Dunno what to make of that.

For fun, I extracted the values for requests/s into a table; maybe that is of any use. (And pesky Github doesn't accept file names without extension, and no *.sh or *.csv files. Darn.)

[typescript2.txt](https://github.com/kraih/mojo/files/154917/typescript2.txt)
[typescript3.txt](https://github.com/kraih/mojo/files/154916/typescript3.txt)
[typescript4.txt](https://github.com/kraih/mojo/files/154954/typescript4.txt)

[mojo-workers.csv.txt](https://github.com/kraih/mojo/files/154953/mojo-workers.csv.txt)

**Comment by kraih** [comment]
I really hope those results are not valid, otherwise we would have a lot of work to do.

**Comment by ribasushi** [comment]
Tangentially: perhaps there is a large establishment using Mojo that can donate CPUtime on a larger box for further testing.
E.g. the way [ServerCentral provided](http://www.masteringperl.org/2015/12/ive-found-over-200-excellent-numbers/) @briandfoy 80 cores to look for stuff

**Comment by jyrgenn** [comment]
More results with -M 2 and -M 5, respectively.
[multicore-benchmark.sh.txt](https://github.com/kraih/mojo/files/155111/multicore-benchmark.sh.txt)

[typescript-M2.txt](https://github.com/kraih/mojo/files/155105/typescript-M2.txt)
[typescript-M5.txt](https://github.com/kraih/mojo/files/155107/typescript-M5.txt)
[typescript-M5b.txt](https://github.com/kraih/mojo/files/155106/typescript-M5b.txt)

```
typescript-M2.txt:======== running with 2 workers
typescript-M2.txt:Requests/sec:   3297.08
typescript-M2.txt:======== running with 4 workers
typescript-M2.txt:Requests/sec:   6848.40
typescript-M2.txt:======== running with 6 workers
typescript-M2.txt:Requests/sec:  10258.88
typescript-M2.txt:======== running with 8 workers
typescript-M2.txt:Requests/sec:   7107.24
typescript-M2.txt:======== running with 10 workers
typescript-M2.txt:Requests/sec:   3633.44
typescript-M2.txt:======== running with 12 workers
typescript-M2.txt:Requests/sec:   4227.07
typescript-M2.txt:======== running with 14 workers
typescript-M2.txt:Requests/sec:  16374.49
typescript-M2.txt:======== running with 16 workers
typescript-M2.txt:======== running with 18 workers
typescript-M2.txt:Requests/sec:   3754.41
typescript-M2.txt:======== running with 20 workers
typescript-M2.txt:Requests/sec:   2653.64
typescript-M2.txt:======== running with 22 workers
typescript-M2.txt:Requests/sec:  11632.83
typescript-M2.txt:======== running with 24 workers
typescript-M2.txt:Requests/sec:  10521.71
typescript-M5.txt:======== running with 2 workers
typescript-M5.txt:Requests/sec:   3199.20
typescript-M5.txt:======== running with 4 workers
typescript-M5.txt:Requests/sec:   6507.45
typescript-M5.txt:======== running with 6 workers
typescript-M5.txt:Requests/sec:  10442.67
typescript-M5.txt:======== running with 8 workers
typescript-M5.txt:Requests/sec:   5065.49
typescript-M5.txt:======== running with 10 workers
typescript-M5.txt:Requests/sec:   3978.57
typescript-M5.txt:======== running with 12 workers
typescript-M5.txt:Requests/sec:   8653.46
typescript-M5.txt:======== running with 14 workers
typescript-M5.txt:Requests/sec:   9886.64
typescript-M5.txt:======== running with 16 workers
typescript-M5.txt:Requests/sec:   3199.90
typescript-M5.txt:======== running with 18 workers
typescript-M5.txt:Requests/sec:   2734.76
typescript-M5.txt:======== running with 20 workers
typescript-M5.txt:Requests/sec:  18723.67
typescript-M5.txt:======== running with 22 workers
typescript-M5.txt:Requests/sec:   2021.80
typescript-M5.txt:======== running with 24 workers
typescript-M5.txt:Requests/sec:   1614.69
typescript-M5b.txt:======== running with 2 workers
typescript-M5b.txt:Requests/sec:   3265.98
typescript-M5b.txt:======== running with 4 workers
typescript-M5b.txt:Requests/sec:   6592.93
typescript-M5b.txt:======== running with 6 workers
typescript-M5b.txt:Requests/sec:  10347.86
typescript-M5b.txt:======== running with 8 workers
typescript-M5b.txt:Requests/sec:   6635.31
typescript-M5b.txt:======== running with 10 workers
typescript-M5b.txt:Requests/sec:   4025.01
typescript-M5b.txt:======== running with 12 workers
typescript-M5b.txt:Requests/sec:   4639.24
typescript-M5b.txt:======== running with 14 workers
typescript-M5b.txt:Requests/sec:  15606.98
typescript-M5b.txt:======== running with 16 workers
typescript-M5b.txt:======== running with 18 workers
typescript-M5b.txt:Requests/sec:   4145.14
typescript-M5b.txt:======== running with 20 workers
typescript-M5b.txt:Requests/sec:   3347.29
typescript-M5b.txt:======== running with 22 workers
typescript-M5b.txt:Requests/sec:  12196.62
typescript-M5b.txt:======== running with 24 workers
typescript-M5b.txt:Requests/sec:   9203.04
```

**Comment by kraih** [comment]
Ok, if it is not the multi-accept, we have to find out what else could cause the load to be so unevenly distributed.

**Comment by jyrgenn** [comment]
Some more runs with Mojolicious-6.51.

[typescript-run1.txt](https://github.com/kraih/mojo/files/155305/typescript-run1.txt)
[typescript-run2.txt](https://github.com/kraih/mojo/files/155307/typescript-run2.txt)
[typescript-run3.txt](https://github.com/kraih/mojo/files/155308/typescript-run3.txt)
[typescript-run4.txt](https://github.com/kraih/mojo/files/155306/typescript-run4.txt)
[typescript-run5.txt](https://github.com/kraih/mojo/files/155309/typescript-run5.txt)
[typescript-run6.txt](https://github.com/kraih/mojo/files/155304/typescript-run6.txt)
[typescript-run7.txt](https://github.com/kraih/mojo/files/155310/typescript-run7.txt)

[7runs.csv.txt](https://github.com/kraih/mojo/files/155313/7runs.csv.txt)

**Comment by kraih** [comment]
Thanks, i think we have enough results for now, as long as they don't show a new pattern.

**Comment by kraih** [comment]
It appears that for these kinds of load tests we have to limit the number of connections each worker is allowed to handle concurrently.
```
perl examples/fast.pl prefork -w 8 -c 16 -a 0 -r 1000 -m production -l http://*:8080
```
So, for 8 CPU cores and 128 concurrent connections, we would end up with 8 workers that each handle 16 connections. Additionally, it seems like a good idea to disable automatic restarting of workers, and increase the number of keep-alive requests per connection.
```
wrk -c 128 -d 30s http://127.0.0.1:8080/
```

**Comment by heikojansen** [comment]
We have a server that is currently solely used for tests and development tasks; this allows me to run these benchmark tests on an otherwise idle system but I have to wait for a time when it is not used for other in house tasks. 
So generally I should be able to repeat the benchmark tests when asked for but I can´t promise to be able to do that immediately on request since the system may be in use at the time.

The system itself is running SLES 12 SP 1 on a 2 socket / 6 cores per socket / 2 threads per core (Hyperthreading) architecture (Xeon X5675 at 3.07GHz) with 24 GB of RAM.

I installed Perl 5.22.1 via plenv and added only Mojolicious. I´ve adapted the benchmark script by jyrgenn to use the parameters in kraih´s latest post: 
[multicore-benchmark.sh.txt](https://github.com/kraih/mojo/files/156397/multicore-benchmark.sh.txt)
I did not test variations of the number of connections; only the number of workers was changed.

I´ve run the script with both v6.51 and v6.52:

[mojo_651.txt](https://github.com/kraih/mojo/files/156402/mojo_651.txt)
[mojo_652.txt](https://github.com/kraih/mojo/files/156403/mojo_652.txt)

I have to admit that I currently don´t know much about performance tuning so you´ll have to tell me what params to use for additional tests if you need any. We don´t have any Mojolicious apps under heavy load so far, but we´re working on a larger app (which will make heavy use of the non-blocking features) and I hope to gain some insight this way...

**Comment by jyrgenn** [comment]
A few test runs with 6.52 and the latest parameters above showed that everything was *totally* fine, all processes used 100 % (or what they could get) CPU from beginning to end, totally stable, every time. Great, @kraih, I guess you nailed it!

Details to follow, must hurry to a meeting now.

**Comment by kraih** [comment]
Thanks everyone!

**Comment by kraih** [comment]
The curve for @jyrgenn 's latest data looks pretty good.
![curve](https://cloud.githubusercontent.com/assets/30094/13503030/b324cf18-e16d-11e5-9fc7-1f6124363f52.png)

**Comment by kraih** [comment]
The curve for @heikojansen's data looks even better. (also 12 CPU cores with hyper-threading)
![curve](https://cloud.githubusercontent.com/assets/30094/13505068/9e65d482-e177-11e5-89eb-1ad405269515.png)

**Comment by kraih** [comment]
In case someone wants to run more benchmarks in the future, here's an updated script.
```bash
#!/bin/sh

PORT=8080
ADDR=127.0.0.1
WRK=/usr/local/bin/wrk
FAST=/Users/sri/repo/mojo/examples/fast.pl
PID=/Users/sri/prefork.pid
CONNECTIONS=128
MAXWORKERS=128

WORKERS=2
while [ $WORKERS -lt $MAXWORKERS ]; do
    echo ''
    let CLIENTS=(CONNECTIONS/WORKERS)+1
    echo ======== running with $WORKERS workers and $CLIENTS connections per worker
    perl $FAST prefork -w $WORKERS -c $CLIENTS -a 0 -r 100000 -m production -l http://$ADDR:$PORT -P $PID &
    sleep 2
    $WRK -c $CONNECTIONS -d 30s http://$ADDR:$PORT/
    sleep 2
    while [ -f $PID ]; do
        kill -s QUIT $(cat $PID)
        sleep 1
    done
    echo ========
    let WORKERS+=2
done
```

**Comment by mpapec** [comment]
Ok, here are the results for above benchmark,
https://gist.github.com/mpapec/bd9bae3dd7a59c8ee749984d7173e9f6

**Comment by kraih** [comment]
@mpapec The curve looks pretty good, until there's not enough connections anymore to scale further.
<img width="833" alt="curve" src="https://cloud.githubusercontent.com/assets/30094/17458112/24995860-5c09-11e6-80e8-3f256ee1ded9.png">

**Comment by mpapec** [comment]
Included EV in case it shows improvements over vanilla ioloop. Btw, what is your opinion on HyperThreading in scaling context (are there real benefits from quasi cpu cores)?

CONNECTIONS=512
https://gist.github.com/mpapec/3a7bff7513d12278413319e631df09ab

CONNECTIONS=512 && use EV
https://gist.github.com/mpapec/7cbfec10a6482269b575a8999300b5d8

CONNECTIONS=9000 && use EV
https://gist.github.com/mpapec/3bf1ab859506948c7d61139265123d2c

**Comment by kraih** [comment]
@mpapec A Hyper-Thread seems to be worth about 20% or a real CPU core.

**Comment by mpapec** [comment]
Opteron 64 cores,
https://gist.github.com/mpapec/2f242879debd6015f02829d41c4c9600

(paired cores share FPU and L2)
http://www.theregister.co.uk/2015/11/06/amd_sued_cores/
