### ISSUE TITLE
label_for when used with tag_field missing id attribute

### ISSUE THREAD

**Issue by chy-causer** [kraih/mojo#932]
According to the [HTML5 spec](https://www.w3.org/TR/html5/forms.html#the-label-element), when a label tag contains a `for` attribute it must accompany a labelable element of matching `id`. This is to aid usability of forms in browsers as well as to help screen readers.

The following commit adds a failing test that should hopefully explain what I mean:
https://github.com/chy-causer/mojo/commit/c4f43e7b0073aa59cd712dc2f5b4e5c419a93e30

I used `Mojo::DOM` in the test rather than hard-coded the `id` and `for` attributes directly because a fully working solution could possibly have to rewrite these attributes. A naive solution of

```
%= label_for foo => '<Foo>'
%= text_field foo => 'bar'

<label for="foo">&lt;Foo&gt;</label>
<input name="foo" id="foo" type="text" value="bar"> 
```
may well break HTML validation on existing sites whenever multiple fields for name `foo` are rendered on a page.

It is possible that this is an intractable problem, and if so, may I please request a short note or example in [the docs for `label_for`](http://mojolicious.org/perldoc/Mojolicious/Plugin/TagHelpers#label_for) and [rendering guides ](http://mojolicious.org/perldoc/Mojolicious/Guides/Rendering) indicating that when `label_for` is used, the `input` field requires its `id` attribute to match? I was scratching my head for a bit as to why my label tags were not clickable.

Many thanks.

**Comment by kraih** [comment]
Thanks, fixed.
