### ISSUE TITLE
Morbo does not ignore .swp files anymore

### ISSUE THREAD

**Issue by arthoq** [kraih/mojo#934]
I have just updated Mojolicious and now Morbo does not ignore the .swp files created by Vim anymore. Is this a bug?

**Comment by arthoq** [comment]
Is this the wrong place to ask?

**Comment by evoyy** [comment]
I just upgraded 6.41 -> 6.55 and found the same issue. Morbo is restarting whenever I type anything. I have reverted back to 6.41 for now.

**Comment by jhthorsen** [comment]
We know about the issue. It can be fixed with this patch:

```
RawEditGraphNewPowered by Mojopaste
diff --git a/lib/Mojo/Server/Morbo.pm b/lib/Mojo/Server/Morbo.pm
index 9217ea9..873e86e 100644
--- a/lib/Mojo/Server/Morbo.pm
+++ b/lib/Mojo/Server/Morbo.pm
@@ -4,6 +4,7 @@ use Mojo::Base -base;
 # "Linda: With Haley's Comet out of ice, Earth is experiencing the devastating
 #         effects of sudden, intense global warming.
 #  Morbo: Morbo is pleased but sticky."
+use File::Basename 'basename';
 use Mojo::Server::Daemon;
 use Mojo::Util qw(deprecated files);
 use POSIX 'WNOHANG';
@@ -24,6 +25,7 @@ sub modified_files {
   my $cache = $self->{cache} ||= {};
   my @files;
   for my $file (map { -f $_ && -r _ ? $_ : files $_ } @{$self->watch}) {
+    next if basename($file) =~ /^\./;
     my ($size, $mtime) = (stat $file)[7, 9];
     my $stats = $cache->{$file} ||= [$^T, $size];
     next if $mtime <= $stats->[0] && $size == $stats->[1];
diff --git a/t/mojo/morbo.t b/t/mojo/morbo.t
index ed53db8..c213afa 100644
--- a/t/mojo/morbo.t
+++ b/t/mojo/morbo.t
@@ -116,9 +116,10 @@ is $tx->res->body, 'Hello!', 'right content';

 # New file(s)
 is_deeply $morbo->modified_files, [], 'directory has not changed';
-my @new = map { catfile $subdir, "$_.txt" } qw/test testing/;
+my @new = map { catfile $subdir, "$_.txt" } qw(.skip.swp test testing);
 spurt 'whatever', $_ for @new;
-is_deeply $morbo->modified_files, \@new, 'two files have changed';
+is_deeply $morbo->modified_files, [grep { $_ !~ /skip\.swp/ } @new],
+  'two files have changed';
 is_deeply $morbo->modified_files, [], 'directory has not changed again';
```

Need to decide if this is the right thing to do.

**Comment by evoyy** [comment]
The patch is working, thanks.

It looks like a nice solution to me. I don't think anybody puts application code in dotfiles. But if you want to be conservative you could enable it via a --ignore-dotfiles switch.

**Comment by arthoq** [comment]
Yes, the patch works.

**Comment by jberger** [comment]
:+1: for @jhthorsen 's patch as long as it includes some documentation somewhere

**Comment by pink-mist** [comment]
:+1: from me too

**Comment by kraih** [comment]
You don't think it might be problematic that this can't handle directories like `.git`? Is it better for performance to check the prefix before or after mtime/size?

**Comment by jberger** [comment]
hmmmm, yeah, handling `.git` would probably be wise though it is less important than swp since you have to save and commit before the `.git` directory is changed

**Comment by jhthorsen** [comment]
I supposed stat() is a lot slower than calling a perl function.

What do you mean with "can't handle directories like .git" @kraih ? Do you mean ```--watch .git``` or ```--watch .``` ? If so, I imagine that would be slow either way. At least this patch avoids watching temp files while editing.

**Comment by jhthorsen** [comment]
As @jberger pointed out, here is what plack does: https://metacpan.org/source/MIYAGAWA/Plack-1.0039/lib/Plack/Loader/Restarter.pm#L55

I think something like this is a middle way:

    next if basename($file) =~ m!\.(?:bak|swp|swpx|swx)$|~$|_flymake\.p[lm]$|\.#!;

**Comment by kraih** [comment]
@jhthorsen I mean it doesn't ignore files inside a directory with dot prefix, like `.git`. That regex looks horrible to me.

**Comment by jberger** [comment]
@jhthorsen makes a point about `.git`, you have to explicitly watch that directory for changes (or else watch `.`). Regarding the Plack regex, I said at the time that that didn't look very Mojo to me :smile:

**Comment by kraih** [comment]
@jhthorsen What are `.swpx` and `.swx` files anyway?

**Comment by jhthorsen** [comment]
Yeah, I think the regex is a mess as well. Let's not make it more complicated than we have to, and currently users are complaining about dotfiles.

I'm +1 on the patch, since it's simple and makes morbo behave like it used before https://github.com/kraih/mojo/commit/ea8dc338c66c504d53b28dd1c4ba34783a6fc8a7#diff-52d3ad944c9afec616d8ccbcc2f1ce2eL48

**Comment by jberger** [comment]
I would be interested some performance metric if possible.

**Comment by kraih** [comment]
@jhthorsen I don't think that is true, it looks like the old code used to ignore directories with a dot prefix too.

**Comment by kraih** [comment]
Note that i'm not saying it should ignore directories like `.git`, just asking the question if it might be problematic not to do so. If users actually do `-w .`, then that's possibly thousands of additional files to check every second.

**Comment by kraih** [comment]
Quick benchmark for the Mojolicious repo on OS X with SSD.
```
~/repo/mojo $ perl -MMojo::Server::Morbo -Mojo -E 'my $m = Mojo::Server::Morbo->new(watch => ["."]); n { $m->modified_files } 10'
1.66039 wallclock secs ( 0.48 usr +  1.18 sys =  1.66 CPU) @  6.02/s (n=10)
~/repo/mojo $ find . | wc -l
    5048
```

**Comment by kraih** [comment]
Almost forgot, these are the results with @jhthorsen's patch applied. So there's a very noticeable performance cost.
```
~/repo/mojo $ perl -Ilib -MMojo::Server::Morbo -Mojo -E 'my $m = Mojo::Server::Morbo->new(watch => ["."]); n { $m->modified_files } 10'
2.49952 wallclock secs ( 1.30 usr +  1.20 sys =  2.50 CPU) @  4.00/s (n=10)
```
And if the dot prefix check gets moved behind the mtime/size check it jumps back to `6.02/s`. I strongly recommend you optimize that part.

**Comment by jhthorsen** [comment]
That's awful! :disappointed: Guess I've learned a lesson... I think that if speed is an issue, then we should't do so much stat()/for(). Here is a new idea:

```
diff --git a/lib/Mojo/Server/Morbo.pm b/lib/Mojo/Server/Morbo.pm
index 9217ea9..e6ed571 100644
--- a/lib/Mojo/Server/Morbo.pm
+++ b/lib/Mojo/Server/Morbo.pm
@@ -6,6 +6,7 @@ use Mojo::Base -base;
 #  Morbo: Morbo is pleased but sticky."
 use Mojo::Server::Daemon;
 use Mojo::Util qw(deprecated files);
+use File::Find ();
 use POSIX 'WNOHANG';

 has daemon => sub { Mojo::Server::Daemon->new };
@@ -20,16 +21,21 @@ sub check {

 sub modified_files {
   my $self = shift;
-
   my $cache = $self->{cache} ||= {};
   my @files;
-  for my $file (map { -f $_ && -r _ ? $_ : files $_ } @{$self->watch}) {
-    my ($size, $mtime) = (stat $file)[7, 9];
-    my $stats = $cache->{$file} ||= [$^T, $size];
-    next if $mtime <= $stats->[0] && $size == $stats->[1];
-    @$stats = ($mtime, $size);
-    push @files, $file;
-  }
+
+  no warnings;    # skip "Can't stat" warnings
+  File::Find::find(
+    sub {
+      return if /^\./ or -d _;
+      my ($size, $mtime) = (stat _)[7, 9];
+      my $prev = $cache->{$File::Find::name} ||= [$^T, $size];
+      return if $mtime <= $prev->[0] && $size == $prev->[1];
+      @$prev = ($mtime, $size);
+      push @files, $File::Find::name;
+    },
+    $_
+  ) for @{$self->watch};

   return \@files;
 }
```

Test case and benchmark:

```
$ for i in $(seq 0 5000); do touch "lib/x_$i"; done
$ find lib/ -type d | wc -l
      29
$ find lib/ -type f | wc -l
    5134
$ git checkout master
$ perl -Ilib -MMojo::Server::Morbo -Mojo -E 'my $m = Mojo::Server::Morbo->new(watch => ["lib"]); n { $m->modified_files } 50'
1.71442 wallclock secs ( 0.83 usr +  0.88 sys =  1.71 CPU) @ 29.24/s (n=50)
$ git checkout dotfiles
$ perl -Ilib -MMojo::Server::Morbo -Mojo -E 'my $m = Mojo::Server::Morbo->new(watch => ["lib"]); n { $m->modified_files } 50'
1.11585 wallclock secs ( 0.69 usr +  0.42 sys =  1.11 CPU) @ 45.05/s (n=50)
```

The difference is even bigger when watching ".", but that would be cheating since the patch above also skips directories starting with ```.```, like ```.git```.

**Comment by jhthorsen** [comment]
New patch:

```
diff --git a/lib/Mojo/Server/Morbo.pm b/lib/Mojo/Server/Morbo.pm
index 9217ea9..879a925 100644
--- a/lib/Mojo/Server/Morbo.pm
+++ b/lib/Mojo/Server/Morbo.pm
@@ -5,7 +5,9 @@ use Mojo::Base -base;
 #         effects of sudden, intense global warming.
 #  Morbo: Morbo is pleased but sticky."
 use Mojo::Server::Daemon;
-use Mojo::Util qw(deprecated files);
+use Mojo::Util qw(deprecated);
+use File::Find ();
+use File::Spec::Functions 'splitpath';
 use POSIX 'WNOHANG';

 has daemon => sub { Mojo::Server::Daemon->new };
@@ -20,17 +22,21 @@ sub check {

 sub modified_files {
   my $self = shift;
-
   my $cache = $self->{cache} ||= {};
   my @files;
-  for my $file (map { -f $_ && -r _ ? $_ : files $_ } @{$self->watch}) {
-    my ($size, $mtime) = (stat $file)[7, 9];
-    my $stats = $cache->{$file} ||= [$^T, $size];
-    next if $mtime <= $stats->[0] && $size == $stats->[1];
-    @$stats = ($mtime, $size);
-    push @files, $file;
-  }

+  my $wanted = sub {
+    return if -d $_;
+    my ($size, $mtime) = (stat _)[7, 9];
+    my $prev = $cache->{$File::Find::name} ||= [$^T, $size];
+    return if $mtime <= $prev->[0] && $size == $prev->[1];
+    return if (splitpath $File::Find::name)[2] =~ /^\./;
+    @$prev = ($mtime, $size);
+    push @files, $File::Find::name;
+  };
+
+  no warnings;    # skip "Can't stat" warnings
+  File::Find::find({no_chdir => 1, wanted => $wanted}, $_) for @{$self->watch};
   return \@files;
 }
```

Benchmark on 5163 files with n=50:
* with patch: 1.2915s
* without patch: 1.74053s

Here is more information from the discussion on IRC: http://irclog.perlgeek.de/mojo/2016-03-14#i_12180034

**Comment by kraih** [comment]
Just wanted to mention that @jhthorsen's latest patch should also result in the deprecation of `Mojo::Util::files` if it gets chosen.

**Comment by kraih** [comment]
This should really be two issues, the first about ignoring dotfiles efficiently with the current code, and the second about optimizing Morbo by deprecating `Mojo::Util::files`.

**Comment by aanoaa** [comment]
Is there no way to ignore file via pattern?
like `lib/Foo/Controller/Bar_flymake.pm`

is this wrong place to ask?
