### ISSUE TITLE
Strange Mojolicious::Lite's under behaviour

### ISSUE THREAD

**Issue by Evolve32** [kraih/mojo#936]
Hi folks

I encountered a problem with 'under' method and not sure is it a bug or it's just a desired behaviour and I simply misuse feature. I have a next snippet of code in my startup routine atop of newly generated app with 'mojo generate app'. To shorten each 'to' method call I set Example controller to be used for all next calls after first line with '->to('example#')' and it works fine for any/get/post/etc methods but fails for routes which created with 'under' method.
```perl
$r = $r->any('/')->to('example#');
$r->get('/' => 'index')->to('#welcome');

my $bla = $r->under('/bla');
$bla->get('/la' => { text => "hello laalala" });

$r->get('/testtext' => { text => 'good' });
my $tt = $r->under('/test');
$tt->get('/text' => { text => 'whee!!' });

$r->get('/some-data/:msg' => { msg => 'hello world' })
	 ->to('#somedata');

my $json = $r->under('/json');
$json->get('/tmpl' => { format => 'json' })->to('#json_template');
$json->get('/dyna')->to('#json_dynamic');
```

For instance lines '$bla->get...', '$tt->get...', and '$json->get...' will not be rendered and in logs I see
```
[Sun Mar 13 21:35:09 2016] [debug] GET "/test/text"
[Sun Mar 13 21:35:09 2016] [debug] Nothing has been rendered, expecting delayed response
```

To fix this I can add sub {1} for my $tt definition so that it will looks like this
```perl 
my $tt = $r->under('/test' => sub {1});
```
But is it really desired behaviour?

I guess one more related problem with this is that I can't set default controller with 'under' method. Next code doesn't work as expected, it will also try delayed response as previous example:
```perl
$r = $r->under('/')->to('example#');
```
The only difference from first snippet in this post is that 'under' used in place of 'any'. But with 'under' all routes become broken.

PS I have read documentation but didn't found anything about preferable order of any/get/post/etc and under method calls.

**Comment by jberger** [comment]
I'm afraid we don't understand what you are asking about. Per policy we are closing the issue (http://mojolicious.org/perldoc/Mojolicious/Guides/Contributing#REPORTING-BUGS) but it may be reopened if you can clarify.
