### ISSUE TITLE
[feature request] timings in Mojo::UserAgent

### ISSUE THREAD

**Issue by avkhozov** [kraih/mojo#939]
I think for applications, integrated with many http services, will be useful some statistics for each transaction: time for dns lookup, connection time, request time, new tcp connection or reused cached, etc. Like stats in chromium:
![qg2qcpv](https://cloud.githubusercontent.com/assets/427039/13990256/7107b2f8-f135-11e5-9b14-c55856272bd2.png)

It is possible for implementation and could be done in Mojo::UserAgent?

**Comment by kraih** [comment]
:-1: We should already have hooks to make most of these work, but i don't see this become part of `Mojo::UserAgent` itself, since it costs quite a bit of performance.

**Comment by s1037989** [comment]
Is the solution to create a non core sub class Mojo::UserAgent::WithTimings?

And then use it with:

$ua = DEBUG ? Mojo::UserAgent::::WithTimings->new : Mojo::UserAgent->new;

Is that a valid way? Is there a better way?

**Comment by kraih** [comment]
Looks like this didn't pass the vote.
