### ISSUE TITLE
Mojo::JSON doesn't produce the same output on repeated runs

### ISSUE THREAD

**Issue by shadowcat-mst** [kraih/mojo#941]
There's no sort when it traverses the keys of a JSON document.

This means that if I want to tell if my output has changed, I have to serialize to a -different- format first that is canonical, then do the JSON encoding.

This also means I can't e.g. use a sha1 to generate an etag for caching, and upsets HTTP cache servers in general.

All 'fixing' this would require is changing 'keys' to 'sort keys' in _encode_object and I'd be happy to do that w/tests, but I'm wondering if there's a reason it hasn't already been done? (if there is a reason, I'm also happy to write a doc patch to make it explicit ... and if it's already in the docs, then my apologies for my reading comprehension sucking)

**Comment by kraih** [comment]
This has come up before (a few times actually), but so far it has not managed to get the required votes. https://github.com/kraih/mojo/pull/665

**Comment by jhthorsen** [comment]
I'm still :-1: and I stand by my comments in #665.

**Comment by kraih** [comment]
For the record, i've tried replicating @daoswald's results from 2014, and have not been able to. https://github.com/kraih/mojo/pull/665#issuecomment-51255616

**Comment by pink-mist** [comment]
I've just tried as well, and can't find any significant impact from adding a ```sort```, so I'm going to vote :+1:.

**Comment by kraih** [comment]
With this version i do see a small performance loss. https://gist.github.com/anonymous/fca9dd4d0f766b6d653d

**Comment by shadowcat-mst** [comment]
So, (1) being able to use 'eq' in tests rather than is_deeply is really nice sometimes, (2) it's much easier for me to diff changes this way, and (3) "caching should depend on the input", well, yes, but while I *can* do that, there's a bunch of really easy caching tricks at middleware/http proxy/etc. layers that don't *have* the input and I'd like the option to use those as well. Also, if, for example, I'm building up a data structure from somewhere, being able to generate the etag by sha1-ing the content is often quicker overall than having to serialize it twice, once for etag generation and once for json.

**Comment by shadowcat-mst** [comment]
I think really what I'm saying is "not sorting feels like a micro-optimisation that costs me more in usability than it's worth in performance". I'm fairly sure that the time I'd save from not having to deal with this would be sufficient to do an extra NYTProf run and therefore end up with a simpler and faster codebase in the end overall. The question then becomes whether that's true of everybody else, nobody else, or somewhere in between.

**Comment by kraih** [comment]
Guess i'm still neutral on this issue, while i can see sorting making everything more dwim, i also want that extra 1% performance.

**Comment by leejo** [comment]
Predictable and repeatable output is favourable if the overhead is negligible, and i have no doubt that this issue will just come up again and again. So :+1:

**Comment by kraih** [comment]
One more thing, this has the potential to be a breaking change for people using tied hashes (like `Mango::BSON::Document`) for a custom order. Not that i think it's common practice, but worth considering.

**Comment by leejo** [comment]
FWIW if you remove the unnecessary ops from `sub _encode_object`, to bring it more inline with `sub _encode_array`, and do the same with `sub _encode_value` then you get back most of performance lost by sorting the object keys:

```diff
diff --git a/lib/Mojo/JSON.pm b/lib/Mojo/JSON.pm
index df032ad..6eee6f0 100644
--- a/lib/Mojo/JSON.pm
+++ b/lib/Mojo/JSON.pm
@@ -211,10 +211,9 @@ sub _encode_array {
 }

 sub _encode_object {
-  my $object = shift;
-  my @pairs = map { _encode_string($_) . ':' . _encode_value($object->{$_}) }
-    keys %$object;
-  return '{' . join(',', @pairs) . '}';
+  '{' . join(
+    ',', map { _encode_string($_) . ':' . _encode_value($_[0]->{$_}) } keys %{$_[0]}
+   ) . '}';
 }

@@ -224,39 +223,37 @@ sub _encode_string {
 }

 sub _encode_value {
-  my $value = shift;
-
   # Reference
-  if (my $ref = ref $value) {
+  if (my $ref = ref $_[0]) {

     # Object
-    return _encode_object($value) if $ref eq 'HASH';
+    return _encode_object($_[0]) if $ref eq 'HASH';

     # Array
-    return _encode_array($value) if $ref eq 'ARRAY';
+    return _encode_array($_[0]) if $ref eq 'ARRAY';

     # True or false
-    return $$value ? 'true' : 'false' if $ref eq 'SCALAR';
-    return $value  ? 'true' : 'false' if $ref eq 'JSON::PP::Boolean';
+    return ${$_[0]} ? 'true' : 'false' if $ref eq 'SCALAR';
+    return $_[0]  ? 'true' : 'false' if $ref eq 'JSON::PP::Boolean';

     # Everything else
-    return _encode_string($value)
-      unless blessed $value && (my $sub = $value->can('TO_JSON'));
-    return _encode_value($value->$sub);
+    return _encode_string($_[0])
+      unless blessed $_[0] && (my $sub = $_[0]->can('TO_JSON'));
+    return _encode_value($_[0]->$sub);
   }

   # Null
-  return 'null' unless defined $value;
+  return 'null' unless defined $_[0];

   # Number
   no warnings 'numeric';
-  return $value
-    if length((my $dummy = '') & $value)
-    && 0 + $value eq $value
-    && $value * 0 == 0;
+  return $_[0]
+    if length((my $dummy = '') & $_[0])
+    && 0 + $_[0] eq $_[0]
+    && $_[0] * 0 == 0;

   # String
-  return _encode_string($value);
+  return _encode_string($_[0]);
 }

 sub _throw {
```

Currently:

```
[leejohnson@lees-macbook-air J0 C10044 13:46:00 * master]
/Users/leejohnson/working/mojo > perl -Ilib sortdumbbench.pl
encode_json: Ran 1050 iterations (41 outliers).
encode_json: Rounded run time per iteration: 2.9237e-02 +/- 9.3e-05 (0.3%)
```

With above diff applied + sorting the keys:

```
[leejohnson@lees-macbook-air J0 C10043 13:44:52 * master]
/Users/leejohnson/working/mojo > perl -Ilib sortdumbbench.pl
encode_json: Ran 1050 iterations (42 outliers).
encode_json: Rounded run time per iteration: 2.936e-02 +/- 1.1e-04 (0.4%)
```

That's a difference of 0.4% on 0.03s, or 0.0001s. That's on a rather large JSON struct, on more typical JSON data it's going to be in the order of µs.

Benchmarking code:

```perl
#!perl

use strict;
use warnings;

use Mojo::JSON qw/decode_json encode_json/;
use Dumbbench;

my $json = join '', <DATA>;

our $structure = decode_json($json);
our $rv;

my $bench = Dumbbench->new(
  target_rel_precision => 0.5 / 100,
  initial_runs         => 1000,
);

$bench->add_instances(
  Dumbbench::Instance::PerlSub->new(
    name => 'encode_json',
    code => sub {
      $main::rv = encode_json($main::structure);
    }
  )
);

$bench->run;
$bench->report;

__DATA__
# same as in https://gist.github.com/anonymous/fca9dd4d0f766b6d653d
```

**Comment by shadowcat-mst** [comment]
so, seems it's less than 1% at this point - @kraih looks like we have +2, -1, and a patch that (a) works (b) would let you add multi-key object tests to json.t (which I presume this issue is why there currently aren't any). Thoughts? (I'm not sure how the mojo process works here)

**Comment by kraih** [comment]
@shadowcat-mst So far all votes from members of the core team have been -1 or neutral, so i'm afraid it doesn't look like this will pass.

**Comment by jhthorsen** [comment]
I thought @jberger had some input...

**Comment by marcusramberg** [comment]
I think this is a solid idea, and I don't see significant downsides, so
I'm +1.

M

**Comment by jberger** [comment]
I'm generally +1 as well, but I don't know what performance cost is worth the feature and don't know how to judge that. I have a use case at work where we get recurring messages from an external service. We would like to determine if they are the same data as the last stored message and only store it if it changes. This is rather similar to caching. Currently we also use one of the other JSON emitters which allows canonical representations. If Mojo::JSON could do this we would likely use it for this purpose as we do for the others, without it we would continue on as we are now.

I do wonder about the fact that (assuming it is correct) we don't have tests for emitting a JSON object with multiple keys. Accepting this feature or not it would probably be good to cover that. For me that might be enough to tip the scale.

**Comment by kraih** [comment]
Thanks, this proposal passed the vote. https://github.com/kraih/mojo/commit/5f47058d37534ab77398f9df620625a59283f809
