### ISSUE TITLE
load_class twice

### ISSUE THREAD

**Issue by tadegenban** [kraih/mojo#944]
I got this issue when play with Mojo::IOLoop, see this simple code:
`
use Mojo::IOLoop;

my $loop = Mojo::IOLoop->new;
say Dumper $loop->reactor;

`
I got :
-- Reactor initialized (Mojo::Reactor::Poll)
-- Reactor initialized (Mojo::Reactor::EV)
Mojo::Reactor::EV

I didn't install EV module, but the reactor will be Mojo::Reactor::EV eventually.

This issue came from load_class from Mojo::Loader, see:
`
say load_class('Mojo::Reactor::EV') ? 'load fail' : 'load ok';
say load_class('Mojo::Reactor::EV') ? 'load fail' : 'load ok';

`
load fail
load ok

**Comment by kiwiroy** [comment]
Using this code
```perl

use Test::More;

sub load_me {
    my $class = shift;

    return undef if $class->can('new') || eval "require $class; 1";

    return 1;
}

diag Mojo::Reactor::EV->can('new') || 'cannot new';

is load_me('Mojo::Reactor::EV'), 1, 'not loading first';
is load_me('Mojo::Reactor::EV'), 1, 'not loading second';

diag "Now ->can('new') returns ", Mojo::Reactor::EV->can('new');

is load_me('Mojo::NotHere'), 1, 'never load';
is load_me('Mojo::NotHere'), 1, 'never load again';

done_testing();
```

This is result without `EV` installed.`

```
t/mojo/944.t .. # cannot new
t/mojo/944.t .. 1/? 
#   Failed test 'not loading second'
#   at t/mojo/944.t line 15.
#          got: undef
#     expected: '1'
# Now ->can('new') returns CODE(0x14cef40)
# Looks like you failed 1 test of 4.
t/mojo/944.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/4 subtests 
```

**Comment by kraih** [comment]
Thanks, fixed.
