### ISSUE TITLE
406 to OPTIONS request

### ISSUE THREAD

**Issue by ungrim97** [kraih/mojo#946]
Hi,

I am getting a 406 response from Mojolicious when I make an options request and there is no route enabled to handle it. This seems erroneous.

I would expect either a 405 (Method Not Allowed) or a 404 (Resource Not Found). In this case as there is no route enabled then a 404 seems most appropriate. Unless Mojolicous can tell that the URL would resolve for another Method then a 405 would be best.

Please let me know if I am wrong

https://gist.github.com/ungrim97/3bf8202aa0d2b0e27283447df514ba03

**Comment by kraih** [comment]
Nothing in Mojolicious uses 406.

**Comment by karenetheridge** [comment]
Possibly the same issue as https://github.com/andk/pause/issues/205

I upgraded IO::Socket::SSL (to 2.025) and Net::SSLeay (to 1.74)  today. one of these could be the culprit?

**Comment by ungrim97** [comment]
@karenetheridge Sadly not.

@kraih Having dug deeper this seems to be due to the 'accepts' helpers deliberately failing if there are multiple content-types in the accept header and the X-Request-With is not set to 'XMLHttpRequest'. This is thus causing my error handling to return 406 the 404 error as it can't determine a format to return the error message in.

What is the rational between not handling the accept header properly in this situation.

**Comment by jberger** [comment]
406 sounds like the correct error code if the accepts header cannot be
satisfied

**Comment by ungrim97** [comment]
@jberger It would yes. This case was caused by the accepts helper method matching on an Accept header with more than one mime type in it unless the X-Request-With is set. This is a documented feature but keeps catching me out
