### ISSUE TITLE
Ungraceful stop

### ISSUE THREAD

**Issue by jixam** [kraih/mojo#947]
This one-liner creates a server that fails every other request (as the server restarts):

perl -E 'use Mojo::Server::Prefork; Mojo::Server::Prefork->new(workers=>1, accepts=>2)->run;'

The bug bisects to 7eb73468ed4d23edefa7995d6adcbd328cac68fa and this patch seems to fix it:

```diff
--- a/lib/Mojo/IOLoop.pm
+++ b/lib/Mojo/IOLoop.pm
@@ -142,7 +142,7 @@ sub stop { _instance(shift)->reactor->stop }

 sub stop_gracefully {
   my $self = _instance(shift)->_not_accepting;
-  ++$self->{stop} and !$self->emit('finish')->_in and $self->stop;
+  $self->{stop}++ and !$self->emit('finish')->_in and $self->stop;
 }

 sub stream {
```

I cannot claim to fully understand what's happening, so other changes may be needed.

**Comment by kraih** [comment]
I can confirm the problem, but the proposed patch does not look like a solution.

**Comment by kraih** [comment]
Thanks, fixed.
