### ISSUE TITLE
Mojo::UserAgent SPNEGO Support

### ISSUE THREAD

**Issue by subogero** [kraih/mojo#948]

**Comment by subogero** [comment]
Would it be difficult to add SPNEGO authentication support to the non-blocking Mojo::UserAgent?

For `LWP::UserAgent` this is provided by the `LWP::Authen::Negotiate` and `GSSAPI` modules.

**Comment by jberger** [comment]
Looking at LWP::Authen::Negotiate (which requires GSSAPI external dependency) and in consideration of the core development [Rule](http://mojolicious.org/perldoc/Mojolicious/Guides/Contributing#Rules) "A feature is only needed when the majority of the user base benefits from it." I don't think this is very likely to be accepted. Certainly it isn't something any of the core team would have the time or inclination to write.

I'd encourage you to see if it is something you can implement independently as a CPAN extension.

**Comment by kraih** [comment]
If it can't be implemented as a CPAN extension, i'm sure we can extend the `Mojo::UserAgent` api to make it possible.

**Comment by melak** [comment]
What would the mechanics of a UserAgent extension/plugin/whatever look like?
