### ISSUE TITLE
Bug with calling callback after write data to client with content_length header

### ISSUE THREAD

**Issue by Logioniz** [kraih/mojo#949]
In accordance with the [documentation](https://metacpan.org/pod/Mojolicious::Controller#write), I believe that callback should be called always. But when you set the content_length header, then the last callback is not invoked. Below is the test that shows this behavior.

```perl
#!/usr/bin/perl
use Mojolicious::Lite;
use Test::Mojo;
use Test::More;

get '/' => sub {
  my $c = shift->render_later;
  $c->res->headers->content_length(2);
  $c->write('11', sub { app->defaults(qwe => 1234); $c->finish });
};

app->start;

my $t = Test::Mojo->new;
$t->get_ok('/')->status_is(200);
is app->defaults('qwe'), 1234;

done_testing;

```

 I believe that this is a bug, since it's not documented.

**Comment by kraih** [comment]
Looks like a bug.

**Comment by anparker** [comment]
Documentation for write says it write dynamic content, but if you set content_length, content does not treated us dynamic any more.

https://metacpan.org/source/SRI/Mojolicious-6.60/lib/Mojo/Content.pm#L62

I disabled check for content_length in this line and test above passed. But I don't think, that is a solution.

**Comment by anparker** [comment]
https://metacpan.org/source/SRI/Mojolicious-6.60/lib/Mojo/Transaction/HTTP.pm#L66

Here, when all needed data has been send, transaction is marked as completed. And get_body_chunk will never be called again. That's only place, where drain event for Mojo::Content emitted.

http://pastebin.com/HTN1WXE2

This thing worked, but it looks more like workaround.

**Comment by kraih** [comment]
Thanks, should be fixed.
