### ISSUE TITLE
Some amount of shared state in renderer due to change in v6.54

### ISSUE THREAD

**Issue by nnutter** [kraih/mojo#951]
We had some of our app's tests start failing when we upgraded Mojolicious from v6.53 to v6.54.  Here's a test (which also fails on v6.61) that demonstrates the change in behavior,

```
use Mojolicious;
use Test::More;

use Mojo::Base -strict;

my $app = Mojolicious->new();
my $c   = $app->build_controller;
eval {$c->render_to_string(inline => 'some_var: <%= $some_var %>')};
ok($@, 'before "pollution" missing variable dies');
$c->render_to_string(
    inline   => 'some_var: <%= $some_var %>',
    some_var => 'some_value',
);
eval {$c->render_to_string(inline => 'some_var: <%= $some_var %>')};
ok($@, 'after "pollution" missing variable dies');
done_testing();
```

I don't yet understand the issue well enough to judge the severity of the problem but I thought I would at least report it for now.

**Comment by kraih** [comment]
Looks like undefined behaviour to me, or did you see anything in the docs that would suggest a certain behaviour?

**Comment by nnutter** [comment]
Perhaps it's subjective but the bits of the docs that might constrain the behavior are,

for Embedded Perl,

> For all templates `strict`, `warnings`, `utf8` and Perl 5.10 `features` are automatically enabled.

and

> At the beginning of the template, stash values that don't have invalid characters in their name get automatically initialized as normal variables, and the controller object as both `$self` and `$c`.

For `Mojolicious::Controller::render()`,

>  all additional key/value pairs get merged into the "stash".

So the only variables that I would expect to be declared are those that are in the controller's stash (with valid names), the controller itself as `$self` and `$c`, and any key-value pairs that were passed into the controller's `render()` call.  Because `strict` is on I would also expect undeclared variables to cause an exception.

**Comment by kraih** [comment]
Ok, the choice here is between always giving an error, or drastically reducing memory usage. Andi'm afraid i've not seen a good enough reason to sacrifice memory savings.
