### ISSUE TITLE
Changing worker user in websocket server

### ISSUE THREAD

**Issue by tfrizzell** [kraih/mojo#957]
I've come across some code snippets from last year in which developers were able to change the effective user for websocket workers with a 'user' setting in the configuration. This doesn't seem to work anymore and I was wondering if there is another way to accomplish this; the best solution I've been able to come up with so far is manually changing the effective user as requests are received.

**Comment by jberger** [comment]
I think the functionality you are looking for now exists as a plugin https://metacpan.org/pod/Mojolicious::Plugin::SetUserGroup . I'm a little confused about what you mean about "websocket worker" but if you simply mean "server worker processes" which might also handle websockets then I believe that is the case. 

In the future, we don't prefer opening issues for support requests. Going forward can you please contact one of the following venues for support? http://mojolicious.org/perldoc/Mojolicious/Guides/Contributing#SUPPORT Thanks
