### ISSUE TITLE
Remove FindBin from modules

### ISSUE THREAD

**Issue by jberger** [kraih/mojo#958]
FindBin is essentially a helper for scripts, its use in modules, especially Mojo::Home has been questioned for example in #955 . Some proposals have been to set MOJO_HOME earlier in the script startup process or rather using the (mostly) `cwd` based behaviors from FindBin (as seen here https://metacpan.org/source/RJBS/perl-5.24.0/lib/FindBin.pm#L100-105) to avoid some of the crazier things that FindBin has to do to support things like following links etc which Mojo::Home doesn't care about.

**Comment by kraih** [comment]
First stab at formalizing the home detection strategy. https://github.com/kraih/mojo/commit/4ae568a73e9f0f8b9c67de44f68b2b89c15a786d

**Comment by kraih** [comment]
Think all remaining uses of `FindBin` are fine.
