### ISSUE TITLE
Mojo::Asset::File does not allow appending to existing file

### ISSUE THREAD

**Issue by chorny** [kraih/mojo#962]
* Mojolicious version: 6.62
* Operating system: Windows XP

Found while investigating a problem in Mojolicious::Plugin::AssetPack
Existing file is opened in read-only mode (see https://github.com/kraih/mojo/blob/master/lib/Mojo/Asset/File.pm#L20 ), so add_chunk() does not work (error message is misleading: "Can't write to asset: Bad file descriptor"). It should be documented (or changed).

**Comment by kraih** [comment]
Maybe it should be documented somehow, but this is not a bug.

**Comment by nicomen** [comment]
Documenting for future $search_engine users:

I ran into the same issue. Of course I should probably not be using this module as a way to do a raw logfile , but anyhow, sending a preopened handle in helps you get around the default behaviour of Mojo::Asset::File:

```
my $handle = Mojo::File->new($server->config->{log_file})->open('+>>');
my $rawlog = Mojo::Asset::File->new( cleanup => 0, handle => $handle );
...
$rawlog->add_chunk(...);
```
