### ISSUE TITLE
Uninit value in string calling Mojo::DOM::CSS.select()

### ISSUE THREAD

**Issue by ronsavage** [kraih/mojo#963]
* Mojolicious version: 6.62
* Perl version: 5.20
* Operating system: Debian 8.4

```bash
shell> perl -MMojolicious -MU -e 'print $Mojolicious::VERSION, "\n"; $dom = Mojo::DOM -> new(q|<sup id="cite_ref-18" class="reference"><a href="#cite_note-18">[a]</a></sup>|); $css = Mojo::DOM::CSS -> new($dom) -> select(q|sup|)'
6.62
Use of uninitialized value in string eq at /home/ron/perl5/perlbrew/perls/perl-5.20.2/lib/site_perl/5.20.2/Mojo/DOM/CSS.pm line 202.
```

I expect no warning re uninit.

But I get this warning:
Use of uninitialized value in string eq at /home/ron/perl5/perlbrew/perls/perl-
5.20.2/lib/site_perl/5.20.2/Mojo/DOM/CSS.pm line 202.

**Comment by jberger** [comment]
Is there some reason you are trying to use Mojo::CSS separately from Mojo::DOM? I get no warnings (and indeed I get output) from 

```bash
perl -MMojo::DOM -E 'my $dom = Mojo::DOM->new(q|<sup id="cite_ref-18" class="reference"><a href="#cite_note-18">[a]</a></sup>|)->find(q|sup|)->join->say'
```

I could dive into why you are getting an error, but I'm not going to take the time unless there is some reason to be invoking the components separately. If there is such a reason, please feel free to reopen.

**Comment by ronsavage** [comment]
Just for the record, I wasn't using Mojo::DOM:CSS separately from Mojo::DOM. As per the classic Perl mantra, I chopped a module showing the error down to the minimum example which still showed the error. Getting it down to 1 line, is I think, a very good example. So, not appropriate to accuse me of chopping things out.

**Comment by kraih** [comment]
@ronsavage But that error only happens because you are using `Mojo::DOM::CSS` separately.

**Comment by jberger** [comment]
@ronsavage I didn't accuse you of anything. I couldn't replicate your results with a standard usage and was wondering if you needed the nonstandard way, in which case I would have reviewed how one even goes about using those modules in that way. I'm sorry if I sounded accusatory.

**Comment by ronsavage** [comment]
Hi Sebastian

Hmmm. OK. That's the type of answer I wanted.

On 30/05/16 20:30, Sebastian Riedel wrote:
> @ronsavage <https://github.com/ronsavage> But that error only happens
> because you are using |Mojo::DOM::CSS| separately.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kraih/mojo/issues/963#issuecomment-222463401>, or
> mute the thread
> <https://github.com/notifications/unsubscribe/AABT-Cvbc_l5PxeD2OzT78oreT4VnrWOks5qGrxRgaJpZM4InKmy>.
>

-- 
Ron Savage - savage.net.au

**Comment by kraih** [comment]
You should try our official support channels next time. http://mojolicious.org/perldoc/Mojolicious/Guides/Contributing#SUPPORT
