### ISSUE TITLE
mojo generate silently overwrites previous file(s)

### ISSUE THREAD

**Issue by szabgab** [kraih/mojo#965]
* Mojolicious version: 6.62
* Perl version: 5.22.0
* Operating system: ubuntu/vivid32

### Steps to reproduce the behavior
```$ mojo generate lite_app```
Creates myapp.pl as expected
Edit myapp.pl
```$ mojo generate lite_app```

### Expected behavior
The second run should either ask me if I want to overwrite the previous file or just refuse to work.

### Actual behavior
myapp.pl reverted to the original state without asking first.

The same behaviour is observed when running ```mojo generate app``` and changing the ```my_app/lib/MyApp.pm``` file.

**Comment by kraih** [comment]
Seems reasonable.

**Comment by szabgab** [comment]
👍
