### ISSUE TITLE
L10n in route action name

### ISSUE THREAD

**Issue by mche** [kraih/mojo#966]
* Mojolicious version: 6.56 (Clinking Beer Mugs)
* Perl version: v5.18.2 (linux)
* Operating system: Linux

### Steps to reproduce the behavior
[test fail](https://github.com/mche/mojo/blob/master/t/mojolicious/routes-l10n.t)
Log:
`[Wed Jun  1 21:10:31 2016] [debug] GET "/l10n"`
`[Wed Jun  1 21:10:31 2016] [debug] Action "버그" is not allowed`

### Expected behavior
content of GET /l10n is "완료"

### Actual behavior
404 Not Found

**Comment by kraih** [comment]
Any changes regarding this might have security implications that need to be considered.

**Comment by jhthorsen** [comment]
Do we need to support this?

**Comment by anparker** [comment]
I don't think using anything except [\w]

**Comment by anparker** [comment]
I don't think using anything except `\w+` in subroutine names is a good idea.

**Comment by jberger** [comment]
Just for information's sake (read: I'm not arguing in any direction) perl allows unicode in identifiers as long as it matches `/\w/` (see http://perldoc.perl.org/perlunifaq.html#Can-I-use-Unicode-in-my-Perl-sources%3f). By comparison, Mojolicious allows a much smaller subset of method names for `action` given by not being "hidden" as defined here: https://github.com/kraih/mojo/blob/aea16c61fd730a14053539332707ff3f770e7277/lib/Mojolicious/Routes.pm#L50-L54

**Comment by mche** [comment]
I think that to avoid security and other risks you should give for endpoint mojo user the feature to configure hidden method like:

`$app->routes->your_method_name_allow_action(qr/[\x{ac00}-\x{d7af}]/)`

**Comment by mche** [comment]
still, let along notice similar thing:

```
use Mojo::Base -base;
has qw[궁];
```

`Attribute "궁" invalid at /home/elk/perl5/lib/perl5/Mojo/Base.pm line 37.`

That is regexp also.

**Comment by kraih** [comment]
If there's a security risk, we will avoid it, but definitely not make it optional.

**Comment by kraih** [comment]
It appears that there is not much interest in unicode identifiers at the moment, and the exact naming rules are still unclear, so i'm afraid we'll not support them for now.
