### ISSUE TITLE
Mojo::Exception inheritance

### ISSUE THREAD

**Issue by cono** [kraih/mojo#968]
* Mojolicious version: 6.62
* Perl version: 5.20.2
* Operating system: Gentoo Linux 13.0

### Steps to reproduce the behavior
I would like to customize Mojo::Exception by adding additional fields: code,data, ...
But this constructor prevents me to do so:
`sub new { @_ > 1 ? shift->SUPER::new(message => shift) : shift->SUPER::new }`

### Expected behavior
I would like to have ability to inherit Mojo::Exception and add additional fields.

Is it possible to change it atleast too `@_ == 2 ? shift->SUPER::new(message => shift) : shift->SUPER::new(@_)` ?

**Comment by kraih** [comment]
Just overload `new` and perform the check yourself.

**Comment by kraih** [comment]
To be more clear, and extension like this would only be considered if there was a use case for it in the Mojolicious core distribution.

**Comment by cono** [comment]
Well, I wanted to get to the Mojo::Base to fullfill fields defined by: `has`

**Comment by kraih** [comment]
And you can't do that now?

**Comment by cono** [comment]
I can, but it will be a bit hackish, especially if you decide to add one more layer between Base <- HERE -> Exception in future
If I still call Base's new directly, I will loose this logic.
So I'm just asking to keep this in OOP way. I do't want to define the particular name of the class, I still want this to be done for me with SUPER keyword.
