### ISSUE TITLE
Parameter to verify certificate chain when use Mojo::IOLoop::Client (Mojo::UserAgent)

### ISSUE THREAD

**Issue by Logioniz** [kraih/mojo#971]
In current version of Mojo to check certificate chain need to set `tls_ca` param (`ca` param in Mojo::UserAgent) to true value or specify file which not exist.

I believe that this unpredictable behavior.
I think that need to add additional param (something like `tls_verify`) to implicit verify certificate chain.

**Comment by kraih** [comment]
Don't think this issue contains enough information to consider it a feature request. Perhaps you should try discussing it on IRC or the mailing-list first.

**Comment by avkhozov** [comment]
I think the question was that there is no way to explicitly set ``SSL_verify_mode`` to ``SSL_VERIFY_PEER`` without specifying the ``SSL_ca_file``.

@Logioniz you can set ``ca`` attribute to ``\undef`` for this (check docs https://metacpan.org/pod/distribution/IO-Socket-SSL/lib/IO/Socket/SSL.pod#SSL_ca-SSL_ca_file-SSL_ca_path)

May be this use case should be described in ``ca`` docs.

**Comment by Logioniz** [comment]
@avkhozov, thanks, i think it should be documented.
