### ISSUE TITLE
loss of precision when rendering JSON with big numbers

### ISSUE THREAD

**Issue by stuartskelton** [kraih/mojo#973]
* Mojolicious version: 6.60
* Perl version: Perl 5.16.3
* Operating system: MacOS 10.5.5 and Ubuntu linux

### Steps to reproduce the behavior

When rendering a JSON structure that has a large integer, there is a loss of precision.

```
#!/usr/bin/env perl
use Mojolicious::Lite;

my $json = {
    big_int => 123456789012345678901234567890,
};

get '/' => sub {
    my $c = shift;
    $c->render( json => $json );
};

app->start;
__DATA__
```
### Expected behavior
{"big_int":123456789012345678901234567890}
### Actual behavior
{"big_int":1.23456789012346e+29}

**Comment by kraih** [comment]
The precision is lost before the value reaches `Mojo::JSON`.
```
$ perl -E 'say 123456789012345678901234567890' 
1.23456789012346e+29
```

**Comment by kraih** [comment]
In the future you might want to try our official IRC channel or mailing-list first. http://mojolicious.org/perldoc/Mojolicious/Guides/Contributing#SUPPORT

**Comment by stuartskelton** [comment]
Thank you, to work around this issue is to use the  `bignum` pragma.
