### ISSUE TITLE
Spurious spaces inserted in all_text between elements

### ISSUE THREAD

**Issue by ailin-nemui** [kraih/mojo#974]
* Mojolicious version: 6.63
* Perl version: v5.24.0
* Operating system: openSUSE Tumbleweed (20160612) (x86_64)

### Steps to reproduce the behavior
```
perl -Mojo -E'say x(q{<span>Y</span>XXX<span>Y</span>})->all_text(0)'
```

### Expected behavior
should output:
```
YXXXY
```

### Actual behavior
output:
```
Y XXX Y
```
(spurious spaces between spans)

**Comment by jberger** [comment]
Formatted as a failing test:

```perl
use Mojo::Base -strict;

use Mojo::DOM;
use Test::More;

my $dom = Mojo::DOM->new(q{<td class="blob-code blob-code-inner js-file-line" id="LC187">irssi_add <span class="pl-s"><span class="pl-pds">&#39;</span>adv_windowlist<span class="pl-pds">&#39;</span></span> <span class="pl-s"><span class="pl-pds">&#39;</span>1<span class="pl-pds">&#39;</span></span></td>});
my $text = $dom->all_text(0);

is $text, q{irssi_add 'adv_windowlist' '1'};

done_testing;
```

**Comment by ailin-nemui** [comment]
Formatted as a failing test:

```perl
use Mojo::Base -strict;

use Mojo::DOM;
use Test::More;

my $dom = Mojo::DOM->new(q{<span>Y</span>XXX<span>Y</span>});
my $text = $dom->all_text(0);

is $text, q{YXXXY};

done_testing;
```

**Comment by kraih** [comment]
I'm afraid this is not a bug. And any changes to the current behavior would have to be based on research into specs and current browser behavior, so the information provided here is not enough.

**Comment by ailin-nemui** [comment]
If you select such a text in browser (Firefox, ie, chrome) and copy it, it comes out without spaces...

**Comment by jhthorsen** [comment]
Does not seem like jquery/javasript cares abouit white space:
```
var s = $("<span>x</span><span>y</span>").text()
console.log(s); // "xy"
$('body').text(JSON.stringify(s.split(""))); // ["x","y"]
```

https://jsbin.com/mimokixofo/edit?html,output

**Comment by lindleyw** [comment]
Per the [w3 HTML spec](https://www.w3.org/TR/html401/struct/text.html) §9.1: " In HTML, only the following characters are defined as white space characters: [space, tab, FF, zero width space, line breaks]". The example at bottom of §9.3 shows that in `…s</A>,…` there is no whitespace between the `s` and the comma.

Finally, consider the inconsistent generation of the space here:

`$ perl -Mojo -E'say x(q{To<b>m</b>,Bob})->all_text(0)' | hexdump -C`
`00000000  54 6f 20 6d 2c 42 6f 62  0a                       |To m,Bob.|`

**Comment by jhthorsen** [comment]
I've tried to put together som more browser test cases: https://cdn.rawgit.com/anonymous/222436447e2efcb17c69287539684de1/raw/f5bca80e4b2c8405032c47b7de285403e7adc96c/mojo-dom.html

What do you think?

**Comment by kraih** [comment]
The original issue should be resolved, everything else can be discussed in a new issue or on IRC.
