### ISSUE TITLE
Lose trailing slash while create absolute url

### ISSUE THREAD

**Issue by avkhozov** [kraih/mojo#975]
* Mojolicious version: 6.66
* Perl version: 5.22.1
* Operating system: Ubuntu 16.04 LTS

### Steps to reproduce the behavior
```bash
$ perl -MMojo::URL -le '$u = Mojo::URL->new("http://x.com/a/"); $x = Mojo::URL->new("?page=1")->to_abs($u); print $x;'
http://x.com/a?page=1
```

### Expected behavior
Expected url is ``http://x.com/a/?page=1``

### Actual behavior
``to_abs`` drop trailing slash, but browsers leave trailing slash when address bar has trailng slash and href attr contains only query string.

**Comment by kraih** [comment]
Thanks, should be fixed.
