### ISSUE TITLE
Memory leak when using delay in subroutine

### ISSUE THREAD

**Issue by mlen108** [kraih/mojo#982]
* Mojolicious version: 6.66
* Perl version: v5.20.2 (built for x86_64-linux-gnu-thread-multi)
* Operating system: debian 4.5.5-x86_64

### Steps to reproduce the behavior

I have long running app which develops a memory leak so I'm trying to figure out where & why. I'm Perl noob so perhaps I made some stupid mistake in there.

Would appreciate your help.

Below is a sample code (extracted from my app):

```perl
#!/usr/bin/env perl

use v5.20.2;
use strict;
use warnings;

use Mojo::UserAgent;
use Mojo::IOLoop;
use Memory::Usage;

my $mu = Memory::Usage->new();
$mu->record('before');

my $ua = Mojo::UserAgent->new;
my $tx = $ua->build_tx(GET => 'google.pl');

my $delay = Mojo::IOLoop->delay;

my $end = $delay->begin;
$ua->start($tx => sub {
  my (undef, $x) = @_;
  say $x->res->code;
  $end->();
});
$delay->wait;

$mu->record('after');
$mu->dump();
```

### Expected behavior

Memory usage on "after" should remain as "before".

### Actual behavior

Higher values in "after" indicate there's memory leak.

```
time    vsz (  diff)    rss (  diff) shared (  diff)   code (  diff)   data (  diff)
     0  130164 ( 130164)  28328 ( 28328)   6640 (  6640)      8 (     8)  62832 ( 62832) before
     0  200128 ( 69964)  28576 (   248)   6848 (   208)      8 (     0)  63196 (   364) after
```

**Comment by jberger** [comment]
A process will continue to claim memory as it needs it. Your process will indeed need more memory as it makes the request and gets the response. This isn't a leak. 

While processes can claim more memory from the operating system in general they can't give it back (until they finish). Long running processes can reuse the memory they claimed but no longer needed elsewhere. A leak occurs when though you no longer need the old section of memory, the process for some reason doesn't reuse it and thus continues to claim more and more (eventually starving your system if it goes on long enough).

In your example if you looped over many requests (being sure not to hold on to the results on each iteration) and yet the process memory grew on each iteration then THAT would be a leak.

Now, I see why you opened this as a bug report, you thought there was a potential leak. That said generally support is offered via other channels listed here: http://mojolicious.org/perldoc#SUPPORT .

**Comment by jberger** [comment]
It has been mentioned on IRC that you probably "fixed" your bug in paring it down to a simple demo. If that is the case, see which variables they close over and see if any of them create a cycle. You can use Devel::Cycle (with a little practice) to help identify them.

**Comment by mlen108** [comment]
Thanks @jberger for responding.

My app is supposed to process tens of thousands of GET requests per minute so as you can imagine it runs out of memory pretty quickly. And eventually it gets killed by OS. I would like to get its memory usage as low as possible.

The mentioned `Devel::Cycle` doesn't seem to be working for me (too new Perl?).

Anyway, I narrowed the *potential* problem to Mojo's UserAgent methods, so here is the simple test again.

Sorry for very basic scenario - could you please explain why Mojo uses more memory? The use of `LWP::UserAgent` is just an example (don't intend to use it in my app).

`Mojo::UserAgent`:
```perl
#!/usr/bin/env perl

use v5.20.2;
use strict;
use warnings;
use Mojo::UserAgent;
use Memory::Usage;

my $mu = Memory::Usage->new();
$mu->record('before');
my $ua = Mojo::UserAgent->new;
$ua->get('google');
$mu->record('first');
$ua->get('google.co.uk');
$mu->record('second');
$ua->get('bbc.co.uk');
$mu->record('after');
$mu->dump();
```

Results:
```
  time    vsz (  diff)    rss (  diff) shared (  diff)   code (  diff)   data (  diff)
     0  130156 ( 130156)  28480 ( 28480)   6796 (  6796)      8 (     8)  62824 ( 62824) before
     0  199904 ( 69748)  28724 (   244)   7008 (   212)      8 (     0)  62972 (   148) first
     0  265572 ( 65668)  28744 (    20)   7008 (     0)      8 (     0)  63236 (   264) second
     0  331108 ( 65536)  28752 (     8)   7008 (     0)      8 (     0)  63368 (   132) after
```

---

`LWP::UserAgent`:
```perl
#!/usr/bin/env perl

use v5.20.2;
use strict;
use warnings;
use Memory::Usage;
use LWP::UserAgent;

my $ua = LWP::UserAgent->new;
my $mu = Memory::Usage->new();
$mu->record('before');
$ua->get('google.pl');
$mu->record('first');
$ua->get('google.co.uk');
$mu->record('second');
$ua->get('bbc.co.uk');
$mu->record('after');
$mu->dump();
```

Results:
```
  time    vsz (  diff)    rss (  diff) shared (  diff)   code (  diff)   data (  diff)
     0  27952 ( 27952)   8628 (  8628)   3928 (  3928)      8 (     8)   5108 (  5108) before
     0  28348 (   396)   8892 (   264)   3928 (     0)      8 (     0)   5504 (   396) first
     0  28348 (     0)   8892 (     0)   3928 (     0)      8 (     0)   5504 (     0) second
     0  28348 (     0)   8892 (     0)   3928 (     0)      8 (     0)   5504 (     0) after
```

I tried to free accidental resources by using `weaken` / `undef` but not to avail.

**Comment by kraih** [comment]
I second @jberger's recommendation, you should discuss this on our official support channels. Afraid i don't see anything here that looks like a memory leak.
