### ISSUE TITLE
Perl 5.10.1: warnings "Can't call method "remove" on an undefined value ... during global destruction"

### ISSUE THREAD

**Issue by dolmen** [kraih/mojo#985]
* Mojolicious version: 7.01
* Perl version: 5.10.1
* Operating system: Ubuntu 16.04

### Steps to reproduce the behavior
cpan SRI/Mojolicious-7.01.tar.gz

### Expected behavior
No warnings when running the testsuite

### Actual behavior
```
t/mojo/user_agent.t
	(in cleanup) Can't call method "remove" on an undefined value at .../.cpan/build/Mojolicious-7.01-2/blib/lib/Mojo/Server/Daemon.pm line 26, <DATA> line 2231 during global destruction.
	(in cleanup) Can't call method "stop" on an undefined value at .../.cpan/build/Mojolicious-7.01-2/blib/lib/Mojo/IOLoop.pm line 174, <DATA> line 2231 during global destruction.
	(in cleanup) Can't call method "start" on an undefined value at .../.cpan/build/Mojolicious-7.01-2/blib/lib/Mojo/IOLoop.pm line 167, <DATA> line 2231 during global destruction.
Use of uninitialized value $loop in hash element at .../.cpan/build/Mojolicious-7.01-2/blib/lib/Mojo/UserAgent.pm line 194, <DATA> line 2231 during global destruction.
	(in cleanup) Can't call method "remove" on an undefined value at .../share/.cpan/build/Mojolicious-7.01-2/blib/lib/Mojo/UserAgent.pm line 272, <DATA> line 2231 during global destruction.
```
Similar issues in t/mojolicious/commands.t, t/mojolicious/embedded_lite_app.t, t/mojolicious/mite_app.t, t/mojolicious/ojo.t

**Comment by kraih** [comment]
We are fine with warnings on old versions of Perl, as long as the distribution is installable. http://mojolicious.org/perldoc/Mojolicious/Guides/FAQ#Which-versions-of-Perl-are-supported-by-Mojolicious

**Comment by 4p00rv** [comment]
@dolmen  I might be too late, but use `$tx->completed` instead of `$tx->finish` It dequeues the previous loop and avoids any warnings.

**Comment by jberger** [comment]
`completed` is a "low-level" method and shouldn't be used by the average user. http://mojolicious.org/perldoc/Mojo/Transaction#completed.

**Comment by 4p00rv** [comment]
@jberger Then closed would do the same by emitting `finish` event on `completed`
