### ISSUE TITLE
t/mojo/user_agent_tls.t fails with OpenSSL 1.0.2+ and LibreSSL

### ISSUE THREAD

**Issue by noxxi** [kraih/mojo#987]
* Mojolicious version: latest (commit  039a827) but also older
* Perl version: any
* Operating system: any system with OpenSSL 1.0.2 or LibreSSL

### Steps to reproduce the behavior
run t/mojo/user_agent_tls.t with TEST_TLS=1

### Expected behavior
test should pass

### Actual behavior
test fails because it tries to create a HTTPS server with SSLv3
SSLv3 is no longer supported with LibreSSL and OpenSSL 1.0.2

### Possible fix
simply replace all occurrences of SSLv3 with TLSv1 in this file.
TLSv1 (i.e. TLS 1.0) is also supported by any OpenSSL/LibreSSL version supported by Net::SSLeay/IO::Socket::SSL

**Comment by jberger** [comment]
I have OpenSSL v1.0.2g (OSX) and the test passes for me. I'm happy to make the change but I don't know how to verify with the system I have.

**Comment by noxxi** [comment]
On Thu, Aug 11, 2016 at 09:29:45AM -0700, Joel Berger <notifications@github.com> wrote:
> I have OpenSSL v1.0.2g (OSX) and the test passes for me. I'm happy to make the
> change but I don't know how to verify with the system I have.

It looks like disabling of SSLv3 is a Debian (und thus Ubuntu) specific
thing. Thus if you want to see how the test fails you either need to
recompile your own OpenSSL without SSLv3 support or grab an image of Ubuntu
16.04 and install it in some VM.
If you don't need to see yourself how it fails here is the output:

  ok 1 - not successful
  ... ok 2..14
  ok 15 - has error
  not ok 16 - successful
  #   Failed test 'successful'
  #   at t/mojo/user_agent_tls.t line 98.
  not ok 17 - no error
  #   Failed test 'no error'
  #   at t/mojo/user_agent_tls.t line 99.
  Use of uninitialized value $stream in hash element at /home/work/tmp/Mojolicious-7.01/blib/lib/Mojo/IOLoop.pm line 144.
  Use of uninitialized value $stream in hash element at /home/work/tmp/Mojolicious-7.01/blib/lib/Mojo/IOLoop.pm line 144.
  Can't call method "handle" on an undefined value at t/mojo/user_agent_tls.t line 100.
  # Tests were run but no plan was declared and done_testing() was not seen.
  # Looks like your test exited with 11 just after 17.

If every SSLv3 is changed to TLSv1 (see attached patch) the test passes:

  ok 1 - not successful
  ... ok 2..14
  ok 15 - has error
  ok 16 - successful
  ok 17 - no error
  ok 18 - AES256-SHA has been negotiatied
  ok 19 - TLSv1 has been negotiatied
  1..19

Since TLSv1 is support with all OpenSSL versions you should be able to apply
this patch and the test should pass for you. Thus there is actually no harm
done, i.e. the test passed for you before (forcing SSLv3) and it passes now
(forcing TLSv1). And on systems with disabled SSLv3 (i.e. at least recent
Debian, Ubuntu and OpenBSD with LibreSSL) the test failed before and will
now pass.

Regards,
Steffen

--- t/mojo/user_agent_tls.t.orig	2016-08-11 19:41:45.188957151 +0200
+++ t/mojo/user_agent_tls.t	2016-08-11 19:41:54.644843965 +0200
@@ -86,20 +86,20 @@
   . '&ca=t/mojo/certs/ca.crt'
   . '&ciphers=AES256-SHA:ALL'
   . '&verify=0x00'
-  . '&version=SSLv3';
+  . '&version=TLSv1';
 $daemon->listen([$listen])->start;
 $port = Mojo::IOLoop->acceptor($daemon->acceptors->[0])->port;
 
 # Invalid certificate
 $ua = Mojo::UserAgent->new(ioloop => $ua->ioloop);
 $ua->cert('t/mojo/certs/bad.crt')->key('t/mojo/certs/bad.key');
-IO::Socket::SSL::set_defaults(SSL_version => 'SSLv3');
+IO::Socket::SSL::set_defaults(SSL_version => 'TLSv1');
 $tx = $ua->get("https://127.0.0.1:$port");
 ok $tx->success, 'successful';
 ok !$tx->error, 'no error';
 is $ua->ioloop->stream($tx->connection)->handle->get_cipher, 'AES256-SHA',
   'AES256-SHA has been negotiatied';
-is $ua->ioloop->stream($tx->connection)->handle->get_sslversion, 'SSLv3',
-  'SSLv3 has been negotiatied';
+is $ua->ioloop->stream($tx->connection)->handle->get_sslversion, 'TLSv1',
+  'TLSv1 has been negotiatied';
 
 done_testing();
