### ISSUE TITLE
UserAgent appears to make a localhost:80 http request when given a file:/// URL

### ISSUE THREAD

**Issue by shadowcat-mst** [kraih/mojo#988]
* Mojolicious version: 7.01
* Perl version: 5.14.2
* Operating system: Debian 7.10

### Steps to reproduce the behavior
mojo get file:///foo/bar.txt

(or $ua->get(...))

### Expected behavior
Since file:/// URLs aren't handled by the useragent, I'd've expected it to die() with an error message telling me I'm an idiot (and similar for any other unsupported URL type).

### Actual behavior
mojo performed a GET request for http://localhost/foo/bar.txt

**Comment by shadowcat-mst** [comment]
From my POV 'silently doing the wrong thing' is a bug, not a missing feature - though, OTOH, I guess you could see it as more a usability failure.

Either way, it was really -ing confusing the first time I hit it :)

**Comment by jberger** [comment]
I did look into this over the weekend a little bit. The problem is when/where could/should the error come from; especially assuming we don't want to make `$ua->get('file://...')` die in-place on nonblocking requests.

There is also the broader question, should we limit all unexpected schemes or just file? Assuming we want to limit all unknown schemes the obvious place to throw the exception is here: https://github.com/kraih/mojo/blob/70c177dc48fa65bc6498c7a0c39b4458903fe991/lib/Mojo/UserAgent.pm#L98 . The problem is that to this point all exceptions (see `_error`) assume there is a connection id in the hash of data. This one does not yet have the id so the infrastructure for reporting errors would have to change (or maybe I'm just not seeing it).

**Comment by jberger** [comment]
I had considered another thought which would be to build a Mojo::Asset::File for the file in question. However I do worry that there is code in the wild that wouldn't be guarding against that and suddenly they might get local files leaking into the world. There would likely need to be some kind of guard established that would protect that and so now this would need to be a whole new designed feature. I don't see that happening. I just mention here to note that I have thought about it.

**Comment by Grinnz** [comment]
Also keep in mind if you wanted to build a Mojo::Asset::File you would need to map the file: URL to the filesystem a la URI::file (for example the url `file:///C:/foo/bar` which on win32 would map to `C:\foo\bar` and on unix to `./C:%5Cfoo%5Cbar`). So it's probably not worth going down that path.

**Comment by Grinnz** [comment]
For the error, I would think it should ideally throw an exception immediately (croak to the caller of the method). It's an invalid parameter error not a connection error.

**Comment by kraih** [comment]
Do we have an implementation yet?

**Comment by kraih** [comment]
After posting a patch on IRC and talking a bit about it, i'm afraid i have to vote :-1: on this. Because there is simply too much data the user provides for us to validate everything, and this would set a dangerous precedent. https://gist.github.com/anonymous/6cb0ed7ad64c91c05facd6f49a41df53

**Comment by jhthorsen** [comment]
👎 from me as well.

**Comment by shadowcat-mst** [comment]
I appreciate that you can't validate everything, but that's not the same as "not making a completely different sort of request".

If I tell Mojo to do something wrong, and it does something wrong, well, stupid me.

If I tell Mojo to do something, and it instead does something completely different, that's rather confusing.

I'm not sure how "don't silently do something completely different to what the user asked for" is a dangerous precedent?

**Comment by jhthorsen** [comment]
How is ```mojo get file:///foo/bar.txt``` you not telling mojo to do something wrong?

**Comment by shadowcat-mst** [comment]
My point here is the difference between it attempting to do what I asked, right or wrong, and doing something completely different.

So far, the rest of mojo has been free of such nasal daemonesque moments.

**Comment by shadowcat-mst** [comment]
Basically, I was figuring that whichever bit of code decides whether it's making an http or https request should already be poking the URL scheme somehow, so at that point you're already extracting and testing it, at which point adding a third case for 'throw error' should be relatively easy and you're already paying for checking the proto there anyway.

**Comment by shadowcat-mst** [comment]
Looking in Transactor.pm, there's plenty of prior art for validating this. For example, from 'sub redirect' -

    return undef if ($proto ne 'http' && $proto ne 'https') || !$location->host;

**Comment by lindleyw** [comment]
Could something this basic suffice?

https://gist.github.com/lindleyw/19052f7a91103ad353f38f2f5deb44b6

**Comment by jhthorsen** [comment]
There's no $tx at that point, so where do you catch the error?

**Comment by kraih** [comment]
@lindleyw Have you actually tested that approach? Because it doesn't seem viable at all to me.

**Comment by kraih** [comment]
@shadowcat-mst None of the proposed patches match those criteria.

**Comment by shadowcat-mst** [comment]
It's a trifle inefficient in the case where it's erroring, but given the point is to point out a bug I'm not sure I mind, and the following seems to work:

    diff --git a/lib/Mojo/UserAgent.pm b/lib/Mojo/UserAgent.pm
    index ebe9537..adc01a8 100644
    --- a/lib/Mojo/UserAgent.pm
    +++ b/lib/Mojo/UserAgent.pm
    @@ -293,6 +293,14 @@ sub _start {
     
       # Application server
       my $url = $tx->req->url;
    +  my $proto = $url->protocol;
    +
    +  if ($proto && $proto ne 'http' && $proto ne 'https') {
    +    $tx->res->error(qq/Unsupported protocol "$proto"/);
    +    $self->ioloop->next_tick(sub { $cb->($self, $tx) });
    +    return;
    +  }
    +
       unless ($url->is_abs) {
         my $base
           = $loop == $self->ioloop ? $self->server->url : $self->server->nb_url;
    diff --git a/t/mojo/user_agent.t b/t/mojo/user_agent.t
    index de5e604..2697be7 100644
    --- a/t/mojo/user_agent.t
    +++ b/t/mojo/user_agent.t
    @@ -592,4 +592,11 @@ Mojo::IOLoop->delay(
     )->wait;
     is scalar @$result, 2, 'two active connections';
     
    +# Unsupported protocol
    +like
    +  $ua->get('file:///etc/passwd')->res->error,
    +  qr/Unsupported protocol "file"/,
    +  'right error';
    +
    +
     done_testing();

**Comment by kraih** [comment]
@shadowcat-mst How would you explain the inconsistency in URL validation between the request URL (`$tx->req->url`) and the proxy URL (`$tx->req->proxy`)?

**Comment by shadowcat-mst** [comment]
Currently, if you give it a ridiculous proxy -

    sherlock$ perl -Mojo -MData::Dumper -E 'my $ua = app->ua; $ua->proxy->http("file://home/matthewt/tmp/foo"); say Dumper $ua->get("http://google.com/")->res->error'
    $VAR1 = {
              'message' => 'Can\'t connect: Name or service not known'
    };

you get an error rather than it silently making an http request to localhost.

So from my POV, I'm making things less inconsistent. We could even make the error the same, although I think the error I stole from your original patch is better.

**Comment by kraih** [comment]
@shadowcat-mst Your test case is a little misleading though.
```
perl -Mojo -MData::Dumper -E 'my $ua = app->ua; $ua->proxy->http("file://mojolicious.org/matthewt/tmp/foo"); say Dumper $ua->get("http://google.com/")->res->error'
$VAR1 = undef;
```
Here a request is actually performed.

**Comment by shadowcat-mst** [comment]
@kraih Really? I did an strace and couldn't find a connect().

**Comment by kraih** [comment]
@shadowcat-mst YA RLY!
```
$ MOJO_USERAGENT_DEBUG=1 perl -Mojo -MData::Dumper -E 'my $ua = app->ua; $ua->proxy->http("file://mojolicious.org/matthewt/tmp/foo"); say Dumper $ua->get("http://google.com/")->res->error'
-- Blocking request (http://google.com/)
-- Connect c338ca711bfc9cee65ed3b43de8f1b25 (file://mojolicious.org:80)
-- Client >>> Server (http://google.com/)
GET http://google.com/ HTTP/1.1\x0d
Accept-Encoding: gzip\x0d
User-Agent: Mojolicious (Perl)\x0d
Host: google.com\x0d
Content-Length: 0\x0d
\x0d

-- Client >>> Server (http://google.com/)

-- Client <<< Server (http://google.com/)
HTTP/1.1 200 OK\x0d
Server: nginx\x0d
Date: Fri, 19 Aug 2016 20:37:30 GMT\x0d
Content-Type: text/html;charset=UTF-8\x0d
Transfer-Encoding: chunked\x0d
Connection: keep-alive\x0d
Content-Encoding: gzip\x0d
\x0d
4d\x0d
\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\x03\x0b??,V\x00???\x12\x85\x92\x8cT\x85????Ң?T\x85??R??T\x85\x9c???̼t\x85??"=\x05???T\x85?\x9c??t=...\x00h?\x02?;\x00\x00\x00\x0d
0\x0d
\x0d

$VAR1 = undef;
```
Your original test case bailed out during DNS lookup, but if you get past that a request can be performed.

**Comment by shadowcat-mst** [comment]
@kraih Nuts. Good catch. Ok, going to have to have a think about this.

**Comment by kraih** [comment]
Honestly, what worries me most is the security implications, such as users suddenly expecting all input values to be validated if one is.
```
$ua->get('file://mojolicio.us/foo' => {'Content-Type' => "text/plain\nAuthorization: foo"});
```

**Comment by shadowcat-mst** [comment]
Right, the distinction that I'm trying to draw is that I'm fine with "users are responsible for validating data, and if you pass wrong data it will still do exactly what you told it" - but in this case, if I pass wrong data it does something that, to my mind, isn't even within shouting distance of what I told it to do.

Your header example seems entirely expected. I'd also not feel upset if a file:// URL revealed files on disk because again that's what I passed. But the current behaviour is, to me, more in the category of "oh, and if you put a newline in a header, mojo silently switches from GET to POST" - honestly, I think I'd've preferred nasal daemons to "makes a request to localhost:80 for a file:// URL" ;)

So I guess before we spend more time thinking about the code, I guess the question is - does that distinction make sense as a thing that exists (and if not, why not), and if so what do you think about "doing the wrong thing you asked for is not our fault, but nasal daemons are a bug" precedent that I'd like to set here.

**Comment by marcusramberg** [comment]
Kinda seems like this thing isn't really worth the hassle. 👎

**Comment by jberger** [comment]
For the record, I think that saying that the UserAgent can't handle any protocols except "http(s)?" is different that expecting full validation. As @kraih mentioned, Mojo::Pg checks for `postgresql://` but doesn't validate queries.

**Comment by kraih** [comment]
Looks like the majority agrees that we should just leave everything the way it is.
