### ISSUE TITLE
Test::Mojo::json_is does not work correctly with the $desc in Unicode

### ISSUE THREAD

**Issue by asan13** [kraih/mojo#995]
* Mojolicious version: 5.54
* Perl version: 5.20.2
* Operating system: Debian 8.5 (x86_64) 

### Steps to reproduce the behavior
```perl
use ut8;
use open qw(:std :utf8);

my $t = Test::Mojo->new('MyApp');
   
$t  -> get_ok('foo')
    -> json_is('/xxx' => 'yyy', 'Комментарий');
```
_Output_
```
    ok 1 - GET http://localhost:36491/test/foo
    ok 2 - ÐÐ¾Ð¼Ð¼ÐµÐ½ÑÐ°ÑÐ¸Ð¹
```
### Expected behavior
```
    ok 1 - GET http://localhost:36491/test/foo
    ok 2 - 'Комментарий'
```
### Actual behavior
Breaks description of the test, if it is in Unicode.

The reason is that the 'json_is' _always_ makes 'encode' for the parametr '$desc'. And it breaks the output if used _use open qw(:std :utf8);_
```perl
sub json_is {
  my $self = shift;
  my ($p, $data) = @_ > 1 ? (shift, shift) : ('', shift);
  my $desc = encode 'UTF-8', shift || qq{exact match for JSON Pointer "$p"}; # <<<==========
  return $self->_test('is_deeply', $self->tx->res->json($p), $data, $desc);
}
```
In similar functions done differently, and there is no problem. For example, json_like:
```perl
sub json_like {
  my ($self, $p, $regex, $desc) = @_;
  $desc ||= encode 'UTF-8', qq{similar match for JSON Pointer "$p"}; # <<<========
```

**Comment by kraih** [comment]
How to handle Unicode output on `STDERR` and `STDOUT` in Mojolicious has been an open question for years now. So far it seemed like the safes choice not to mess with Perl defaults, therefore our expectation is that you don't do either. Of course we are open to proposals for changing this, but they would have to take the whole framework into account.

**Comment by kraih** [comment]
Also, please feel free to discuss this on IRC, a few of the many problems with possible proposals have already been brought up there today.

**Comment by asan13** [comment]
It is just that the implementation of the 'json_is' did not differ from the rest 'json_ | content_' etc. It seems enough:

```perl
sub json_is {
  my $self = shift;
  my ($p, $data) = @_ > 1 ? (shift, shift) : ('', shift);
  # my $desc = encode 'UTF-8', shift || qq{exact match for JSON Pointer "$p"};
  my $desc = shift;
  $desc ||= encode 'UTF-8', qq{exact match for JSON Pointer "$p"};
```

P.S. I read IRC channel, but I do not know much English for interactive communication)

**Comment by kraih** [comment]
I see what you mean, and i'm afraid you won't like my solution, which is to make all tests behave consistently. https://github.com/kraih/mojo/commit/8fdf806ff56520bd79dfe0fe8fc24315918bfd37

**Comment by asan13** [comment]
Hi again!
One more attempt.

In the new Mojo broke description for tests (to be expected). If you remove `use open (':std')`, we have a lot of warnings, if you remove `use utf8`, we have a broken regexp. 

Why even touch the user comment of the test? Doing forced `encode`, we do not leave the choice to the user. 
I think that encoding user's strings to utf8 is bad practice.
The following test demonstrates the problem:

```perl
#!/usr/bin/perl

use warnings;
use strict;
use utf8;
use open qw(:std :utf8);

use Test::More tests    => 6;

BEGIN {
    require_ok 'Mojolicious';
    use_ok 'Test::Mojo';
}

{
    package TstApp;
    use Mojo::Base 'Mojolicious';

    sub startup {
        my ($self) = @_;

        $self->routes
            -> get('/ping')
            -> to(cb => sub { return shift->render(text => 'pong') })
            -> name('ping');
    }
}

package main;

my $t = Test::Mojo->new('TstApp');

note 'тесты mojo';
$t  -> get_ok('/ping')
    -> status_is(200)
    -> content_is('pong', 'Запрос выполнен успешно');

note 'другие тесты';
my $str_from_somewhere = 'Привет, медвед';

like $str_from_somewhere => qr{\w,\s\w}, 'Еще тест прошел';
```

Old Mojo looks fine (5.54):
```txt
1..6
ok 1 - require Mojolicious;
ok 2 - use Test::Mojo;
# тесты mojo
ok 3 - GET /ping
ok 4 - 200 OK
ok 5 - Запрос выполнен успешно
# другие тесты
ok 6 - Еще тест прошел
```

current  mojo breaks descriptions:
```txt
1..6
ok 1 - require Mojolicious;
ok 2 - use Test::Mojo;
# тесты mojo
ok 3 - GET /ping
ok 4 - 200 OK
ok 5 - ÐÐ°Ð¿ÑÐ¾Ñ Ð²ÑÐ¿Ð¾Ð»Ð½ÐµÐ½ ÑÑÐ¿ÐµÑÐ½Ð¾
# другие тесты
ok 6 - Еще тест прошел
```


commmenting `use open :std` have warnings:
```txt
1..6
ok 1 - require Mojolicious;
ok 2 - use Test::Mojo;
Wide character in print at /usr/share/perl/5.20/Test/Builder.pm line 1821, <DATA> line 2125.
# тесты mojo
ok 3 - GET /ping
ok 4 - 200 OK
Wide character in print at /usr/share/perl/5.20/Test/Builder.pm line 1821, <DATA> line 2125.
ok 5 - Запрос выполнен успешно
Wide character in print at /usr/share/perl/5.20/Test/Builder.pm line 1821, <DATA> line 2125.
# другие тесты
Wide character in print at /usr/share/perl/5.20/Test/Builder.pm line 1821, <DATA> line 2125.
ok 6 - Еще тест прошел
```

commenting use utf8 breaks regexps tests:
```txt
1..6
ok 1 - require Mojolicious;
ok 2 - use Test::Mojo;
# тесты mojo
ok 3 - GET /ping
ok 4 - 200 OK
ok 5 - Запрос выполнен успешно
# другие тесты
not ok 6 - Еще тест прошел
#   Failed test 'Еще тест прошел'
#   at test.t line 44.
#                   'Привет, медвед'
#     doesn't match '(?^:\w,\s\w)'
# Looks like you failed 1 test of 6.
```

So. I think that Test::Mojo shouldn't use encode for user's descriptions (like Test::More - it doesn't use `encode`. And the other library modules)

Regards.
